### ISSUE TITLE
主附表的生成代码后主表是逻辑删除，附表数据是物理删除，已经验证了多个表

### ISSUE THREAD

**Issue by peak666** [jeecgboot/JeecgBoot#5162]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
主附表的生成代码后主表是逻辑删除，附表数据是物理删除，已经验证了多个表

##### 截图&代码：
主表是逻辑删除
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/363175e7-d4ef-4388-aaed-486e5b6e90ac)

附表数据被物理删除了
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/b70d70e3-849b-40d2-9742-c74dec510a0f)

生成的代码都带着逻辑删除的字段
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/f073b358-6d74-4069-b2cf-d0b226040ac1)
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/93c935d0-685c-474a-9c62-e849be0fb42c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/9bc83213-6638-434a-960a-6110342531ea)
可以扩展此处，这块是写死的物理删除

**Comment by zhangdaiscott** [comment]
xp

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312
