### ISSUE TITLE
建议在线表单增加视图表类型，并导入视图后修改编辑不用再次发布

### ISSUE THREAD

**Issue by maxid** [jeecgboot/JeecgBoot#5608]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
导入视图后，编辑字段备注等操作不能生效，因为必须发布，但视图是只读的，因此无发进行发布
目前通过修改表数据临时解决

视图的应用场景：
1. 视图可以控制字段范围，过滤敏感字段
2. 记录有删除状态（del_flag）或有效状态（status），视图可以过滤这些特定条件
3. 结合第1，2点组合如关联记录等组件使用

建议：表类型增加视图类型，并修改不用进行发布
或关联记录支持选择《Online报表》

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/927429/eb5abb54-0820-4481-87dd-19c5eff1fcb2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xxlxg1976** [comment]
支持增加视图
