### ISSUE TITLE
Online表单开发中，找不到和数据库 bigint 匹配的数据类型

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#5871]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
数据库已有的表，字段类型是 bigint ，应该选界面上的哪种数据类型？
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/927e15b1-3edf-4e91-be8c-be06b09d684e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr  待后面规划

**Comment by zhangdaiscott** [comment]
暂时收录到
https://github.com/jeecgboot/JeecgBoot/issues/1312
