### ISSUE TITLE
关于jeecgboot的online表单数据库字段默认值为空而不是空字符串

### ISSUE THREAD

**Issue by MuShan-bit** [jeecgboot/JeecgBoot#5956]
强烈建议不要让它为null，而是空字符串，可以避免很多问题

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312

**Comment by softboy99** [comment]
大佬，这个需求还没有搞定吗？
