### ISSUE TITLE
仪表盘不支持字典颜色配置项

### ISSUE THREAD

**Issue by lifeizhan** [jeecgboot/JeecgBoot#6086]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1.字典配置了文本颜色，前端没有使用这个颜色

2.仪表盘的API #{usename} 动态参数不能自动获取当前用户信息那要怎么传递

##### 截图&代码：
![8SOR3@S%8{V7}L@_K0P6R07](https://github.com/jeecgboot/jeecg-boot/assets/166230777/1a4f8efa-0eae-4b3d-ab7c-f34e987536e8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这边不支持字典颜色

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
配置的什么图表

**Comment by lsqGitHub716** [comment]
什么图表，怎样配置的？你想让字典颜色在哪里生效？

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312
