### ISSUE TITLE
autopoi通过word模板生成word时：三目、求长、常量、日期转换没起效果

### ISSUE THREAD

**Issue by xiaosehu** [jeecgboot/JeecgBoot#6096]
版本号：v3.4.3
前端版本：vue2版

问题描述：
1、三目、求长、常量、日期转换没起效果

截图&代码：
<img width="759" alt="d6e19d39439584ff1607902953e2e67" src="https://github.com/jeecgboot/jeecg-boot/assets/142964044/777b064a-05f5-4e60-a562-33dfcdb694a1">

代码：
XWPFDocument doc = WordExportUtil.exportWord07(templatePath, params);
String tmpPath = temDir + fileName;
FileOutputStream fos = new FileOutputStream(tmpPath);
doc.write(fos);

下面是我的word模板文件：
[export.docx](https://github.com/jeecgboot/jeecg-boot/files/14905644/export.docx)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
