### ISSUE TITLE
SuperQuery 高级查询

### ISSUE THREAD

**Issue by kikyolu** [jeecgboot/JeecgBoot#6101]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图看看

**Comment by GrongGao** [comment]
> 截图看看

![image](https://github.com/jeecgboot/jeecg-boot/assets/138291937/bb5d2e51-f672-41aa-81f0-68734dc723f8)

**Comment by Qiu-Jun** [comment]
> 级查询查询后关闭窗口 loading 状态未改变

一样，你确认会关闭弹窗吗

**Comment by peerles** [comment]
怎么解决？

**Comment by Qiu-Jun** [comment]
> 一样，查询后弹窗不关闭，一直loading状态

他们关闭了这个issue，你拉下最新代码看看吧。之前我们公司的，我自己手写了个，不用他们的
