### ISSUE TITLE
autoupoi可否升级支持poi5+

### ISSUE THREAD

**Issue by Yan31** [jeecgboot/JeecgBoot#6118]
##### 问题描述：
autoupi版本1.4.7，目前不支持poi升级到5+，此处会报错

##### 截图&代码：
![Snipaste_2024-04-12_14-23-07](https://github.com/jeecgboot/jeecg-boot/assets/36350691/96ad102b-b2b5-4c24-98f8-741dabfb3633)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312
