### ISSUE TITLE
自建Cloud模块找不到Mapper解决完之后，主键IdType.ASSIGN_ID新增会重复

### ISSUE THREAD

**Issue by pinktigerkk** [jeecgboot/JeecgBoot#6230]
各位大佬请教一个问题通过自动代码生成的基础代码之后我写了一个简单的查询但是一直报错
org.apache.ibatis.binding.BindingException:Invalid bound statement (not found)
找不到Mapper.xml的文件
![YA}FPPR(GM}C`@NBZI R_BU](https://github.com/jeecgboot/jeecg-boot/assets/45219794/417906f6-bf08-460a-8b7e-d2a5a7e4aaa3)

![ATF CVBJ(OLU J8`T3MAB2T](https://github.com/jeecgboot/jeecg-boot/assets/45219794/4d79610b-4485-4062-a061-1f5108856429)

然后我把xml文件挪到了resources下顺利找到了Mapper.xml的文件,但是在新增的时候会偶尔报错Duplicate entry '' for key 'PRIMARY'主键重复
![9G)6O%O@S%(HS VM$5I@{V3](https://github.com/jeecgboot/jeecg-boot/assets/45219794/afe31f76-0ddb-4bb0-8a49-da7255d04fe2)

然后我把实体类的Id改为ASSIGN_UUID之后就会正常新增不会重复请问有哪位大佬能解答一下这个问题
![Z~(JS3X9ZR5LX{`ES}ESYWS](https://github.com/jeecgboot/jeecg-boot/assets/45219794/f70e2316-1a50-42bb-8be0-f26e39cfe9ca)
![M$ L_29M79%J8Z3T(H85NRX](https://github.com/jeecgboot/jeecg-boot/assets/45219794/ccbb6cb2-4c24-4149-b0a7-1e21433f3ed9)

![image](https://github.com/jeecgboot/jeecg-boot/assets/45219794/0f497446-2331-4d46-ba0c-71bb4ddc31fe)

在启动类我手动加上了
@MapperScan({"org.jeecg.**.mapper.**"})因为之前没加会找不到Mapper文件

请问这个ASSIGN_ID(3)主键重复是因为我把Mapper.xml挪到了resources的原因吗

**Comment by EightMonth** [comment]
@Bean
public IdentifierGenerator identifierGenerator() {
    return new DefaultIdentifierGenerator(workerId, datacenterId);
}

该ID生成策略为雪花算法，多实例不指定workId, datacenterId可能会造成重复。
在启动类添加以上代码覆盖默认ID生成实现，可使用配置随机生成，再引入上述代码实现动态ID，默认通过网卡或mac码生成
