### ISSUE TITLE
autoApi导入数据错乱有时候还会报错

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#6244]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
我使用jeecg的代码生成器生成的导入接口导入excel数据错乱，而且还会报错，必须是先用jeecg生成好的导出接口先导出一个excel，在这个上面去修改添加数据，在导入才没问题，自己建的excel就有问题,就一个简简单单的列表dao'jin导进去还报错。

##### 截图&代码：
![1716386415106](https://github.com/jeecgboot/jeecg-boot/assets/132029411/45298dad-3400-447f-8520-51818b339d2c)
![1716386429530](https://github.com/jeecgboot/jeecg-boot/assets/132029411/dc52fd5b-f478-460d-a0c9-600f2f97bc5a)
![1716386481906](https://github.com/jeecgboot/jeecg-boot/assets/132029411/fe514b88-3297-4497-b946-f5b5bd4e1d68)
![46c4ff9463a7621145cc851de43844a](https://github.com/jeecgboot/jeecg-boot/assets/132029411/26ece498-b51d-477c-940e-44eddab03528)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
后台错误日志截图

**Comment by yzh20021029** [comment]
![1716520691454](https://github.com/jeecgboot/jeecg-boot/assets/132029411/255ab637-e193-4981-858f-31c07603d139)

**Comment by yzh20021029** [comment]
可以解决一下嘛

**Comment by jeecgos** [comment]
您需要先导出，在导出的文档中修改数据，再导入，这个应该是格式不匹配导致的。
