### ISSUE TITLE
autoApi导入excel报错。

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#6246]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：

我是用jeecg生成导入接口导入excel会报错，只有用jeecg生成的导出接口先导出一个excel，在这个excel上进行更改数据或者添加数据然后在导入就是正常的，如果是自己创建了个excel导入就会报错。
##### 截图&代码：
![1716388365525](https://github.com/jeecgboot/jeecg-boot/assets/132029411/f0b320b4-fb8b-46d4-9153-8b4b9b1a122b)
![1716388379406](https://github.com/jeecgboot/jeecg-boot/assets/132029411/5b51f2f5-a4ce-4a0e-a78b-ec28935508cf)
![3770ccecd6b59f3939fd1f240fc5367](https://github.com/jeecgboot/jeecg-boot/assets/132029411/30c8f7b5-0863-4865-9449-4d24bca3d7c1)
![1716388423336](https://github.com/jeecgboot/jeecg-boot/assets/132029411/f2298fd4-7d62-48fb-ac11-4e8da6b4bfea)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
你自己创建的格式对吗

**Comment by zhangdaiscott** [comment]
无回复关闭
