### ISSUE TITLE
POI 注解使用问题

### ISSUE THREAD

**Issue by qing-chen-zero** [jeecgboot/JeecgBoot#6256]
##### 问题描述：
在多个一对多的情况下，例如实体A有个@ExcellCollection的注解，属性类型是List<B>
在实体B中，又有多个@ExcelCollection的注解，例如
@ExcelCollection("第一个") 
private List<C> cs; 

@ExcelCollection("第二个") 
private List<D> ds; 

但是导出的时候，会导致嵌入的Collection对象不能正常的显示在excel文件中，显示的是list的value值
这种情况应该如何处理呢？是否在后续的计划中，考虑加入这种机制。

##### 截图&代码：

![Snipaste_2024-05-27_11-46-36](https://github.com/jeecgboot/jeecg-boot/assets/56945731/53e5bab8-ca8c-4719-a944-76d50447aca9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
版本号不对

**Comment by lwris** [comment]
> 版本号不对

需要更新到哪个版本？
