### ISSUE TITLE
请教关于使用autopoi导出问题

### ISSUE THREAD

**Issue by NameAce** [jeecgboot/JeecgBoot#6258]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue2版

##### 问题描述：

关于使用autopoi导出时，是否支持指定某一列，当这一列的值满足某个条件时，设置该单元格的样式。
比如：有一列“产品编码”，当“产品编码”为我设置的某些值时，设置该单元格的字体为红色。如下图所示
是否可以实现

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/42397253/d394f6d3-724f-41f9-9d8f-2de72b52fea0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
自动没有，可以自己实现导出逻辑

**Comment by lmhfq** [comment]
如何实现
