### ISSUE TITLE
敲敲云看板大屏,标注地图组件联动无反应

### ISSUE THREAD

**Issue by stiflerro** [jeecgboot/JeecgBoot#6263]
问题描述：
大屏中使用联网地图-在线地图.配置交互-组件联动.发布后,点击地图未能出发联动组件的动态数据的接口调用.

截图说明：
![image](https://github.com/jeecgboot/jeecg-boot/assets/24203193/96f21bc7-cf7f-43b5-b3f9-5946c4ae0a53)

重现步骤：
1.请问是那个 组织-应用-菜单 ?
大屏设计器-我的大屏

2.菜单访问链接是？
https://app.qiaoqiaoyun.com/myapps/screen

友情提示（为了提高issue处理效率）
未按格式要求发帖，会被直接删掉;
针对不好重现的问题，请录制视频或写明详细重现步骤;
输入图片说明
![image](https://github.com/jeecgboot/jeecg-boot/assets/24203193/cb3c25be-4874-4c88-b207-1680fe2471e2)

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
