### ISSUE TITLE
写接口的时候，要在这个接口里去调用第三方接口，并且第三方接口有多个部署环境，有不需要手动切换baseurl的实现方式吗

### ISSUE THREAD

**Issue by zgya** [jeecgboot/JeecgBoot#6269]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
写接口的时候，要在这个接口里去调用第三方接口，并且第三方接口有多个部署环境，有不需要手动切换baseurl的实现方式吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
没有
