### ISSUE TITLE
微服务多租户feign 调用,401

### ISSUE THREAD

**Issue by FWorldCodeZ** [jeecgboot/JeecgBoot#6271]
##### 问题描述：
FeignConfig  类需增加 Authorization 请求头，否则微服务多租户feign 调用会401，比如权限调用时就会出现该问题

**Comment by FWorldCodeZ** [comment]
同时,建议多租户redis缓存数据，进行按租户隔离

**Comment by leeore123** [comment]
我这里微服务用@dict注解，有时候突然会报401

**Comment by zhangdaiscott** [comment]
是不是接口慢导致？可以打印日志看看
