### ISSUE TITLE
用户首先登录然后再注册后，无法登陆

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/JeecgBoot#6272]
##### 问题描述：
用户如果没有注册先进行登录，然后再去注册后登录会出现无法登陆的情况
用户第一次登录缓存了NULL值，如果注册时不清理缓存，那么再次登录时将无法登陆

![image](https://github.com/jeecgboot/jeecg-boot/assets/7546194/566cc599-ff00-4a01-b478-dbb048d309b7)

##### 截图&代码：

解决办法： 在注册成功后，清理缓存
            redisUtil.del(CacheConstant.SYS_USERS_CACHE + "::" + username);

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by EightMonth** [comment]
按说明操作未复现该问题，先登录，后注册，再登录可成功登录
