### ISSUE TITLE
国际化语言包必须定义对象吗？如果是key是字符串就无法解析；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/JeecgBoot#6275]
##### 问题描述：国际化语言包的key定义成字符串无法解决，必须是对象类型才行；例如使用“sys.a.b.c”:"111"就不行，必须是
"sys":{
"a":{
"b":{
"c":"111"
}
}
}
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
必须，点是js的对象调用属性的意思
