### ISSUE TITLE
请问BasicTable 表格怎么根据某个字段值设置整行的样式？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#6278]
##### 问题描述：请问BasicTable 表格怎么根据某个字段值设置整行的样式？该字段不直接展示在列表上。
比如这条数据有个属性值<3，就将整行背景颜色设置成绿色，请问怎么处理

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by liaozhiyang** [comment]
有个rowClassName属性。
basicTable是基于antd table的，所以antd table属性方法基本都支持。[自定义带斑马纹](https://next.antdv.com/components/table-cn/#components-table-demo-stripe)


编码：
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/ea448c50-ada4-4b99-928b-85fd388689b1)
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/06be4ab8-77d7-4ab6-9c9b-919dc60affc3)

效果：
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/7a96fdd4-aa12-4520-83da-348f1433fbb7)
