### ISSUE TITLE
请问Auto Poi怎么设置单元格整行的背景颜色和文字颜色

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#6280]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by lsqGitHub716** [comment]
[Excel的样式自定义参考文档](https://ojrjjvdr7z.k.topthink.com/autopoi/autopoi/annotation/styleCustom.html)

[excel根据模板导出参考文档](https://ojrjjvdr7z.k.topthink.com/autopoi/autopoi/example/templateExport.html)
自定义文本的样式
![image](https://github.com/user-attachments/assets/bc61f570-5d18-446c-93fb-a0b626d26b82)

![image](https://github.com/user-attachments/assets/50a565c6-332c-4f20-aaec-90271d31ba3f)
