### ISSUE TITLE
头像/文件下载用到的JUpload组件中，download按钮不生效

### ISSUE THREAD

**Issue by Yaaeeee** [jeecgboot/JeecgBoot#6294]
##### 问题描述：

我将用户管理中-编辑-上传头像的组件从JImageUpload组件换成了JUpload组件，看JUpload里面有个参数是download，且官方的文档也有对download参数进行说明，但是不论我在user.data.ts中传不传download: true,这个参数，页面上都不会显示对应的下载按钮。

##### 截图&代码：

![企业微信截图_20240605150821](https://github.com/jeecgboot/jeecg-boot/assets/101372213/d233e486-78b6-49f0-9d4e-a67f871d762a)
![2](https://github.com/jeecgboot/jeecg-boot/assets/101372213/37730487-a3a5-4bd1-920f-1039f61da36d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/101372213/e4c957ad-8808-4bad-aa86-fc150f37b646)
![image](https://github.com/jeecgboot/jeecg-boot/assets/101372213/fd460f86-fd45-49bc-b65a-2c2c1e5c8eee)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
请用最新版试试
