### ISSUE TITLE
【用户管理】添加用户时，输入邮箱和手机号时，每输入一个字符，输入框就闪烁一下，体验不佳

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6323]
##### 版本号：
3.7.0

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3

##### 问题描述：
1. 新增用户时，输入邮箱和手机号时，每输入一个字符，就会校验下格式，输入框就闪烁一次，晃的眼晕
2. 在新增用户时，如果不小心点到抽屉窗口外面，抽屉窗口隐藏后，所有输入的数据都清空，要重新输入一次。

以上问题导致用户体验不佳，希望改善下。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请录个视频

**Comment by citynook** [comment]
@zhangdaiscott 
![screenshots](https://github.com/jeecgboot/jeecg-boot/assets/127393297/a2c0b045-4d89-4ff9-b771-ed591f5bddac)

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
修复了
