### ISSUE TITLE
3.7.0 ——nacos

### ISSUE THREAD

**Issue by YeyuchenBa** [jeecgboot/JeecgBoot#6328]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
3.7.0 的nacos 支持适配达梦吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by YeyuchenBa** [comment]
因为这个是jeecg 封装的nacos  nacos 2.x版本后就有dm插件了 我也集成不进来

**Comment by YeyuchenBa** [comment]
![Uploading 1718702781054.jpg…]()

**Comment by YeyuchenBa** [comment]
![1718702781054](https://github.com/jeecgboot/jeecg-boot/assets/117083299/ff757db7-a5f3-423e-ab3b-2895ab46ef51)

**Comment by zhangdaiscott** [comment]
可以直接用官方的先，没什么区别

**Comment by YeyuchenBa** [comment]
是否可以集成呢 这样不用单独整

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/nacos-dashboard/tree/master/nacos-2.2.3

**Comment by YeyuchenBa** [comment]
这个怎么集成替换 还是要单独在整一下吗.

**Comment by zhangdaiscott** [comment]
你下载源码，自己改一版
