### ISSUE TITLE
online生成代码导出功能提示没权限。

### ISSUE THREAD

**Issue by hnnhxy** [jeecgboot/JeecgBoot#6335]
##### 问题描述：
Online生成的代码放在默认位置后，页面打开正常，权限也增加授权过了， 增、删、改、查、导入都好使，就唯独导出提示没有权限。

##### 截图&代码：
![8245ba81c79fdff7d9966a0f35403164](https://github.com/jeecgboot/jeecg-boot/assets/173246353/76eef7a9-a615-4c5b-884b-a1cc6002b0ba)
![ef3f7c616c6200fc14c86ae361c9c0c8](https://github.com/jeecgboot/jeecg-boot/assets/173246353/9088470d-8b6c-42fe-91b6-5860fe220d26)
![ed86b8a8f16cf3c11e307ba1a652a5c9](https://github.com/jeecgboot/jeecg-boot/assets/173246353/e7cdb2e3-142c-4376-a336-6e79f0ec6a50)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台报什么错误，贴一下

**Comment by hnnhxy** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/173246353/ba890d18-076c-4393-9d49-7557e7c49895)

**Comment by zhangdaiscott** [comment]
看看是不是生成的权限配置，手工改下，我这边测没问题

**Comment by hnnhxy** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/173246353/52b1cfbe-3e3c-42bc-af9e-3b11afd2f4f0)
后端代码放的位置对么？
![image](https://github.com/jeecgboot/JeecgBoot/assets/173246353/d2ab5a30-293f-4dcf-abc4-d4aebf0c8f32)
那个地方看生成的权限。

**Comment by zhangdaiscott** [comment]
生成的菜单插入 sql

**Comment by zhangdaiscott** [comment]
我这边测试没问题
