### ISSUE TITLE
Oline表单下拉搜索框控件在编辑页面报错：字典Code格式不正确

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/JeecgBoot#6336]
##### 问题描述：
Oline表单配置控件类型为下拉搜索框时，配置数据字典后，新增、查询、保存、列表都正常，但是在编辑时会提示“字典Code格式不正确”，经过测试只支持配置数据表和字段了，之前版本这样使用没有问题。

分析原因是因为加载页面是调用的接口为loadDictItem而不是getDictItems，在loadDictItem方法中判断code代码没有逗号则报错。

期望：修复该bug，跟之前版本一样，在编辑时不报错。

##### 截图&代码：

![image](https://github.com/jeecgboot/JeecgBoot/assets/16589026/770eb7d0-0cc6-4238-a25a-afbd68b9eb15)

![1718797931207](https://github.com/jeecgboot/JeecgBoot/assets/16589026/83d3ca15-b887-4acd-ae90-868b882d3f5c)

![image](https://github.com/jeecgboot/JeecgBoot/assets/16589026/21b68e5c-1e15-473e-a1b9-5c9844e729a3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/4be24213-adf3-4255-819c-5b87b0b1fcfa)
之前online下拉搜索框只支持表字典，不支持数据字典。
该功能已添加，下一版本发布。
