### ISSUE TITLE
vue3页面列表不展示

### ISSUE THREAD

**Issue by hada-02** [jeecgboot/JeecgBoot#6337]
版本号：3.7

分支： master

前端版本: vue3

问题描述：将生成的前端代码贴进前端以后，列表展示不出来，前端没有调用list接口。但是添加、导出功能正常，用knife4j测试后端接口都正常。

截图&代码：
![微信图片_20240620093315](https://github.com/jeecgboot/JeecgBoot/assets/148771766/9e80b3ca-f9db-4bff-b5ee-e79094087f04)
![微信图片_20240620093650](https://github.com/jeecgboot/JeecgBoot/assets/148771766/dd0c8ea3-edc8-4295-b4c9-9dbec774126c)
![微信图片_20240620094851](https://github.com/jeecgboot/JeecgBoot/assets/148771766/9cdbd610-fb6b-4e69-8a89-7d08302e6698)

友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12什么错

**Comment by hada-02** [comment]
> F12什么错
![微信图片_20240620103751](https://github.com/jeecgboot/JeecgBoot/assets/148771766/5cf3cf3d-ba16-4d6f-b564-59af3b507b0f)

**Comment by zhangdaiscott** [comment]
是接口不通还是接口返回null，这种问题自己跟一下不是更快吗

**Comment by hada-02** [comment]
> 是接口不通还是接口返回null，这种问题自己跟一下不是更快吗

是根本没调接口。api里面有list，这串前端代码是直接从生成里面拉出来的，没有修改过。跟着哔哩哔哩那个视频原封不动也是没有展示出列表。

**Comment by zhangdaiscott** [comment]
不清楚，我们这边测试没问题
