### ISSUE TITLE
项目启动报XXX表不存在。数据库中是小写的表名  比如：Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist   存在的表是eecg-boot.qrtz_locks

### ISSUE THREAD

**Issue by windInJune** [jeecgboot/JeecgBoot#6340]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写
https://jeecg.com/doc/qa 
问题2
