### ISSUE TITLE
表单开发中编辑保存超时

### ISSUE THREAD

**Issue by arturc63oby** [jeecgboot/JeecgBoot#6343]
##### 版本号：
3.6.3

##### 分支： master？还是springboot3?
 master

##### 前端版本: vue3版？还是 vue2版？
vue3版

##### 问题描述：
online 表单开发，能新增无法编辑

##### 截图&代码：
![image](https://github.com/jeecgboot/JeecgBoot/assets/153253671/ba1f1715-6027-458d-b2aa-c77f71e4f0fe)
![image](https://github.com/jeecgboot/JeecgBoot/assets/153253671/00174a9d-cdf5-4b7d-93ca-1617c6787d3e)
![image](https://github.com/jeecgboot/JeecgBoot/assets/153253671/053cdeea-faf6-4618-9ca9-a415d9c6a385)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前端和后端版本一致吗

**Comment by arturc63oby** [comment]
> 前端和后端版本一致吗

一致

**Comment by zhangdaiscott** [comment]
不清楚，建议升级到最新版
