### ISSUE TITLE
Redis health check failed

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JeecgBoot#6346]
##### 问题描述：启动报错Redis health check failed
org.springframework.data.redis.RedisSystemException: Cannot read Redis info; nested exception is java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

##### 截图&代码：
![image](https://github.com/jeecgboot/JeecgBoot/assets/74187378/597da2ae-0dad-49f7-8f70-ef596d34bd06)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 12341234-yangboran** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/74187378/9693556e-256d-4ca0-8f0c-7ee84579cdd4)

**Comment by zhangdaiscott** [comment]
补充版本号

**Comment by 12341234-yangboran** [comment]
3.7.0

**Comment by zhangdaiscott** [comment]
测试无问题
![image](https://github.com/jeecgboot/JeecgBoot/assets/3162115/7b38691e-9c65-4daa-8341-ee7cfb53dffb)

**Comment by necan** [comment]
不要用 Windows 版本的 Redis，有 BUG，换成 Linux 版本的 Redis 就没有此问题！
