### ISSUE TITLE
printJS的type === 'html'无法分页

### ISSUE THREAD

**Issue by q060831** [jeecgboot/JeecgBoot#6348]
版本号：3.5.3

问题描述：printJS当type为html时，调用的是`vue-print-nb-jeecg`插件，这个插件不支持`page-break-after: always`分页.改成调用print-js就没有这个问题

截图&代码：

![printjs](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/24561313-62fc-4215-b1b1-6b29d471066f)

![nb](https://github.com/jeecgboot/jeecgboot-vue3/assets/23691018/60c9190c-b91d-4cef-8dd2-891a9b5ba755)

**Comment by zhangdaiscott** [comment]
暂时收录
