### ISSUE TITLE
【吐槽大会】请吐槽vue3版本不好用不宜用的地方

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/JeecgBoot#6349]
官方即将开展vue3不宜用、不好用、封装过于复杂的专项工作，请大家在评论区留言，我们会根据大家的需求去改进优化！！

**Comment by 12345ZMTHL** [comment]
> vue3版本感觉很好用，开发起来很快。 但是打包后样式出现问题一致困扰我 #6396
> 
> BasicTable封装的有点狠，我一般都直接用vue3原生form

加一，刚刚就被折磨了一波，找个查询参数找半天，心态都有点小崩.......
