### ISSUE TITLE
jvxetable 使用编辑的时候卡顿问题；同时发现滚动条也会有卡顿的问题

### ISSUE THREAD

**Issue by Adonis-li** [jeecgboot/JeecgBoot#6353]
##### 版本号：
3.6.0

##### 问题描述：
jvxetable 有严重卡顿现象，我访问了官网部署后的程序一样有卡顿。访问地址为：http://boot3.jeecg.com/jeecg/j-vxe-table-demo/normal；访问的是高级示例的表格。展开二百条后。下拉选和输入框的延迟特别的高。能达到好几秒才能响应；进度条也会有明显的卡顿问题

##### 截图&代码：

https://github.com/jeecgboot/jeecgboot-vue3/assets/53810297/6ad00ec9-5a43-4589-9bc5-90def7de45e6

![1703487206664](https://github.com/jeecgboot/jeecgboot-vue3/assets/53810297/4396ce73-6d2b-44d1-acba-bece7e7a33cf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liwenzheng-git** [comment]
问题解决了吗
