### ISSUE TITLE
聚合路由没有效果，而是直接跳转到了某一个页面

### ISSUE THREAD

**Issue by csf-hub** [jeecgboot/JeecgBoot#6354]
##### 问题描述：
菜单中配置完聚合路由没有效果，而是直接跳转到了某一个页面

##### 截图&代码：
<img width="1080" alt="1" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/82623310/ef65f0e0-3f8a-4be0-acce-491deeaa4d1f">
<img width="1008" alt="2" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/82623310/000d7396-7d34-408c-8cd8-78764d191f3f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
归集到 https://github.com/jeecgboot/JeecgBoot/issues/7089
