### ISSUE TITLE
微应用接入，二级页面动态路由，菜单只配置了微应用一级页面，点击二级页面，UI错误，且点击其他tab，路由无响应

### ISSUE THREAD

**Issue by huying12345** [jeecgboot/JeecgBoot#6356]
##### 问题描述：微应用以qiankun接入，二级页面（审批详情）是子应用动态路由
情况1. 菜单只配置了子应用一级页面，点击二级页面，UI显示错误；
情况2. 若把二级页面配置了菜单，且相关角色权限已配置，当进入二级页面之后，点击其他tab，路由无响应，页面报错。
在该二级页面点击回退按钮返回后，tab又可以正常点击。

##### 截图&代码：
报错时，tablist 打印：[
    {
        "meta": {
            "keepAlive": false,
            "internalOrExternal": false,
            "icon": "ant-design:bank-filled",
            "componentName": "Analysis",
            "title": "首页",
            "ignoreKeepAlive": true,
            "affix": true
        },
        "name": "dashboard-workbench",
        "path": "/dashboard/workbench",
        "params": {},
        "query": {},
        "fullPath": "/dashboard/workbench"
    },
    {
        "fullPath": "/cmsBpm/processList",
        "path": "/cmsBpm/processList",
        "query": {},
        "hash": "",
        "name": "cmsBpm-processList",
        "params": {},
        "meta": {
            "keepAlive": true,
            "internalOrExternal": true,
            "icon": "ant-design:appstore-twotone",
            "componentName": "index",
            "title": "工作台",
            "single": true,
            "affix": false,
            "ignoreKeepAlive": false,
            "loaded": false
        },
        "href": "/cmsBpm/processList",
        "matched": [
            {
                "meta": {
                    "keepAlive": false,
                    "internalOrExternal": false,
                    "icon": "ion:grid-outline",
                    "componentName": "index",
                    "title": "Dashboard",
                    "single": true,
                    "affix": false
                },
                "name": "dashboardParent",
                "path": ""
            },
            {
                "meta": {
                    "keepAlive": true,
                    "internalOrExternal": true,
                    "icon": "ant-design:appstore-twotone",
                    "title": "工作台",
                    "ignoreKeepAlive": false
                },
                "name": "cmsBpm-processList",
                "path": "/cmsBpm/processList"
            }
        ]
    },
    {
        "fullPath": "/cmsBpm/taskDetail/254/b00233e5-5c1b-11ed-a0a3-5ae4308428c9",
        "path": "/cmsBpm/taskDetail/254/b00233e5-5c1b-11ed-a0a3-5ae4308428c9",
        "query": {},
        "hash": "",
        "name": "cmsBpm-taskDetail-@id-@processInstanceId",
        "params": {
            "id": "254",
            "processInstanceId": "b00233e5-5c1b-11ed-a0a3-5ae4308428c9"
        },
        "meta": {
            "keepAlive": false,
            "internalOrExternal": false,
            "icon": "ant-design:pull-request-outlined",
            "componentName": "index",
            "title": "审批详情",
            "single": true,
            "affix": false,
            "hideMenu": true,
            "hideTab": true,
            "hideBreadcrumb": true,
            "ignoreKeepAlive": true,
            "loaded": false
        },
        "href": "/cmsBpm/taskDetail/254/b00233e5-5c1b-11ed-a0a3-5ae4308428c9",
        "matched": [
            {
                "meta": {
                    "keepAlive": false,
                    "internalOrExternal": false,
                    "icon": "ion:grid-outline",
                    "componentName": "index",
                    "title": "Dashboard",
                    "single": true,
                    "affix": false
                },
                "name": "dashboardParent",
                "path": ""
            },
            {
                "meta": {
                    "hideMenu": true,
                    "keepAlive": false,
                    "internalOrExternal": false,
                    "hideTab": true,
                    "icon": "ant-design:pull-request-outlined",
                    "title": "审批详情",
                    "hideBreadcrumb": true,
                    "ignoreKeepAlive": true
                },
                "name": "cmsBpm-taskDetail-@id-@processInstanceId",
                "path": "/cmsBpm/taskDetail/:id/:processInstanceId"
            }
        ]
    }
]

<img width="837" alt="1" src="https://user-images.githubusercontent.com/23715980/203947474-21eb2f50-2a75-44cd-90ac-27f34dc16d9f.png">
<img width="833" alt="2" src="https://user-images.githubusercontent.com/23715980/203947486-8d4ff6ea-a0d7-48dc-aa26-775276f82d82.png">
<img width="667" alt="3" src="https://user-images.githubusercontent.com/23715980/203947496-3043b8c7-816f-412a-a58c-eef509beede4.png">
<img width="308" alt="4" src="https://user-images.githubusercontent.com/23715980/203947506-6f56cd4d-9ab3-4a39-8cb8-ea1569c28a8d.png">
<img width="682" alt="5" src="https://user-images.githubusercontent.com/23715980/203947539-a4ae31f0-302a-40ff-ba20-656735984e92.png">
<img width="708" alt="6" src="https://user-images.githubusercontent.com/23715980/203947514-e120b37f-e1b2-4bc2-9710-6e2ec5acfdc1.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by benben120** [comment]
可以给个 接入qiankun的完整示例代码看下吗 大大
