### ISSUE TITLE
为什么树状表格远程数据有展开按钮，但先获取数据再把数据赋给dataSource就没有展开按钮，子数据都是异步获取的，配置expandIconColumnIndex也没用

### ISSUE THREAD

**Issue by ayss-xjh** [jeecgboot/JeecgBoot#6358]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/665b0f00-a268-4985-a44b-a6fff1e4ba34)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/55195263/3f97013f-493b-400d-8057-82d0707ad598)

##### 前端安装环境：node18

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
能贴代码吗？
静态数据中有children吗？

下图dataSource 就是静态数据，能出现展开按钮：

![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/e9a8e23a-cdf8-4842-aeca-6b62a09c5fae)
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/dc80eda5-ed7b-40a4-b144-386060094cfd)
