### ISSUE TITLE
selectedRowKeys.value = 在什么时机 进行赋值呢

### ISSUE THREAD

**Issue by axinger** [jeecgboot/JeecgBoot#6359]
##### 截图&代码： 目前使用这样方式
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/18339649/6cc99ce2-1556-4c77-b945-201d63a72382)

然后在选中后 selectionChange,

  <BasicTable @register="registerTable" :rowSelection="rowSelection" @selection-change="selectionChange">
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/18339649/d61ca03b-7415-48c3-8cd2-560b9a5c751f)

  function selectionChange(val: any) {
    console.log('selectionChange = ' + JSON.stringify(val));
}
![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/18339649/ffc8c452-68e2-4ed1-b045-2f0054341bab)

![图片](https://github.com/jeecgboot/jeecgboot-vue3/assets/18339649/c1d42879-18fa-44ef-896a-a47b7495b85d)

只能获取到最新点击的数据,  "keys":["16000001","16000002","16000003","16000004","16000005"],   "rows":[{"id":"16000005",........}]  ,这里没有 selectedRowKeys.value =  起初赋值的 数据,   selectedRowKeys.value = 在什么时机 进行赋值呢

**Comment by liaozhiyang** [comment]
通过你上面的描述，测试应该是这个地方的问题。
你可试下，如有结果可反馈：
<img width="1134" alt="image" src="https://github.com/jeecgboot/JeecgBoot/assets/8199499/19153618-8ed0-4b19-a367-27c089156292">
