### ISSUE TITLE
uni-app，online表单开发的接口，如何获取字典表的label名称

### ISSUE THREAD

**Issue by duanzhihuaData** [jeecgboot/JeecgBoot#6362]
##### 版本号：
3.6.3

##### 问题描述：
使用online表单开发，其中工地id字段使用字典表配置，web端可展示字典表名称。在uni-app中如何获取工地id的名称？目前接口返回没有_dictText这个属性。

##### 截图&代码：
![J9E}9Z~{@%@VTVQU%{G$Y0X](https://github.com/jeecgboot/jeecgboot-vue3/assets/58547522/8c20a925-12f9-411c-b8a9-1f41187ad07a)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
你意思online表单这里配置的表字典，这uniapp里面渲染的不对吗？请加一些截图描述一下你的业务场景？

**Comment by zhangdaiscott** [comment]
无回复，关闭
