### ISSUE TITLE
Jpopup增强

### ISSUE THREAD

**Issue by zhaokun1300352** [jeecgboot/JeecgBoot#6363]
##### 版本号：
3.6.1

##### 问题描述：
Jpopup增强。建议Jpopup添加如下方法，可以更加精细的管理modal

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/77821202/a3a3617c-8881-4603-b001-5eefb87cb519)
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/77821202/4c2f0d20-e35b-4776-83b2-b481e1e45196)

用法

![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/77821202/54e965bf-6534-41a3-acaf-db3efafe1564)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312
