### ISSUE TITLE
JPopup弹窗选择组件如何渲染图片？

### ISSUE THREAD

**Issue by Misaka10148** [jeecgboot/JeecgBoot#6365]
##### 版本号：
3.6.3

##### 问题描述：
JPopup弹窗选择组件配置了对应的online报表，在online报表中存在一个存放图片url地址的字段，在JPopup弹窗只显图片url地址，无法渲染对应的图片。
JPopup弹窗选择组件是否支持渲染图片？前端代码如何修改才能渲染图片？
##### 截图&代码：
![微信截图_20240612182832](https://github.com/jeecgboot/jeecgboot-vue3/assets/81210336/54453c56-55fe-49ff-8908-be17c25f8fd2)
![微信截图_20240612182921](https://github.com/jeecgboot/jeecgboot-vue3/assets/81210336/40766821-cfde-480c-ba03-9ba800a9ce6a)
![微信截图_20240612183014](https://github.com/jeecgboot/jeecgboot-vue3/assets/81210336/bc1d9929-2fb0-4f28-8b4f-a963e371bc42)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已新增该功能，下一版本发布。
