### ISSUE TITLE
BasicTable 表格搜索表单，“展开/收起”操作反应问题

### ISSUE THREAD

**Issue by chenmonkey** [jeecgboot/JeecgBoot#6369]
##### 问题描述：当BasicTable 表格搜索表单，搜索项为7个（默认收起状态，每行展示4个搜索项）时，“展开/收起”操作反应问题
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32865506/6d1f00cf-4d33-4a22-b54c-3f89a45d5494)

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32865506/056e688e-53b1-4277-814a-fb7a87c786d0)

当BasicTable 表格搜索项展开正好排列两行时，第一次点击展开，显示是“展开”状态，但是搜索项并未展开
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/32865506/6e7a237b-ece0-43b2-a425-4f9874748126)
继而点击“收起”操作，表单项展开又自动恢复到收起，第三次点击“展开/收起”操作才正常

**Comment by zhangdaiscott** [comment]
请确认最新版是否存在问题

**Comment by chenmonkey** [comment]
依旧存在，tabs标签页下，存在此问题

**Comment by liaozhiyang** [comment]
![iShot_2024-07-09_20 05 28](https://github.com/jeecgboot/JeecgBoot/assets/8199499/215448de-2b6e-4bb8-a16e-d69eb2e7cf12)
有更详情的信息吗？这边测试没复现

**Comment by chenmonkey** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/32865506/831c1c26-3632-485d-9722-59749e653aca)
![image](https://github.com/jeecgboot/JeecgBoot/assets/32865506/f368254b-56d6-4399-a27c-fc25786badbb)
改动 系统监控-日志管理 代码如下
1.修改monitor-index.vue代码
```
<template>
  <div>
    <a-tabs defaultActiveKey="4" @change="tabChange" size="small">
      <a-tab-pane tab="异常日志" key="4">
        <TableList logType="4" />
      </a-tab-pane>
      <a-tab-pane tab="登录日志" key="1">
        <TableList logType="1" />
      </a-tab-pane>
      <a-tab-pane tab="操作日志" key="2">
        <TableList logType="2" />
      </a-tab-pane>
    </a-tabs>
  </div>
</template>
<script lang="ts" name="monitor-log" setup>
  import { ref } from 'vue';
  import TableList from './TableList.vue';
</script>
<style lang="less" scoped>
  .error-box {
    white-space: break-spaces;
  }
</style>
```
2.新增monitor-TableList.vue代码

**Comment by liaozhiyang** [comment]
写法有问题，换成getSearchSchema.value即可。

![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/91d7e9ef-777b-4c88-b754-0bce8ab161fb)

computed其实没用，最好是直接判断即可。
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/2a9da3a3-ac63-49c3-b36d-78fe3be9305b)
