### ISSUE TITLE
3.7.0 BasicForm component 为DatePicker或MonthPicker等组件下赋值默认值 defaultValue会报错

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6373]
##### 版本号：
3.7.0 

##### 问题描述：
BasicForm component 为DatePicker或MonthPicker等组件下赋值默认值 defaultValue会报错

##### 截图&代码：
![image](https://github.com/jeecgboot/JeecgBoot-vue3/assets/162244360/a774fac7-32ba-40ec-b838-458ee464d48a)
![image](https://github.com/jeecgboot/JeecgBoot-vue3/assets/162244360/f0411f79-b80c-4739-9cbb-ba7248f6bf27)
![image](https://github.com/jeecgboot/JeecgBoot-vue3/assets/162244360/4878a133-e078-4118-8038-e3889d328e10)
![image](https://github.com/jeecgboot/JeecgBoot-vue3/assets/162244360/2098a1eb-0db8-4d47-abe1-aa4b077c6458)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
经测试，没复现。你上面的图打不开，请提供更相信的信息
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/b7f20581-2b0a-4b16-bb97-e9522fa221c5)

**Comment by benben120** [comment]
> 经测试，没复现。你上面的图打不开，请提供更相信的信息 ![image](https://private-user-images.githubusercontent.com/8199499/344992730-b7f20581-2b0a-4b16-bb97-e9522fa221c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODk0OTMsIm5iZiI6MTcxOTk4OTE5MywicGF0aCI6Ii84MTk5NDk5LzM0NDk5MjczMC1iN2YyMDU4MS0yYjBhLTRiMTYtYmI5Ny1lOTUyMmZhMjIxYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDY0NjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVjYjYxMDE5MzMzMTA5ZTRiMzFkOGIzOTQ4ZjA4OTlkNDg5ZDEzNWM1MTk5Y2U3ZjczYzkxNDI0NGZhNjg1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6aoj7MzK63BMQ4iQCXhZCMD12uUe0JSyXy48v6Gh7Qg)

直接使用 new Date() 未转译就会报错无法执行

**Comment by liaozhiyang** [comment]
直接使用new Date()不可以。
antd 规定了value是dayjs对象，你可以dayjs(new Date())，在使用了valueFormat下，value也可使用字符串（如我上图所示）
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/7b83a72d-6ead-4646-829e-8886a17551f3)
