### ISSUE TITLE
暗黑主题模式下，按钮风格不一致，有的显示边框，有的不显示，并且鼠标放在按钮上的时候，也没有焦点显示

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6374]
##### 版本号：
3.7.0

##### 问题描述：
暗黑主题模式下，按钮风格不一致，以【用户管理】为例：
查询按钮没有显示边框，鼠标放在上面也没有反应，
重置按钮显示边框，鼠标放在上面会有焦点反应。

工具条上的新增、导出等按钮，以及项目配置面板中的复制按钮，都和查讯按钮一样。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/32491b6d-5ef6-4b62-9e87-82e6d2824b43)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/033a1343-a611-4b73-bf5e-fe086594870f)

你本地可可在src/design/index.less 文件按如下进行修改：
```
html[data-theme='dark'] {
  .jeecg-form-detail-effect {
    * {
      color: #606266;
    }
    .ant-upload-text-icon, a {
      color:rgba(255, 255, 255, 0.25) ;
    }
    .ant-select-selector,
    .ant-btn,
    .ant-input,
    .ant-input-affix-wrapper,
    .ant-picker,
    .ant-input-number {
      background-color: transparent !important;
    }

    .ant-select-selection-item {
      background-color: transparent !important;
    }
    // 暗黑模式下输入框等icon隐藏
    .ant-picker-suffix,.ant-select-arrow {
      content:" ";
      display: none;
    }
  }
}
```
