### ISSUE TITLE
componentProps函数形式，在updateSchema中无效

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#6375]
##### 版本号：
3.6.2

##### 问题描述：
在updateSchema中设置componentProps，函数形式不生效，原因是`src/utils/index.ts`中`deepMerge`里：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/19619291/bfe39c43-aa36-48a6-9ed5-b5e4fa46b138)

**Comment by zhangdaiscott** [comment]
请先更新到最新版 3.7.0
