### ISSUE TITLE
jeecg仪表板打不开

### ISSUE THREAD

**Issue by HJY-666** [jeecgboot/JeecgBoot#6382]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 截图&代码：
![image](https://github.com/jeecgboot/JeecgBoot/assets/58809237/997703c6-427d-405c-9bdd-285cc9252248)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本号多少，
老版本的话，gateway缺少网关请求配置
