### ISSUE TITLE
多租户模式下，【租户角色】新增角色后，列表中看不到新增记录，在【角色管理】中可以看到

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6383]
##### 版本号：
3.7.0

##### 问题描述：
多租户模式下，【租户角色】新增角色后，列表中看不到新增记录，在【角色管理】中可以看到。

感觉和多租户相关的一些功能总是出问题，希望可以完整测试下。

##### 截图&代码：
![screenshots 1](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/8eaf5804-818f-4921-abd5-1c42f1ae0d1f)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by LvJianfeng** [comment]
@zhangdaiscott 3.9.3又发生了同样的问题
