### ISSUE TITLE
国际化 推荐I18n-ally插件配置配置问题

### ISSUE THREAD

**Issue by zyf-0208** [jeecgboot/JeecgBoot#6389]
##### 截图&代码：
我的配置:
![q1](https://github.com/jeecgboot/jeecgboot-vue3/assets/58580072/07331acb-4c47-4519-a447-f6b8b9c12431)
展示效果:
第一条插件可以显示出来但不正确,第二条才是正确的代码
![q2](https://github.com/jeecgboot/jeecgboot-vue3/assets/58580072/744da10d-fecb-491f-9646-a4d57c4c892a)

##### 前端安装环境：

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?
- node版本号：？
- pnpm版本号：？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jkhuang** [comment]
@zyf-0208 @zhangdaiscott 我也遇到通用问题，请问怎么解决的？
