### ISSUE TITLE
JSelectUser选择用户     选择非第一页用户后，再次选择时 ，无法选择，且网页直接卡死

### ISSUE THREAD

**Issue by hyc-chinese** [jeecgboot/JeecgBoot#6391]
##### 问题描述：用于表单内时， 组件选择用户时，选择第非第一页用户后 点击确认， 表单正确回显，再点击表单选择 时，此时直接页面卡死 ，不报任何错误，组件页无法选择，
 如果在第一次选择后，如过要再选择用户，先清空第一次的选择 ，此时载重新选择 ，则不会导致此BUG出现

##### 截图&代码：
{
      field: 'otherEmails',
      component: 'JSelectUser',
      label: '其他抄送人',
      componentProps: {
        rowKey: 'email',
        labelKey: 'realname',
      },
    },

##### 前端安装环境： windows

> 如果你是启动报错，请说明你的前端环境

- 采用的是pnpm安装还是yarn?   pnpm
- node版本号：？  16.5.1
- pnpm版本号：？ 8.6

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by CharlesWuu** [comment]
这个需要改动哪里?有提交的修改记录看吗?
