### ISSUE TITLE
JVxeTable列过长（出现横向滚动条）时无法拖拽排序

### ISSUE THREAD

**Issue by RamboWu** [jeecgboot/JeecgBoot#6399]
##### 版本号：

3.5.3
##### 问题描述：
JVxeTable 中 加入了Dragsort属性后，如果 columns的宽度过长，出现横条滚动条的时候，将无法拖拽，只能进行点击拖拽

##### 截图&代码：

![90293ecaa677a34b50a91fc9f60706e](https://github.com/jeecgboot/jeecgboot-vue3/assets/3425194/7c2dd813-a045-48ed-847c-78cd2a7062ac)
![7c7632e16cc6b7a97a195806e1fbd75](https://github.com/jeecgboot/jeecgboot-vue3/assets/3425194/69f3b290-818a-4bbb-9ac4-9f10db8de7b7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 1372037590** [comment]
你好，截图看不到，可以再发一下吗

**Comment by RamboWu** [comment]
> 确实有该问题，是因为columns中的dragSort和rowSelection默认是fixed:left导致。如果要解决该问题则fixed不可设置。
> 
> 已修复，下一版本发布。 你本地可按如下文件进行修改
> 
> src/components/jeecg/JVxeTable/src/vxe.data.ts 文件: <img alt="image" width="1258" src="https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/86c20694-264b-4b2e-bd16-490bb0d03f46">
> 
> ```
>   dragSortFixed: propTypes.oneOf(['left', 'none']).def('left'),
>   rowSelectionFixed: propTypes.oneOf(['left', 'none']).def('left'),
> ```
> 
> src/components/jeecg/JVxeTable/src/hooks/useColumns.ts 文件中： ![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/5f0d29fb-e19c-4990-bcba-7a2e9fb7e525) ![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/bbfba5aa-94ba-4e09-b0d8-b9324b4690f5)
> 
> src/views/demo/jeecg/JVxeTableDemo/JVxeDemo3.vue 文件： ![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/8199499/71f9c7be-89db-438f-836a-365facb680d2)

可以发一下你的图片嘛

**Comment by RamboWu** [comment]
@liaozhiyang 可以发一下你的图片么，看不到了。

**Comment by RamboWu** [comment]
@liaozhiyang 没事了，我在 项目中看到了代码

**Comment by 1372037590** [comment]
@RamboWu 请问源码在哪，只看到【issues/1162】JVxeTable列过长（出现横向滚动条）时无法拖拽排序 的处理，但加上去好像没有用

**Comment by liaozhiyang** [comment]
@1372037590 你可以看看这个例子。
![image](https://github.com/user-attachments/assets/f398ab14-0267-4626-a46c-bc0ae49bd8ea)

**Comment by 1372037590** [comment]
@liaozhiyang 谢谢，可以了，看文档真不知道怎么配
