### ISSUE TITLE
online表单开发页面打开报错 The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=53eb7e43' does not provide an export named 'default'

### ISSUE THREAD

**Issue by STAR5201** [jeecgboot/JeecgBoot#6400]
##### 版本号：
jeecgbootVue3 3.6.3
node v18.1.0
npm 8.8.0
8.15.5
##### 问题描述：
1项目运行报错找不到src\common\mixin\Mixin.js
2路由打开在线开发报错
无法打开在线开发页面,点击菜单跳转,控制台报错
The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=53eb7e43' does not provide an export named 'default'
##### 截图&代码：
![QQ截图20240330194014](https://github.com/jeecgboot/jeecgboot-vue3/assets/53025758/dd121d50-b1c3-443a-9bb5-2a709aee4e89)
![QQ截图20240330194112](https://github.com/jeecgboot/jeecgboot-vue3/assets/53025758/65ece726-04c9-45ee-a72e-142dfbae9961)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by a6666669** [comment]
![1723537267788](https://github.com/user-attachments/assets/f6be3424-eaf2-4527-8491-cc2ab3de2405)
