### ISSUE TITLE
BasicTable行编辑（editRow、record.onEdit）,reload之后无法拿到二次编辑的值

### ISSUE THREAD

**Issue by HaoyuLee** [jeecgboot/JeecgBoot#6474]
##### 截图&代码：

官网示例可复现
1. 行编辑并保存
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/32022ca4-3c1f-4f01-97c2-3fc91e6cb3dc)
2. reload 列表
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/c8b3b9c4-836e-4cb9-b143-fb25831539e9)
3. 二次编辑-保存
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/37102468/be5563e1-ecba-499d-a5ba-6ad5ece51b16)

**Comment by hang132** [comment]
> > 前几天我已经找到原因，在我们代码中自己解决了一下。 关键代码位置
> > ```
> > // src/components/Table/src/components/editable/EditableCell.vue  348行
> > // 应该是只有该组件首次渲染时才会附加editValueRefs等属性，reload之后dataSource重新赋值，但是此处代码没有重新执行，也就丢失了这些属性
> > if (props.column.dataIndex) {
> >   if (!props.record.editValueRefs) props.record.editValueRefs = {};
> >   props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
> > }
> > ```
> 
> 我这边也有同样问题，在配置表格时，去掉“rowKey”配置，或者设置空，就能正常保存了。应该是设置了Rowkey之后，Vue的diff算法原因，record的部分方法没有追加上去（ submitCbs、validCbs、CancelCbs等），所以导致valid一直为false
> 
> @zhangdaiscott 烦请官方解决一下呢

也不太行是为什么啊

**Comment by hang132** [comment]
> rowKey

怎么解决的

**Comment by terry8210** [comment]
怎么解决的

**Comment by 1404zlz** [comment]
> > 前几天我已经找到原因，在我们代码中自己解决了一下。关键代码位置
> > ```
> > // src/components/Table/src/components/editable/EditableCell.vue  348行
> > // 应该是只有该组件首次渲染时才会附加editValueRefs等属性，reload之后dataSource重新赋值，但是此处代码没有重新执行，也就丢失了这些属性
> > if (props.column.dataIndex) {
> >   if (!props.record.editValueRefs) props.record.editValueRefs = {};
> >   props.record.editValueRefs[props.column.dataIndex] = currentValueRef;
> > }
> > ```
> 
> 我这边也有同样问题，在配置表格时，去掉“rowKey”配置，或者设置空，就能正常保存了。应该是设置了Rowkey之后，Vue的diff算法原因，record的部分方法没有追加上去（ submitCbs、validCbs、CancelCbs等），所以导致valid一直为false
> 
> @zhangdaiscott 烦请官方解决一下呢

rowKey="",就能解决，强无敌啊老哥

**Comment by szh18** [comment]
一摸一样的问题 第一次可以保存成功 第二次就死活校验不过去了 没有editValueRefs属性

**Comment by heaxo** [comment]
我也出现了，重新设置setTableData后editValueRefs属性丢失....

**Comment by heaxo** [comment]
这个问题没解决，咋关闭了。目前只能去掉rowKey吗？
