### ISSUE TITLE
下载最新版本运行时报错：无法读取 file:///xxxxx 错误

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6505]
##### 版本号：
jeecgboot-vue3: 2023.9.28下载的源码
node: 18.16.1
pnpm : 8.8.0

##### 问题描述：
2023.9.28日下载最新版本，未做任何修改，登录系统后，vscode 控制台输出错误信息：
  [vite] connecting...
[vite] connected.
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/vue-grid-layout%403.0.0-beta1_%40interactjs%2Bcore%401.10.19_%40interactjs%2Butils%401.10.19/node_modules/vue-grid-layout/dist/webpack%3A/VueGridLayout/node_modules/%40interactjs/core/defaultOptions.js 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.19_@interactjs+utils@1.10.19\node_modules\vue-grid-layout\dist\webpack:\VueGridLayout\node_modules\@interactjs\core\defaultOptions.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/vue-grid-layout%403.0.0-beta1_%40interactjs%2Bcore%401.10.19_%40interactjs%2Butils%401.10.19/node_modules/vue-grid-layout/dist/webpack%3A/VueGridLayout/node_modules/mitt/dist/mitt.es.js 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\vue-grid-layout@3.0.0-beta1_@interactjs+core@1.10.19_@interactjs+utils@1.10.19\node_modules\vue-grid-layout\dist\webpack:\VueGridLayout\node_modules\mitt\dist\mitt.es.js.map'
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
geo3D exists.
geo3D exists.
---初始化---， 全局注册仪表盘--------------
node_modules import.meta:  {url: 'http://localhost:3100/node_modules/.pnpm/@jeec…es/@jeecg/online/index-6a09a912.mjs?v=44c62821', resolve: ƒ}
--- online init ----
注册antd组件完成！
[Vue Router warn]: Absolute path "/testTab/id1" must have the exact same param named "id" as its parent "/feat/testTab/:id".
[Vue Router warn]: Absolute path "/feat/testTab/id2" must have the exact same param named "id" as its parent "/feat/testTab/:id".
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/helper.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\helper.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/data/dateSplits.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\data\dateSplits.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/data/const.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\data\const.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/date/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\date\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/levenshtein.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\levenshtein.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/data/l33tTable.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\data\l33tTable.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/data/translationKeys.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\data\translationKeys.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/matching/unmunger/TrieNode.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\matching\unmunger\TrieNode.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/matching/unmunger/l33tTableToTrieNode.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\matching\unmunger\l33tTableToTrieNode.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/Options.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\Options.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/matching/reverse.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\matching\reverse.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/matching/unmunger/getCleanPasswords.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\matching\unmunger\getCleanPasswords.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/matching/l33t.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\matching\l33t.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/regex/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\regex\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/scoring/utils.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\scoring\utils.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/bruteforce/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\bruteforce\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/date/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\date\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/scoring/uppercase.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\scoring\uppercase.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/variants/scoring/l33t.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\variants\scoring\l33t.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/regex/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\regex\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/repeat/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\repeat\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/sequence/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\sequence\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/spatial/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\spatial\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/separator/scoring.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\separator\scoring.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/scoring/estimate.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\scoring\estimate.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/scoring/index.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\scoring\index.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/repeat/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\repeat\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/sequence/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\sequence\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/spatial/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\spatial\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/separator/matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\separator\matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/Matching.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\Matching.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/TimeEstimates.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\TimeEstimates.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/bruteforce/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\bruteforce\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/date/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\date\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/dictionary/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\dictionary\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/regex/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\regex\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/repeat/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\repeat\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/sequence/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\sequence\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/spatial/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\spatial\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/matcher/separator/feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\matcher\separator\feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/Feedback.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\Feedback.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/debounce.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\debounce.js.map'
无法读取 file:///D:/Work/Gitlab/Maxbase/maxbase-vue/node_modules/.pnpm/%40zxcvbn-ts%2Bcore%403.0.4/node_modules/%40zxcvbn-ts/core/src/index.ts 的源映射: ENOENT: no such file or directory, open 'd:\Work\Gitlab\Maxbase\maxbase-vue\node_modules\.pnpm\@zxcvbn-ts+core@3.0.4\node_modules\@zxcvbn-ts\core\src\index.js.map'

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/127393297/bda0bac9-943e-45d9-9c16-367b7f6dfe59)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by delicacyyy** [comment]
![Image](https://github.com/user-attachments/assets/fcac9ac2-e841-4376-81c2-073d51815f37) 我这边也是
