### ISSUE TITLE
如何实现Tab切换时，保持页面的筛选条件和表格数据不变。

### ISSUE THREAD

**Issue by wallace46886799** [jeecgboot/JeecgBoot#6542]
##### 版本号：
jeecgboot-vue3 3.4.4
##### 问题描述：
如何实现Tab切换时，保持页面的筛选条件和表格数据不变，谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by softboy99** [comment]
这个问题在最新的3.7版本依然存在
