### ISSUE TITLE
动态路由菜单启用了“缓存路由”后，切换tab时页面依旧会刷新

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6543]
##### 版本号：
V3.5.1

##### 问题描述：
路由菜单在启用“是否缓存路由”后，切换tab时页面不会刷新，但动态路由菜单在换切tab时页面依旧会刷新。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by softboy99** [comment]
@xiaogangya12138 的方法有效， @citynook ,

**Comment by softboy99** [comment]
@zhangdaiscott ， @xiaogangya12138 ， @citynook ，

静态和动态路由都支持，菜单里配不配组件名称都可以：

<img width="837" height="658" alt="Image" src="https://github.com/user-attachments/assets/bf7c3e17-2fda-48e7-8879-223eda3b23de" />
