### ISSUE TITLE
在centos7中下载依赖pnpm i时 mozjpeg依赖下载不下来

### ISSUE THREAD

**Issue by flowerburied** [jeecgboot/JeecgBoot#6551]
##### 版本号：
3.5.0

##### 问题描述：

在centos7中下载依赖pnpm i时
mozjpeg依赖下载不下来

看过别人的issues替换依赖包,但没有解决根本问题
https://github.com/jeecgboot/jeecgboot-vue3/issues/375

希望官方解决在centos7下依赖不能pnpm i一键下载的问题

##### 截图&代码：

```
└─ Failed in 9.7s at /opt/front_end_project_address/passengertransport/passengerTransport_vue3/node_modules/.pnpm/registry.npmmirror.com+mozjpeg@7.1.1/node_modules/mozjpeg
 ELIFECYCLE  Command failed with exit code 1.
```
![image](https://user-images.githubusercontent.com/35652270/228418264-474f8b7d-4f0b-4f9b-b649-869f476f8163.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 13124243593** [comment]
<img width="1554" height="712" alt="Image" src="https://github.com/user-attachments/assets/6a8e7196-8590-4a4b-b4de-abec77e9bf84" />
