### ISSUE TITLE
提示"[JVxeTable] normal 组件尚未注册，获取增强失败"

### ISSUE THREAD

**Issue by 1161325721** [jeecgboot/JeecgBoot#6555]
##### 版本号：
3.4.4 vue3

##### 问题描述：
实现步骤：
1、创建一个按钮
2、创建一个modal弹窗
3、在里面modal弹窗添加一个JVxeTable
4、页面中点击按钮弹窗打开，弹窗可以正常打开
5、随便修改代码，我这边将第28行的代码注释掉
6、再次点击按钮出现报错

modal如果设置destroyOnClose，还会出现整个浏览器页面会卡住，电脑cpu飙到100%，只能强制关掉浏览器
F5刷新页面后可以解决问题，但这导致在开发时每次修改代码后都要刷新页面，有点麻烦

##### 截图&代码：
<img width="667" alt="1671640009722" src="https://user-images.githubusercontent.com/61100025/208955066-a1ca35f0-1d96-4ddd-a3ad-4698cbcab2e8.png">
<img width="473" alt="1671639127124" src="https://user-images.githubusercontent.com/61100025/208955104-0abe9835-ed45-4819-9933-1bc6651f2bb7.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by softboy99** [comment]
已经关闭，解决了吗？
