### ISSUE TITLE
打包后时间控件无法选择

### ISSUE THREAD

**Issue by mujun1209** [jeecgboot/JeecgBoot#6557]
##### 版本号：
3.4.3

##### 问题描述：
打包发布后时间控件无法选择

##### 截图&代码：
 <a-col :lg="8">
              <a-form-item label="到仓提货开始时间">
                <a-time-picker
                  placeholder="请输入到仓提货开始时间"
                  value-format="HH:mm:ss"
                  v-model:value="queryParam.pickTimeStart"
                  style="width: 100%"
                />
              </a-form-item>
            </a-col>

![image](https://user-images.githubusercontent.com/1551206/205542329-68577423-bfa0-493c-924d-bada98cfde8e.png)

点击时间选择组件后，组件就消失了。怀疑是有事件冲突了，日期选择也有相同问题。在本地开发启动不存在该问题。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jiangyuhui0922** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
