### ISSUE TITLE
iframe 打开本地目录html文件无效问题。急急急急！！！！！

### ISSUE THREAD

**Issue by luo969** [jeecgboot/JeecgBoot#6560]
##### 问题描述：最新3.4.4版本的。iframe 配置src 为本地路径的html。无法打开，直接跳转回首页。

旧的v1.2.0 | Vue3前端UI 2022-06-06 的版本就可以正常打开。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15951772/203685590-1b97e16c-961c-4ffb-992f-59d02c2c9399.png)
就直接调回首页，如下图
![image](https://user-images.githubusercontent.com/15951772/203685801-14bf0c24-a142-4ef7-b475-0de56701050d.png)
![image](https://user-images.githubusercontent.com/15951772/203685847-37f22b95-1856-4b99-9b3c-ce70e858aaad.png)

测试的index2.html的本地路径和Index.html同级
![image](https://user-images.githubusercontent.com/15951772/203686674-9148c409-3a79-46fd-a4bd-7c1722c703cf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by l1518501871** [comment]
你好！我使用iframe也遇到了同样的情况，想知道怎么处理
