### ISSUE TITLE
Tag mismatch! 报错但是不影响使用

### ISSUE THREAD

**Issue by oweson** [jeecgboot/JeecgBoot#6632]
##### 版本号：

master分支，3.7.0

##### 问题描述：
Tag mismatch! 报错但是不影响使用

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/37206469/1bf0252d-aac2-4ca1-8fd8-008a5439aa13)

#### 友情提示：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请确保问题描述清楚，方便我们理解并一次性调查解决问题；
  - 如果使用的不是master，请说明你使用的那个分支

**Comment by lzq52066** [comment]
我也碰到了这个问题，网上说是shiro记住我功能产生的问题，把cookie清除以后我就没这个问题了

**Comment by oweson** [comment]
> 我也碰到了这个问题，网上说是shiro记住我功能产生的问题，把cookie清除以后我就没这个问题了
清除不行，开个无痕浏览器就没事了，太奇怪了
