### ISSUE TITLE
微服务版本 启动nacos报错

### ISSUE THREAD

**Issue by dong76880** [jeecgboot/JeecgBoot#6633]
##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/28744763/a0a44b86-73bb-4f63-bdeb-0a950a2828b0)

是否是jar包冲突？

#### 友情提示：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请确保问题描述清楚，方便我们理解并一次性调查解决问题；
  - 如果使用的不是master，请说明你使用的那个分支

**Comment by dong76880** [comment]
"C:\Program Files\Java\jdk1.8.0_131\bin\java.exe" "-javaagent:E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.1.1\lib\idea_rt.jar=59983:E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.1.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;E:\hs\dev\coding-sxyr\jeecg3.7.0\jeecg-boot\jeecg-server-cloud\jeecg-cloud-nacos\target\classes;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\tomcat\embed\tomcat-embed-jasper\9.0.83\tomcat-embed-jasper-9.0.83.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\tomcat\embed\tomcat-embed-core\9.0.83\tomcat-embed-core-9.0.83.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\tomcat\tomcat-annotations-api\9.0.83\tomcat-annotations-api-9.0.83.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\tomcat\embed\tomcat-embed-el\9.0.83\tomcat-embed-el-9.0.83.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\eclipse\jdt\ecj\3.26.0\ecj-3.26.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-security\2.7.18\spring-boot-starter-security-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter\2.7.18\spring-boot-starter-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-autoconfigure\2.7.18\spring-boot-autoconfigure-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-logging\2.7.18\spring-boot-starter-logging-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\logging\log4j\log4j-to-slf4j\2.17.0\log4j-to-slf4j-2.17.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-core\5.3.31\spring-core-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-jcl\5.3.31\spring-jcl-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-aop\5.3.31\spring-aop-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-beans\5.3.31\spring-beans-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\security\spring-security-config\5.7.11\spring-security-config-5.7.11.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\security\spring-security-core\5.7.11\spring-security-core-5.7.11.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\security\spring-security-crypto\5.7.11\spring-security-crypto-5.7.11.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-context\5.3.31\spring-context-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\security\spring-security-web\5.7.11\spring-security-web-5.7.11.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-expression\5.3.31\spring-expression-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-web\5.3.31\spring-web-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-naming\2.2.3\nacos-naming-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-core\2.2.3\nacos-core-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-common\2.2.3\nacos-common-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-consistency\2.2.3\nacos-consistency-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\caucho\hessian\4.0.63\hessian-4.0.63.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-auth\2.2.3\nacos-auth-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-sys\2.2.3\nacos-sys-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-custom-environment-plugin\2.2.3\nacos-custom-environment-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-trace-plugin\2.2.3\nacos-trace-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-test\5.3.31\spring-test-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-test\2.7.18\spring-boot-test-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\alipay\sofa\jraft-core\1.3.12\jraft-core-1.3.12.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\ow2\asm\asm\6.0\asm-6.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\rocksdb\rocksdbjni\7.7.3\rocksdbjni-7.7.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\net\java\dev\jna\jna\5.5.0\jna-5.5.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jctools\jctools-core\2.1.1\jctools-core-2.1.1.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\lmax\disruptor\3.3.7\disruptor-3.3.7.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\alipay\sofa\hessian\3.3.6\hessian-3.3.6.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\dropwizard\metrics\metrics-core\4.2.22\metrics-core-4.2.22.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\alipay\sofa\rpc-grpc-impl\1.3.12\rpc-grpc-impl-1.3.12.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-webmvc\5.3.31\spring-webmvc-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-api\2.2.3\nacos-api-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot\2.7.18\spring-boot-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-web\2.7.18\spring-boot-starter-web-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-json\2.7.18\spring-boot-starter-json-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.5\jackson-datatype-jdk8-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.5\jackson-datatype-jsr310-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.5\jackson-module-parameter-names-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\codehaus\jackson\jackson-core-asl\1.9.13\jackson-core-asl-1.9.13.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\ch\qos\logback\logback-classic\1.2.12\logback-classic-1.2.12.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\ch\qos\logback\logback-core\1.2.12\logback-core-1.2.12.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\javatuples\javatuples\1.2\javatuples-1.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\httpcomponents\httpclient\4.5.14\httpclient-4.5.14.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\mysql\mysql-connector-java\8.0.28\mysql-connector-java-8.0.28.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\slf4j\log4j-over-slf4j\1.7.36\log4j-over-slf4j-1.7.36.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\slf4j\jcl-over-slf4j\1.7.36\jcl-over-slf4j-1.7.36.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-cmdb\2.2.3\nacos-cmdb-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\micrometer\micrometer-registry-prometheus\1.9.17\micrometer-registry-prometheus-1.9.17.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\micrometer\micrometer-core\1.9.17\micrometer-core-1.9.17.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\hdrhistogram\HdrHistogram\2.1.12\HdrHistogram-2.1.12.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\prometheus\simpleclient_common\0.15.0\simpleclient_common-0.15.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\micrometer\micrometer-registry-elastic\1.9.17\micrometer-registry-elastic-1.9.17.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\micrometer\micrometer-registry-influx\1.9.17\micrometer-registry-influx-1.9.17.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-actuator\2.7.18\spring-boot-starter-actuator-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-actuator-autoconfigure\2.7.18\spring-boot-actuator-autoconfigure-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-actuator\2.7.18\spring-boot-actuator-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-istio\2.2.3\nacos-istio-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-client\2.2.3\nacos-client-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-auth-plugin\2.2.3\nacos-auth-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\prometheus\simpleclient\0.15.0\simpleclient-0.15.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\prometheus\simpleclient_tracer_otel\0.15.0\simpleclient_tracer_otel-0.15.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\prometheus\simpleclient_tracer_common\0.15.0\simpleclient_tracer_common-0.15.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\prometheus\simpleclient_tracer_otel_agent\0.15.0\simpleclient_tracer_otel_agent-0.15.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-netty-shaded\1.50.2\grpc-netty-shaded-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\guava\guava\31.1-android\guava-31.1-android.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\checkerframework\checker-qual\3.12.0\checker-qual-3.12.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\errorprone\error_prone_annotations\2.14.0\error_prone_annotations-2.14.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\perfmark\perfmark-api\0.25.0\perfmark-api-0.25.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-core\1.50.2\grpc-core-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\code\gson\gson\2.9.1\gson-2.9.1.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\android\annotations\4.1.1.4\annotations-4.1.1.4.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\codehaus\mojo\animal-sniffer-annotations\1.21\animal-sniffer-annotations-1.21.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-protobuf\1.50.2\grpc-protobuf-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-api\1.50.2\grpc-api-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-context\1.50.2\grpc-context-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-protobuf-lite\1.50.2\grpc-protobuf-lite-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\grpc\grpc-stub\1.50.2\grpc-stub-1.50.2.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\api\grpc\proto-google-common-protos\2.7.1\proto-google-common-protos-2.7.1.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\google\protobuf\protobuf-java\3.21.11\protobuf-java-3.21.11.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\io\envoyproxy\controlplane\api\0.1.27\api-0.1.27.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-config\2.2.3\nacos-config-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-jdbc\2.7.18\spring-boot-starter-jdbc-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\zaxxer\HikariCP\4.0.3\HikariCP-4.0.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-jdbc\5.3.31\spring-jdbc-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\spring-tx\5.3.31\spring-tx-5.3.31.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\commons-io\commons-io\2.7\commons-io-2.7.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\derby\derby\10.14.2.0\derby-10.14.2.0.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-encryption-plugin\2.2.3\nacos-encryption-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\httpcomponents\httpasyncclient\4.1.5\httpasyncclient-4.1.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\httpcomponents\httpcore-nio\4.4.16\httpcore-nio-4.4.16.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-tomcat\2.7.18\spring-boot-starter-tomcat-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.83\tomcat-embed-websocket-9.0.83.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\core\jackson-core\2.13.5\jackson-core-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\core\jackson-databind\2.13.5\jackson-databind-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\com\fasterxml\jackson\core\jackson-annotations\2.13.5\jackson-annotations-2.13.5.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\boot\spring-boot-starter-aop\2.7.18\spring-boot-starter-aop-2.7.18.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\aspectj\aspectjweaver\1.9.7\aspectjweaver-1.9.7.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-contrl-plugin\2.2.3\nacos-contrl-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-datasource-plugin\2.2.3\nacos-datasource-plugin-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-console\2.2.3\nacos-console-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-plugin-default-impl\2.2.3\nacos-plugin-default-impl-2.2.3.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\springframework\ldap\spring-ldap-core\2.4.1\spring-ldap-core-2.4.1.jar;E:\hs\dev\coding-sxyr\maven\mavenRepository\org\jeecgframework\nacos\nacos-prometheus\2.2.3\nacos-prometheus-2.2.3.jar" com.alibaba.nacos.JeecgNacosApplication

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 13592
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://192.168.31.233:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2024-06-22 17:15:26.607  INFO 13592 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8848 (http)
2024-06-22 17:15:26.902  INFO 13592 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2710 ms
2024-06-22 17:15:29.276  WARN 13592 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namingHealthController': Unsatisfied dependency expressed through field 'healthOperatorV2'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthOperatorV2Impl' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\librocksdbjni6547979714819021860.dll: Can't find dependent libraries
2024-06-22 17:15:29.298  INFO 13592 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: C:\Users\Administrator\nacos\logs
2024-06-22 17:15:29.299  INFO 13592 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: C:\Users\Administrator\nacos\conf
2024-06-22 17:15:29.299  INFO 13592 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: C:\Users\Administrator\nacos\data
2024-06-22 17:15:29.301 ERROR 13592 --- [           main] c.a.n.c.l.StartingApplicationListener    : Startup errors : 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namingHealthController': Unsatisfied dependency expressed through field 'healthOperatorV2'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthOperatorV2Impl' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/E:/hs/dev/coding-sxyr/maven/mavenRepository/org/jeecgframework/nacos/nacos-naming/2.2.3/nacos-naming-2.2.3.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\librocksdbjni6547979714819021860.dll: Can't find dependent libraries
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at com.alibaba.nacos.JeecgNacosApplication.main(JeecgNacosApplication.java:33)

**Comment by zhangdaiscott** [comment]
jdk几？怎么出现的，我们没遇到过

**Comment by dong76880** [comment]
jdk1.8；按照官网文档配置单服务为微服务，然后，启动nacos服务 时就出现了。

**Comment by zhangdaiscott** [comment]
数据库配置了吗

**Comment by dong76880** [comment]
运行了 ，官网的  tables_nacos.sql，  可能是我本地环境的问题，我单独下载的阿里的nacos.zip  也报同样问题

**Comment by zhangdaiscott** [comment]
好的，看看是不是jdk什么的问题
