### ISSUE TITLE
企业微信登录成功后没有给登录用户设置登录部门，orgCode为空，导致添加其它的数据没有自动注入sys_org_code

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#6634]
##### 版本号：
3.6.3
##### 问题描述：
企业微信登录成功后调用/getLoginUser/{token}/{thirdType}/{tenantId}这个接口没有给登录用户设置登录部门，orgCode为空，导致添加其它的数据没有自动注入sys_org_code,我提一下意见，就是这个登录的部门不能默认取这个用户所属部门的第一个部门，应该是所有的部门为登录部门，如果都是默认取第一个部门为登录部门，那其它的所属部门就没办法做权限了
##### 错误截图：
![1719071944085](https://github.com/jeecgboot/JeecgBoot/assets/132029411/11405f3b-aa93-4565-99e5-c724f47842f8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请确保问题描述清楚，方便我们理解并一次性调查解决问题；
  - 如果使用的不是master，请说明你使用的那个分支

**Comment by zhangdaiscott** [comment]
ws

**Comment by yzh20021029** [comment]
这个后续会处理吗

**Comment by 1298191366** [comment]
已修复，待新版本发布
