### ISSUE TITLE
数据字典中，条件规则，提示"数据值不能包含特殊字符"

### ISSUE THREAD

**Issue by LelandACM** [jeecgboot/JeecgBoot#6638]
##### 版本号：
vue3: 3.7.0
##### 问题描述：
数据字典的值只能是数字或者字符串，目前已有的添加的数据字典不能够编辑，会提示错误
##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/19402747/9fa3e448-c484-4fb6-b504-b3b4d57e3898)

临时解决办法：
我注释了下面的判断条件
```
 if (new RegExp("[`~!@#$^&*()=|{}'.<>《》/?！￥（）—【】‘；：”“。，、？]").test(value)) {
    return Promise.reject('数据值不能包含特殊字符！');
 }
```

#### 友情提示：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请确保问题描述清楚，方便我们理解并一次性调查解决问题；
  - 如果使用的不是master，请说明你使用的那个分支

**Comment by zhangdaiscott** [comment]
特殊字符不允许，目前允许下划线横岗

**Comment by huangwei2013** [comment]
挺限制字典的使用范围的，本来想作为配置表来用
