### ISSUE TITLE
JVxeTable linkageConfig优化建议

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6639]
##### 版本号：
3.7.0

##### 问题描述：
// 优化1 - linkageKey 支持1对多 或者多个parent对应一个子级
JVxeTable // 联动下一级的字段key： linkageKey?: string;
可以优化成 可以支持联动多个下级字段吗？
比如 字段a联动linkageKey: 'b,c'
支持选择a后自动带出b和c的联动下拉，
目前只支持一种下一级字段，局限性有点高

// 优化2 - requestData 回调支持返回对象 而不是固定id
在实际场景中，如果关联的多层级联动下拉里 每一个层级调用的api接口不一样，超过两个层级时，第三层级无法判断第二层级的parent是哪个key值，如果返回对应的父级对象object，可以取自己想取的字段 会便利很多

#### 友情提示：
  - 未按格式要求发帖、描述过于简单，会被直接删掉;
  - 描述问题 请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明使用的分支;

**Comment by CodeXiaoYan** [comment]
哈哈哈我用另一种方法实现了这个需求，linkageKey确实满足不了

**Comment by benben120** [comment]
> 哈哈哈我用另一种方法实现了这个需求，linkageKey确实满足不了

展开说说？

**Comment by CodeXiaoYan** [comment]
改源码啊，取当前行的值做options

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312
