### ISSUE TITLE
autoapi导出嵌套了两层的循环列表数据，只导出了外层数据

### ISSUE THREAD

**Issue by allerLee** [jeecgboot/JeecgBoot#6641]
##### 问题描述：

使用autoapi自定义模版excel导出时，循环嵌套了两层数据，只导出了第一层数据，可以导出多层数据吗？

##### 错误截图：

模板：![模板](https://github.com/jeecgboot/JeecgBoot/assets/59719045/1398c0a3-b671-4c59-b154-08f88c08f4a2)
导出文件：
![导出文件](https://github.com/jeecgboot/JeecgBoot/assets/59719045/88f98a72-4a90-41ab-91fa-ab06c947625c)

数据格式截图：
 
![数据格式](https://github.com/jeecgboot/JeecgBoot/assets/59719045/1c6bc585-1328-474d-813b-4cb3a901d2f8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
cr

**Comment by lsqGitHub716** [comment]
真长情况下，你需要生成的单据是什么样的，感觉你配置的这个数据结构和循环有问题。
