### ISSUE TITLE
积木报表token校验失败

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JeecgBoot#6642]
##### 问题描述：
打开积木报表页面失败

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/74187378/d640be0b-db31-438c-8ca6-1af86b672a62)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
怎么不带着token访问

**Comment by 12341234-yangboran** [comment]
是按照文档中的方式通过路径跳转的
![Uploading image.png…]()

**Comment by 12341234-yangboran** [comment]
3.7.0版本不能这样访问吗

**Comment by 12341234-yangboran** [comment]
没事了，从低代码开发-积木报表设计能跳进去
