### ISSUE TITLE
错误信息语句不通顺

### ISSUE THREAD

**Issue by citynook** [jeecgboot/JeecgBoot#6643]
##### 版本号：
3.7.0

##### 问题描述：
jeecg-boot-base-core/src/main/java/org/jeecg/common/desensitization/util/SensitiveInfoUtil.java
jeecg-boot-base-core/src/main/java/org/jeecg/common/exception/JeecgBootExceptionHandler.java
上面两个文件中的错误信息感觉是不通顺的，是否应为：”没有权限，请联系管理员授权，然后刷新缓存！“ 或 ”没有权限，请联系管理员授权后刷新缓存！“

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/127393297/4e9bd062-213b-412e-9258-7b109e6f36e4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
收到
