### ISSUE TITLE
启动报错依赖冲突问题？

### ISSUE THREAD

**Issue by zxzMrzxz** [jeecgboot/JeecgBoot#6644]
##### 问题描述：
启动报错
The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/96802834/b3e5f772-289a-4b0a-ab78-38f01d279aa9)

**Comment by zhangdaiscott** [comment]
你写的什么版本号

**Comment by zxzMrzxz** [comment]
不好意思，版本号写错了 我拉的最新的代码，拉下来后修改了yaml，redis和mysql地址，启动后就会报这个
![image](https://github.com/jeecgboot/JeecgBoot/assets/96802834/ed9c9704-f1a0-44d3-87c2-37b12a3bed14)



Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-06-25 16:25:10.093 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter:40 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Disconnected from the target VM, address: '127.0.0.1:49904', transport: 'socket'

Process finished with exit code 1
