### ISSUE TITLE
Online表单开发-页面属性日期类型选择年月日

### ISSUE THREAD

**Issue by wangyanna13** [jeecgboot/JeecgBoot#6645]
##### 版本号：
v3.6.3 使用的tag：v3.6.3分支

##### 问题描述：
Online表单开发-页面属性日期类型选择年月日，高级配置中没有如下日期格式可供选择：

年
年月
年周
年季度
年月日

**Comment by wangyanna13** [comment]
Online表单开发-页面属性日期类型选择年月日，高级配置中有日期格式可供选择

**Comment by zhangdaiscott** [comment]
升级到最新版
