### ISSUE TITLE
Online表单-代码生成器bug

### ISSUE THREAD

**Issue by testnet0** [jeecgboot/JeecgBoot#6647]
##### 版本号：
V3.7.0

##### 问题描述：
Online表单开发，选择生成内嵌子表风格，生成的前端代码有bug：
![image](https://github.com/jeecgboot/JeecgBoot/assets/18673513/01d561db-65b8-4ba3-9e7d-41e73d2aaede)
获取数据使用了res.result.records，实际后端返回数据中不包含records字段而是res.result,会导致子表展开数据没办法加载
![image](https://github.com/jeecgboot/JeecgBoot/assets/18673513/666832d6-f2d4-4af0-b100-6ff9889f6520)

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/18673513/338ba8ea-1352-4ea9-9ec8-b0f5dd9b44b7)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
今天刚测试没问题啊，内嵌可以展开

**Comment by testnet0** [comment]
> 生成内嵌子表风格

可以展开 但是数据没有，你看下前端获取数据loadData的代码呢

**Comment by testnet0** [comment]
在线测试是没问题的，生成的代码不行，我手动改成了dataSource.value = res.result;才行

**Comment by zhangdaiscott** [comment]
就是生成的代码，测试没问题

**Comment by testnet0** [comment]
不好意思，目前看来问题是调整了表单风格，没有替换后端代码导致的
