### ISSUE TITLE
前后端版本适配问题

### ISSUE THREAD

**Issue by coral-zone** [jeecgboot/JeecgBoot#6648]
##### 问题描述：
请问下，后端版本3.0.0 能用前端jeecgboot-vue3版本的吗？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下载最新版
