### ISSUE TITLE
自建服务启动报错

### ISSUE THREAD

**Issue by YeyuchenBa** [jeecgboot/JeecgBoot#6649]
##### 问题描述：
自建服务启动报错

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/117083299/01730fef-c31d-4ef1-af96-c2b5640e46cf)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
单体还是微服务

**Comment by YeyuchenBa** [comment]
微服务 自建的新模块服务

**Comment by YeyuchenBa** [comment]
新模块启动报的错误

**Comment by YeyuchenBa** [comment]
其他 的system  demo  nacos  网关 都正常启动  新建的服务 启动报错

**Comment by zhangdaiscott** [comment]
https://www.bilibili.com/video/BV1WS421d72B/?spm_id_from=333.788&vd_source=cb14e69038db5fdd4d51267bbb548dd7

无法判断，自己看视频吧
