### ISSUE TITLE
开启租户数据隔离，接入钉钉后默认租户为0了

### ISSUE THREAD

**Issue by zivchen666** [jeecgboot/JeecgBoot#6652]
##### 问题描述：
1.开启了租户数据隔离，且在浏览器登录能正确加载租户，显示正确的数据。
2.接入钉钉后请求接口，显示租户id为0，不能正确加载数据。

##### 错误截图：
1.浏览器正确的租户id：
![1719473242233](https://github.com/jeecgboot/JeecgBoot/assets/66064612/a19b4692-7cd9-472a-8d3e-7c8705e6beae)

2.钉钉错误的id：
![image](https://github.com/jeecgboot/JeecgBoot/assets/66064612/93c348b4-d98f-4d7a-86c4-c2b8d7ae5ea9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zivchen666** [comment]
> 怎么接入的钉钉?

按照官方文档(http://doc.jeecg.com/2292480#_41)，走的h5微应用接入的。
ps：
1.接入后登录，功能都是正常的。只是数据权限不对，开启了租户隔离，因为第三方登录后再请求接口看到tenantId 为0，所以不对。
2.手动在右上角切换租户，选择唯一的租户后，数据是对的了。但是这里三方登录应该是还是有问题的。

**Comment by 1298191366** [comment]
已修复，待新版本发布
