### ISSUE TITLE
BasicTable组件dataSource属性当一页的数据量100左右，滚动table会出现[Vue warn]: Unhandled error during execution of watcher callback

### ISSUE THREAD

**Issue by desheng** [jeecgboot/JeecgBoot#6653]
##### 版本号：
3.7

##### 问题描述：
BasicTable组件dataSource属性当一页的数据量100左右，滚动table会出现[Vue warn]: Unhandled error during execution of watcher callback
并进一步引发 RangeError: Maximum call stack size exceeded 错误！
ps：这应该是表格的渲染和更新过程引起了递归调用过多的问题。

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/73417804/672a9d55-ff9b-449a-9995-5d82f4b5f512)
![image](https://github.com/jeecgboot/JeecgBoot/assets/73417804/17072b06-accb-4c3e-a4ec-effcd1e15ad3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by desheng** [comment]
我的table数据中含有图片，80/页开始就会不断的递归调用，其他纯文本数据table目前没有这个问题
![image](https://github.com/jeecgboot/JeecgBoot/assets/73417804/8607a235-c969-47db-b824-9e3de5328235)

**Comment by zhangdaiscott** [comment]
zy

**Comment by desheng** [comment]
请问有解决方案吗？

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/2043806b-394e-4d06-b2f7-c49010d111a3)
开发和生产都没复现，有更详细的信息吗？你可在系统用户页面也试试

**Comment by desheng** [comment]
我这边系统用户页面测试也没问题，是不是我所有的图片都使用外链的原因造成的（本地没有保存图片），100条/页时需要加载外链图片

**Comment by liaozhiyang** [comment]
图片太大太多会引起一定的卡顿，但是你上面那个报错应该是有程序一直在运行导致的，你检查下代码，看是否有遗漏。
可提供代码上来定位是底层引起的还是业务引起的，否则这边没法帮定位。

**Comment by desheng** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/73417804/3ed8d9b4-eff6-40a9-9747-2673e9df3ea5)
这是代码、没有进行改动，

**Comment by liaozhiyang** [comment]
既然系统用户那边没问题，那你看这边和那边写的有什么不同？根据目前提供的信息没复现该问题。

**Comment by desheng** [comment]
系统用户那边是用的customRender: render.renderAvatar,   我这里是renderImage，查了好久没查出什么问题...
