### ISSUE TITLE
只部署系统服务和自己的业务服务使用过程会token失效

### ISSUE THREAD

**Issue by FuFengs** [jeecgboot/JeecgBoot#6654]
##### 问题描述：
后端部署方式只用部署了系统服务和自己写的业务模块,在使用过程中会fegin调用系统的接口获取用户信息,接口调用失败就会返回登录页面重新登陆,这个有没有什么解决方法. 

##### 错误截图：
![QQ图片20240627100410](https://github.com/jeecgboot/JeecgBoot/assets/146088638/f019d3f8-29ca-4330-ac91-137cdc0732cc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个为什么会报这样 问题？

**Comment by FuFengs** [comment]
这个是 在使用过程中 不定时 会出现这个问题

**Comment by zhangdaiscott** [comment]
提供重现步骤，不然无法处理
