### ISSUE TITLE
vue3前端tableContext解构出来的getRawDataSource没有数据

### ISSUE THREAD

**Issue by ve03** [jeecgboot/JeecgBoot#6656]
##### 版本号：
3.6.1

##### 问题描述：
vue3前端tableContext解构出来的getRawDataSource方法没有获取到数据，列表是正常有数据显示的

##### 错误截图：
![1](https://github.com/jeecgboot/JeecgBoot/assets/157146280/e79b9e99-86b0-4206-bd40-a4b4bbf040fe)
![2](https://github.com/jeecgboot/JeecgBoot/assets/157146280/8b3487a2-169c-4872-b56e-815c12e98b03)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
先升级到最新，老版本无法处理

**Comment by ve03** [comment]
> 先升级到最新，老版本无法处理

我从新下载了新版本测试（V3.7.0），也是一样

**Comment by zhangdaiscott** [comment]
那你重新发个issue，用最新版测试
