### ISSUE TITLE
Jeecg Boot如何去接入别人已经部署好的CAS单点登录

### ISSUE THREAD

**Issue by Ryan-Xia** [jeecgboot/JeecgBoot#6657]
##### 问题描述：
Jeecg Boot如何去接入别人已经部署好的CAS单点登录？
<img width="1300" alt="截屏2024-06-27 14 22 51" src="https://github.com/jeecgboot/JeecgBoot/assets/34828209/4ea6e752-04a3-483a-acfa-ff8399f48f67">
如图换成别人的地址就可以了吗？
<img width="834" alt="截屏2024-06-27 14 24 13" src="https://github.com/jeecgboot/JeecgBoot/assets/34828209/e5718e28-6e47-4c80-8a1a-01bdfb6c98b9">
这里的validateUrl要修改呢？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
根据我们的文档， 摸索订制开发吧
