### ISSUE TITLE
自定义手动上传无法获取文件对象

### ISSUE THREAD

**Issue by 1372037590** [jeecgboot/JeecgBoot#6658]
##### 版本号：
3.6.3

##### 问题描述：
自定义手动上传组件，想在basicForm返回时获取fileList，但似乎把List转成了Stirng?
若直接用fileList.value的话，form获取到的是[File,Object],[File,Object]
若使用JSON.stringify(fileList.value),获取后再转回来却不是原本哪个fileList对象，请问怎么解决呢

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/48141783/f6127bd5-0a7f-4b7f-9a0b-192eb47d15f0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by 1372037590** [comment]
使用await validate();获取的值不是文件对象，目前的解决方法只能通过子组件调用父组件方法传值

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
你用的是那个组件，贴一下代码

**Comment by 1372037590** [comment]
就是自己定义了一个组件MUpload
在basicForm组件里引用
    field: 'fileList',
    component: 'MUpload',
子组件里的实现上传，目的是想上传后获得一个fileList，和其他参数再统一提交传到后端
 <a-upload
    :file-list="fileList"
    v-model="fileList"
    :before-upload="beforeUpload"
    :max-count="maxFileCount"
    :multiple="multipleFlag"
    @remove="handleRemove"
  >
但是basicForm 里面封装的方法await validate();只能拿到String字符串，无法拿fileList对象数组

**Comment by 1372037590** [comment]
好的谢谢
