### ISSUE TITLE
JVxeTable控件的合并相同列的单元格以及动态禁用的问题

### ISSUE THREAD

**Issue by shiruicha** [jeecgboot/JeecgBoot#6659]
##### 问题描述：

JVxeTable中想合并相同列的单元格
  如果上下列相同的话合并单元格
动态禁用单元格
  判断前列的值根据前列的值动态禁用后列的单元格

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
未按格式要求发帖、描述过于简单的，会被直接删掉;
