### ISSUE TITLE
BasicForm加载

### ISSUE THREAD

**Issue by modefeng** [jeecgboot/JeecgBoot#6663]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
多少

**Comment by modefeng** [comment]
> 多少

页面大概70字段，需要等待大概4秒界面才会显示，随着字段增加，需要时间越久

**Comment by zhangdaiscott** [comment]
写个原生的form试试
