### ISSUE TITLE
数据导出慢

### ISSUE THREAD

**Issue by modefeng** [jeecgboot/JeecgBoot#6664]
##### 版本号：
3.6.3

##### 问题描述：
导出时，会调用queryDict做字典表的翻译，如果多个字段使用的是同一个字典表，也会多次调用queryDict方法翻译。当字典表中的数据达到几万条时，处理耗时会很长，导致导出时间很久，甚至无法导出

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
有缓存吧，不会去调用底层

**Comment by modefeng** [comment]
> 有缓存吧，不会去调用底层

我是以某张表作为字段的字典表，导出会查询这个表的所有数据，这个表的数据多的时候，就会很慢

**Comment by zhangdaiscott** [comment]
那肯定慢，你是用另外一个表作为关联翻译

**Comment by modefeng** [comment]
> 那肯定慢，你是用另外一个表作为关联翻译

@dict注解支持以另外表作为字典表，也就可能存在这表的数据偏多的情况，那这个有什么解决方案吗？
