### ISSUE TITLE
甘特图组件悬浮窗高度问题

### ISSUE THREAD

**Issue by guanjieyanzoudashi** [jeecgboot/JeecgBoot#6665]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by guanjieyanzoudashi** [comment]
![6e4ef52e611ca42c0009911c5112e8c](https://github.com/jeecgboot/JeecgBoot/assets/26960411/43f31296-0878-4530-8f23-a99a38a2f3bc)
![08a2b283df063740462d5af913f6b60](https://github.com/jeecgboot/JeecgBoot/assets/26960411/2d67807a-7bd3-4986-b78b-b1674ac5705d)

**Comment by zhangdaiscott** [comment]
这是你自己写的页面吧？我们咋分析

**Comment by guanjieyanzoudashi** [comment]
确实是自己写的 但是我看demo里面有这个甘特图组件让后我在这个基础上加了一些内容 发现有这个问题 但是我单独使用甘特图组件（不使用Jeecgboot）就没有这个问题&nbsp;&nbsp;


无处安放的灵魂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月28日(星期五) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JeecgBoot] 甘特图组件悬浮窗高度问题 (Issue #6665)














 
这是你自己写的页面吧？我们咋分析

**Comment by guanjieyanzoudashi** [comment]
是不是框架的布局影响到了这个显示 想找到这个问题

**Comment by guanjieyanzoudashi** [comment]
是不是框架的布局影响到了这个显示 想找到这个问题

**Comment by guanjieyanzoudashi** [comment]
可以在甘特图组件那个demo页面 甘特图上面放一点高度内容就可以复现出来这个问题

**Comment by zhangdaiscott** [comment]
提供你的完整代码，不然我们无法处理

**Comment by guanjieyanzoudashi** [comment]
<template>
  <div id="main">


        <div id="focusInfo">
          <div class="flexDiv">
            <div class="width">
              <span class="column-name">项目序号：</span>
              <span>{{ focusInfo.focusNo }}</span>
            </div>
            <div class="width">
              <span class="column-name">重点工作任务：</span>
              <span>{{ focusInfo.focusName }}</span>
            </div>
          </div>
          <div class="flexDiv">
            <div class="width">
              <span class="column-name">填报科室：</span>
              <span>{{ focusInfo.focusDept }}</span>
            </div>
            <div class="width">
              <span class="column-name">重点工作类型：</span>
              <span>{{ focusInfo.focusType }}</span>
            </div>
          </div>
          <div class="flexDiv">
            <div class="width">
              <span class="column-name">协作科室：</span>
              <span>{{ focusInfo.focusCollDept }}</span>
            </div>
            <div class="width">
              <span class="column-name">起止时间：</span>
              <span>{{ focusInfo.focusBeginDate }} ~ {{ focusInfo.focusEndDate }}</span>
            </div>
          </div>
          <div class="flexDiv">
            <div class="width">
              <span class="column-name">责任人：</span>
              <span>{{ focusInfo.focusDept }}</span>
            </div>
            <div class="width">
              <span class="column-name">参与人：</span>
              <span>{{ focusInfo.focusMember }}</span>
            </div>
          </div>
          <div class="flexDiv" v-if="focusInfo.isInn === '02'">
            <div class="width">
              <span class="column-name">创新类型：</span>
              <span>{{ focusInfo.innType }}</span>
            </div>
            <div class="width">
              <span class="column-name">项目级别：</span>
              <span>{{ focusInfo.innLevel }}</span>
            </div>
          </div>
        </div>
        <div id="scheduleInfo">
          <span class="text-name">进度计划：</span>
          
          <BasicTable @register="registerTable">
            
            <template #tableTitle>
              <a-button type="primary" @click="scheduleAdd" preIcon="ant-design:plus-outlined"> 新增</a-button>
            </template>
            
            <template #action="{ record }">
              <TableAction :actions="getTableAction(record)" />
            </template>
            <template #bodyCell="{ column, record, index, text }"> </template>
          </BasicTable>
          
          <TbScheduleInfoModal ref="scheduleModal" @success="scheduleSuccess" />
        </div>
    <section class="my-gantt">
      <div id="gantt_here" style=" width: 100%;height: 100%;" ></div>
    </section>
    <div id="monthInfo">
      <span class="text-name">完成情况记录：</span>
      
      <BasicTable @register="monthTable">
        
        <template #tableTitle>
          <a-button type="primary" @click="monthAdd" preIcon="ant-design:plus-outlined"> 新增</a-button>
        </template>
        
        <template #action="{ record }">
          <TableAction :actions="getTableActionMonth(record)" />
        </template>
        <template #bodyCell="{ column, record, index, text }"> </template>
      </BasicTable>
      
      <TbMonthInfoModal ref="monthModal" @success="monthSuccess" />
    </div>
    <div id="back">
      <a-button type="primary" class="back-icon" @click="goback"> 返回 </a-button>
    </div>
  </div>
</template>

<script lang="ts" name="focus-tbFocusInfo" setup>
  import { ref, reactive, onMounted } from 'vue';
  // import * as echarts from "echarts";
  import * as echarts from 'echarts';
  import { gantt } from 'dhtmlx-gantt';
  import 'dhtmlx-gantt/codebase/dhtmlxgantt.css';
  import demoData from './ganttData.json';
  import {Dayjs} from 'dayjs';
  import dayjs from 'dayjs'
  import { BasicTable, useTable, TableAction } from '/@/components/Table';
  import { useListPage } from '/@/hooks/system/useListPage';
  import { columns1 } from './TbScheduleInfo.data';
  import { columns2 } from './TbMonthInfo.data';
  import { list, deleteOne } from './TbScheduleInfo.api';
  import { monthList, deleteMonth } from './TbMonthInfo.api';
  import { downloadFile } from '/@/utils/common/renderUtils';
  import { useUserStore } from '/@/store/modules/user';
  import JDictSelectTag from '/@/components/Form/src/jeecg/components/JDictSelectTag.vue';
  import { useRouter, useRoute } from 'vue-router';
  import { queryByIdApi, getGantt } from './TbFocusInfo.api';
  import TbScheduleInfoModal from '@/views/focus/components/TbScheduleInfoModal.vue';
  import TbMonthInfoModal from '@/views/focus/components/TbMonthInfoModal.vue';
  import { useTabs } from '/@/hooks/web/useTabs';
  const { closeCurrent } = useTabs();
  const { refreshPage } = useTabs();
  const formRef = ref();
  const queryParam = reactive<any>({});
  const toggleSearchStatus = ref<boolean>(false);
  const scheduleModal = ref();
  const monthModal = ref();
  const innAddModal = ref();
  const focusInfo = ref({});
  const userStore = useUserStore();
  const route = useRoute();
  const router = useRouter();

  const gantData=ref([])
  const getGantData= async () => {
    await getGantt({
     id:route.query.id
    }).then((res)=>{
      console.log(res)

      initGantt(res);
      // gantData.value=res.result
      // console.log(gantData.value)
    })
  };
  const zoomConfig = {
    levels: [
      {
        name: 'day',
        scale_height: 60,
        scales: [{ unit: 'day', step: 1, format: '%d %M' }]
      },
      {
        name: 'week',
        scale_height: 60,
        scales: [
          {
            unit: 'week',
            step: 1,
            format: function (date) {
              let dateToStr = gantt.date.date_to_str('%m-%d')
              let endDate = gantt.date.add(date, -6, 'day')
              let weekNum = gantt.date.date_to_str('%W')(date) //第几周
              return dateToStr(endDate) + ' 至 ' + dateToStr(date)
            }
          },
          {
            unit: 'day',
            step: 1,
            format: '%d', // + "周%D"
            css: function (date) {
              if (date.getDay() == 0 || date.getDay() == 6) {
                return 'day-item weekend weekend-border-bottom'
              } else {
                return 'day-item'
              }
            }
          }
        ]
      },
      {
        name: 'month',
        scale_height: 60,
        min_column_width: 18,
        scales: [
          { unit: 'month', format: '%Y-%m' },
          {
            unit: 'day',
            step: 1,
            format: '%d',
            // css: function (date) {
            //   if (date.getDay() == 0 || date.getDay() == 6) {
            //     return 'day-item weekend weekend-border-bottom'
            //   } else {
            //     return 'day-item'
            //   }
            // }
          }
        ]
      },
      {
        name: 'quarter',
        height: 60,
        min_column_width: 50,
        scales: [
          {
            unit: 'quarter',
            step: 1,
            format: function (date) {
              let yearStr = new Date(date).getFullYear() + '年'
              let dateToStr = gantt.date.date_to_str('%M')
              let endDate = gantt.date.add(gantt.date.add(date, 3, 'month'), -1, 'day')
              return yearStr + dateToStr(date) + ' - ' + dateToStr(endDate)
            }
          },
          {
            unit: 'week',
            step: 1,
            format: function (date) {
              let dateToStr = gantt.date.date_to_str('%m-%d')
              let endDate = gantt.date.add(date, 6, 'day')
              let weekNum = gantt.date.date_to_str('%W')(date)
              return dateToStr(date) + ' 至 ' + dateToStr(endDate)
            }
          }
        ]
      },
      {
        name: 'year',
        scale_height: 50,
        min_column_width: 50,
        scales: [
          { unit: 'year', step: 1, format: '%Y年' },
          { unit: 'month', format: '%Y-%m' }
        ]
      }
    ],

  }





  //初始化甘特图
  const initGantt = (res) => {



    gantt.config.xml_date = "%Y-%m-%d";
    gantt.config.scale_height = 50; //设置甘特图的表头高度
    //鼠标移入展示信息




    //时间展示 2021-10-11 07:22
    gantt.templates.tooltip_date_format = gantt.date.date_to_str("%Y-%m-%d")
    //鼠标移入展示信息
    gantt.config.readonly = true //甘蔗图只读属性
    gantt.config.round_dnd_dates = false //将任务开始时间和结束时间自动“四舍五入'
    gantt.config.fit_tasks = true
    gantt.config.root_id = "root"
    gantt.i18n.setLocale('cn')

    //添加taba栏
    gantt.config.columns = [
      {name:"name", label:"项目", align: 'center', width: 120},

    ]

    let gant={
      data:[]
    }

    gant.data=res

    gantt.plugins({
      tooltip: true
    })

    gantt.attachEvent("onGanttReady", function(){
      var tooltips = gantt.ext.tooltips;
      tooltips.tooltip.setViewport(gantt.$task_data);
      console.log(gantt.$task_data)
      // let heightData=gantt.$task_data.style.height+59
      console.log(gantt.$task_data.style.height)
      // document.getElementsByClassName("my-gantt")[0].style.height=heightData
    });

    // gantt.templates.tooltip_text = function (start, end, task) {
    //   console.log(task)
    //   if(task.type=="1"){
    //     return (
    //
    //       "<br/><span>计划开始时间:</span> " +
    //       gantt.templates.tooltip_date_format(start) +
    //       "<br/><span>计划结束时间:</span> " +
    //       gantt.templates.tooltip_date_format(end)
    //
    //     );
    //   }
    //
    // }

    gantt.templates.tooltip_text = function (start, end, task) {

      // gantt.config.tooltip_offset_y = 10;




      if (task.type =="1") {
        // gantt.config.tooltip_offset_y = 10;
        return (

          "<br/><span>计划开始时间:</span> " +
          gantt.templates.tooltip_date_format(start) +
          "<br/><span>计划结束时间:</span> " +
          gantt.templates.tooltip_date_format(end)
        );
      }
      else {
        return (
          "<br/><span>完成情况开始时间:</span> " +
          gantt.templates.tooltip_date_format(start) +
          "<br/><span>完成情况结束时间:</span> " +
          gantt.templates.tooltip_date_format(end)

        );
      }



    }




    //
    gantt.init('gantt_here') //初始化
    gantt.parse(gant) //填充数据
    gantt.ext.zoom.init(zoomConfig)
    gantt.ext.zoom.setLevel('month') //切换到指定的缩放级别

  }




  //进度计划
  //注册table数据
  const { tableContext: tableContext1 } = useListPage({
    tableProps: {
      title: '进度计划',
      api: list,
      columns: columns1,
      canResize: false,
      useSearchForm: false,
      showIndexColumn: true,
      actionColumn: {
        width: 150,
        fixed: 'right',
      },
      beforeFetch: (params) => {
        params.focusId = route.query.id;
        return Object.assign(params, queryParam);
      },
    },
  });
  const [
    registerTable,
    {
      reload: reload1,
      collapseAll: collapseAll1,
      updateTableDataRecord: updateTableDataRecord1,
      findTableDataRecord: findTableDataRecord1,
      getDataSource: getDataSource1,
    },
    { rowSelection: rowSelection1, selectedRowKeys: selectedRowKeys1 },
  ] = tableContext1;

  //月度完成情况
  //注册table数据
  const { tableContext: tableContext2 } = useListPage({
    tableProps: {
      title: '完成情况记录',
      api: monthList,
      columns: columns2,
      canResize: false,
      useSearchForm: false,
      showIndexColumn: true,
      actionColumn: {
        width: 150,
        fixed: 'right',
      },
      beforeFetch: (params) => {
        params.focusId = route.query.id;
        return Object.assign(params, queryParam);
      },
    },
  });
  const [
    monthTable,
    {
      reload: reload2,
      collapseAll: collapseAll2,
      updateTableDataRecord: updateTableDataRecord2,
      findTableDataRecord: findTableDataRecord2,
      getDataSource: getDataSource2,
    },
    { rowSelection: rowSelection2, selectedRowKeys: selectedRowKeys2 },
  ] = tableContext2;

  //返回上一级
  const goback = () => {
    closeCurrent();
    router.push({ name: 'focus-TbFocusInfoList' });
  };

  onMounted( () => {
    // getData()
    queryById();
    getGantData()



  });

  const queryById = async () => {
    await queryByIdApi({
      pageNo: 1,
      pageSize: 10,
      id: route.query.id,
    }).then((res) => {
      focusInfo.value = res.result;
    });
  };

  //进度计划
  /**
   * 新增事件
   */
  function scheduleAdd() {
    const focusId = route.query.id;
    scheduleModal.value.disableSubmit = false;
    scheduleModal.value.add(focusId);
  }

  /**
   * 编辑事件
   */
  function scheduleEdit(record: Recordable) {
    scheduleModal.value.disableSubmit = false;
    let planDate=[record.planBeginDate,record.planEndDate]
    const dayjsDates = planDate.map(dateStr => {
      return dayjs(dateStr);
    });
    record.planDate=dayjsDates
    scheduleModal.value.edit(record);
  }

  /**
   * 删除事件
   */
  async function scheduleDelete(record) {
    await deleteOne({ id: record.id }, scheduleSuccess);
  }

  /**
   * 成功回调
   */
  function scheduleSuccess() {
    refreshPage();
    (selectedRowKeys1.value = []) && reload1();
    getGantData()
  }

  /**
   * 操作栏
   */
  function getTableAction(record) {
    return [
      {
        label: '编辑',
        onClick: scheduleEdit.bind(null, record),
      },
      {
        label: '删除',
        popConfirm: {
          title: '是否确认删除',
          confirm: scheduleDelete.bind(null, record),
        },
      },
    ];
  }

  //月度完成情况
  /**
   * 新增事件
   */
  function monthAdd() {
    debugger;
    const focusId = route.query.id;
    monthModal.value.disableSubmit = false;
    monthModal.value.add(focusId);
  }

  /**
   * 编辑事件
   */
  function monthEdit(record: Recordable) {
    monthModal.value.disableSubmit = false;
    let planDate=[record.planBeginDate,record.planEndDate]
    const dayjsDates = planDate.map(dateStr => {
      return dayjs(dateStr);
    });
    record.planDate=dayjsDates
    monthModal.value.edit(record);
    console.log(record)

    // console.log(dayjsDates)
  }

  /**
   * 删除事件
   */
  async function monthDelete(record) {
    await deleteMonth({ id: record.id }, monthSuccess);
  }

  /**
   * 成功回调
   */
  function monthSuccess() {
    refreshPage();
    (selectedRowKeys2.value = []) && reload2();
    getGantData()
  }

  /**
   * 操作栏
   */
  function getTableActionMonth(record) {
    return [
      {
        label: '附件',
        onClick: getAnnex.bind(null, record),
      },
      {
        label: '编辑',
        onClick: monthEdit.bind(null, record),
      },
      {
        label: '删除',
        popConfirm: {
          title: '是否确认删除',
          confirm: monthDelete.bind(null, record),
        },
      },
    ];
  }
  /**
   * 附件
   * @param record
   */
  function getAnnex(record: Recordable) {
    console.log(record.id);
    router.push({ path: '/focus/TbAnnexInfoList', query: { id: record.id, type: '1' } });
  }
</script>

<style lang="less" scoped>

  .jeecg-basic-table-form-container {
    padding: 0;
    .table-page-search-submitButtons {
      display: block;
      margin-bottom: 24px;
      white-space: nowrap;
    }
    .query-group-cust {
      width: calc(50% - 15px);
      min-width: 100px !important;
    }
    .query-group-split-cust {
      width: 30px;
      display: inline-block;
      text-align: center;
    }
  }
  #main {

    background-color: #ffffff;
    margin-top: 25px;
    margin-left: 25px;
    margin-right: 25px;
    .my-gantt {
      height: 100vh;
      width: 75vw;
      margin: 0 auto;
      margin-top: 20px;
      padding-top: 30px;
      margin-bottom: 20px;
      //#gantt_here{
      //  position: absolute;
      //}


      .time-box {
        text-align: center;
        margin-bottom: 20px;
      }
      //::v-deep .gantt-container {
      //  width: 100%;
      //  height: 100%;
      //  .weekend {
      //    background: #ff9e2f;
      //    color: #fff;
      //  }
      //}
    }

   /deep/ .gantt_tooltip{
      position: relative;
    }
  }
  //#focusInfo{
  //  background-color: #ffffff;
  //  margin-top: 50px;
  //}
  .text-line {
    margin-left: 50px;
    height: 50px;
  }
  .column-name {
    display: inline-block;
    width: 98px;
    text-align: right;
    font-weight: bold;
  }
  .column-name-right {
    display: inline-block;
    width: 100px;
    text-align: right;
    font-weight: bold;
  }
  .text-name {
    display: inline-block;
    text-align: right;
    font-weight: bold;
  }
  #scheduleInfo {
    margin-left: 50px;
    margin-right: 50px;
  }
  #gantt {
    //padding-top: 320px;
    margin-left: 50px;
    margin-right: 50px;
  }
  #monthInfo {
    //padding-top: 320px;
    margin-left: 50px;
    margin-right: 50px;
  }
  #back {
    padding: 10px;
    text-align: center;
  }
  #chart {
    width: 100%;
    height: 500px;
    margin: 50px auto;
  }
  .flexDiv {
    display: flex;
    padding: 12px 24px 12px 24px;
    .width {
      width: 50%;
    }
    .divPosition {
      position: relative;
      .divAbsolute {
        position: absolute;
        height: 100%;
      }
      .titleMargin {
        display: inline-block;
        margin-left: 140px;
      }
    }
  }


  ///deep/ .gantt_tooltip{
  //  position: absolute!important;
  //}
</style>

**Comment by guanjieyanzoudashi** [comment]
我写个简单的demo吧
