### ISSUE TITLE
仪表盘组件

### ISSUE THREAD

**Issue by lifei636** [jeecgboot/JeecgBoot#6666]
##### 版本号：
后端 v3.7 master
前端 v3.7 master 
前后一体仓库
##### 问题描述：

源码运行时，仪表盘设计-常用里没有表单选项
但官方文档有，本地仪表盘-案例模板列表里有的模板里也有
![image](https://github.com/jeecgboot/JeecgBoot/assets/39741572/ab0b215b-984c-4760-8182-3f9d502ae4d8)

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/39741572/c1a64e9f-3813-4678-aa6e-714a434f44e9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
后面版本会逐步放开更多功能
