### ISSUE TITLE
jvxetable编辑时 不聚焦时默认显示数据框问题

### ISSUE THREAD

**Issue by 1999LonelyCHEN** [jeecgboot/JeecgBoot#6670]
##### 问题描述：
1.jvxetable编辑时默认不显示输入框
![image](https://github.com/jeecgboot/JeecgBoot/assets/62411169/741c3078-dcee-463b-91d6-591dec81f752)

2.使用下方配置后无作用
editRender:{
      autofocus:true,
      name:"input"
    }
3.想实现功能：默认显示输入框，而不是鼠标点击过后显示（请问修改哪里可以实现呢？）
![image](https://github.com/jeecgboot/JeecgBoot/assets/62411169/3cf23f32-0b83-42ce-bc8e-0a9acce6c35b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
描述过于简单

**Comment by 1999LonelyCHEN** [comment]
> 描述过于简单

您好，我修改了下问题，请您在帮忙看下谢谢

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
目前不支持

**Comment by 1999LonelyCHEN** [comment]
好的，谢谢
