### ISSUE TITLE
让租户能管理自己子账号功能

### ISSUE THREAD

**Issue by zzc2001** [jeecgboot/JeecgBoot#6671]
##### 版本号：
3.7.0

##### 问题描述：
因为我理解的租户功能是后台能给这个租户添加套餐（功能模块），那么租户是不是应该有一个自己的后台管理能增删改查子账号不然就只能让管理员在后台给他们添加账号让他们登录这样好像有点冲突

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/3162115/4adefc35-5fbc-480a-b046-401914df23cc)
