### ISSUE TITLE
springboot3 分支，online 表单添加下拉框组件后，功能测试页面编辑报错

### ISSUE THREAD

**Issue by LyuKhao** [jeecgboot/JeecgBoot#6672]
##### 版本号：
3.7.0_all  springboot3 分支

##### 问题描述：

online 在线表单配置下拉框组件，测试页面添加数据后，点击编辑报错（图一 图二）。

分析代码发现此方法已在 mybatis-plus 3.5.3.2 版本中移除（图三）
`
public final QueryWrapper<T> select(String... columns) {
        return select(Arrays.asList(columns));
    }
`

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/40912886/93d28993-3f0a-44b1-ba93-ce5113fe906a)
![image](https://github.com/jeecgboot/JeecgBoot/assets/40912886/bffefbcf-f36f-4ae2-b6a1-892f3b2877a7)

![image](https://github.com/jeecgboot/JeecgBoot/assets/40912886/052d87cb-9d7a-4896-bbaa-455650a8abee)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
online模块lib暂时未升级，可能是不兼容

**Comment by zhangdaiscott** [comment]
更新代码把
