### ISSUE TITLE
JVxeTable的禁用问题

### ISSUE THREAD

**Issue by shiruicha** [jeecgboot/JeecgBoot#6673]
##### 问题描述：
JVxeTable如何做到如图如果第一列是转账的话禁用收款方的本行单元格 如果第一列是核销预支的话解除禁用收款方的本行单元格

##### 错误截图：

![76dd8fb5117fde0446d8d84b421aa46](https://github.com/jeecgboot/JeecgBoot/assets/84765979/c0a7fd61-c1df-49c7-8398-b7776101c43b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by shiruicha** [comment]
请大佬们解惑，如图我想展示的效果是第一行的收款方是禁用状态 第二行的收款方是放开状态

**Comment by RamboWu** [comment]
@zhangdaiscott 这个问题 没有解决，怎么关闭了呀。
