### ISSUE TITLE
表格导出怎么增加加参数或者修改传参

### ISSUE THREAD

**Issue by nashuang123** [jeecgboot/JeecgBoot#6674]
##### 问题描述：

麻烦指导一下 表格在导出时 如果想增加参数或者修改参数要怎么写 谢谢

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by chb88888** [comment]
你好请问解决了吗，我也遇到这个问题了
