### ISSUE TITLE
3.7.0微服务启动jeecg-demo-cloud-start和jeecg-system-cloud-start启动遇到问题

### ISSUE THREAD

**Issue by naaaameeee** [jeecgboot/JeecgBoot#6675]
##### 问题描述：

Description:

The bean 'corsFilter', defined in class path resource [org/jeecg/config/WebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/jeecg/starter/cloud/config/GwCorsFilter.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Process finished with exit code 1
尝试在application.yml和nacos 的jeecg-dev.yml里配置无效
![image](https://github.com/jeecgboot/JeecgBoot/assets/99253064/89c483e3-4dfe-42ef-aa88-28aeb877da8b)

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/99253064/a9f4102a-3418-48e0-b371-3dce9da145b9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
先启动nacos

**Comment by naaaameeee** [comment]
不是nacos的问题，早就启动了，很诡异，我清了遍maven就ok了
