### ISSUE TITLE
生成一对多代码时找不到方法getSum()

### ISSUE THREAD

**Issue by Vickyyu2000** [jeecgboot/JeecgBoot#6676]
##### 版本号：
jeecg-boot 3.7.0

##### 问题描述：
根据教程《13. 新建模块和代码生成树表和一对多表单》步骤，生成一对多代码的时候报错，找不到getSum()的方法。
sdk使用的22
新手找不出来解决的办法

##### 错误截图：

![1719815650032](https://github.com/jeecgboot/JeecgBoot/assets/123125581/3569349c-e82f-4386-b1e1-8149d34db358)

**Comment by zhangdaiscott** [comment]
自己查生成代码报错原因，看看是不是关键词导致
