### ISSUE TITLE
mybatis-plus 可以升级到3.5.7吗

### ISSUE THREAD

**Issue by Vergil-x** [jeecgboot/JeecgBoot#6677]
##### 版本号：

3.7.0_all（发布日期：2024-06-23）
##### 问题描述：

mybatis-plus 有安全漏洞，可以升级到3.5.7版本吗，这个版本改了jsqlparser的依赖，有不少要改的地方

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
可以升级，哪里有报错？

**Comment by Vergil-x** [comment]
3.5.7用了4.9版本的jsqlparser api变动比较大 ，jimu报表 minidao 的依赖都用了jsqlparser这个依赖，还有项目里的这几个类都用的老版本的jsql的api
![Snipaste_2024-07-01_17-09-04](https://github.com/jeecgboot/JeecgBoot/assets/30331101/fe8225eb-8f71-40ee-b0d1-23e7b9d5880c)

**Comment by zhangdaiscott** [comment]
排除积木报表的依赖就行

**Comment by Vergil-x** [comment]
排除了之后，启动的时候会报错，就是因为3.5.7版本的mybatis-plus用了新版本的jsql
![Snipaste_2024-07-01_17-37-33](https://github.com/jeecgboot/JeecgBoot/assets/30331101/9b1e4fb3-0f08-435e-88a3-2769b1a16643)
![Snipaste_2024-07-01_17-37-46](https://github.com/jeecgboot/JeecgBoot/assets/30331101/9a2507a4-0b48-48b6-b04b-678f61817256)

**Comment by Vergil-x** [comment]
排除了之后，启动的时候会报错
![Snipaste_2024-07-01_17-37-33](https://github.com/jeecgboot/JeecgBoot/assets/30331101/9870dd35-ccdb-4739-9be8-0f0a600d7b4e)

![Snipaste_2024-07-01_17-37-46](https://github.com/jeecgboot/JeecgBoot/assets/30331101/da3ba886-f879-4430-930b-69d91848ce64)

**Comment by zhangdaiscott** [comment]
还有冲突的地方，或者你排除后未生效

**Comment by Vergil-x** [comment]
> 还有冲突的地方，或者你排除后未生效

没了，3.5.7版本的mybatisplus只能用4.9的jsql，这个没办法，用了4.9的jsql，只能把项目里用的老版本的jsql api改掉，我改了一遍能启动了，积木报表那边又报错了

**Comment by zhangdaiscott** [comment]
你应该是排除积木报表的，不是mybatisplus的

**Comment by zhangdaiscott** [comment]
暂时收录到 “新需求汇总”
https://github.com/jeecgboot/JeecgBoot/issues/1312

**Comment by softboy99** [comment]
确实太老了
