### ISSUE TITLE
前端Online在线表单修改内置组件

### ISSUE THREAD

**Issue by jie426543** [jeecgboot/JeecgBoot#6678]
##### 版本号：
JEECG BOOT 低代码平台（Vue3前端）
===============

当前最新版本： 1.2.0（发布时间：20220606）

##### 问题描述：
我想修改在线表单中的组件，该在哪去修改，在线表单的组件代码是在前端代码中修改还是哪里，比如我要修改确认按钮的文字，或者修改在线表单中新弹出弹窗的组件，该怎么去修改，谢谢

##### 错误截图：

![问题截图](https://github.com/jeecgboot/JeecgBoot/assets/84946910/7eeb24ca-1333-4cbd-bf8b-0746e2b4af29)
![image](https://github.com/jeecgboot/JeecgBoot/assets/84946910/e08d3e87-39c2-4f6d-9997-f55501e5a7fc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不支持

**Comment by jie426543** [comment]
> 不支持

好的，谢谢
