### ISSUE TITLE
Online表单表字典的条件过滤参数问题

### ISSUE THREAD

**Issue by Liuudaa** [jeecgboot/JeecgBoot#6679]
##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/174313650/e85c4ec8-3cd5-4f9b-9526-5fc2f2c18045)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
后面会上这个功能，暂时不支持

**Comment by zhangdaiscott** [comment]
已经支持，下个版本发布
