### ISSUE TITLE
自动生成的代码“分页列表查询”在大数据时，显示第一页10条数据也很慢，如何改进？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/JeecgBoot#6680]
##### 版本号：
3.5.5

##### 问题描述：
自动生成的代码，如下：
@ApiOperation(value="andonraw-分页列表查询", notes="andonraw-分页列表查询")
	@GetMapping(value = "/list")
	public Result<IPage<Andonraw>> queryPageList(Andonraw andonraw,
								   @RequestParam(name="pageNo", defaultValue="1") Integer pageNo,
								   @RequestParam(name="pageSize", defaultValue="10") Integer pageSize,
								   HttpServletRequest req) {
		QueryWrapper<Andonraw> queryWrapper = QueryGenerator.initQueryWrapper(andonraw, req.getParameterMap());
		Page<Andonraw> page = new Page<Andonraw>(pageNo, pageSize);
		IPage<Andonraw> pageList = andonrawService.page(page, queryWrapper);
		return Result.OK(pageList);
	}

当数据表特别大时，查询特别慢，甚至无法载入数据。但是实际上是按照分页显示，每页也只有10条数据，为什么会这么慢？如果在mysql里面查询，一次查询上千条数据是很快的。这个问题要怎么解决？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
分页为什么慢

**Comment by ciahua** [comment]
> 分页为什么慢

数据量特别大。但是不管多大的数据量，每页也只显示10条数据啊，为什么会慢呢？

**Comment by ciahua** [comment]
数据表的索引我也做了，没什么改善。

**Comment by zhangdaiscott** [comment]
什么数据库，把执行的sql，放到数据库里执行看看

**Comment by ciahua** [comment]
> 什么数据库，把执行的sql，放到数据库里执行看看

没有执行的sql，就是顶楼这段代码，是jeecg自动生成的，不知道对应的sql是什么。数据库是你们推荐的mysql 5.7。但是如果我用sql查询几千条记录，那是很快的。我的意思是，既然是分页查询，那每次只会查询10条出来，为什么也那么慢？

**Comment by zhangdaiscott** [comment]
是这个道理，你需要自己排查原因

**Comment by ciahua** [comment]
> 是这个道理，你需要自己排查原因

你们自己没有这样的问题吗？应该也是一样的吧。

**Comment by zhangdaiscott** [comment]
你自己个性化问题
我们上亿的业务系统数据也问题，演示系统日志表几十万数据也没卡

**Comment by ciahua** [comment]
> 你自己个性化问题 我们上亿的业务系统数据也问题，演示系统日志表几十万数据也没卡

哦？问题是这个代码是你们的自动生成代码功能完成的啊。我都没改过的。给点提示，从哪里去优化？
