### ISSUE TITLE
Online表单开发-权限控制-数据权限相关问题

### ISSUE THREAD

**Issue by eric-e-zhang** [jeecgboot/JeecgBoot#6682]
##### 版本号：
V3.7.0

##### 问题描述：
Online表单开发-权限控制-数据权限中，添加了“只查看自己的”数据权限规则，授权给相关角色用户，用户无法查看到自己添加的数据，预期是可以只看到自己添加的数据。

##### 错误截图：
![20240701-201939](https://github.com/jeecgboot/JeecgBoot/assets/1749660/d8a21b76-00e9-4294-8d27-ab91a52c0426)
![20240701-202732](https://github.com/jeecgboot/JeecgBoot/assets/1749660/fd228cec-c1e1-486d-bcac-c2821fb79bb2)
![20240701-202748](https://github.com/jeecgboot/JeecgBoot/assets/1749660/703b16d9-40f9-4185-a423-0a3d217079e1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/3162115/bdff3b59-0cf2-4bc0-ba19-17e993cca5e0)
