### ISSUE TITLE
如何配置多文件入口？

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/JeecgBoot#6684]
##### 版本号：
3.4.3 Vue3版本

##### 问题描述：
我有一个静态文件需要通过iframe加载，但是现在默认都是跳转首页(排查后发现是`vite-plugin-html`插件的原因，注释掉后正常加载)
我在`build/vite/html.ts`文件中配置了多入口，但是无效

能否提供一个配置示例？
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liaozhiyang** [comment]
你之前应该是这样配置多入口的吧？如果使用了vite-plugin-html插件，这种就失效了，会走vite-plugin-html的配置，得通过vite-plugin-html配置多入口。
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/aa59bf01-5f52-4eb3-8d40-1c38c12c43b4)


步骤如下：
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/500479ed-9552-4527-ac4c-a30976be9a2f)
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/5c841e00-0519-4ca3-98de-0fbf79e4bf7a)

效果如下：
![iShot_2024-07-10_16 52 32](https://github.com/jeecgboot/JeecgBoot/assets/8199499/c802f46d-6c32-4233-9c18-5b113cd4e52c)

**Comment by l1518501871** [comment]
@liaozhiyang  牛啊，哥

**Comment by lanbohello163** [comment]
@liaozhiyang 大佬，请教下多入口vite.config.ts配置了base路径时，怎么调整呢？会报找不到src/multiPage/home/main.ts
