### ISSUE TITLE
JVxeTable表头列内容多，设置文字换行，多选、序号两列错位

### ISSUE THREAD

**Issue by mengrose** [jeecgboot/JeecgBoot#6686]
##### 版本号：
3.7.0_all

##### 问题描述：
JVxeTable表头列内容多，设置文字换行，多选、序号两列错位。
使用JVxeTable的原生属性show-header-overflow="false"，设置表头列换行
![image](https://github.com/jeecgboot/JeecgBoot/assets/42018550/57b15d8d-56fd-454c-872e-3ee76f315658)

##### 错误截图：
界面错位效果

![image](https://github.com/jeecgboot/JeecgBoot/assets/42018550/e756dc40-2a39-4716-b2b9-24ad887652e2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liaozhiyang** [comment]
没复现，对框架代码有改动吗？或者再下载一份纯净的代码试下该功能。
![image](https://github.com/jeecgboot/JeecgBoot/assets/8199499/a46d545b-d608-44ff-bf4b-8f44ecbb8eae)

**Comment by mengrose** [comment]
@liaozhiyang 重新拉取的代码，测试结果
![image](https://github.com/user-attachments/assets/d1774db7-2ab1-44e1-a0e2-b743db15dce0)

![image](https://github.com/user-attachments/assets/1950a3d0-2306-44ae-8295-64666258b933)

**Comment by liaozhiyang** [comment]
<img width="492" alt="image" src="https://github.com/user-attachments/assets/4fab1bc5-6e95-4b99-933d-ffc07c255d55">
如果是布尔值需要加上:

**Comment by mengrose** [comment]
@liaozhiyang 可以了，感谢！！！ 还想冒昧的问下，你的vscode使用的是什么主题
