### ISSUE TITLE
BasicTable可编辑单元格使用多选ApiSelect类型无法回显

### ISSUE THREAD

**Issue by 17356212005** [jeecgboot/JeecgBoot#6687]
版本号：3.7.0

问题描述：BasicTable可编辑单元格使用多选ApiSelect类型无法回显

错误日志&截图：
![微信图片_20240629175823](https://github.com/jeecgboot/JeecgBoot/assets/54160081/5adcd48d-33fb-4921-af6c-11db3b52f887)
![微信图片_20240702163634](https://github.com/jeecgboot/JeecgBoot/assets/54160081/b7fe1e15-a05f-421d-95fd-8070ea226af5)

分支是 springboot3

**Comment by zhangdaiscott** [comment]
跟后台没关系吧

**Comment by 17356212005** [comment]
前端的问题，应该是组件封装的问题

**Comment by zhangdaiscott** [comment]
列表渲染的是字符串文本，未渲染成ApiSelect控件，所以需要你手工翻译

**Comment by Jsping68** [comment]
ApiSelect在BasicTable中没有好的解决方式。我在编辑页面中的ApiSelect组件的editRow和editable分别设置为true，在详情页中，在setTableData后使用nextTick遍历getDataSource重新设置每行对应的列的值，然后设置(row as EditRecordRow).onEdit?.(false, true);也可以解决，希望有所帮助：

![image](https://github.com/user-attachments/assets/70479043-bc13-42e8-86b9-fcbf0b694a24)
