### ISSUE TITLE
登录没有跳转新界面

### ISSUE THREAD

**Issue by dearmcx** [jeecgboot/JeecgBoot#6690]
##### 版本号：
3.4.3-GA

##### 问题描述：
数据库是dm8数据库，注册用户后可以在数据库的sys_user中看到用户，登录的时候没有跳转界面，后端报错
![2024-07-02_190512](https://github.com/jeecgboot/JeecgBoot/assets/44113973/69693db9-6d1d-4f9e-a2e5-5dcafa2346bb)
![2024-07-02_190401](https://github.com/jeecgboot/JeecgBoot/assets/44113973/bdb529ce-f152-485f-aad5-3f87b0a04ec0)

##### 错误截图：
![2024-07-02_190242](https://github.com/jeecgboot/JeecgBoot/assets/44113973/87abc65a-ad8c-44eb-a25a-1d70b91bef81)
![2024-07-02_190818](https://github.com/jeecgboot/JeecgBoot/assets/44113973/3a95cb05-9c38-4784-9a4b-1f2cf40aa9ef)
这里是报错代码位置：
![2024-07-02_191100](https://github.com/jeecgboot/JeecgBoot/assets/44113973/ddc59460-c084-44c6-906d-021c33297a58)

**Comment by zhangdaiscott** [comment]
老版本，自己debug跟代码把
