### ISSUE TITLE
表体字段之间下拉联动实现方案

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#6691]
##### 版本号：
3.7.0

##### 问题描述：
目前下拉组件不支持表体的下拉联动，是否可以支持？
由于不支持，所以采用表体编辑的时候调用changeSubTableOptions(tableName，field，options)的方式变通实现，但是有问题，因为不同行下拉内容都不一样，在编辑事项里面实现，一行修改了，所有行的下拉都变了，能否增加字段的点击事件，点击下拉的时候调changeSubTableOptions(tableName，field，options)，这样就可以保证每一行的下拉都正确

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
描述过于简单
