### ISSUE TITLE
BasicModal弹窗如何实现最小化和多窗口层叠

### ISSUE THREAD

**Issue by chenmonkey** [jeecgboot/JeecgBoot#6692]
##### 问题描述：BasicModal弹窗
目前只能实现最大化，如何实现最小化和多窗口层叠
![image](https://github.com/jeecgboot/JeecgBoot/assets/32865506/26d8466a-ac2c-4d63-88de-8b271e6f1b3f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
需要自己实现
