### ISSUE TITLE
导出后缀为.xlsx的excel文件打不开，提示文件格式或文件扩展名无效

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#6696]
##### 版本号：

3.6.3
##### 问题描述：

前端是自己写的导出逻辑，后台用的是自动代码生成的通用导出的代码，如果导出后缀是xls是可以正常的打开的，如果后缀改为.xlsx，导出就打不开了提示文件格式或文件扩展名无效

##### 错误截图：
![1720065319195](https://github.com/jeecgboot/JeecgBoot/assets/132029411/89852627-67fa-411d-a087-4370302ea6b2)
![1720065349686](https://github.com/jeecgboot/JeecgBoot/assets/132029411/b5304949-1a85-450f-94ac-bab2f2e95d7f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看看autopoi的文档
