### ISSUE TITLE
返回ModelAndView 类型的接口 无法被扫描到接口文档

### ISSUE THREAD

**Issue by zk020106** [jeecgboot/JeecgBoot#6697]
##### 问题描述：
 如果接口没有用result返回对象的话 接口文档不会扫描到这个接口的，项目也是放在org.jeecg下面，请问要怎么样才可以返回文件流切让接口文档识别出来
![05567cf0614fec23a3fb16c41f39f70a](https://github.com/jeecgboot/JeecgBoot/assets/129857206/7cd0fd1a-517b-4f85-a72f-0df9b68ff686)

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/129857206/5a5018a0-e5a0-48b8-b1e7-366416dc17d5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
ModelAndView在spring web的定义是跳转页面使用的，如集成了themeleaf\freemarker时可以使用。swagger是用于生成纯数据接口的文档，不生成是正常的。如果需要使用使用两个方法，一个方法用于跳转页面，一个方法用于数据返回，在数据返回的方法中正常使用swagger注解并且使用@responseBody注解进行修饰。

**Comment by zk020106** [comment]
> ModelAndView在spring web的定义是跳转页面使用的，如集成了themeleaf\freemarker时可以使用。swagger是用于生成纯数据接口的文档，不生成是正常的。如果需要使用使用两个方法，一个方法用于跳转页面，一个方法用于数据返回，在数据返回的方法中正常使用swagger注解并且使用@responsebody注解进行修饰。

但是在上面已经使用了@RestController了

**Comment by EightMonth** [comment]
因为 ModelAndView 是 Spring MVC 中用于返回视图和模型数据的一种方式，而 Swagger 主要关注的是 API 的 HTTP 响应体、状态码等信息，并不直接处理视图逻辑。

**Comment by zk020106** [comment]
感谢！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 09:07 |
| 收件人 | jeecgboot/JeecgBoot ***@***.***> |
| 抄送人 | 莫愁 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/JeecgBoot] 返回ModelAndView 类型的接口 无法被扫描到接口文档 (Issue #6697) |

因为 ModelAndView 是 Spring MVC 中用于返回视图和模型数据的一种方式，而 Swagger 主要关注的是 API 的 HTTP 响应体、状态码等信息，并不直接处理视图逻辑。
