### ISSUE TITLE
缓存路由失效

### ISSUE THREAD

**Issue by 1999LonelyCHEN** [jeecgboot/JeecgBoot#6698]
##### 问题描述：配置缓存路由失效，切换tab还是刷新页面
操作步骤：一级菜单、二级菜单均设置为缓存路由，且二级菜单与 vue页面 name对应，但是依然无法生效

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/62411169/06d033b6-63c3-4f2f-88c1-03d2adec600e)
![image](https://github.com/jeecgboot/JeecgBoot/assets/62411169/0e4c77f1-5696-44cd-82b4-1b4e2ed91d3f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
页面截图

**Comment by 1999LonelyCHEN** [comment]
您好，就是设置两个二级菜单为 缓存路由，都打开后 切换tab还是会默认刷新页面，将之前填写的条件给清空
![image](https://github.com/jeecgboot/JeecgBoot/assets/62411169/a50b2e17-2e51-4f1e-8b14-db742277a400)

**Comment by zhangdaiscott** [comment]
升级到最新版看看是否还存在问题

**Comment by liaozhiyang** [comment]
经测试，无法复现。有更详细的信息吗？
对底层代码有改动吗？目前系统用户和系统角色等是使用了路由缓存。你看下你跟这俩有什么区别吗？
[演示系统-系统用户](http://boot3.jeecg.com/system/user)

**Comment by yang-xianzhu** [comment]
![image](https://github.com/user-attachments/assets/23578ddd-3253-46d5-9257-84bfe4ea46e7)
可以看看name有没有对应上
