### ISSUE TITLE
原来的jeecgboot-vue3仓库怎么没了

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#6700]
##### 版本号：
3.6.2

##### 问题描述：
原来的[jeecgboot-vue3](https://github.com/jeecgboot/jeecgboot-vue3)访问404了，请问什么情况？

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/19619291/f0a6297b-f043-4b4f-8d26-f39e34d1a403)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
前端和后端合并到一起了
