### ISSUE TITLE
连接sql server2019报错

### ISSUE THREAD

**Issue by Jasse1997** [jeecgboot/JeecgBoot#6702]
##### 版本号：
3.7.0

##### 问题描述：
我用3.6.1的时候可以连接上sql server2019，更新到3.7.0的时候就报错了

##### 错误截图：
![1](https://github.com/jeecgboot/JeecgBoot/assets/56105409/15df85a5-d499-4334-a01b-37fcbe64fe5f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
没啥关系吧，换驱动？

**Comment by Jasse1997** [comment]
试了几个版本，换成mssql-jdbc也还是报错，不知道问题点在哪

**Comment by zhangdaiscott** [comment]
2017我们连接没有问题

**Comment by Jasse1997** [comment]
我看网上Microsoft JDBC Driver 6.2 for SQL Server以上的驱动支持2017，
2019要Microsoft JDBC Driver 7.4 for SQL Server以上的驱动才支持，是不是新加的代码有些引用了旧的驱动，
我发现3.6.1，把积木报表换成最新的版本也是报错，用旧版就没问题，但在3.7.0把积木报表换成旧版也还是会报错

**Comment by zhangdaiscott** [comment]
不清楚，自己排查把
