### ISSUE TITLE
Online代码生成不支持多级包名

### ISSUE THREAD

**Issue by SLiGe** [jeecgboot/JeecgBoot#6703]
##### 版本号：
v 3.7.0

##### 问题描述：
Online代码生成不支持多级包名，
例如bussi_package配置为``com.xxx ``,表名为``emr_ns_record_config``
生成的包名是``com.xxx.emr.ns.recordconf``.
目前只能通过手动修改bussi_package实现,还要重启项目，比较麻烦

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
 - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
有计划优化

**Comment by SLiGe** [comment]
贴一下临时解决办法：
```java
@Aspect
@Component
public class CodeGenAspect {
    @Around("execution(* org.jeecg.modules.online.cgform.c.a.b(..))")
    public Object aroundAdvice(ProceedingJoinPoint joinPoint) throws Throwable {
        // 修改参数值
        JSONObject arg = (JSONObject)joinPoint.getArgs()[0];
        org.jeecg.modules.online.cgform.model.d var2 = JSONObject.parseObject(arg.toJSONString(), org.jeecg.modules.online.cgform.model.d.class);
        String entityPackage = var2.getEntityPackage();
        String[] packages = entityPackage.split("_");
        ResourceBundle bundle = ResourceBundle.getBundle("jeecg/jeecg_config");
        String bussiPackage1 = bundle.getString("bussi_package");
        if (packages.length>1){
            var2.setEntityPackage(packages[packages.length-1]);
            StringBuilder bussiPackage = new StringBuilder(bussiPackage1);
            for (int i = 0; i < packages.length-1; i++) {
                bussiPackage = new StringBuilder(bussiPackage + "." + packages[i]);
            }
            org.jeecgframework.codegenerate.a.a.g = bussiPackage.toString();
        }else {
            org.jeecgframework.codegenerate.a.a.g = bussiPackage1;
        }
        // 调用原始方法
        return joinPoint.proceed(joinPoint.getArgs());
    }
}
```

**Comment by SLiGe** [comment]
> 贴一下临时解决办法：
> 
> ```java
> @Aspect
> @Component
> public class CodeGenAspect {
>     @Around("execution(* org.jeecg.modules.online.cgform.c.a.b(..))")
>     public Object aroundAdvice(ProceedingJoinPoint joinPoint) throws Throwable {
>         // 修改参数值
>         JSONObject arg = (JSONObject) joinPoint.getArgs()[0];
>         org.jeecg.modules.online.cgform.model.d var2 = JSONObject.parseObject(arg.toJSONString(), org.jeecg.modules.online.cgform.model.d.class);
>         String entityPackage = var2.getEntityPackage();
>         String[] packages = entityPackage.split("_");
>         ResourceBundle bundle = ResourceBundle.getBundle("jeecg/jeecg_config");
>         String bussiPackage = bundle.getString("bussi_package");
>         if (packages.length > 1) {
>            arg.put("entityPackage",packages[packages.length - 1]);
>             StringBuilder finalBussiPackage = new StringBuilder(bussiPackage);
>             for (int i = 0; i < packages.length - 1; i++) {
>                 finalBussiPackage.append(".").append(packages[i]);
>             }
>             org.jeecgframework.codegenerate.a.a.g = finalBussiPackage.toString();
>         } else {
>             org.jeecgframework.codegenerate.a.a.g = bussiPackage;
>         }
>         // 调用原始方法
>         return joinPoint.proceed(joinPoint.getArgs());
>     }
> }
> ```

不支持``RequestMapping``多级路由

**Comment by zhangdaiscott** [comment]
还有其他地方需要改

**Comment by SLiGe** [comment]
> 还有其他地方需要改

其他的地方我也没法追踪了，等着优化了，或者是否可以告知下还需要改动哪里

**Comment by zhangdaiscott** [comment]
下个版本支持
