### ISSUE TITLE
【Online表单开发】表单添加多个外键无法保存

### ISSUE THREAD

**Issue by zrtzrt** [jeecgboot/JeecgBoot#6758]
##### 版本号：
3.6.1

##### 问题描述：
【Online表单开发】表单添加多个外键无法保存
表单添加多个外键点击保存后只发送了jeecgboot/sys/duplicate/check请求，返回成功后没有发送/jeecgboot/online/cgform/api/editAll，单个外键保存正常。

##### 截图&代码：
![截屏2023-12-22 11 10 32](https://github.com/jeecgboot/jeecgboot-vue3/assets/27396355/2ad8f912-00ae-4e2e-9f25-abcddefa1796)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhouyu629** [comment]
多外键的需求如何实现？

**Comment by yingshi-7** [comment]
不能关联多个表吗?
