### ISSUE TITLE
JVxeTable 控件的 pushrows, addrows,addOrInsert,insertRows 都没有id值，不知道如何才能如何才能有rowkey，而且复制后一直是两个选择，无法取消，必须是同选

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/JeecgBoot#6761]
##### 版本号：
3.6.1

##### 问题描述：
1、JVxeTable 控件的 pushrows, addrows,addOrInsert,insertRows 都没有id值，不知道如何才能如何才能有rowkey.
2、在使用上面的方法后，页面出现同时选中两个，无法取消选中其中一个。

##### 截图&代码：

2、出现的同选和同不选
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/82691864/36fbed6f-650b-4c69-b560-93adaa0d8345)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 3099749306** [comment]
大佬，我也遇到你这种问题了。
我是要将子组件选择的数据在JVxeTable中进行显示，但是第一次选择的时候，传过来的数据明明有id，addRows后id不见了，第二次选择的，addRow后id又有，可以帮忙看下吗？呜呜呜
![image](https://github.com/user-attachments/assets/dfde6dc8-7e04-40b4-9b77-b61592cef27f)

**Comment by 3099749306** [comment]
![image](https://github.com/user-attachments/assets/308673ba-5437-4486-bc12-1563ca35c47a)
![image](https://github.com/user-attachments/assets/c3ad4d06-a149-478b-acdb-6253aba9b995)
