### ISSUE TITLE
登录界面图片验证码更换为滑块验证码

### ISSUE THREAD

**Issue by WFL-Tian** [jeecgboot/JeecgBoot#6766]
##### 版本号：
jeecgboot3.6.0

##### 问题描述：
由于现在安全要求增强，建议将登录界面的图片验证码更换为人机交互的滑块验证，开源比较出名的有AJ-Captcha。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/24720561/065a27ac-d4b8-41c3-85c0-cf14770118d0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by havenothingtosay** [comment]
> https://help.jeecg.com/component/Verify.html 请参考文档自行替换为滑块验证码

请问是否能扩展成后端验证的，目前示例中是固定图片且纯前端验证
