### ISSUE TITLE
仪表盘路由跳转没反应

### ISSUE THREAD

**Issue by Jasse1997** [jeecgboot/JeecgBoot#6852]
##### 版本号：
3.7.0

##### 问题描述：
1、仪表盘设置了路由跳转点击没反应
2、仪表盘的路由跳转到积木报表时，如何携带token参数，现在因为没有携带token参数，所以显示不到数据

##### 错误截图：
![2](https://github.com/jeecgboot/JeecgBoot/assets/56105409/a5d26f2c-4a63-476c-ba39-fee54bf92413)

**Comment by zhangdaiscott** [comment]
/jmreport/list?token=${token}

参考试试

**Comment by Jasse1997** [comment]
${token}也试过了，他没有解析这个${token}，还是原样输出在url上

**Comment by zhangdaiscott** [comment]
好的  sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by Jasse1997** [comment]
好的，谢谢

**Comment by Jasse1997** [comment]
现在我的积木报表版本更新到1.8.1还是没有修复，想问一下这个什么时候能够发布

**Comment by zhangdaiscott** [comment]
仪表盘未升级
