### ISSUE TITLE
生成的代码，数据日志无法使用

### ISSUE THREAD

**Issue by lc0405** [jeecgboot/JeecgBoot#6853]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
代码生成后，默认不集成，需要手工集成

**Comment by lc0405** [comment]
请问有没有什么方便的方法生成data_content数据内容。如果更新时字段较多，一个一个字段的判断太不方便了

**Comment by zhangdaiscott** [comment]
参考
https://help.jeecg.com/java/java/datalog.html

**Comment by jhy0339** [comment]
sys_data_log 里的数据如何插入json，并且分析出结果，有说明文档吗？
我发现online生成的表单，往sys_data_log里的插入的时候数据值有问题

下图是文本类的，显示正常
![image](https://github.com/user-attachments/assets/120ee4c7-a3c3-41dc-a72c-835a8369c79a)

下图是数据字典类的，显示异常
![image](https://github.com/user-attachments/assets/36e2ab22-f296-4904-99df-7e4c9628067c)
