### ISSUE TITLE
JImageUpload 上传失败。

### ISSUE THREAD

**Issue by qtzxly** [jeecgboot/JeecgBoot#6854]
##### 版本号：
  "version": "3.6.3",

##### 问题描述：

JImageUpload组件， 前后端都跑在一台电脑，用localhost上传就ok， 分开两台电脑跑前后端， 其他接口ok，上传就不行

##### 错误截图：
![QQ图片20240708102357](https://github.com/jeecgboot/JeecgBoot/assets/59547757/7e32dc46-3796-49a4-b47b-36eb1d815900)

![QQ图片20240708102405](https://github.com/jeecgboot/JeecgBoot/assets/59547757/bacddd37-3eba-46af-9418-68cf6cfd9573)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/3162115/b403dcbc-74fa-4af3-8fc9-d7b00d76408d)

接口通吗

**Comment by qtzxly** [comment]
https的原因
