### ISSUE TITLE
user-dropdown这个组件用key作为prop名称

### ISSUE THREAD

**Issue by yidao2000** [jeecgboot/JeecgBoot#6855]
##### 版本号：
分支: springboot3,  
版本: 3.7.0（发布日期：2024-06-17） 
vue3部分

##### 问题描述：
在控制台里出现这样的错误,下面错误截图1.

原因:这个错误消息表明你在某个组件中使用了 Vue 的保留属性 key 作为 prop 名称。key 是 Vue 内部使用的一个特殊属性，用于标识节点和组件的唯一性，因此不能将其用作 prop。

解决办法:把key改为itemKey就好了.

这两个文件路径分别是
src/layouts/default/header/components/user-dropdown/index.vue
src/layouts/default/header/components/user-dropdown/DropMenuItem.vue

##### 错误截图：
F12控制台出现的错误,由于无法复现了,我把错误粘贴到sublime里了.
![image](https://github.com/jeecgboot/JeecgBoot/assets/12994137/0f4f606a-ff07-4b10-8cb3-6483e6325274)
把key改为:itemKey
![image](https://github.com/jeecgboot/JeecgBoot/assets/12994137/76498861-f834-4d4a-9e79-8d56cd43ea34)
把key改为itemKey
![image](https://github.com/jeecgboot/JeecgBoot/assets/12994137/22737084-1c3a-494e-af60-18d02bb5d01f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
