### ISSUE TITLE
Online报表设计，搜索条件只展示10条数据

### ISSUE THREAD

**Issue by xiaomanvip** [jeecgboot/JeecgBoot#6857]
##### 版本号：
3.5.0

##### 问题描述：

Online报表设计-动态报表配置明细-选择userId字段为搜索条件，使用字典code使用SQL字典查询，格式如下SELECT username AS value, realname AS text FROM sys_user，但是Popup弹窗引用时，用户信息搜索下拉框只显示10条用户数据。在sql后面拼接limit 20时出现报错提示 LIMIT 20 LIMIT ? ### 
Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'LIMIT 10' at line 1 ; bad SQL grammar [];

##### 错误截图：

操作失败， ### Error querying database. Cause: java.sql.SQLSyntaxErrorException: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 
'LIMIT 10' at line 1 ### The error may exist in URL [jar:file:/E:/myMaven/Repository/org/jeecgframework/boot/hibernate-re/3.4.4-beta/hibernate-re-3.4.4-beta.jar!
/org/jeecg/modules/online/cgreport/mapper/xml/OnlCgreportHeadMapper.xml] ### The error may involve org.jeecg.modules.online.cgreport.mapper.OnlCgreportHeadMapper.
selectPageBySql-Inline ### The error occurred while setting parameters ### SQL: 
SELECT group_code value, group_name text FROM saas_system.sys_group WHERE sys_group.tenant_id = 1001 LIMIT 20 LIMIT ? ### 
Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'LIMIT 10' at line 1 ; bad SQL grammar []; nested exception is 
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to 
your MySQL server version for the right syntax to use near 'LIMIT 10' at line 1

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by xiaomanvip** [comment]
![1001](https://github.com/jeecgboot/JeecgBoot/assets/73579349/30dc56e4-791e-4288-b408-eee52fddf072)
![100101](https://github.com/jeecgboot/JeecgBoot/assets/73579349/7faa9a56-cc76-44b4-b742-b23275149ddc)
![100102](https://github.com/jeecgboot/JeecgBoot/assets/73579349/50e31ac2-b754-4433-b72f-4f5db17f6ed6)

**Comment by xiaomanvip** [comment]
数据库里的工种有一百多个，但是搜索条件里只有10条。

**Comment by zhangdaiscott** [comment]
你搜索就变了
