### ISSUE TITLE
测试功能时发现前端数据进入到controller后，list的数据为NULL  数据丢失

### ISSUE THREAD

**Issue by huoshuigege** [jeecgboot/JeecgBoot#6858]
##### 版本号：
最新版本1.7.8
前端vue3

##### 问题描述：主表和附表在功能测试中可以正常使用，当我将主表生成代码之后，并放入相对应的前端和后端位置后（清除缓存且重启过）  测试功能时发现前端数据进入到controller后，list的数据为NULL  数据丢失   日志输出没有出现错误提示

场景：我创建了两张表  一张主表，一张附表（图片配置在下方）

表单开发的功能测试截图（正常情况）
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/985e05b9-8279-4647-bbf8-c9f831b25038)
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/956866dc-df89-4ba2-a211-95628d9c67f1)

##### 错误截图：
代码生成参数
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/645be68a-2422-4f2c-9b9a-c3bd6bd658a6)

使用前端代码进行添加测试（异常情况）
表单截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/e098a6f4-0948-4125-a5aa-e994b36f11fe)

浏览器截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/b6c65b02-0732-48bd-b1b2-28a9d98b179c)

idea断点截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/80b23a2a-5d87-44a4-be7c-0fce9a4c40e5)
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/d6dee334-ae34-4c08-89c7-bc7c4e6255b3)

放行后浏览器点击详情截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/e4f57404-43ff-4beb-b72b-f8ec93d18c15)

使用Swagger接口进行添加测试（异常情况）
swagger准备数据截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/accbd5ed-8685-4191-9cd8-e16d08601c1a)
idea断点截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/d8cace0f-0540-4693-8dc4-6fe07c8d49b5)
放行后浏览器点击详情截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/6df3900c-133c-4840-b906-09fd5e0dfebe)

建表参数截图
主表
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/770ffbda-663d-4ec1-925e-fb8a5224360d)
附表
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/98a84795-c96f-44e9-8e36-c9c4344bb4b4)
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/008dea82-a129-4333-b96c-7806d6db28ec)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by huoshuigege** [comment]
使用的版本是最新提交的master分支中 日志为：  
[升级jimureport到最新版1.7.8]的版本

**Comment by zhangdaiscott** [comment]
跟积木报表有关系？

**Comment by huoshuigege** [comment]
> 跟积木报表有关系？

我刚才试了一下将积木报表关闭，也依旧是失效的状态
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/7d2c76c8-4da8-431d-b057-2295fe163c14)

当我自己将
@RequestBody TCustomerOrderPage tCustomerOrderPage   替换成    HttpServletRequest request
来接受参数时
可以取出后者的请求体转化成string  进而使用hutool转化成实体类   list中的数据可以正常取出  
但就是使用@RequestBody TCustomerOrderPage tCustomerOrderPage无法正常取出

**Comment by zhangdaiscott** [comment]
版本号写准确了

**Comment by huoshuigege** [comment]
> 版本号写准确了

使用的时主分支最新代码
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/fd47cb56-f64b-4c4b-bbbd-8e4f2897286b)
版本号为3.7.0

使用的jdk版本为java8
前端vue3

**Comment by zhangdaiscott** [comment]
自己debug跟踪生成的代码，看看是不是你生成的时候命名不规范，导致的

**Comment by huoshuigege** [comment]
> 自己debug跟踪生成的代码，看看是不是你生成的时候命名不规范，导致的

好的，谢谢

顺便再问一个问题，为什么我配置了积木报表，但在生成的前端代码没有打印选项（重新生成了很多次代码，所以肯定是删了缓存和重启过的）
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/ff928ea5-3e4e-4bda-a061-7795ff18d119)

功能测试中是正常的
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/2450c573-0317-438f-b2c7-1bd2ea91d743)

但在代码实现的位置没有显示出打印选项，查看前端源码，也没有发现打印的代码
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/6b3869be-9bbc-4c8a-aa8e-fc86eccf61b7)
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/02fce77e-4b6e-4a97-afa5-0f82b20f1bdd)

请问一下何种操作会导致这样的问题

**Comment by zhangdaiscott** [comment]
打印不生成

**Comment by huoshuigege** [comment]
> 打印不生成

我有点没理解，能说的详细一点么  
我应该如何操作可以将打印调整出来

**Comment by zhangdaiscott** [comment]
生成后，手工写代码加上
