### ISSUE TITLE
登录完成后就一直处于等待，不能进入主页面

### ISSUE THREAD

**Issue by shenzw001** [jeecgboot/JeecgBoot#6861]
##### 问题描述：
刚开始的时候是没有问题， 后来不知道是因为清理浏览器缓存，还是什么原因，就不能进入主页面了， 打开无痕窗口可以，后来打开无痕窗口也不行了， 就把chrome重装了 也不行

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/16165120/b064348c-2099-47dd-b9dd-3781955f0084)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
F12报什么错

**Comment by shenzw001** [comment]
看控制台没有报错， 而且还会占cpu和内存； 感觉就是卡到那里了；  那个webSocket的 状态是pending 不知道是不是正常
![image](https://github.com/jeecgboot/JeecgBoot/assets/16165120/de76c36a-27e9-470e-8dc6-ae4a88dff66b)

**Comment by shenzw001** [comment]
![image](https://github.com/jeecgboot/JeecgBoot/assets/16165120/44587fac-1779-48ab-8a76-220d87c68208)

**Comment by LHK8088** [comment]
我也碰到这个问题,https://github.com/jeecgboot/JeecgBoot/issues/6868

**Comment by oswm** [comment]
之前遇到类似的问题，好像是前端代码死循环了。 
export function createPermissionGuard(router: Router) {
  const userStore = useUserStoreWithOut();
  const permissionStore = usePermissionStoreWithOut();
  router.beforeEach(async (to, from, next) => {
    if (
      from.path === ROOT_PATH &&
      to.path === PageEnum.BASE_HOME &&
      userStore.getUserInfo.homePath &&
      userStore.getUserInfo.homePath !== PageEnum.BASE_HOME
    ) {
      next(userStore.getUserInfo.homePath);
      return;
    }

这块代码，如果admin用户的homePath不是‘dashboard/analysis’就会死循环

**Comment by LHK8088** [comment]
感谢楼上回答,我的问题解决了,确实是因为 sys_role_index  表中的 url  变成了 dashboard

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by sjlei** [comment]
### 问题原因

由于角色的自定义首页设为了 `dashboard`，而 `dashboard` 在菜单配置里配置了默认跳转到 `dashboard/analysis`，在此期间vue-router的form.path一直都是`/`，所以就导致了死循环

### 修改方式

限制跳转到自定义首页的次数即可，修改方案参考下图：

![image](https://github.com/user-attachments/assets/a8bf0a4a-dfae-4005-80fb-25c7e9564883)

**Comment by shenzw001** [comment]
按你的方式，已解决， thanks
