### ISSUE TITLE
报错:Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by yidao2000** [jeecgboot/JeecgBoot#6863]
##### 版本号：
 3.7.0（发布日期：2024-06-17） springboot3   前端

##### 问题描述：

f12开发者工具打开,一直报错:Unchecked runtime.lastError: The message port closed before a response was received.
请问如何修复此bug.

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/12994137/f6f8a4da-bd55-4d83-9cbf-985c49805926)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
如何重现出这个错误呢

**Comment by liaozhiyang** [comment]
是chrome第三方扩展程序导致的，尝试一个个关掉试试。
多人反馈跟迅雷下载有关
