### ISSUE TITLE
【3.7.0】searchFormSchema 配置单个label的labelWidth不生效

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6865]
##### 版本号：
3.7.0

##### 问题描述：

searchFormSchema 配置单个label的labelWidth不生效
formConfig统一配置labelWidth才能生效，单个配置不支持

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/162244360/7ff482e5-879e-4411-bd87-170a9d41f5f2)
![image](https://github.com/jeecgboot/JeecgBoot/assets/162244360/67947915-91ac-4323-ab76-6e85e256baf0)
![image](https://github.com/jeecgboot/JeecgBoot/assets/162244360/2a13c25a-b62d-4b2e-bc9f-f7c902d19a30)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by xie-dongbo** [comment]
{
    label: '账号',
    field: 'username',
    component: 'JInput',
    itemProps:{
      labelCol: {sm: {span: 3, offset: 0},style:'max-width:12%' },
      wrapperCol:{ span:5 },
    }
    //colProps: { span: 6 },
  },

**Comment by xie-dongbo** [comment]
瞎调

**Comment by xie-dongbo** [comment]
实际根据字数改下max-width就行

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可按如下图进行修改：
![image](https://github.com/user-attachments/assets/fbf150ef-ee46-4a33-805c-3cbe30c6fcb4)
