### ISSUE TITLE
无法使用主题模板， 在线表单中生成的模板在  功能测试中可以正常的显现   使用代码生成后依旧是默认模板

### ISSUE THREAD

**Issue by huoshuigege** [jeecgboot/JeecgBoot#6866]
##### 版本号：
最新master分支

##### 问题描述：
无法使用主题模板， 在线表单中生成的模板在  功能测试中可以正常的显现   但是将代码生成后（删除原有代码，更新最新代码，清空缓存并重启） 前端浏览器页面显示的依旧是默认主题

主表配置截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/92b588c6-de44-4554-bc5e-6a3c1ce83f66)
子表配置截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/89f41cbe-cad5-4382-9392-0ea7457b9c9b)

功能测试页面（正常情况）
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/9456d70e-3a70-4062-9720-a957ce52bff8)
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/8fa225f0-ee30-4090-a05e-6d2520ff34d9)

##### 错误截图：

代码生成后表单页面（主题依旧是默认主题）
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/eb000bca-b21e-4c2c-a387-9a94a2e67d18)
菜单管理页面
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/80ade271-2abc-44aa-a9a5-249301c73313)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
代码生成的时候，选择一下模板
