### ISSUE TITLE
hibernate-re 3.0.0-beta中在线表单导出大量数据时内存溢出

### ISSUE THREAD

**Issue by zhoujh001** [jeecgboot/JeecgBoot#6867]
##### 版本号：
3.0.0-beta

##### 问题描述：
hibernate-re中关于在线表单导出大量数据时内存溢出

##### 错误截图：
<img width="857" alt="image" src="https://github.com/jeecgboot/JeecgBoot/assets/9425233/c7eb99cf-9ed0-4109-83a0-704039714f25">
((Map)var7).put("pageSize", -521);
此参数会使得org.jeecg.modules.online.cgform.service.a.c#queryAutolistPage方法走全量查询的方法，数据量特别大的时候就会导致内存溢出，FullGC不了导致宕机

**Comment by zhangdaiscott** [comment]
多大的数据量？

**Comment by zhangdaiscott** [comment]
我们忘记那个版本做过优化，可以试下最新版是否存在问题

**Comment by zhoujh001** [comment]
@zhangdaiscott 百万级的数据，我看后面3.2的版本里是做了优化，但是我们项目的版本是3.0的，替换这个jar包的新版本会有问题，启动不了。有针对这个版本的优化版本吗？

**Comment by zhoujh001** [comment]
由于没有源码，自己覆盖类文件来重写比较麻烦

**Comment by zhangdaiscott** [comment]
你可以整体升级

**Comment by zhoujh001** [comment]
整体升级的话，改动就比较大了，项目目前功能比较多，不太好升级。算啦，还是不用这个在线表单的功能了
