### ISSUE TITLE
为什么我配置了积木报表，但在生成的前端代码没有打印选项

### ISSUE THREAD

**Issue by huoshuigege** [jeecgboot/JeecgBoot#6869]
##### 版本号：
最新master版本  3.7.0
vue3
java8

##### 问题描述：
为什么我配置了积木报表，但在生成的前端代码没有打印选项（重新生成了很多次代码，所以肯定是删了缓存和重启过的）
这个问题我昨天问了一下，我理解可能有点问题，还请麻烦老师解答一下下面的问题

**关键问题：代码生成器，会将打印按钮生成出来吗？
如果不能，我应该如何配置才能像功能测试一样，显示出打印按钮**

##### 错误截图：
功能测试中有打印按钮
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/042aa0d0-bfb4-4b01-8a0c-6fa2b4737c3c)

生成代码后没有打印按钮
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/110241b0-757a-4099-873d-e752254066c0)

开启积木报表截图
![image](https://github.com/jeecgboot/JeecgBoot/assets/107799621/fbbe8a31-945f-4c3c-a7ae-226989f61adc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
此功能点不支持代码生成
