### ISSUE TITLE
BasicModal 和 BasicForm 混用加载问题

### ISSUE THREAD

**Issue by CodeXiaoYan** [jeecgboot/JeecgBoot#6870]
##### 问题描述：
 一起使用时候字段大概二十多个就有明显的延迟，点击新增按钮需要等大概800毫秒才将Modal打开

##### 错误截图：
优化问题

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
BasicModal 和 BasicForm 混用加载问题，是怎么用的，贴代码

**Comment by CodeXiaoYan** [comment]
![image](https://github.com/user-attachments/assets/99a5fe92-792f-45eb-b598-627c16e71c13)

**Comment by CodeXiaoYan** [comment]
表单大概20多个字段，使用原生表单没有这个问题，字段多时候性能就有明显的问题

**Comment by zhangdaiscott** [comment]
你的版本号

**Comment by CodeXiaoYan** [comment]
3.6.3

**Comment by zhangdaiscott** [comment]
试试最新版

**Comment by liaozhiyang** [comment]
经测试无复现。测试例子的字段70+，综合各种组件。
你测试时是否打开了vuetools？
或者你下载一份干净代码，把你这段业务代码贴进去试下，看是否还这样。
![iShot_2024-07-17_16 17 59](https://github.com/user-attachments/assets/33403c99-f086-464b-8e0e-103722d7df1c)
