### ISSUE TITLE
Online表单开发-导入数据库表-如何指定其它数据库源(oracl)的指定实例模式

### ISSUE THREAD

**Issue by haohewei123** [jeecgboot/JeecgBoot#6871]
##### 问题描述：
jeecgboot平台数据库A（mysql）
需要生成数据库B（oracle）表的代码：
数据库B的账号为‘zhangsan’，默认对应的数据库实例为T1，需要生成的表在数据库实例T2中。如下图，我制定了schema=T2，没有生效，页面查出来的数据库表还是T1的。请问该如何配置，系统是否支持？

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/49243137/ca85e4d5-9200-43bd-aa97-3e8e07521d6e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/codegen/config.html


注释掉类
jeecg-module-system\jeecg-system-biz\src\main\java\
org\jeecg\config\init\CodeGenerateDbConfig.java

**Comment by haohewei123** [comment]
我已经注释调了。oracle每个用户默认一个实例，我的‘zhangsan’用户默认的是T1的权限，可以通过T2.tablename查询T2的表，我现在需要生成T2实例里的数据库表。

**Comment by haohewei123** [comment]
#oracle
diver_name=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@
username=zhangsan
password=
database_name=
schema=T2
odeGenerateDbConfig.java类已经注释。按照上面的配置，我查出来的还是T1里的表，schema=T2并没有生效
