### ISSUE TITLE
后台打包问题

### ISSUE THREAD

**Issue by 2058148607** [jeecgboot/JeecgBoot#6872]
##### 错误截图：
![ed0f5d4891b1a5bcc8e32352b5c0fa6](https://github.com/jeecgboot/JeecgBoot/assets/91590452/77158b78-3c55-4cfd-8f28-6a3b35690df2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看不出来
