### ISSUE TITLE
Online表单开发-导入数据库表-如何指定其它数据库源(oracl)的指定实例模式

### ISSUE THREAD

**Issue by haohewei123** [jeecgboot/JeecgBoot#6873]
##### 问题描述：
jeecgboot平台数据库A（mysql）
需要生成数据库B（oracle）表的代码：
数据库B的账号为‘zhangsan’，默认对应的数据库实例为T1，需要生成的表在数据库实例T2中。如下图，我指定了schema=T2，没有生效，页面查出来的数据库表还是T1的。请问该如何配置，系统是否支持？
【CodeGenerateDbConfig类已经注释调了。】
#oracle
diver_name=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@
username=
password=
database_name=
schema=T2

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
启动类加上下面代码，试试

```
@EnableAutoConfiguration(exclude={CodeGenerateDbConfig.class, org.jeecg.interceptor.a.class})
```

![image](https://github.com/jeecgboot/JeecgBoot/assets/3162115/626be235-5d45-4825-b509-a1354ce1f475)

**Comment by haohewei123** [comment]
你好，1、启动类直接加@EnableAutoConfiguration(exclude={CodeGenerateDbConfig.class, org.jeecg.interceptor.a.class})，@EnableAutoConfiguration会报红，因为@SpringBootApplication注解里已经包含@EnableAutoConfiguration了。
2、我直接在@SpringBootApplication加的exclude={org.jeecg.interceptor.a.class}，手动注释调CodeGenerateDbConfig.class类。
@SpringBootApplication(exclude={org.jeecg.interceptor.a.class},scanBasePackages = {"org.jeecg","com.hhw"})；
启动报错：java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- org.jeecg.interceptor.a
3、我直接在@SpringBootApplication加的exclude={CodeGenerateDbConfig.class, org.jeecg.interceptor.a.class}
代码：@SpringBootApplication(exclude={CodeGenerateDbConfig.class, org.jeecg.interceptor.a.class},scanBasePackages = {"org.jeecg","com.hhw"})
报错：
java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- org.jeecg.config.init.CodeGenerateDbConfig
	- org.jeecg.interceptor.a

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/codegen/config.html
按照2没问题
