### ISSUE TITLE
v3.6.3版本的JeecgBoot-Vue3源码找不到

### ISSUE THREAD

**Issue by hyy0416** [jeecgboot/JeecgBoot#6874]
##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/78094828/800f43db-3ca5-4b8b-aafb-7b8b48bbb379)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
为什么要用老版本

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JeecgBoot-vue3

临时放开，下午关闭
