### ISSUE TITLE
部门角色授权错误

### ISSUE THREAD

**Issue by fy-kenny** [jeecgboot/JeecgBoot#6875]
##### 版本号：
3.7.0

##### 问题描述：
系统管理->我的部门->部门角色->授权

##### 错误截图：

![image](https://github.com/jeecgboot/JeecgBoot/assets/1905343/148333ca-a72f-4dd4-9d02-d0670b40b228)

**Comment by zhangdaiscott** [comment]
sq

**Comment by liaozhiyang** [comment]
你是点了添加部门角色按钮之后，然后在列表点击的授权吧？

你本地可在 src/views/system/departUser/components/DepartRoleInfoTab.vue 文件按如下图进行修改：
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/cb316a3b-adc9-447d-831c-07880bafbe78">
