### ISSUE TITLE
Redis 锁无法释放，造成redis死锁造成大量的redis exists redis命令引起redis QPS异常飙升

### ISSUE THREAD

**Issue by TMN-WH** [jeecgboot/JeecgBoot#6876]
##### 版本号：
3.5.2

##### 问题描述：
使用CacheEvict注解 在清理缓存时未对redis锁添加超时时间，一旦遇到网络问题或者程序异常退出会存在锁无法释放，造成死锁，下次进入时所有线程均无法获取锁，形成死锁且无法恢复。

##### 错误截图：
![20240710-150359](https://github.com/jeecgboot/JeecgBoot/assets/45516554/f48e73a2-d203-4366-a136-bbfa2212e03a)

![20240710-150604](https://github.com/jeecgboot/JeecgBoot/assets/45516554/b23b69bd-e3cd-439c-a7df-f688f1306043)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
同类问题
https://github.com/jeecgboot/JeecgBoot/issues/6876
https://github.com/jeecgboot/JeecgBoot/issues/6636
