### ISSUE TITLE
怎么自定义内嵌页面

### ISSUE THREAD

**Issue by itwanghao0310** [jeecgboot/JeecgBoot#6877]
##### 版本号：
3.5.4
##### 问题描述：
怎么自定义页面内嵌到布局里,菜单栏不显示子菜单

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
iframe嵌套？
