### ISSUE TITLE
swagger无法关闭 production: true 不生效

### ISSUE THREAD

**Issue by wzy109871** [jeecgboot/JeecgBoot#6880]
##### 版本号：
3.7.0

##### 问题描述：
jeecg-prod.yaml中配置如下
knife4j:
  production: true
  basic:
    enable: false
    username: jeecg
    password: jeecg@123
程序是微服务架构，启动后通过http://127.0.0.1/jeecg-system/#/home  任然可以打开swagger
有没有办法在生产环境关闭swagger

##### 错误截图：
![image](https://github.com/jeecgboot/JeecgBoot/assets/51878550/8012a45e-62fc-4dff-91c7-1544f8cabec0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
不光是gateway要使用这个配置，子服务同样也需要这个配置，gateway只是起文档的聚合作用，gateway配置只是关闭了文档的聚合
