### ISSUE TITLE
根据部门选择用户组件配置查询参数不生效

### ISSUE THREAD

**Issue by kios996** [jeecgboot/JeecgBoot#6881]
##### 版本号：
3.5

##### 问题描述：
前端使用根据部门选择用户组件，在配置了查询参数后，组件查询并不生效

##### 错误截图：
![676e0735483cbecf24c82dd7035804f6](https://github.com/jeecgboot/JeecgBoot/assets/82084531/a68cbaae-7f42-449e-9695-257659050a20)
![90c4407302ccda7cac2b67a2518ab7a2](https://github.com/jeecgboot/JeecgBoot/assets/82084531/61dbf56e-bacd-4908-83eb-49ab79d0ee3f)
![7cff397b651b0db13a881ad6bd46d318](https://github.com/jeecgboot/JeecgBoot/assets/82084531/db17f6ff-cb3c-4b56-98ff-859bad70a417)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己改的无法处理

**Comment by kios996** [comment]
不是我自己改的啊，我现在用的是系统封装的，我自己的注释了不是吗？
