### ISSUE TITLE
代码生成器生成的form布局跑偏了，如何解决？

### ISSUE THREAD

**Issue by oswm** [jeecgboot/JeecgBoot#6882]
##### 版本号：
  "version": "3.7.0",

##### 问题描述：

使用代码生成器生成的BasicForm表单里面的内容布局偏左，看着不协调。
另外官网演示页面的form也有跑偏现象

##### 错误截图：

<img width="802" alt="截屏2024-07-11 15 15 30" src="https://github.com/jeecgboot/JeecgBoot/assets/39638600/278f6108-82eb-47f9-9d32-289f0205c0b8">

<img width="705" alt="截屏2024-07-11 15 23 24" src="https://github.com/jeecgboot/JeecgBoot/assets/39638600/4b3c0b9f-8a15-4f1b-a74e-dfb2688494d4">

#### 友情提示：
请帮帮孩子吧！

**Comment by tongwudi** [comment]
![微信图片_20240711164424](https://github.com/jeecgboot/JeecgBoot/assets/28473716/4cc71783-d9e5-471c-ae46-812622814d53)

**Comment by zhangdaiscott** [comment]
sq

**Comment by oswm** [comment]
感谢楼上解答，但是修改labelWidth不生效。
另外有以下问题：
![image](https://github.com/user-attachments/assets/0cd8ff91-3baf-43d4-aa54-06d7b24ca57d)

**Comment by oswm** [comment]
![截屏2024-07-12 16 19 37](https://github.com/user-attachments/assets/fefbe75f-8159-403a-a201-a2257adde275)

**Comment by lsqGitHub716** [comment]
[https://help.jeecg.com/basicForm/useForm.html#22-labelcol%E5%92%8Cwrappercol-%E5%B1%9E%E6%80%A7]
(![image](https://github.com/user-attachments/assets/e8514f15-d29c-4391-9e16-47e3f3ff2e9f))
![image](https://github.com/user-attachments/assets/8ec8fe35-b816-4707-916f-5da9a33888f6)
