### ISSUE TITLE
JPopup控件 单选模式下 已选择数据标签项存在问题，求助帮忙看看

### ISSUE THREAD

**Issue by dangyuxuan** [jeecgboot/JeecgBoot#6883]
##### 版本号：
开源3.7.0版本

##### 问题描述：
单选模式下：
![image](https://github.com/jeecgboot/JeecgBoot/assets/49737368/8d386d62-402e-4420-9dd3-256080529c6c)

首次打开控件，显示正常
![image](https://github.com/jeecgboot/JeecgBoot/assets/49737368/32fad7ab-bc0d-4409-8a94-3035b212e9aa)
然后点击关闭后，再次打开
![image](https://github.com/jeecgboot/JeecgBoot/assets/49737368/96aecf1f-5cf4-44fd-bba1-9398e6d83a1e)
并且点击清空无法清空

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地在 src/components/jeecg/OnLine/hooks/usePopBiz.ts 文件可按如下进行修改：
![image](https://github.com/user-attachments/assets/337d535d-dd61-48ec-9290-8f6ecd02b96e)
