### ISSUE TITLE
登录完成后前端死循环，不能进入主页面

### ISSUE THREAD

**Issue by Noah9111111** [jeecgboot/JeecgBoot#6884]
##### 版本号：
3.7

##### 问题描述：
在项目重启后出现的问题，有两个相同issue的解决方法尝试后均无效（清除cookie，改url），前后端均无报错。关联issue #6861，#6868。怀疑是项目死循环。

##### 错误截图：
前后端均无报错：
![image](https://github.com/user-attachments/assets/209bf5fc-0d9f-4df3-ae36-8e6d3f273e69)
![image](https://github.com/user-attachments/assets/9e8aeec0-579a-4275-b777-7bad06a0866b)

控制台：
![image](https://github.com/user-attachments/assets/33e20e9a-9b78-4520-ac31-38ebc5f7ef9e)

内存情况：
<img width="716" alt="image" src="https://github.com/user-attachments/assets/32656c4c-0505-49cd-9f71-347d633d19da">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Noah9111111** [comment]
![image](https://github.com/user-attachments/assets/d01a21e4-85c2-4104-a0dc-908e50a43ded)

**Comment by sjlei** [comment]
问题已修复，下版本发布
