### ISSUE TITLE
java: 程序包org.jeecg.modules.jmreport.api不存在

### ISSUE THREAD

**Issue by zdxyb** [jeecgboot/JeecgBoot#6885]
##### 版本号：
2.4.3

##### 问题描述：
提示java: 程序包org.jeecg.modules.jmreport.api不存在

##### 错误截图：

![image](https://github.com/user-attachments/assets/8bd7984e-6181-4b23-8b29-df543c8a67eb)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
确认下积木报表依赖是不是没下载成功
