### ISSUE TITLE
浏览器标签页上的logo在哪里改呢,里面是一个敲字的logo.

### ISSUE THREAD

**Issue by yidao2000** [jeecgboot/JeecgBoot#6886]
##### 版本号：
3.7.0 springboot3  vue3 

##### 问题描述：

别的logo都改了,浏览器标签页上的logo在哪里改呢,里面是一个敲字的logo.

##### 错误截图：

![image](https://github.com/user-attachments/assets/867d73c4-4370-48f4-aeab-d82473941e23)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
支持.png等格式的浏览器走的是public目录下的logo.png，否则走的是public目录下的favicon.ico
<img width="954" alt="image" src="https://github.com/user-attachments/assets/b3c9912d-2111-4974-ad33-6a4d557c2557">
