### ISSUE TITLE
微服务demo启动异常：The bean 'dataSource', defined in class path resource

### ISSUE THREAD

**Issue by AmeliaGitHub** [jeecgboot/JeecgBoot#6887]
##### 版本号：
3.7.0_all

##### 问题描述：
1.nacos启动异常：修改.yml文件中的MYSQL-HOST值为127.0.0.1后，解决。
2.demo启动异常：按照网上的一些办法尝试修改后，仍未解决。

##### 错误截图：
![微信图片_20240712160438](https://github.com/user-attachments/assets/fd148fd2-0013-4a0e-8c19-7524b6844101)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
安装文档配置host了吗
```
127.0.0.1 jeecg-boot-redis
127.0.0.1 jeecg-boot-mysql
127.0.0.1 jeecg-boot-nacos
127.0.0.1 jeecg-boot-gateway
127.0.0.1 jeecg-boot-system
127.0.0.1 jeecg-boot-sentinel
127.0.0.1 jeecg-boot-xxljob
127.0.0.1 jeecg-boot-rabbitmq
```
https://help.jeecg.com/java/springcloud/switchcloud/monomer.html

**Comment by AmeliaGitHub** [comment]
这是来自QQ邮箱的自动回复邮件。
 
已收到您的邮件，祝您工作愉快!

**Comment by AmeliaGitHub** [comment]
> 安装文档配置host了吗
> 
> ```
> 127.0.0.1 jeecg-boot-redis
> 127.0.0.1 jeecg-boot-mysql
> 127.0.0.1 jeecg-boot-nacos
> 127.0.0.1 jeecg-boot-gateway
> 127.0.0.1 jeecg-boot-system
> 127.0.0.1 jeecg-boot-sentinel
> 127.0.0.1 jeecg-boot-xxljob
> 127.0.0.1 jeecg-boot-rabbitmq
> ```
> 
> https://help.jeecg.com/java/springcloud/switchcloud/monomer.html

问题已解决，是host配置问题，非常感谢！
