### ISSUE TITLE
druid数据库密码加密后，同步数据库->普通同步（保留表数据）报错

### ISSUE THREAD

**Issue by github4twsh** [jeecgboot/JeecgBoot#6889]
jeecgboot 版本号：3.7.0

 问题描述：
1、参照“druid数据库密码加密-https://help.jeecg.com/java/java/config/dbencryption.html”对mysql的root密码加密后，在“Online表单开发->同步数据库->普通同步（保留表数据）”，报错：操作失败，Cannot invoke "String.indexOf(String)" because "<local1>" is null。终端提示：

 at java.base/java.lang.Thread.run(Thread.java:1570)
2024-07-12 21:56:45.210 [http-nio-8080-exec-5] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:112 - Cannot invoke "String.indexOf(String)" because "<local1>" is null
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "<local1>" is null
2、然而，在“Online表单开发->同步数据库->强制同步（删除表，重新生成）”是正常的。
3、去掉“对mysql的root密码加密后”，在“Online表单开发->同步数据库->普通同步（保留表数据）”又正常。

友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/java/config/dbencryption.html

**Comment by github4twsh** [comment]
我是按照这个文档修改的，修改后，在“Online表单开发->同步数据库->强制同步（删除表，重新生成）”是正常的，而“Online表单开发->同步数据库->普通同步（保留表数据）”出错。

**Comment by sjlei** [comment]
问题已修复，下版本发布
