### ISSUE TITLE
BasicTable中使用rowSelection的onSelect方法无效

### ISSUE THREAD

**Issue by h3m4** [jeecgboot/JeecgBoot#6890]
##### 版本号：
3.6.3

##### 问题描述：
BasicTable中使用rowSelection的onSelect方法无效

##### 错误截图：

![微信图片编辑_20240713010901](https://github.com/user-attachments/assets/ac9eef7b-32d3-4827-9198-1a220de806a5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级
