### ISSUE TITLE
最新版本（v3.7.0+） 的表单评论附件上传功能无法使用

### ISSUE THREAD

**Issue by sxx412** [jeecgboot/JeecgBoot#6891]
##### 版本号：
v3.7.0+

##### 问题描述：
最新版本的表单评论附件上传功能也是无法使用，评论界面有上传功能，文件也有上传服务器，但是并没有记录到关联的数据表，导致无法预览和下载。

查看了代码，发现在SysCommentServiceImpl类的saveOneFileComment方法的173行，更新文件关联表的处理被注释导致。

##### 错误截图：

![image](https://github.com/user-attachments/assets/5c563fd2-6d49-4cfa-8ffa-63a44fc91ddc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
开源版暂时不支持这个功能
