### ISSUE TITLE
开启多租户后给用户角色授权，不管怎么登录，菜单都为临时角色的权限

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/JeecgBoot#6893]
##### 问题描述：
开启多租户后给用户角色授权，不管怎么登录，菜单都为临时角色的权限，原因是代码中写死了临时角色；

##### 错误截图：
![image](https://github.com/user-attachments/assets/27b3649a-45e8-43eb-86db-502ab15a6513)
![image](https://github.com/user-attachments/assets/bfea94e6-6404-4bf4-b519-29da30897dd0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你得分配租户下的角色给这个用户

**Comment by softboy99** [comment]
分配了依然如此，开启多租户后，新增的菜单都看不到
