### ISSUE TITLE
online表单开发，表单不显示字段，单据保存后，该字段后台数据被清空

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#6895]
##### 版本号：
2.6.3

##### 问题描述：
olnine表单开发，一些字段，不需要在前台显示出来，所以配置了表单不显示，但是后台这些字段是通过程序赋值了，这些单据，如果被修改保存了，发现数据库里面这些不显示的字段的值全部空了，怎么处理这个问题？

##### 错误截图：
![image](https://github.com/user-attachments/assets/02781c66-4583-426e-903b-3e66d2b2eb5e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
没这功能啊

**Comment by zhangdaiscott** [comment]
除非你勾选了非存储字段，不然不会清数据
