### ISSUE TITLE
online表单的js增强onlChange()不能响应联动组件的下拉组件值的变化

### ISSUE THREAD

**Issue by Romanticcat-Lin** [jeecgboot/JeecgBoot#6897]
##### 版本号：
3.7.0

##### 问题描述：
online表单的js增强功能，在使用“关联修改控件值【单表/主表】”功能时，假设A值是一个下拉组件，B值根据A值下拉选中的值生成，发现js代码onlChange()不能监听到下拉控件值的改变，无法触发。（如果是A值是文本输入框则是正常的）

##### 错误截图：
![1](https://github.com/user-attachments/assets/c31d6f0c-c4a0-4716-b348-2cfb4e4f741d)

F12控制台也未输出console.log信息

![2](https://github.com/user-attachments/assets/ac2c7350-796e-4110-90d3-1ebbf87e8524)

**Comment by Romanticcat-Lin** [comment]
最新测试，下拉是可以响应的，我用的是联动组件，属性是文本框，页面显示为下拉联动：
![3](https://github.com/user-attachments/assets/b21b02cf-29cd-424e-a303-80501c58f34c)

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
