### ISSUE TITLE
jeecg-cloud-nacos兼容达梦，对jeecg-boot版本是否有要求，3.5版本能否支持？

### ISSUE THREAD

**Issue by jackey35** [jeecgboot/JeecgBoot#6898]
##### 版本号：
jeecg-boot 3.5

##### 问题描述：

jeecg-cloud-nacos兼容达梦，对jeecg-boot版本是否有要求，3.5版本能否支持？同版本是否可以兼容kingbase？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你可以单独升级nacos
对jeecgboot应该不没要求

**Comment by jackey35** [comment]
目前我使用3.5版本，使用https://help.jeecg.com/java/springcloud/component/nacos.html这个帮助文档测试兼容达梦，应用启动直接报错，看着nacos整个环境没初始化
![image](https://github.com/user-attachments/assets/ee55bfad-405a-4712-8828-c78ce40976d8)
