### ISSUE TITLE
微服务环境下knife4j配置不生效,设置了knife4j.basic.enable=true还是可以直接访问knife4j

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#6900]
##### 版本号：

3.7.0_all
##### 问题描述：

微服务环境下knife4j配置不生效,设置了knife4j.basic.enable=true还是可以直接访问knife4j，没有弹出需要输入用户名密码的框，单体环境下是生效的，3.6.3也是一样的。

##### 错误截图：
![1721042521672](https://github.com/user-attachments/assets/839f9d2a-3ccf-48e7-be13-5246ecde8f36)
![1721042582909](https://github.com/user-attachments/assets/f4f32963-93c2-4512-9987-c6d22550a8aa)
![1721042611710](https://github.com/user-attachments/assets/d8048968-4f25-499e-9981-f8465d2ef23b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
使用knife4j.production=true可以关闭swagger
