### ISSUE TITLE
菜单管理中配置的路由，没有name，页面中要跳转的话只能写死url吗？

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#6901]
##### 版本号：
3.6.3

##### 问题描述：
在菜单管理中配置的路由a，如果在其他页面中想跳转至a，router,push({name: })是不是不能写name，只能写path？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![Uploading image.png…]()

自定义name

**Comment by havenothingtosay** [comment]
@zhangdaiscott 抱歉，你的回复中图片未成功上传
![image](https://github.com/user-attachments/assets/bc0bd1ba-5ef5-41f7-84b0-b3b6171ab2ed)
