### ISSUE TITLE
多租户问题

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6902]
##### 版本号：
3.6.3

##### 问题描述：
我开启多租户后，用jeecg-boot生成的添加方法，第一个可以自动添加租户id，第二个不行。MybatisPlusSaasConfig里面表都配置了，实体里面也有

##### 错误截图：
![image](https://github.com/user-attachments/assets/50734ead-4d09-488b-ad35-c3dbd2a08db3)
![image](https://github.com/user-attachments/assets/fc4ed90d-a1a8-49dc-8987-b0fd7c30a3ed)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你这样发问题，我们猜不到

**Comment by zjfksj** [comment]
第二个图片在添加的时候都获取不到登录用户，
![261C97CC-49C1-4f4b-B3BC-036086B66DD5](https://github.com/user-attachments/assets/dbb204aa-067e-4782-8403-b4813acd20ca)
![53807930-95BD-40a5-867C-FE0932DA2F83](https://github.com/user-attachments/assets/00bff213-7309-4ecf-819c-0e428fe9a78d)

**Comment by zjfksj** [comment]
![image](https://github.com/user-attachments/assets/4600bc46-472f-4091-af00-0c57ab8693b4)
这个图片是第一个接口，正常的可以获取到用户信息
