### ISSUE TITLE
springboot3版本的xxl_job进入任务调度管理页面报错

### ISSUE THREAD

**Issue by wanghuabao** [jeecgboot/JeecgBoot#6903]
##### 版本号：
3.7.0 springboot3

##### 问题描述：
springboot3版本的xxl_job进入任务调度管理页面报错

##### 错误截图：
![image](https://github.com/user-attachments/assets/26fe8fef-1d92-4276-805d-6f7727cd3269)

![image](https://github.com/user-attachments/assets/cddf4a45-38d1-437f-ba69-3c9cebb71a1a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yak33** [comment]
我是sas分支，也遇到了。原因是XXL_JOB_LOGIN_IDENTITY获取不到值，默认写死「admin」吧，反正管理页面只有一个用户
![QQ_1721263546758](https://github.com/user-attachments/assets/502a9eed-a338-4acb-834d-a54061b99b90)

**Comment by wanghuabao** [comment]
这个问题解决了，谢谢

**Comment by yak33** [comment]
> 这个问题解决了，谢谢

请问你是怎么解决的？

**Comment by wanghuabao** [comment]
改成固定值了，没有解决取不到值的问题
![image](https://github.com/user-attachments/assets/68301f37-0dfb-4894-b9af-7b4054a5243a)

**Comment by yak33** [comment]
噢哦哦，你也是固定值了呀，我还以为能获取到值了。。
但是，为什么获取不到值呢这个变量？
