### ISSUE TITLE
使用 #bodyCell插槽不生效

### ISSUE THREAD

**Issue by itwanghao0310** [jeecgboot/JeecgBoot#6904]
##### 版本号：
3.5.3

##### 问题描述：
在BasicTable里使用 #bodyCell插槽不生效

##### 错误截图：
![image](https://github.com/user-attachments/assets/414826bf-ef78-4eea-ba62-8a28160071d2)
![image](https://github.com/user-attachments/assets/a7128efd-dbf8-40dd-a690-499a3d907d55)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yang-xianzhu** [comment]
#bodyCell换成#enable，然后不要里面的v-if

**Comment by itwanghao0310** [comment]
谢谢,解决了




杠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 使用 #bodyCell插槽不生效 (Issue #6904)





 
#bodyCell换成#enable，然后不要里面的v-if
