### ISSUE TITLE
SecurityUtils.getSubject()   该方法执行后返回null

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6905]
##### 版本号：
3.6.3

##### 问题描述：
开启多租户
![image](https://github.com/user-attachments/assets/8706c251-941a-40c7-a7ae-04b16db3fc12)
开启表扫描
![image](https://github.com/user-attachments/assets/a033e65d-4ff4-4b34-ac59-ec7823d7a4eb)
添加景区正常（可以获取到登录用户及租户）
添加
![image](https://github.com/user-attachments/assets/e7590e93-9408-405e-874b-bd868edc39d0)
获取到用户登录名
![image](https://github.com/user-attachments/assets/fc7aa561-6cfb-4512-8ebb-18309012f3d3)
获取到租户ID
![image](https://github.com/user-attachments/assets/0d16ee7c-91ed-4ca6-800d-e6b432761894)

添加景点错误（获取不了登录用户以及租户）
在此基础上增加景点
![image](https://github.com/user-attachments/assets/1ac3c9b0-a74e-4d35-aca2-7d0d4cc44aee)
获取用户失败
![image](https://github.com/user-attachments/assets/f1b3e8e4-218f-4115-ac03-75b01e29605d)
根据跟踪代码发现ThreadContext.getSubject(); 为null
![image](https://github.com/user-attachments/assets/581dcd85-2330-4ebd-bc48-af9bf9d7660f)
获取的租户ID也为0
![Uploading image.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
是不是请求排除了shiro拦截了
