### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by lmh-cbcmsw** [jeecgboot/JeecgBoot#6906]
##### 错误截图：
![image](https://github.com/user-attachments/assets/9699ac61-70a8-448b-9e6d-bf6e48774525)
![image](https://github.com/user-attachments/assets/ce04e4e0-0f39-4cd9-90fc-9e74c5f94c55)
![image](https://github.com/user-attachments/assets/ce04e4e0-0f39-4cd9-90fc-9e74c5f94c55)
![image](https://github.com/user-attachments/assets/13aa4d02-e3cb-4639-bbee-47200fc640a5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by lmh-cbcmsw** [comment]
![image](https://github.com/user-attachments/assets/a086f511-af6b-438e-a21e-272b553f9c10)
命令行是这样的，跟着视频的

**Comment by lmh-cbcmsw** [comment]
![image](https://github.com/user-attachments/assets/2b3b6e49-e3fe-46e5-9004-e6fc72c3523f)
视频是这个

**Comment by zhangdaiscott** [comment]
这么明显的错误看不出吗，数据库账号密码不对
