### ISSUE TITLE
进入前端页面的时候报错，提示没有找到包

### ISSUE THREAD

**Issue by shihuiyuan123** [jeecgboot/JeecgBoot#6909]
##### 问题描述：在cmd输入指令pnpm dev进入网址，弹出报错
 Cannot find package 'E:\jeecgbootv3.7tool\JeecgBoot-master\JeecgBoot-master\jeecgboot-vue3\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.3.3_@types+node@20.14.10_less@4.2.0_terser@5.31.2__vue@3.4.31_typescript@4.9.5_\node_modules\@babel\plugin-transform-typescript\package.json' imported from E:\jeecgbootv3.7tool\JeecgBoot-master\JeecgBoot-master\jeecgboot-vue3\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.3.3_@types+node@20.14.10_less@4.2.0_terser@5.31.2__vue@3.4.31_typescript@4.9.5_\node_modules\@vitejs\plugin-vue-jsx\dist\index.cjs

##### 错误截图：
![1](https://github.com/user-attachments/assets/b17f0151-712c-4228-a3f4-f0ee349733c2)
![1721182880289](https://github.com/user-attachments/assets/2a85034a-2b44-4eb3-8679-9df55469f4ab)
![1721182891772](https://github.com/user-attachments/assets/bacb484f-9669-4070-a890-335c8654b17f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
依赖下载有问题，删除依赖使用 pnpm i

**Comment by juwencheng** [comment]
解决了吗？我也遇到这个问题

**Comment by juwencheng** [comment]
切换 node 版本为 18.12.1 之后，可以正常运行；在20.10.0版本下提示错误

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/56a13245-10d1-40c5-8429-4fddbf083762)

**Comment by powanjuanshu** [comment]
node 20.13.1 同样的错误

**Comment by zhangdaiscott** [comment]
使用我们默认的lock
