### ISSUE TITLE
二级页面获取不到当前登录用户

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6910]
##### 版本号：
3.6.3

##### 问题描述：
通过列表跳转的二级页面都获取不到当前登录用户

##### 错误截图：
![image](https://github.com/user-attachments/assets/05f392e4-48db-4734-9874-33e22a73d5da)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zjfksj** [comment]
![image](https://github.com/user-attachments/assets/782fc24b-9802-47eb-8907-2bf8cd44aed3)
![image](https://github.com/user-attachments/assets/7bf49b31-d418-4abf-94c7-1d5526e80e97)
列表都获取不到

**Comment by zhangdaiscott** [comment]
跟二级页面没关系，你是否排除了这个请求shiro拦截

**Comment by zjfksj** [comment]
确实时因为把接口加到shiro白名单里了
