### ISSUE TITLE
3.7.0 springboot3 Gateway后台服务API接口文档打开404

### ISSUE THREAD

**Issue by wanghuabao** [jeecgboot/JeecgBoot#6911]
##### 版本号：
3.7.0 springboot3 

##### 问题描述：
3.7.0 springboot3 Gateway后台服务API接口文档打开404

##### 错误截图：

![image](https://github.com/user-attachments/assets/6c7e40f1-297d-48d1-8f96-f3ba967791c1)
![image](https://github.com/user-attachments/assets/e355528c-a5ef-4097-adb4-633bbf385180)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yak33** [comment]
你看gateway的启动类里，是不是有个注掉的方法？那个应该是文档的地址

**Comment by zhangdaiscott** [comment]
？我们测试没问题啊，看看视频

**Comment by wanghuabao** [comment]
https://github.com/user-attachments/assets/ec25d3d8-44c8-4cf4-818a-e24e9c73d278

**Comment by wanghuabao** [comment]
![image](https://github.com/user-attachments/assets/7d9e80b1-09d6-4540-a681-4274c07b35db)

**Comment by wanghuabao** [comment]
https://github.com/user-attachments/assets/45cfd6a2-2e1b-44de-9d1c-656cfb52ae9d

**Comment by wanghuabao** [comment]
@zhangdaiscott system和demo的文档都能单独打开，gateway不行，配置只改动了数据源和端口

**Comment by yak33** [comment]
sas版本，我的也是gateway打不开，404

**Comment by EightMonth** [comment]
没有问题
![image](https://github.com/user-attachments/assets/b0c9171d-4844-47ee-90de-8608c0588a05)

**Comment by zhangdaiscott** [comment]
> 20240718_114403.mp4

微服务的话是有springboot3分组

你的gateway为什么是8080端口，应该你环境配置有问题
