### ISSUE TITLE
JVxeTable列过长（出现横向滚动条）时无法拖拽排序

### ISSUE THREAD

**Issue by 1372037590** [jeecgboot/JeecgBoot#6913]
##### 问题描述：
JVxeTable列过长（出现横向滚动条）时无法拖拽排序

##### 错误截图：
就拿官网最新演示地址online在线代码生成，打开f12,窗口小了有横向滚动条就无法拖动排序了，我用JVxeTable开发也遇到了这个问题，
本地代码加了解决【issues/1162】JVxeTable列过长（出现横向滚动条）时无法拖拽排序  相关的代码也还是有这个问题
![Tlink图片_20240717162901](https://github.com/user-attachments/assets/d1dbdfd8-795d-4234-95d3-421fa47a6a07)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by 1372037590** [comment]
dragSortFixed="none"  加上这个属性就可以了，文档实在看不出得配这个

**Comment by zhangdaiscott** [comment]
我们改改文档

**Comment by liaozhiyang** [comment]
文档已更新。

[JVxetable表格组件](https://help.jeecg.com/component/JVxeTable.html#%E5%9F%BA%E7%A1%80%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE)
