### ISSUE TITLE
jeecgboot-vue3

### ISSUE THREAD

**Issue by 2572190756** [jeecgboot/JeecgBoot#6916]
##### 问题描述：
前端安装依赖时  报错 @iconify/iconify 
@iconify/iconify 包已经不再维护

##### 错误截图：

![image](https://github.com/user-attachments/assets/ed6e7f32-f84b-4583-8a38-40e7401ff112)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy
