### ISSUE TITLE
校验规则（唯一性校验）失效问题

### ISSUE THREAD

**Issue by goatown** [jeecgboot/JeecgBoot#6917]
##### 版本号：
分支：master
版本：当前最新版本： 3.7.0_all（发布时间：2024-06-23）

##### 问题描述：
在线开发配置校验规则（唯一性校验），生成代码后打开新增页面输入框第一次不会触发错误信息，只有移到别的输入框再回来必须重新输入才会提示，在线功能测试同样有此问题

##### 错误截图：
![微信截图_20240718143846](https://github.com/user-attachments/assets/28e65fca-3031-41dc-ac6f-21eef485af5f)
![微信截图_20240718143856](https://github.com/user-attachments/assets/50af5a52-9da4-4335-9b05-0c11428daf4e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
失去焦点也会触发，不是输入的时候时候校验是为了性能

**Comment by goatown** [comment]
感谢大佬回复，刚验证 boot.jeecg.com 正常，可能是我们网络慢的问题，useForm添加了下防抖可以使用了。
