### ISSUE TITLE
切换标签页页面一直处于加载状态，Cannot access 'ScrollContainer' before initialization。

### ISSUE THREAD

**Issue by Excins** [jeecgboot/JeecgBoot#6920]
##### 版本号：

3.7.0
##### 问题描述：
页面一直处于加载状态。截图显示的内容是上一个标签页内容，还没切换到当前标签页。
Cannot access 'ScrollContainer' before initialization
错误发生位置：IconList.vue:52。
可能复现错误的方法：假设打开菜单A，然后去源码里修改与A页面无关的代码。回到浏览器点击菜单B，错误也许会复现。
去切换长期未切换菜单。

##### 错误截图：
![image](https://github.com/user-attachments/assets/b3550128-c850-40f0-95de-6c3b7bdf671f)

![image](https://github.com/user-attachments/assets/ddfe62bc-eea1-4e37-8cf7-9da006548b24)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Excins** [comment]
IconList.vue这是框架自己的东西。

**Comment by zhangdaiscott** [comment]
重新步骤？

**Comment by chenmonkey** [comment]
开发模式下，修改代码之后，再回到页面，控制台就会报这个错误

**Comment by Excins** [comment]
问题描述里面有，大概就是楼上说的。

**Comment by wyx666518** [comment]
3.7.0是有这个问题，偶发性问题

**Comment by Xgs97** [comment]
![image](https://github.com/user-attachments/assets/7babc1e0-f572-40c6-9ea1-785bb39bf2d3)
把ScrollContainer的引入放在最后面

**Comment by liaozhiyang** [comment]
已修复，下版本发布。

可在这个组件中把 ScrollContainer 删除，这个在实际中没用到。

可在本地 src/components/Icon/src/IconList.vue 文件按如下图进行修改：
![image](https://github.com/user-attachments/assets/1ea08b4f-4222-4470-83aa-14b7090199e2)
