### ISSUE TITLE
原生vue3设置排序字段后不生效报错

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/JeecgBoot#6921]
##### 问题描述：
原生vue3设置排序字段后不生效报错

##### 错误截图：
![image](https://github.com/user-attachments/assets/f98c75a2-d035-4ae6-89fb-40c3fd8b2ed1)

![image](https://github.com/user-attachments/assets/1fa03fc3-9dab-4db3-a3b4-275b5e769a57)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你有字段名叫sort的吗

**Comment by 520-x** [comment]
有啊后台实体类有这个字段，然后还报没有

**Comment by zhangdaiscott** [comment]
贴后台代码
