### ISSUE TITLE
xxl-job使用报错

### ISSUE THREAD

**Issue by itwanghao0310** [jeecgboot/JeecgBoot#6922]
##### 版本号：
3.5.3

##### 问题描述：
使用xxl-job的时候xxl-job服务经常报连接超时(connect timed out)偶尔能正常使用,微服务有时候会报错( xxl-job provider netty_http server caught exception java.io.IOException: 你的主机中的软件中止了一个已建立的连接。)和读取超时,应该在哪里改连接时间呢?小白求解

##### 错误截图：
![image](https://github.com/user-attachments/assets/2a0af8fc-0533-4c60-b404-4548f9322d3e)
![image](https://github.com/user-attachments/assets/3e831546-a6c4-4008-984b-68c8e1f9ecff)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jeecg-server-cloud\jeecg-visual\jeecg-cloud-xxljob\src\main\resources\application.yml
