### ISSUE TITLE
前端：modal 的 props 定义似乎应该用defineProps包一下，不然在webstorm下 BasicModal.vue 一片红

### ISSUE THREAD

**Issue by git-xyz** [jeecgboot/JeecgBoot#6923]
##### 问题描述：

src/components/Modal/src/BasicModal.vue

这个问题在webstorm 最新版本上可以复现
应该是一个类型错误，不影响使用，但是开发时比较难受

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/user-attachments/assets/cee3c6e4-8020-4c29-92f6-59ec8327c99c)
![image](https://github.com/user-attachments/assets/0536e093-a55c-46a6-9c1d-e4405aba0799)

BasicModal 使用的是 defineComponent 非setup，所以不应该使用 defineProps。

你说的都是这样的吗？这是都是格式问题，你可以格式化下。为了更好的看修改日志框架暂时不做调整
