### ISSUE TITLE
微服务架构中，自定义创建服务redis无法保持常长连接，system不会报错

### ISSUE THREAD

**Issue by xiaoqiu0817** [jeecgboot/JeecgBoot#6924]
##### 版本号：
jeecgboot 3.7.0

##### 问题描述：
微服务架构中，自定义服务redis无法保持常长连接，system不会报错

##### 错误截图：
Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out
![image](https://github.com/user-attachments/assets/8549aebd-db50-41cf-b269-334f4074d328)
![image](https://github.com/user-attachments/assets/0df77eea-b3fc-42a1-94b1-57a2c06ab6c5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自定义创建服务redis，详细说明如何使用的
