### ISSUE TITLE
关于xlsx模版导出图片出错问题

### ISSUE THREAD

**Issue by q060831** [jeecgboot/JeecgBoot#6925]
版本号：3.7.0

问题描述：
导出的数组数据中包含图片时，如果使用xlsx模版(JeecgTemplateExcelView)导出，只要有图片(使用ImageEntity)就会报错`org.apache.poi.hssf.usermodel.HSSFClientAnchor cannot be cast to org.apache.poi.xssf.usermodel.XSSFClientAnchor`,这是是图片引起，`ExcelExportOfTemplateUtil.createImageCell`创建图片单元格时是要判断Excel类型的（默认： HSSF）,但是跟踪方法并没有设置该值.

推测：在ExcelExportOfTemplateUtil类的parseTemplate方法中添加`workbook`判断可解决
```
	private void parseTemplate(Sheet sheet, Map<String, Object> map, boolean colForeach) throws Exception {
		if (workbook instanceof XSSFWorkbook) {
			super.type = ExcelType.XSSF;
		}
                ......
     ｝
```

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
已修复，待新版本发布。
