### ISSUE TITLE
表单编辑报错：接口请求超时，刷新界面重试。导致无法保存

### ISSUE THREAD

**Issue by ice0coffee** [jeecgboot/JeecgBoot#6927]
##### 版本号：
3.7.0_all

##### 问题描述：
在JeecgBoot的Online表单开发中，对一个表创建之后进行编辑，编辑完对某些字段段进行修改，然后保存时候，一直保存失败，错误信息提示为：接口请求超时，刷新界面重试。

##### 错误截图：

![error](https://github.com/user-attachments/assets/347c4f46-081c-4c8d-bb62-5517b8792b06)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
为什么会超时

**Comment by ice0coffee** [comment]
我也不知道为啥会超时呀，能不能延长一下超时时间呢？但是我不知道在哪修改对应代码

**Comment by zhangdaiscott** [comment]
超时本身有问题，并不是修改超时时间的事

**Comment by ice0coffee** [comment]
但是新建一个表就不会超时，只有建完表之后保存才会超时。

**Comment by zhangdaiscott** [comment]
那看看是那个接口导致

**Comment by RenZhixin-666** [comment]
这个问题解决了吗，怎么解决的？我也遇到相同的问题了

**Comment by shaocongyou** [comment]
我也遇到了这个问题

**Comment by RenZhixin-666** [comment]
我遇到的这个问题解决了，是因为redis中已持久化的缓存导致的，重启redis无效，清除redis缓存后就好了
