### ISSUE TITLE
vue3前端tinynce中的对象类型 RawEditorSettings不存在定义

### ISSUE THREAD

**Issue by dugudongfangshuo** [jeecgboot/JeecgBoot#6928]
##### 版本号：
3.7.0

##### 问题描述：
jeecgboot-vue3/src/components/Tinymce/src/Editor.vue
vue3前端tinynce中的对象类型 RawEditorSettings不存在定义

##### 错误截图：
![image](https://github.com/user-attachments/assets/014bd85a-824c-4958-a159-ed3ec5c395c5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

![image](https://github.com/user-attachments/assets/dc9c485b-c84f-49d4-a134-9c1305b5cc6d)
