### ISSUE TITLE
前端接收的日期变成时间戳

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6929]
##### 版本号：
3.6.3

##### 问题描述：
后端查出来的日期，前端接收到就是时间戳，很多个接口都是
![image](https://github.com/user-attachments/assets/b078fc5e-fafc-46b9-a08e-aafa6a513c75)
![image](https://github.com/user-attachments/assets/102ce63f-a2f9-4ef5-9736-251c6c8c48e0)
![image](https://github.com/user-attachments/assets/30f7edae-18f9-49a2-982b-6d67a442a8b8)
角色管理日期格式也变了
![image](https://github.com/user-attachments/assets/463629c6-2eef-4687-a954-7a8e1e6149b3)
好像只有用户管理没变
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己改过什么？怎么出现的

**Comment by zjfksj** [comment]
看过了那段时间就没改过配置，都是业务代码

**Comment by zjfksj** [comment]
是昨天中午出现的问题

**Comment by zhangdaiscott** [comment]
那需要自己排查，突然变了，肯定跟本地环境有关，或者可以参考下我们最新版近期改过此处配置不生效的问题

![image](https://github.com/user-attachments/assets/67c323a3-4543-48f8-be29-779ec38f17f7)

**Comment by zhangdaiscott** [comment]
org\jeecg\config\WebMvcConfiguration.java
