### ISSUE TITLE
使用MAVEN创建模块时报错：Error downloading org:jeecg-cloud-gen:jar:3

### ISSUE THREAD

**Issue by grayfox333** [jeecgboot/JeecgBoot#6931]
##### 版本号：
3.7.0

##### 问题描述：
创建模块的命令：mvn archetype:generate -DgroupId=org.jeecg.modules.moyu3g -Dmodule=moyu3g -Dmodule-up-first=Moyu3g -DartifactId=jeecg-module-moyu3g -Dversion=3.7.0 -DarchetypeGroupId=org.jeecgframework.archetype -DarchetypeArtifactId=jeecg-cloud-gen -DarchetypeVersion=3.5.0 -X

执行过程中，它在报错，导致模块创建失败：
Archetype org:jeecg-cloud-gen:3 doesn't exist
org.apache.maven.archetype.downloader.DownloadException: Error downloading org:jeecg-cloud-gen:jar:3.
    at org.apache.maven.archetype.downloader.DefaultDownloader.download (DefaultDownloader.java:84)

我使用的开发环境是IDEA，但使用命令行，也遇到同样的问题，按照我的理解，它应该使用的是：
.m2\repository\org\jeecgframework\archetype\jeecg-cloud-gen\3.5.0
这个文件也已经在我的 .m2中，但它并没有被使用。

附件文件是完整的MVN日志。

##### 错误截图：

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jeecg-boot-parent: The desired archetype does not exist (org:jeecg-cloud-gen:3) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project jeecg-boot-parent: The desired archetype does not exist (org:jeecg-cloud-gen:3)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
[log.txt](https://github.com/user-attachments/files/16319461/log.txt)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
完整的命令是什么

**Comment by grayfox333** [comment]
> mvn archetype:generate -DgroupId=org.jeecg.modules.moyu3g -Dmodule=moyu3g -Dmodule-up-first=Moyu3g -DartifactId=jeecg-module-moyu3g -Dversion=3.7.0 -DarchetypeGroupId=org.jeecgframework.archetype -DarchetypeArtifactId=jeecg-cloud-gen -DarchetypeVersion=3.5.0 -X

**Comment by grayfox333** [comment]
其实是想在JeecgBoot/jeecg-boot这个目录下创建一个叫jeecg-module-moyu3g的子模块。

**Comment by grayfox333** [comment]
> 完整的命令是什么

mvn archetype:generate -DgroupId=org.jeecg.modules.moyu3g -Dmodule=moyu3g -Dmodule-up-first=Moyu3g -DartifactId=jeecg-module-moyu3g -Dversion=3.7.0 -DarchetypeGroupId=org.jeecgframework.archetype -DarchetypeArtifactId=jeecg-cloud-gen -DarchetypeVersion=3.5.0 -X

**Comment by grayfox333** [comment]
很邪门啊，突然又成功了，同一个命令试着执行了一整天，一直失败，为啥现在突然又好了？

**Comment by robindongwen** [comment]
我也出现了同样的问题，是一直找不到 jeecg-cloud-gen这个包，请问这个包在哪里下载

**Comment by dhzhen2009** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.3.1:generate (default-cli) on project jeecg-boot-parent: The desired archetype does not exist (org.apache.maven.archetypes:jeecg-cloud-gen:3.5.0) -> [Help 1]

**Comment by dhzhen2009** [comment]
mvn archetype:generate \
-DgroupId=org.jeecg.modules.freightbill \
-Dmodule=freightbill\
-Dmodule-up-first=Freightbill\
-DartifactId=jeecg-module-freightbill \
-Dversion=3.8.0\
-DarchetypeGroupId=org.jeecgframework.archetype \
-DarchetypeArtifactId=jeecg-cloud-gen \
-DarchetypeVersion=3.5.0
报错
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.3.1:generate (default-cli) on project jeecg-boot-parent: The desired archetype does not exist (org.apache.maven.archetypes:jeecg-cloud-gen:3.5.0) -> [Help 1]


私服里没有jeecg-cloud-gen:3.5.0,只有2.4.2的,官方文档里说3.5.0不用改?怎么解决

**Comment by 4ugust1** [comment]
maven中央仓库中有这个版本的jar，修改maven的settings中的mirror，并且在pom文件中增加repository就可以解决

```
<mirror>
    <id>nexus-aliyun</id>
    <mirrorOf>*,!jeecg-cloud,!jeecg,!jeecg-snapshots,!getui-nexus</mirrorOf>
    <name>Nexus aliyun</name>
    <url>https://maven.aliyun.com/nexus/content/groups/public</url>
</mirror> 
```

```
<repository>
      <id>jeecg-cloud</id>
      <name>jeecg snapshots Repository</name>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
```
