### ISSUE TITLE
增强JS在子表模态框不执行问题反馈

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#6933]
##### 版本号：
3.7.0

##### 问题描述：
JS增强，子表部分有新增和单个编辑两个弹出的模态框。这两个操作弹出的模态框里，增强的JS代码不执行。

增加js如下，可改变子表单行的总价，以及主表的总价和总数量：
let total = 0, nums = 0;
      this.getSubTableInstance('bc_order_det').getValues((err,values)=>{
        console.log("values:", values);
      	if(values && values.length > 0){
        	for(let item of values){
            console.log("item info:", item);
            if(item.fact_price!='' && item.order_num != ''){
              total += item.fact_price * item.order_num;
              nums += item.order_num;
            }
          }
        }
      });
      this.triggleChangeValues({total_price: total});
      this.triggleChangeValues({total_amount: nums});
      if(event.row.fact_price!='' && event.row.order_num!=''){
      	this.triggleChangeValues({"total_price":event.row.fact_price*event.row.order_num},event.row.id, event.target);
      }

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhouyu629** [comment]
![q1](https://github.com/user-attachments/assets/fd6b5c2c-e232-4652-b536-d717d444a414)
![q2](https://github.com/user-attachments/assets/ee52bbfb-e4ed-471a-9e13-7bee148e7bed)

**Comment by zhangdaiscott** [comment]
目前还没实现，后面做

**Comment by zhouyu629** [comment]
> 目前还没实现，后面做

怎么屏蔽这两个按钮

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
你使用的是哪个事件？
1.子表改变更改主表：

这种场景应该使用 [子表改主表](https://ojrjjvdr7z.k.topthink.com/enhanceJs/form/subchangemain.html)

我使用 子表名_onlChange 事件能实现你的要求。

编辑效果：
![iShot_2024-07-29_18 40 41](https://github.com/user-attachments/assets/015645ce-f2be-4ddc-832f-63a73e2c9bf7)

新增效果：
![iShot_2024-07-29_18 41 53](https://github.com/user-attachments/assets/1d80bbc6-b6a7-482c-8b04-df6f8c1e118a)


```

jee_detail_onlChange(){
  return {
    price(){
      let total = 0
	  // 使用getSubTableInstance方法替换原有的refmap取值
      this.getSubTableInstance('jee_detail').getValues((err,values)=>{
        if(values && values.length>0){
        for(let item of values){
          total+=item.price*item.num;
          }
        }
        this.triggleChangeValues({money: total})
      }) 
    },
    num(){
      let total = 0
	  // 使用getSubTableInstance方法替换原有的refmap取值
      this.getSubTableInstance('jee_detail').getValues((err,values)=>{
        if(values && values.length>0){
        for(let item of values){
          total+=item.price*item.num;
          }
        }
        this.triggleChangeValues({money: total})
      }) 
    }
  }
}

```

2. 改变子表单行的总价？
这个场景在你js代码中没有体现
