### ISSUE TITLE
子表数据记录删除如何修改主表的值

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#6934]
##### 版本号：
3.7.0

##### 问题描述：
子表数据记录删除如何修改主表的值。
订单主表的总价字段，如何在订单明细表中删除一行记录后，修改这个总价？
是否有类似子表afterDelete的方法来执行？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by tb2888** [comment]
有方法么？

**Comment by zhouyu629** [comment]
> 有方法么？

js加强很多功能没实现，没办法。
我生成代码后，自己实现了。
