### ISSUE TITLE
程序包org.jeecg.modules.drag.service不存在

### ISSUE THREAD

**Issue by zhanbei1** [jeecgboot/JeecgBoot#6936]
##### 版本号：
commit号为：58986562
最新master分支

##### 问题描述：
无法找到有关drag下的包

##### 错误截图：

<img width="1050" alt="截屏2024-07-21 21 18 29" src="https://github.com/user-attachments/assets/d6710d53-1564-4508-bb4e-99de65eea189">

**Comment by zhangdaiscott** [comment]
？

**Comment by zhanbei1** [comment]
> ？

是我哪里没有描述清吗？？我按照官方文档:https://help.jeecg.com/java/setup/idea/startup.html在我本地的Idea上启动jeecg-boot后端服务，发现无法启动，一直在保错，说这个drag相关的包找不到。

**Comment by zhangdaiscott** [comment]
那个版本，为什么会出现这个问题？

**Comment by zhanbei1** [comment]
> 那个版本，为什么会出现这个问题？

抱歉，是我本地maven的问题，导致这个包一直无法下载下来，我尝试手动从maven下拉这个包，放入到本地仓库，启动没有问题。感谢您的开源贡献，辛苦。

同时这个Issue我将会在这个评论之后关闭
