### ISSUE TITLE
原生vue3设置排序字段后不生效报错

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/JeecgBoot#6937]
##### 错误截图：

![image](https://github.com/user-attachments/assets/63112658-579e-4454-81b4-6165438a868f)

![image](https://github.com/user-attachments/assets/48222071-7f91-430d-b88c-756bb68a5558)
![image](https://github.com/user-attachments/assets/1854ff6f-2cda-4324-9146-cb43c6dcad4f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by sjlei** [comment]
目前无法用于排序的字段有：class、ids、page、rows、sort、order
可以换个名字，比如 order_by

**Comment by sjlei** [comment]
sort、order这两个字段将在下版本可用于排序
