### ISSUE TITLE
用户权限 SysPermissionMapper queryDepartPermissionList、queryPermissionByTestRoleId接口中is_route、keep_alive、is_leaf字段数据丢失问题

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/JeecgBoot#6939]
##### 问题描述：
 修改方法如下，修改resultMap="SysPermission"
![image](https://github.com/user-attachments/assets/d6a5c3ac-3c0c-4168-9d97-3c2fd8ccaa0a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
?

**Comment by ma19881117** [comment]
实体bean中的这几个字段没有正确将值映射进去
![Uploading image.png…]()

**Comment by EightMonth** [comment]
未复现，修改后，尝试执行clean install之后再重启
![image](https://github.com/user-attachments/assets/974338f2-a117-4961-8b12-3e848e5d22dc)
