### ISSUE TITLE
[报表问题] 是否支持百万级别数据导出呢？

### ISSUE THREAD

**Issue by xiaoxpai** [jeecgboot/JeecgBoot#6940]
##### 版本号：
3.6

##### 问题描述：
首先感谢jeecgboot开源，其次在研究报表这一块业务，有个疑问，数据是否支持百万数据量导出? 或者最大支持多少数据量？因为在官方文档报表这块好像没有具体描述

##### 错误截图：
无

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
积木报表最新版的做了优化，支持大数据导出，我们测试100万没问题

https://help.jeecg.com/jimureport/export-excel-optimize.html
