### ISSUE TITLE
【积木报表】开发阶段修改前后端的签名密钥串导致门户设计的SQL解析提示签名验证失败错误，恢复默认签名密钥串使用正常

### ISSUE THREAD

**Issue by Romanticcat-Lin** [jeecgboot/JeecgBoot#6941]
##### 版本号：
v3.7.0

##### 问题描述：
有关 积木报表的 仪表盘工作台的 门户设计 功能，在添加数据集时，发现如果修改了前后端的签名密钥串时（见图1），无法正常使用SQL解析功能，使用默认的签名密钥串才使用正常，是否在积木报表内有地方需要同时修改签名密钥串？

##### 错误截图：
![1](https://github.com/user-attachments/assets/0e6f19f9-cc58-46e4-ae5b-ed38226d6430)

![2](https://github.com/user-attachments/assets/557a6384-f8c4-4049-a7ed-ea64cd4754c1)

![3](https://github.com/user-attachments/assets/84fc8757-f495-4c15-9ace-04d9ed3d3253)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
仪表盘jar包里面写死的，暂时不要改，后面我们看看怎么支持用户自己扩展

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
