### ISSUE TITLE
仪表盘设计器不能使用https

### ISSUE THREAD

**Issue by a364901254** [jeecgboot/JeecgBoot#6942]
##### 版本号：
Jeecg  Boot Version: 3.6.3

##### 问题描述：
仪表盘设计器设计好后，如果加上域名发送https请求时，/drag/page/queryById、/drag/page/addVisitsNumber会变成http，
就是这类接口
##### 错误截图：
![1](https://github.com/user-attachments/assets/ce76efdc-4a93-4a2c-95db-fb492ca11cc0)
![2](https://github.com/user-attachments/assets/a0f79fca-68fe-40d2-adf2-f73c0eb30648)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级最新版看看

**Comment by a364901254** [comment]
> 升级最新版看看


升级后还是同样的问题

**Comment by zhangdaiscott** [comment]
演示系统无问题啊
![image](https://github.com/user-attachments/assets/95dfdee3-78e5-4194-ac73-630aa5ebd831)

**Comment by a364901254** [comment]
![image](https://github.com/user-attachments/assets/31c7e3ce-375a-44b1-a503-f18636275363)
![1721874730195](https://github.com/user-attachments/assets/3321f48a-5d96-4c2c-8d5d-7ff76c3da020)
drag/page/queryById，这个请求的前面路径是要在哪里配置，我头部的请求确实是https

**Comment by twosSign** [comment]
请问下这个最后怎么解决的呢？我升级了仪表盘也没用！

**Comment by zhangdaiscott** [comment]
我们演示系统不就是https吗

**Comment by twosSign** [comment]
我jeecgboot是3.6.3的，然后把积木报表升级到和演示系统一样得1.8打包后放到线上还是请求的http，在之前小于1.8的时候甚至直接请求了我的IP，而不是访问的域名地址，升级到1.8后访问域名了，但是还是http。

**Comment by twosSign** [comment]
![image](https://github.com/user-attachments/assets/3dccd3c6-797e-4e92-88a1-8b787760105a


> 我们演示系统不就是https吗

![Uploading f7095d271bbfd2f27d977de7cdf3fb7b.png…]()
