### ISSUE TITLE
官网的表格组件，在应用mock自动生成数据的演示中，翻页后，数据的id和图片都不会自动刷新，而vben官网是可以刷新的。

### ISSUE THREAD

**Issue by kevinchan1979** [jeecgboot/JeecgBoot#6943]
##### 问题描述：

官网的表格组件，在应用mock自动生成数据的演示中，翻页后，数据的id和图片都不会自动刷新，而vben官网是可以刷新的。

##### 错误截图：

![d6b9f326cbe2b156536b257e6d1ac6af](https://github.com/user-attachments/assets/b1666fe4-6281-4c05-be5b-b62adc9e6588)

正确的应该是翻页后，id和图片都会刷新

![a5f31164f32e03ea658c3ce538f28d77](https://github.com/user-attachments/assets/0a8b4232-48aa-473c-8f92-62cc835a34bc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本更新。

你本地在 mock/demo/table-demo.ts 文件可按如下进行修改：

![image](https://github.com/user-attachments/assets/2dcc66a4-a581-48cc-95fd-a0dff9846914)


```
const { page = 1, pageNo = 1, pageSize = 20 } = query;
return resultPageSuccess(+pageNo || +page, +pageSize, demoList);
```

效果：

![image](https://github.com/user-attachments/assets/af3cc056-8800-4e6e-a388-d9c89321117d)
