### ISSUE TITLE
微服务模块间Feign调用时401 Unauthorized

### ISSUE THREAD

**Issue by yak33** [jeecgboot/JeecgBoot#6944]
##### 版本号：
3.7.0 ALL  SpringBoot3 SAS版本

##### 问题描述：

新建微服务模块，Feign调用时401 Unauthorized

##### 错误截图：
直接调用没问题：
![QQ_1721697748460](https://github.com/user-attachments/assets/9fe5d312-aa40-4fcf-a01a-159154dd6f1e)
通过微服务间调用报错：
![QQ_1721697786045](https://github.com/user-attachments/assets/c0e6bfb4-7c09-443a-8d44-fcc1cf0973fa)
调用代码：
![QQ_1721697820304](https://github.com/user-attachments/assets/ee1ed651-6d88-4a69-8bd4-c3ff84d0e223)
![QQ_1721697869688](https://github.com/user-attachments/assets/848e645d-c00c-484f-a5ec-759d9d2a6be6)
![QQ_1721697884223](https://github.com/user-attachments/assets/3aab14cb-a754-4655-88bc-aca94f0e5747)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
确认下是否是你自己的问题，如果架构有问题的话，demo和system之间的交互也会有这个问题

**Comment by yak33** [comment]
我demo和system也会报401权限问题。难道不是因为FeignConfig没有传递Authorization信息吗？SAS版本而不是shiro
![QQ_1721814069845](https://github.com/user-attachments/assets/965a6dcd-90a2-4117-a21a-0a23f4280970)

**Comment by yak33** [comment]
我把依赖的项目jeecg-boot-starter3拉下来，改了改重新打包后，测试可以了
![QQ_1721817973271](https://github.com/user-attachments/assets/dcf3644f-050a-4881-b954-c29e866a6bed)
![QQ_1721818239128](https://github.com/user-attachments/assets/8b93bc64-e5b7-4403-a5cd-11170faee57d)
