### ISSUE TITLE
添加方法获取不到当前登录用户（没有加入shiro排除）

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6945]
##### 版本号：
3.6.3

##### 问题描述：
![facdfa55cee11375ca5a5ffd54db765a](https://github.com/user-attachments/assets/86e3fdb7-5632-41c8-a85e-4fea7b40084f)
![image](https://github.com/user-attachments/assets/8f771820-4165-4794-bb81-c2e54c4ada74)
还有其他地方有配置吗

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这种问题自己debug
