### ISSUE TITLE
【3.7.3】jVxeTable 自定义表头渲染问题

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6946]
##### 版本号：
3.7.3

##### 问题描述：
在代码data.ts中配置了slots: {header: 'invoiceType'}
template中也添加了<template #invoiceType> 123 </template>
页面正常显示了自定义的配置表头 但是会提示报错
由于JVXEType同时需要配置.select, 是否能同时支持自定义表头呢

##### 错误截图：
![image](https://github.com/user-attachments/assets/d60c532c-3992-46e5-9e6c-b6ace4a0c6cf)
![image](https://github.com/user-attachments/assets/762b70f3-d282-4465-82dd-f4177dc59041)
![image](https://github.com/user-attachments/assets/4361a52d-916b-48f0-bce3-131bea08191b)
![image](https://github.com/user-attachments/assets/b28b2e35-3626-4126-9d8f-1fe7dc0e9d29)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
没有此版本号
