### ISSUE TITLE
【3.7.3】jeecg-qiankun 提议

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6947]
##### 版本号：

3.7.3
##### 问题描述：
官方给的文档关于qiankun的内容vue3版本的 较为模糊，能否补充具体实现流程的视频操作或者代码，文档描述建议更清晰一些，或者项目提供一些可查看的示例菜单，代码。
比如通过qiankun对接旧版vue2jeecgboot项目 还有旧版前后端不分离的jeecgboot项目

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
几个乾坤问题
https://github.com/jeecgboot/JeecgBoot/issues/6356
https://github.com/jeecgboot/JeecgBoot/issues/6351

**Comment by zhangdaiscott** [comment]
已经修复，下个版本提供jeecg作为子应用方案代码

**Comment by benben120** [comment]
> 已经修复，下个版本提供jeecg作为子应用方案代码

下个版本大约什么时候发布？

**Comment by benben120** [comment]
> 已经修复，下个版本提供jeecg作为子应用方案代码

@zhangdaiscott 你好 可以问下 jeecg作为子应用方案代码 大概什么时间发布呢
