### ISSUE TITLE
微服务版本无法访问积木报表

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JeecgBoot#6949]
##### 版本号：
3.7.0 微服务版本

##### 问题描述：
微服务前后端部署后，访问首页能正常打开，通过菜单访问积木设计器无法访问，nginx中server端口号已设为默认 80
访问返回 304
http://10.137.72.231/jmreport/list?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjIwMTYxNzQsInVzZXJuYW1lIjoiYWRtaW4ifQ.sUWc0iCAMvdAfAE1hIums9DknRn_l3GAX5aYhlo8o6o

##### 错误截图：

![image](https://github.com/user-attachments/assets/8e733459-9cbb-43d4-ae39-267664bf11ba)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
是通过后台端口访问的吗
