### ISSUE TITLE
JVxeTable表格Column配置formatter属性不生效

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/JeecgBoot#6950]
##### 版本号：
3.7.0_all

##### 问题描述：
JVxeTable表格Column配置formatter格式化输出内容不生效
1.JVxeTable配置
```
<JVxeTable
          ref="contactsRef"
          :toolbar="false"
          dragSort
          :rowNumber="false"
          sortKey="sortNo"
          :sortBegin="1"
          :maxHeight="580"
          :columns="columns"
          :dataSource="dataSource"
          @dragged="handleDragged"
        />
```
2.Column配置
// 客源详情联系人列表数据（VXETable)
```
export const columns: JVxeColumn[] = [
 ......
  {
    title: '最后跟进时间',
    align: 'left',
    key: 'lastFollowTime',
    width: 170,
    resizable: true,
    formatter({ cellValue, row, column }) {
      const formatValue = (cellValue && cellValue.substring(0, 10)) || '-';
      return formatValue;
    },
  }]
```

3.查询返回的数据，lastFollowTime格式为2024-07-01 24:30:59，想要格式化输出年月日（2024-07-01），但实际上按以上配置输出的还是2024-07-01 24:30:59
##### 错误截图：
<img width="757" alt="image" src="https://github.com/user-attachments/assets/ff9b1937-ffcd-4d09-bd3b-a0ca22502a63">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
