### ISSUE TITLE
rabbitmq配置类的相关问题

### ISSUE THREAD

**Issue by IT-yao** [jeecgboot/JeecgBoot#6951]
##### 问题描述：
从jeecg迁移出来到新的项目的rabbitmq配置会有循环依赖问题，为什么jeecg本身不会，是否做了其他的处理，望解答😫

##### 错误截图：
![1721717986715](https://github.com/user-attachments/assets/898f6b10-e8a4-4a79-97eb-b9ad9c8f34aa)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个不清楚啊
