### ISSUE TITLE
希望 JTreeSelect 组件能支持antdv 对应的a-tree-select 组件的title 插槽

### ISSUE THREAD

**Issue by YGmem** [jeecgboot/JeecgBoot#6953]
##### 版本号：
3.4.4

##### 问题描述：

希望 JTreeSelect 组件能支持antdv 对应的a-tree-select 组件的title 插槽

##### 错误截图：

![image](https://github.com/user-attachments/assets/4e649024-d653-43f3-babc-473706d3cdc4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已新增，下一版本发布。

你本地可在src/components/Form/src/jeecg/components/JTreeSelect.vue 文件按如下进行修改：
![image](https://github.com/user-attachments/assets/a345b42a-cc40-4062-9530-7a11e0723502)
![image](https://github.com/user-attachments/assets/b37759d8-70ed-4db0-9d14-804a39bfa6a4)


```
<template #[name]="data" v-for="name in slotNamesGroup" :key="name">
    <slot :name="name" v-bind="data"></slot>
</template>

import { ref, watch, unref, nextTick, computed } from 'vue';
import { isObject } from '/@/utils/is';
const slots = defineSlots();


 /**
   * 2024-07-29
   * liaozhiyang
   * JTreeSelect 组件能支持antdv 对应的a-tree-select 组件的title 插槽
   */
  const slotNamesGroup = computed(() => {
    const native: string[] = [];
    if (isObject(slots)) {
      for (const name of Object.keys(slots)) {
        native.push(name);
      }
    }
    return native;
  });

```

使用及效果：

![image](https://github.com/user-attachments/assets/dfd39105-0255-4854-bfef-a9ace8d6548f)

**Comment by YGmem** [comment]
> 已新增，下一版本发布。
> 
> 你本地可在src/components/Form/src/jeecg/components/JTreeSelect.vue 文件按如下进行修改： ![image](https://private-user-images.githubusercontent.com/8199499/352935467-a345b42a-cc40-4062-9530-7a11e0723502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzQ4MzcsIm5iZiI6MTcyMjIzNDUzNywicGF0aCI6Ii84MTk5NDk5LzM1MjkzNTQ2Ny1hMzQ1YjQyYS1jYzQwLTQwNjItOTUzMC03YTExZTA3MjM1MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDYyODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjEzYWVjMWFkNjg5YWFmNWVmYTVjMjIzMGIxODNjNjE5ODRlM2Q3YTY1NTgyZGI0OWJhYjEyYzQ4MGYxZTM3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YpDGADDulIzXrrvIjwBNiBP0iVtkKd_rMEfOso2UzZk) ![image](https://private-user-images.githubusercontent.com/8199499/352935532-b37759d8-70ed-4db0-9d14-804a39bfa6a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzQ4MzcsIm5iZiI6MTcyMjIzNDUzNywicGF0aCI6Ii84MTk5NDk5LzM1MjkzNTUzMi1iMzc3NTlkOC03MGVkLTRkYjAtOWQxNC04MDRhMzliZmE2YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDYyODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkyN2VlMThkZGI4ZTdmMDZlYTUwNTBkMzkzMWY2YzBjMDNjYjkzNzE5MDUzYTJlMzgzN2FlZGNlZGNjOGRlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ctbbv-rxiZJcF2-d6tJV3uUMAYWXMXFNanSpQYQW8yY)
> 
> ```
> <template #[name]="data" v-for="name in slotNamesGroup" :key="name">
>     <slot :name="name" v-bind="data"></slot>
> </template>
> 
> import { ref, watch, unref, nextTick, computed } from 'vue';
> import { isObject } from '/@/utils/is';
> const slots = defineSlots();
> 
> 
>  /**
>    * 2024-07-29
>    * liaozhiyang
>    * JTreeSelect 组件能支持antdv 对应的a-tree-select 组件的title 插槽
>    */
>   const slotNamesGroup = computed(() => {
>     const native: string[] = [];
>     if (isObject(slots)) {
>       for (const name of Object.keys(slots)) {
>         native.push(name);
>       }
>     }
>     return native;
>   });
> ```
> 
> 使用及效果：
> 
> ![image](https://private-user-images.githubusercontent.com/8199499/352936427-dfd39105-0255-4854-bfef-a9ace8d6548f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzQ4MzcsIm5iZiI6MTcyMjIzNDUzNywicGF0aCI6Ii84MTk5NDk5LzM1MjkzNjQyNy1kZmQzOTEwNS0wMjU1LTQ4NTQtYmZlZi1hOWFjZThkNjU0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDYyODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGFlNDZmZDM3MWVhMzI1M2M0NTZkM2U5M2NiYjFiZDkyNmM4M2NlY2U5MmNjMWQ5Y2Y1NGM1ZWZjMzI3Yzk5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zg1wpDt6mACKzypO1Bye0J4gkKAN5gCKBiIbp7g9EsY)

感谢
