### ISSUE TITLE
rabbitMq  添加数据时mybatis拦截器获取不到当前登录用户

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#6954]
##### 版本号：
3.6.3

##### 问题描述：
消息前
![GE~F{2X7FZ3X RB39ZHK8`2](https://github.com/user-attachments/assets/4456a791-9d35-447b-bf66-e213567fdbe7)
消息后
![%F6AK8GXPJWR2H41DHJ{I3V](https://github.com/user-attachments/assets/aa3054d4-8924-4fe7-ac63-d91161e41fc9)
处理消息：
![7QO0I}BGH9)DLVCX4E7Z1C](https://github.com/user-attachments/assets/1f6d9edd-3704-44b9-8819-648c92b4d01b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zjfksj** [comment]
导致添加的数据都没有创建人

**Comment by zhangdaiscott** [comment]
mq是无session会话的，获取不到token

看看这个
https://help.jeecg.com/java/springcloud/dev/token.html
