### ISSUE TITLE
升级最新版看看

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/JeecgBoot#6958]
升级最新版看看

_Originally posted by @zhangdaiscott in https://github.com/jeecgboot/JeecgBoot/issues/6948#issuecomment-2244296057_
            

升级到最新版了也不行，取消全选直接什么反应也没有了，我看了代码是有问题的，取消全选数据不返回了
![image](https://user-images.githubusercontent.com/18101484/351670299-a301848f-5cb2-4ad1-b919-1f1a56567e97.png)

**Comment by RacingK93** [comment]
![image](https://github.com/user-attachments/assets/4e54a9cc-5f35-44d8-97aa-77b61c99723c)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可按如下进行修改：
![image](https://github.com/user-attachments/assets/34a7f823-353b-4268-9267-2833eebda842)

效果：
![iShot_2024-07-29_17 27 28](https://github.com/user-attachments/assets/fc71faba-78e7-43d4-82ec-f3b9cc07f50c)

**Comment by liaozhiyang** [comment]
已修复，下一版发布。

你是跨页选择了是吧？

你本地可在src/components/Table/src/hooks/useCustomSelection.tsx 文件按如下图修改：

![image](https://github.com/user-attachments/assets/9a10f98f-0627-449a-adff-607c6880476a)
![image](https://github.com/user-attachments/assets/ccffe23e-3b97-4e76-8914-a9246f6536ce)

```
function getInvertRows(selectedRows: any, checked: boolean): any {
    const curPageRows = findNodeAll(toRaw(unref(flattedData)), () => true, {
      children: propsRef.value.childrenColumnName ?? 'children',
    });
    const selectedkeys = selectedRows.map((item) => getRecordKey(item));
    const result: any = [];
    curPageRows.forEach((item) => {
      const curRowkey = getRecordKey(item);
      const index = selectedkeys.findIndex((item) => item === curRowkey);
      if (index == -1) {
        checked && result.push(item);
      } else {
        !checked && result.push(item);
      }
    });
    return result;
  }
```

**Comment by wangz37-35** [comment]
onSelectAll  麻烦也发一下呗

**Comment by wangz37-35** [comment]
我按照你的代码截图修改不行
