### ISSUE TITLE
请问怎么设置账号只能查看报表？

### ISSUE THREAD

**Issue by kuangmin1984** [jeecgboot/JeecgBoot#6959]
##### 版本号：
3.7.0

##### 问题描述：
请问怎么设置账号只能查看积木报表或者说怎么发布报表只供查询？现在账号进去还能设计报表。不想他们登录还能使用设计功能。

##### 错误截图：
账号进去积木报表和管理员账号一样的权限

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/prodSafe.html

**Comment by kuangmin1984** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
