### ISSUE TITLE
打包出现依赖错误问题

### ISSUE THREAD

**Issue by Limxxx** [jeecgboot/JeecgBoot#6960]
##### 版本号：
3.4.0版本

##### 问题描述：

[ERROR] Failed to execute goal on project jeecg-system-local-api: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-system-local-api:jar:3.4.0: Failure to find org.jeecgframework.boot:jeecg-boot-base-core:jar:3.4.0 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jeecg-system-local-api

Process finished with exit code 1

##### 错误截图：
![image](https://github.com/user-attachments/assets/e1fb269a-e49a-43d4-a61d-965ba09c3bf3)
![image](https://github.com/user-attachments/assets/377deecf-1039-4f04-9da6-6c5bc7d66453)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
通过parent install

**Comment by Limxxx** [comment]
是通过parent install的，它一直出现这个问题

**Comment by zhangdaiscott** [comment]
先install core试试
