### ISSUE TITLE
3.7.0数据权限自动生成的系统变量前缀错误

### ISSUE THREAD

**Issue by tsgdnwxg** [jeecgboot/JeecgBoot#6963]
##### 版本号：
3.7.0

##### 问题描述：
在Online表单开发中，使用权限管理-数据权限-新增的方式添加规则时，下拉框所带入的变量前缀为$，但根据文档应为#，也有人员反馈了问题#6682，但是并没有写明白是是用了下拉框带入的数据。

##### 错误截图：
![微信截图_20240725150827](https://github.com/user-attachments/assets/0c4cf227-c409-4690-9e71-f8ca32a4358d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
