### ISSUE TITLE
使用a-upload组件上传，后端获取到文件名乱码，后端接收编码ISO-8859-1。使用postman测试正常

### ISSUE THREAD

**Issue by carteryh** [jeecgboot/JeecgBoot#6966]
##### 版本号：
当期分支

##### 问题描述：
使用a-upload组件上传，后端获取到文件名乱码，后端接收编码ISO-8859-1。使用postman测试正常

##### 错误截图：
vue组件上传：
![image](https://github.com/user-attachments/assets/da158a4f-60cb-4c21-84b2-3a81cec4c742)

postman测试正常：
![image](https://github.com/user-attachments/assets/6624ef80-4cd0-4599-8e4b-0c261c39ce5d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
如何重现

**Comment by carteryh** [comment]
直接使用VUE上传组件，上传中文名附件

**Comment by zhangdaiscott** [comment]
那应该是你本地项目编码是不是有问题，我们演示系统和本地都无问题

**Comment by softboy99** [comment]
遇到了同样的问题， bizPath传中文就乱码
