### ISSUE TITLE
BasicForm 没有自定义按钮的插槽吗

### ISSUE THREAD

**Issue by xiaobili** [jeecgboot/JeecgBoot#6967]
##### 版本号：
3.7

##### 问题描述：
我想在 basicForm中添加一个自定义按钮，翻遍文档也没找到相关的配置或者插槽啊

##### 错误截图：
![image](https://github.com/user-attachments/assets/0e639825-7f7d-47a2-8a03-6c181fba678e)

**Comment by yang-xianzhu** [comment]
你用的BasicModal吧？BasicModal有footer插槽

**Comment by xiaobili** [comment]
> 你用的BasicModal吧？BasicModal有footer插槽

没用modal直接在页面里套的BasicForm

**Comment by xiaobili** [comment]
> 你用的BasicModal吧？BasicModal有footer插槽

下个版本可以在BasicForm里加一个自定义按钮的插槽
