### ISSUE TITLE
vxtable 编译后显示异常

### ISSUE THREAD

**Issue by badxchen** [jeecgboot/JeecgBoot#6969]
##### 版本号：
3.6.3

##### 问题描述：
在开发模式下，vxtable的表头显示正常
编译后，显示不正常

##### 错误截图：
在开发模式下：
![image](https://github.com/user-attachments/assets/35731959-be89-4c52-9f1a-7c638223f44f)
在编译后
![image](https://github.com/user-attachments/assets/70034c9c-79d9-4f83-931d-5bde8e8603ea)

另外在开发模式下可以正常显示，合并单元格
![image](https://github.com/user-attachments/assets/1598c2a2-6fb2-4794-b6f3-51066e09891e)
编译后
![image](https://github.com/user-attachments/assets/8b76ca5b-7e95-40d5-b1fa-1c6799db12b8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版再反馈
