### ISSUE TITLE
生成代码中文乱码

### ISSUE THREAD

**Issue by hengguangjie** [jeecgboot/JeecgBoot#6971]
##### 版本号：
3.4.3

##### 问题描述：
生成代码后，文件中系统的方法注释乱码。自己指定的表名称倒是正常的。idea中也调试了编码格式，没用

##### 错误截图：

![image](https://github.com/user-attachments/assets/b37217b8-6619-4654-b2f2-0fd28141224e)

![image](https://github.com/user-attachments/assets/1104bd08-da46-438f-bf2a-1fab43194d4a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
说明你运行项目的编码不对
