### ISSUE TITLE
急！！！自定义jedis连接报错！！class RedisRxdb extends Jedis

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JeecgBoot#6972]
##### 版本号：
3.7.0 springcloud版本

##### 问题描述：
通过推荐的Maven方式新增了一个，由于自定义了一个redis模块，需要一个重写了Jedis的类来连接redis，执行制定命令获取值，
单独跑测试类没问题，但是在框架中运行就报错 estedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: connection

##### 错误截图：

![image](https://github.com/user-attachments/assets/7ffb792f-16c0-45d7-a748-16ecfeafd77f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Lctiv** [comment]
CommandArguments commandArguments = new CommandArguments 提升找不到类，单独测试类中跑都没问题，是不是框架哪边写死了

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot-starter

**Comment by Lctiv** [comment]
> https://github.com/jeecgboot/jeecg-boot-starter



> https://github.com/jeecgboot/jeecg-boot-starter

请问是有什么答复吗？如何解决，单独放在main方法中可以执行，放到框架中报错找不到类。请问如何解决？这个项目链接是给了做啥？

**Comment by zhangdaiscott** [comment]
这里面有自定义的redis，你写的太简单，有问题自己调查
