### ISSUE TITLE
JAreaSelect组件 警告问题

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#6973]
##### 版本号：

3.7.0_all
##### 问题描述：
JAreaSelect 默认使用FormSchema数组对象渲染 出现警告。

##### 错误截图：
![image](https://github.com/user-attachments/assets/a3aa3086-fa02-499a-adf9-9f74e3fbbb69)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
经测试，这个警告无法复现。


你是在在例子中加了ok事件吧？这样使用是会有警告的。
但是这个组件没有往外面抛ok事件，如果你想添加这个事情，需要emit处定义下。
![image](https://github.com/user-attachments/assets/652f8c3f-0c46-4691-baf6-939bdf51e9cd)

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/b555bc1f-e2de-433c-90b5-f469908a1ed8">
