### ISSUE TITLE
Feign直接相互调用加了token也不好使

### ISSUE THREAD

**Issue by YeyuchenBa** [jeecgboot/JeecgBoot#6974]
##### 版本号：
3.4.3

##### 问题描述：
Feign直接相互调用加了token也不好使

##### 错误截图：

![image](https://github.com/user-attachments/assets/4a550971-c847-4109-9436-fdc11be649d1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看不出所以然
