### ISSUE TITLE
vue3生成的代码优化小建议

### ISSUE THREAD

**Issue by yang-xianzhu** [jeecgboot/JeecgBoot#6976]
##### 版本号：
3.6.3

##### 问题描述：
生成的添加/编辑/详情的弹窗建议添加多一个状态，不然编辑时，弹窗的title会是`编辑` ，看起来很别扭。
![image](https://github.com/user-attachments/assets/de541fd4-2d0c-49bb-b16f-e7039a55c1ae)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
新版代码生成已经优化
