### ISSUE TITLE
online表单设计默认值怎么传参？

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#6977]
##### 版本号：
3.7.0

##### 问题描述：

比如填写默认店铺编号${shop_order_num}，怎么传递prefix这个参数到后台？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
prefix是什么

**Comment by zhouyu629** [comment]
> prefix是什么

前缀啊，我看后台默认前缀是CN，可以传递prefix进来更改生成的前缀

**Comment by zhangdaiscott** [comment]
目前不支持传递参数，写死的
