### ISSUE TITLE
使用外部数据api配置积木报表的数据集的时候，无法适配当前积木报表的需要的list数据集对象

### ISSUE THREAD

**Issue by meiziyuying** [jeecgboot/JeecgBoot#6978]
##### 版本号：
JeecgBoot3.7

##### 问题描述：
使用外部数据api配置积木报表的数据集的时候，无法适配当前积木报表的需要的list数据集对象，

需要一个编辑适配数据对象功能，把外部api返回的数据对象，转换成积木报表所需的list数据对象

##### 错误截图：

![b24ed0d06ecc56b81ac8d820d956a01](https://github.com/user-attachments/assets/1e5d9dfe-2ec0-425e-842d-7366afbd0b60)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by meiziyuying** [comment]
急急急

**Comment by meiziyuying** [comment]
需要一个转换数据对象的适配功能，可以叫数据预处理，或者数据适配

**Comment by zhangdaiscott** [comment]
https://ojrjjvdr7z.k.topthink.com/jimureport/rumen/apiJson.html
