### ISSUE TITLE
Vue3版本 开发文档 页面打开报错

### ISSUE THREAD

**Issue by xuheng8600** [jeecgboot/JeecgBoot#6979]
##### 版本号：
Vue3版本

##### 问题描述：
Vue3版本 开发文档 页面打开报错：

{"code":"40510001","msg":"invisible bucket"}

##### 错误截图：
![image](https://github.com/user-attachments/assets/a3700e5b-6bc4-408c-99d1-ababb7a2eb8d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
好了
