### ISSUE TITLE
online表单开发参照文档生成的菜单打开提示“网络请求错误,未找到该资源!”

### ISSUE THREAD

**Issue by say1yes** [jeecgboot/JeecgBoot#6980]
##### 版本号：
JeecgBoot-master 3.7.0

##### 问题描述：
online表单开发参照文档生成的菜单打开提示“网络请求错误,未找到该资源!”
方式为：1、新增一个导入表单类型的单表。2、直接通过代码生成功能生成到jeecg-module-system的同目录底下（命名为jeecg-module-test4），然后用IDEA把生成的vue3文件夹复制到前端的views目录下并改名为test4文件夹。3、把test4文件夹里的sql语句后，在前端菜单里加授权并通过IDEA重启后台。4、把菜单打开后就提示“网络请求错误,未找到该资源!”
请问是什么原因？
##### 错误截图：

![1](https://github.com/user-attachments/assets/bd983032-b9e9-46df-8524-8b049de13b5c)

**Comment by zhangdaiscott** [comment]
是不是后台依赖没下载成功

**Comment by Hammer-Suen** [comment]
我也有同样的问题, 虽然能使用AI建表, 但是无法使用对话助手
