### ISSUE TITLE
积木报表中集成其他三方数据api（树状api目录），集成后在积木报表配置的时候，选择数据集可以选择切换三方数据集

### ISSUE THREAD

**Issue by meiziyuying** [jeecgboot/JeecgBoot#6981]
##### 版本号：
JeecgBoot3.7

##### 问题描述：
想在积木报表中集成其他三方数据api（树状api目录），集成后在积木报表配置的时候，选择数据集可以选择切换三方数据集，此时隐藏默认数据集管理页面，展示三方数据集目录，并支持选择，此功能为三方数据源api的集成，可以简化报表配置人员的工作量，不再需要关注数据集的加工，而专注于报表开发和业务展示

##### 改进截图：
1.数据集配置，提供三方数据集支持协议和配置界面
![image](https://github.com/user-attachments/assets/340a7cf4-c402-4236-b396-9b67705b6fa9)

2.数据集选择，支持切换三方数据集
![image](https://github.com/user-attachments/assets/d2285700-a1d5-4058-82a3-10992bce6282)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
暂时不现实，第三方的规则如何保持一致兼容
