### ISSUE TITLE
vue3中BasicColumn如何查询字典code对应的字典配置？

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#6984]
##### 版本号：
3.7

##### 问题描述：
数据中没有冗余  _dictText 字段，前端table中想根据数据显示出对应的文本，目前我实现的只能写死，前端取字典的缓存的方法是什么呢？

##### 错误截图：
![Uploading 微信截图_20240729144236.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
图裂了

**Comment by yang-xianzhu** [comment]
试试这个
```
import { getDictItemsByCode } from '/@/utils/dict'; 
```

**Comment by hsql** [comment]
好的，我试一下，谢谢！！！

**Comment by hsql** [comment]
可以了，谢谢
