### ISSUE TITLE
autopoi如何导出在线图片

### ISSUE THREAD

**Issue by 1127945027** [jeecgboot/JeecgBoot#6986]
##### 版本号：
最新版本

##### 问题描述：
你好，请问一下，如果图片在对象存储中，例如在阿里云oss中，数据库有图片对应的阿里云oss的url（但是图片文件不是公共读），如何用autopoi导出在线图片

谢谢

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
把图片字段采用文本的方式，导出的是url地址
