### ISSUE TITLE
开启多租户后Swagger/Knife在线接口文档调试提示无权限

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/JeecgBoot#6987]
##### 问题描述：
开启多租户后Swagger/Knife在线接口文档调试提示无权限
Header目前不能编辑，应该需要增加：x-tenant-id

##### 错误截图：

![image](https://github.com/user-attachments/assets/a7bb9da1-5e9d-45eb-b806-e9b0a3da474f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq
