### ISSUE TITLE
basicTable中树形表格的checkStrictly设置无效

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#6990]
##### 版本号：
3.6.3

##### 问题描述：
basicTable中树形表格的rowSelection使用问题：

1. checkStrictly设置为false，父子数据的勾选状态依然不能联动
2. 想监听每次勾选某条数据的事件，配置了onSelect不生效

![image](https://github.com/user-attachments/assets/de4ab0ab-5917-44c1-b561-59efd1ba97f4)
按照antdv的文档尝试了几种配置，都未生效，请问是basicTable不支持，还是我使用有问题？

##### 错误截图：
联动功能在官方线上功能就不行：http://boot3.jeecg.com/comp/table/treeTable

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
