### ISSUE TITLE
使用部门选择用户（JSelectUserByDept）回显的问题

### ISSUE THREAD

**Issue by chb88888** [jeecgboot/JeecgBoot#6991]
##### 版本号：
jeecgboot-vue3 3.6.3
##### 问题描述：
使用部门选择用户 JSelectUserByDept，修改componentProps里的rowkey改为'id'，labelKey还是'realname',第一次打开选择后会展示id，实际应该展示realname，第二次再打开就好了，且目前有一个必现的报错，求解答

##### 错误截图：

![111](https://github.com/user-attachments/assets/73d69107-0b80-4e69-a0b1-b2b52459e09c)
![222](https://github.com/user-attachments/assets/0f22fc14-88ea-412b-9f07-31c66350dcc1)
![333](https://github.com/user-attachments/assets/1104e6b1-778d-4185-85d0-358b6b8e4620)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by sjlei** [comment]
新版本没问题，请使用新版本验证一下是否可以复现
