### ISSUE TITLE
逻辑删除是否考虑del_flag填充为时间戳或者该数据ID

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/JeecgBoot#6992]
##### 版本号：
3.4.3-GA

##### 问题描述：
后端为了保证数据的唯一性，加了业务字段+del_flag的联合索引，这样删除的数据就只能添加一次，再次删除后就无法添加该数据，
有没有考虑del_flag删除后填充为时间戳或者被删除数据的ID，生效数据填充为0，这样可以保证数据唯一且可以支持多次删除。

##### 错误截图：
无。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
暂时收录到 https://github.com/jeecgboot/JeecgBoot/issues/1312
