### ISSUE TITLE
hook封装的useModal方法不定时出现 useModal instance is undefined!

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/JeecgBoot#6995]
##### 版本号：
3.7.0

##### 问题描述：
编写弹窗的时候通过 register去实现弹窗初始化 但是有时候会出现 useModal instance is undefined!  这个问题不止弹窗会出现 抽屉表单也会出现，个人猜测可能是因为同一个vue文件中声明了多个弹窗 导致的有的弹窗可以，有的弹窗有问题

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
描述问题请图文并茂，方便我们理解并快速定位问题;
