### ISSUE TITLE
nacos2.0.4漏洞问题

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/JeecgBoot#6996]
##### 版本号：
最新版 jeecgboot

##### 问题描述：
Nacos 是阿里巴巴推出来的一个开源项目，这是一个更易于构建云原生应用的动态服务发现、配置管理和服务管理平台。当配置为使用认证时（-Dnacos.core.auth.enabled=true），Nacos使用AuthFilter servlet过滤器来执行认证。这个过滤器有一个后门，使Nacos服务器可以绕过这个过滤器，从而跳过认证检查。这种机制依赖于用户代理的HTTP头，所以它很容易被欺骗。

是否可以升级nacos
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
可以参考最新代码，单独升级nacos就行
