### ISSUE TITLE
主表生成代码无代码

### ISSUE THREAD

**Issue by longmao18** [jeecgboot/JeecgBoot#6997]
##### [错误截图：
![image](https://github.com/user-attachments/assets/ad2e2d03-9758-4e3f-9843-615091ed2720)
![image](https://github.com/user-attachments/assets/715d3674-6fbf-4829-908e-b234450b845a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
是不是代码目录有中文？或者特殊字符

**Comment by longmao18** [comment]
> 是不是代码目录有中文？或者特殊字符

没有呀，全英文的。就是单表的可以生成，主表就不行。

**Comment by longmao18** [comment]
> 是不是代码目录有中文？或者特殊字符
Duplicate of #似乎不是这个问题，该如何解决呀

**Comment by zhangdaiscott** [comment]
提供重现场景，不然无法处理

**Comment by longmao18** [comment]
> 提供重现场景，不然无法处理

就是拉取源代码后，直接勾选已有主表，点击生成代码。
Duplicate of #
