### ISSUE TITLE
生成的Java代码，控制器访问不到

### ISSUE THREAD

**Issue by 191474639** [jeecgboot/JeecgBoot#6998]
##### 版本号：

3.6
##### 问题描述：

生成的Java代码控制器路由访问不到，其它的可以访问

##### 错误截图：
![b01797904924e6c7c5fcfc16c69f9f7e](https://github.com/user-attachments/assets/f16cca2a-16e4-48e0-8c29-244ecac0c218)

![c629e274e3572488f02cf84949ea1f66](https://github.com/user-attachments/assets/500036b8-fe3f-45ef-9a84-d07c374e1462)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
1、注意扫码路径
2、重启了吗
