### ISSUE TITLE
积木报表漏洞

### ISSUE THREAD

**Issue by 12345ZMTHL** [jeecgboot/JeecgBoot#7000]
##### 版本号：
2.2.0

##### 问题描述：

积木报表的漏洞，请问积木报表这个组件是默认引入的嘛？pom文件没找到 jimureport-spring-boot-starter 相关的依赖
##### 错误截图：

![image](https://github.com/user-attachments/assets/a321e8fc-0d4f-409d-ad96-34ae358ee4bd)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
搜索jimureport 可能老的依赖名不一致
搜索后，可以升级到最新版

**Comment by 12345ZMTHL** [comment]
> 搜索jimureport 可能老的依赖名不一致 搜索后，可以升级到最新版

jimureport 这个关键字也搜不到，我看积木报表使用文档需要引入jimureport相关的依赖
