### ISSUE TITLE
springboot3的版本nacos中的jeecg.yaml配置有误

### ISSUE THREAD

**Issue by bfansheng** [jeecgboot/JeecgBoot#7001]
##### 版本号：
3.7.0

##### 问题描述：

jeecg.yaml中DruidDataSourceAutoConfigured的包名在springboot3中已经更改了，但是配置里还是用的旧的

##### 错误截图：

![image](https://github.com/user-attachments/assets/62aa524c-af3d-46a8-9ff5-bc581dedfaac)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
我们提供的sql脚本中是对的，这个忽略就行
nacos中有个springBoot3分组
