### ISSUE TITLE
官网【网关路由】报错

### ISSUE THREAD

**Issue by LeeSmallNorth** [jeecgboot/JeecgBoot#7003]
##### 版本号：

官网演示环境报错

##### 问题描述：

官网演示环境报错

##### 错误截图：

![image](https://github.com/user-attachments/assets/ec383459-c170-4047-958a-e3ad2e5efed2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
好了
