### ISSUE TITLE
没有搜索条件，列表不加载

### ISSUE THREAD

**Issue by wyx666518** [jeecgboot/JeecgBoot#7004]
##### 版本号：
3.7.0

##### 问题描述：
BasicTable，formSearchSchemas为空数据的话，列表不加载。然后，也经常提示Cannot access 'BasicForm' before initialization at BasicTable.vue:104:7

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
描述太简单

**Comment by zhangdaiscott** [comment]
jl

**Comment by wyx666518** [comment]
自动生成代码之后，会生成xxx.data.ts文件，那个里面有个formSearchSchemas的变量。如果这个变量的值是一个空数组，不配置搜索项，那么这个table就不会加载数据。

**Comment by zhangdaiscott** [comment]
这个bug已经修复了，更新代码就行了
