### ISSUE TITLE
一直弹警告是什么问题

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/JeecgBoot#7005]
##### 问题描述：
代码下载过来没有改动过，运行起来就是一直弹警告信息，是不是哪里有问题，后台每请求一次就会出现很多的警告

##### 错误截图：

![微信图片_20240801095528](https://github.com/user-attachments/assets/96209a5c-4fb1-46bd-8c5b-6a5fdf718fc9)

![微信图片_20240801095825](https://github.com/user-attachments/assets/99ac7f05-5e59-443a-872b-90cbfccc9aa2)

**Comment by zhangdaiscott** [comment]
4. 开发环境登录后台报错：Unable to correctly extract the Initialization Vector or ciphertext
问题原因： shiro的rememberMe策略与cookie相关问题引起。

解决方案： 直接清空浏览器的cookie的缓存，建议清空所有的cookie，问题可以得到解决。极有可能是当前浏览器在其他的网站中有过rememberMe的记录导致后台的shiro会用cookie去反序列化导致。
