### ISSUE TITLE
BasicTable slots同时使用customeRender + title， title会不生效

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7006]
##### 版本号：
3.7.0_all

##### 问题描述：
BasicTable slots同时使用customeRender + title， title会不生效

##### 错误截图：
![img_v3_02db_75c2c432-d56e-4398-808b-1a8d858f1d6g](https://github.com/user-attachments/assets/83275d15-3afa-4e06-b731-f4eda33ef6e8)
![img_v3_02db_a658e4b5-500e-4ff2-82ab-505c43e429cg](https://github.com/user-attachments/assets/2bcac489-2809-414c-b8fd-468dd18b29ef)
![image](https://github.com/user-attachments/assets/c9a96b6b-2796-4507-95d5-a0800a87af04)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by lsqGitHub716** [comment]
antd4.0版本，title不支持插槽
![image](https://github.com/user-attachments/assets/9883fa52-b931-4599-b688-b405097d3350)
你可以使用以下方式自定义标题
![image](https://github.com/user-attachments/assets/e4ce2e8d-c7cd-433e-a3a9-5bf6dcce9507)
