### ISSUE TITLE
JSearchSelect组件文本回显问题

### ISSUE THREAD

**Issue by modefeng** [jeecgboot/JeecgBoot#7008]
##### 版本号：
3.6.3

##### 问题描述：
在data.ts中，通过defaultValue来设置使用JSearchSelect组件的字段的默认值，在详情或者编辑页面时，如果这个字段的值是空，JSearchSelect会显示为defaultValue值对应的文本，不会显示为空。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by sjlei** [comment]
未复现该问题，请更新到最新版尝试，或贴出详细的复现代码

**Comment by modefeng** [comment]
data.ts中组件的代码为，通过defaultValue设置默认值
{
    label: '测试',
    field: 'orgCode',
    component: 'JSearchSelect',
    defaultValue: '510107064',
    componentProps: {
      dict: 'organise,orgname,orgcode',
      pageSize: 6,
      async: true,
    },
  },
  在打开basicModal的时候表单赋值时，如果在data中orgCode的值是null，组件显示的内容是defaultValue的510107064，而不是空。
    const [registerModal, { setModalProps, closeModal }] = useModalInner(async (data) => {
    //重置表单
    await resetFields();
    setModalProps({ confirmLoading: false, showCancelBtn: !!data?.showFooter, showOkBtn: !!data?.showFooter });
    isUpdate.value = !!data?.isUpdate;
    if (unref(isUpdate)) {
      //表单赋值
      await setFieldsValue({
        ...data.record,
      });
    }
    // 隐藏底部时禁用整个表单
    setProps({ disabled: !data?.showFooter });
  });

**Comment by sjlei** [comment]
你可以在`setFieldsValue`的时候补充一下`orgCode`字段，因为在`setFieldsValue`时，参数里不存在的值是不会处理的。
``` js
//表单赋值
await setFieldsValue({
    orgCode: '',
    ...data.record,
});
```
![image](https://github.com/user-attachments/assets/1176a730-3d73-4574-8c61-6b09ede6995b)

**Comment by modefeng** [comment]
我打印了data，data中是存在这个字段的
![1](https://github.com/user-attachments/assets/97efabdb-0c4e-45a8-b7df-5892aaa1a640)
![2](https://github.com/user-attachments/assets/bc240f58-ecbf-4ce4-a252-85cefa6c64de)
![3](https://github.com/user-attachments/assets/fa975079-8b81-44ce-9203-161a88a4cee0)

**Comment by sjlei** [comment]
经测试是你加了`async`参数的原因，该问题目前已修复，下版本发布
