### ISSUE TITLE
模糊查询时未转义反斜杠\

### ISSUE THREAD

**Issue by wjcIvan** [jeecgboot/JeecgBoot#7010]
##### 版本号：
http://boot3.jeecg.com/task/myHandleTaskInfo

##### 问题描述：
模糊查询时未转义反斜杠\

##### 错误截图：
![image](https://github.com/user-attachments/assets/0a0bf56d-b408-4575-bb88-e33f1bf4f621)
手动转义后可以查出结果
![image](https://github.com/user-attachments/assets/85306349-6ecf-4cdd-8e2f-6730fc9413b3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by wjcIvan** [comment]
意思是官网环境没更新 实际已经修复了？ 还是不处理

**Comment by zhangdaiscott** [comment]
实际没这样的需求吧

**Comment by wjcIvan** [comment]
找到了这段代码，通过注释看出原本是想处理的，猜测可能是加了之后碰到某些问题，所以取消了，方便告知下是什么问题吗

jeecg-boot/jeecg-boot-base-core/src/main/java/org/jeecg/common/system/query/QueryGenerator.java
```
	/**mysql 模糊查询之特殊字符下划线 （_、\）*/
	public static final String LIKE_MYSQL_SPECIAL_STRS = "_,%";
```
