### ISSUE TITLE
CORS(跨站资源共享)原始验证失败

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/JeecgBoot#7011]
##### 版本号：
springboot2.7

##### 问题描述：
三方安全检查扫描如下，CORS(跨站资源共享)原始验证失败
CORS漏洞是当前服务器对跨源资源的配置不当，导致允许任意源来共享服务器资源，从而导致用户数据泄露、客户端缓存中毒或者服务端缓存中毒
我使用的是微服务版本，这个是否得关闭跨域

##### 错误截图：
![image](https://github.com/user-attachments/assets/c41bb1e3-fa88-42a8-8d20-c4e3cfb782e5)
![image](https://github.com/user-attachments/assets/4a521004-a5ea-4bb5-8d61-973411b46969)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
任意一项值都是 * ,是jeecgBoot给到的通用配置，不代表个人不需要改这个，像你们项目上，就是对来源域有要求，就需要对这个值逐个修改，以满足要求
如Method： GET\POST\PUT等
