### ISSUE TITLE
JVxeTable addRows后表格数据错误

### ISSUE THREAD

**Issue by 3099749306** [jeecgboot/JeecgBoot#7013]
##### 版本号：
3.7.0

##### 问题描述：
在我的业务流程中，首先从子组件的表格中选择数据，回调到JVxeTable表格中。
然而，在第一次选择后回调，拿到的数据中包含了id的字段和值，但是执行addRows方法添加到JVxeTable表格中后，getTableData方法发现id不见了。
当第二次及以后选择后回调，执行addRows方法后，getTableData发现新选择的数据又有id。
我想让每次的选择后，getTableData方法的每行数据都有id，谢谢！

##### 错误截图：
<img width="1070" alt="4e7b0c64ff31e95689ddc61688e43dd" src="https://github.com/user-attachments/assets/640cbf20-cdc0-4e15-a492-941c53a3243b">
<img width="1280" alt="4bcecef4ad13eed2b01a073b8570255" src="https://github.com/user-attachments/assets/da66e0fb-b7c5-480d-ae9b-d5ab5727fdb9">
![image](https://github.com/user-attachments/assets/91d9e387-0f11-47a8-8b99-bafe1770fdec)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by sjlei** [comment]
问题已修复，下版本新增参数：keepNewId
传 true 即可保留新增行的ID
![image](https://github.com/user-attachments/assets/8e85cb57-0af6-422f-85cc-f911504a79ee)
