### ISSUE TITLE
菜单点击自动关闭

### ISSUE THREAD

**Issue by hengguangjie** [jeecgboot/JeecgBoot#7015]
##### 问题描述：
点击三级菜单时，自动关闭二级菜单了

##### 错误截图：
![image](https://github.com/user-attachments/assets/175f774c-07be-4140-a0a8-03ddaedc4d21)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
可以更新代码到最新，最新版演示系统无问题
