### ISSUE TITLE
为什么把jeecg-system-local-api放到jeecg-module-system下？

### ISSUE THREAD

**Issue by pythonlouvre** [jeecgboot/JeecgBoot#7018]
##### 版本号：
3.7.0

##### 问题描述：
为什么把jeecg-system-local-api放到jeecg-module-system下？之前老版本都是放公共模块下的，这样改如果我新增的业务模块要调用system下的api(比如发送系统消息)，我该怎么办？让业务模块依赖system？那system再依赖业务模块不是循环依赖了么？单体的local-api不应该放在公共层供其他模块调用么？怎么放自己模块去了？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
引入jeecg-system-local-api即可， 不需要引入jeecg-module-system
