### ISSUE TITLE
前端提示错误信息： emit is not a function

### ISSUE THREAD

**Issue by kevinchan1979** [jeecgboot/JeecgBoot#7023]
##### 问题描述：

在用户管理界面，点击职位选择弹出框的时候，

前端提示错误信息： emit is not a function
TypeError: emit is not a function~visibleChange

经检查，是
jeecgboot-vue3\src\components\Form\src\jeecg\components\modal\PositionSelectModal.vue
第85行引用useSelectBiz函数的时候，少传了一个参数emit

加上之后，前端正常了。

      const [{ rowSelection, visibleChange, indexColumnProps, getSelectResult, handleDeleteSelected, selectRows }] = useSelectBiz(
        getPositionList,
        getBindValue,
        emit
      );

##### 错误截图：

![微信图片_20240803092910](https://github.com/user-attachments/assets/6dbf8d0e-9608-4f92-9b47-3e581fe93bc7)

##### 修复后截图：

![微信图片_20240803093008](https://github.com/user-attachments/assets/da68c62c-0f1c-47b2-b7ce-c0a8ea6fb3b2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy
