### ISSUE TITLE
仪表盘sql解析

### ISSUE THREAD

**Issue by ZYZZYZZYZZ** [jeecgboot/JeecgBoot#7024]
##### 版本号：
3.7.0_all

##### 问题描述：
仪表盘设计，新增数据集，sql解析那里，报Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)错误

##### 错误截图：
点击三次解析sql以后
![555086c6-df84-432d-9659-9fe20db9ac7a](https://github.com/user-attachments/assets/a98c62d9-70bc-4967-a1c5-e7519b18c6f8)

**Comment by zhangdaiscott** [comment]
数据源配置错误

**Comment by ZYZZYZZYZZ** [comment]
那要怎样修改数据源的配置呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月5日(周一) 上午10:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/JeecgBoot] 仪表盘sql解析 (Issue #7024)




 
数据源配置错误

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/57f2acd2-c3c6-4e36-8465-4756c6e806ee)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/2014bae4-433c-41e9-97cb-d02e22f14686)
