### ISSUE TITLE
按照手册docker部署后 前端无网络

### ISSUE THREAD

**Issue by xust2021** [jeecgboot/JeecgBoot#7026]
##### 版本号：

v3.7.0_all
##### 问题描述：

docker部署后 前端无网络

##### 错误截图：
<img width="790" alt="微信图片_20240804205402" src="https://github.com/user-attachments/assets/e1ecdb83-b64c-4108-afd5-f9eb465c8736">
<img width="960" alt="微信图片_20240804205438" src="https://github.com/user-attachments/assets/034888a3-6e19-4ad8-baa8-7641d8882645">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by xust2021** [comment]
后台8080端口打不开

**Comment by xust2021** [comment]
![image](https://github.com/user-attachments/assets/d361a1f4-8981-4ce9-bbb7-cf041e17f08c)
已修改后端配置，docker日志显示感觉是没修改完，已按手册对应地方进行修改
![image](https://github.com/user-attachments/assets/62af9428-2e98-4e4c-9250-43b6895bbee6)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/docker/quick.html
