### ISSUE TITLE
如何根据部门授权？

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/JeecgBoot#7027]
##### 版本号：

3.4.3   Vue3版本
##### 问题描述：
目前我们是使用角色授权，但是角色关联的是人员。如果人员调动可能会导致权限还在，能不能通过部门授权相关角色？

##### 错误截图：
无

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
有部门角色功能
