### ISSUE TITLE
JSelectUser选择用户可以输入

### ISSUE THREAD

**Issue by chb88888** [jeecgboot/JeecgBoot#7030]
##### 版本号：
jeecgboot-vue3 3.6.3
##### 问题描述：
JSelectUser是打开弹窗选择的，文本框是不可以输入的，但是现在可以输入，在本地跑的代码没有这个问题，但是部署到测试环境就有这个问题，目前只有JSelectUser有这个问题。其实这个问题并没有什么实际影响，但是总觉得不完美，希望得到您的回复谢谢！

##### 错误截图：
![123](https://github.com/user-attachments/assets/e1ef6971-4c08-417b-8c37-0237644c9cc3)
![456](https://github.com/user-attachments/assets/941ab568-88fc-4caf-b717-fe40a79263b0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yang-xianzhu** [comment]
![image](https://github.com/user-attachments/assets/080ae334-c459-48cf-b9b3-a443c8899772)
加上`:showSearch="false"`试试

**Comment by chb88888** [comment]
加上:showSearch="false"已解决
