### ISSUE TITLE
Maven install时出错

### ISSUE THREAD

**Issue by aijekiL** [jeecgboot/JeecgBoot#7031]
##### 问题描述：ependency: org.jeecgframework.boot:jeecg-system-local-api:jar:3.6.3 (compile)
【ERROR】 org.jeecgframework.boot:jeecg-system-local-api:jar:3.6.3 was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced
【ERROR】 org.jeecgframework.boot:jeecg-system-local-api:jar:3.6.3 was not found in https://maven.jeecg.org/nexus/content/repositories/jeecg during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jeecg has elapsed or updates are forced

##### 错误截图：
![Uploading image.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
通过parent install
