### ISSUE TITLE
表单布局

### ISSUE THREAD

**Issue by modefeng** [jeecgboot/JeecgBoot#7032]
##### 版本号：
3.6.3

##### 问题描述：

表单设置布局 layout: 'vertical'  不起作用

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版看看
