### ISSUE TITLE
表格

### ISSUE THREAD

**Issue by xie-dongbo** [jeecgboot/JeecgBoot#7033]
##### 问题描述：
表格多列组合排序混乱

##### 错误截图：
![1722927553264](https://github.com/user-attachments/assets/d3cc0623-451a-4126-ada2-59a635f5fc43)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
？
