### ISSUE TITLE
在线生成代码没有后端代码

### ISSUE THREAD

**Issue by Vickyyu2000** [jeecgboot/JeecgBoot#7036]
##### 版本号：
3.4.3

##### 问题描述：
单表在线生成代码只生成前端代码，没有后端代码；一对多表代码是正常生成的；控制台无报错，配置无更改

##### 错误截图：
![a820e2304e3f82de7aea4f1af351862](https://github.com/user-attachments/assets/c7f4142c-882a-482d-ab63-4521365c45e6)
![8f25fc0ca4fce5073f7f9519f119c24](https://github.com/user-attachments/assets/fbfb97c8-82e2-496f-9df0-a32fab242120)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Vickyyu2000** [comment]
和路径中是否存在中文无关，两张图分别为含有中文的路径和纯英文路径，都是刚拉下来的代码，创建了一个简单的单表进行代码生成

**Comment by Vickyyu2000** [comment]
补充：
![1722933065721](https://github.com/user-attachments/assets/433e0341-b76c-435d-9742-1e558d11246a)
一对多的代码生成是正常的，即使路径包含中文

**Comment by Vickyyu2000** [comment]
继续补充：
换了个随便的路径成功了
![9d15f7a8d24a09882d4dce6e6d64401](https://github.com/user-attachments/assets/51dd00e5-389d-4eee-80e9-206a74f40821)
应该是bug？没办法正常生成在项目的module路径里，任何一个module都不行

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangdaiscott** [comment]
jl

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/14b10d0e-aecd-4607-82f5-3145f22945dc)
