### ISSUE TITLE
依赖冲突

### ISSUE THREAD

**Issue by 2508207487** [jeecgboot/JeecgBoot#7037]
##### 错误截图：
![image](https://github.com/user-attachments/assets/46178ea6-ee20-447f-9316-4783ac22ea20)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
使用pnpm i 来安装
