### ISSUE TITLE
项目配置切换暗黑主题之后，无法自定义顶栏和菜单主题

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7041]
##### 错误截图：
![1723012922056](https://github.com/user-attachments/assets/43a45fcf-118d-455b-8480-223f0f15a895)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by ak-2019** [comment]
![Uploading 1723012922056.png…]()

**Comment by ak-2019** [comment]
![Uploading 1723012922056.png…]()

**Comment by ak-2019** [comment]
![1723012922056](https://github.com/user-attachments/assets/276768d1-a3c6-48fa-9692-1bd113812225)

**Comment by zhangdaiscott** [comment]
你都黑色主题了，设置颜色没效果，特意禁用的
