### ISSUE TITLE
使用appendSchemaByField后提交时验证报错

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/JeecgBoot#7042]
##### 版本号：
3.6.3

##### 问题描述：
使用appendSchemaByField后提交时验证报错，没有找到对应的append的字段

##### 错误截图：

![image](https://github.com/user-attachments/assets/65082dc6-8ed8-4f06-b0d5-379946be6af8)
![1723018815289](https://github.com/user-attachments/assets/58358f34-3255-4640-9ec5-632770df851f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yzmking** [comment]
因为我增加的是数组字段所以来到这个方法 
![image](https://github.com/user-attachments/assets/bb8e2774-313f-4eb3-999e-7c51b85dad85)
但是 formSchema 中并没有 我appendSchemaByField的字段
所以 schema 为 空了，这应该怎么解决

**Comment by zhangdaiscott** [comment]
zy
