### ISSUE TITLE
表格合计显示

### ISSUE THREAD

**Issue by 191474639** [jeecgboot/JeecgBoot#7043]
##### 版本号：

3.6.3
##### 问题描述：
后台统计的合计，怎么在前端显示出来

##### 错误截图：

![image](https://github.com/user-attachments/assets/4ccc7ace-2a0e-42b7-b234-1308393cbd40)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
参考
http://boot3.jeecg.com/comp/table/footerTable
