### ISSUE TITLE
前端上传组件，部署生产环境后，无法上传文件

### ISSUE THREAD

**Issue by xhyooo** [jeecgboot/JeecgBoot#7044]
##### 版本号：
3.7.0

##### 问题描述：

前端上传组件，部署生产环境后，无法上传文件

##### 错误截图：
![image](https://github.com/user-attachments/assets/eac0a6d7-c519-41df-907d-9477426f403a)

TypeError: ce.upload.addEventListener is not a function
    at index-BbxyWJ4z.js:10:6238
    at new Promise (<anonymous>)
    at xhr (index-BbxyWJ4z.js:10:3704)
    at Axios$1.dispatchRequest (index-BbxyWJ4z.js:12:658)
    at Axios$1.<anonymous> (index-BbxyWJ4z.js:12:3859)
    at Generator.throw (<anonymous>)
    at Q (index-BbxyWJ4z.js:2:774)

**Comment by zhangdaiscott** [comment]
这是那个组件啊，我们好像废弃了这个了

**Comment by xhyooo** [comment]
https://help.jeecg.com/component/Upload.html 这个组件

**Comment by xhyooo** [comment]
https://github.com/jeecgboot/JeecgBoot/blob/master/jeecgboot-vue3/src/components/Upload/src/BasicUpload.vue
这个目录路径下，组件还挺好的用的啊，我看文档上面还保留着呢 @zhangdaiscott

**Comment by xhyooo** [comment]
功能没有什么问题，开发模式下，可以正常使用，就是打包编译后，就不能使用了，提示上面截图的错误

**Comment by yang-xianzhu** [comment]
> 功能没有什么问题，开发模式下，可以正常使用，就是打包编译后，就不能使用了，提示上面截图的错误

我也遇到过，你顺着这个组件里面调用方法，我记得是函数里用到了一个入参，但是调用的时候没有，所以报错的

**Comment by xhyooo** [comment]
> > 功能没有什么问题，开发模式下，可以正常使用，就是打包编译后，就不能使用了，提示上面截图的错误
> 
> 我也遇到过，你顺着这个组件里面调用方法，我记得是函数里用到了一个入参，但是调用的时候没有传，所以报错的

什么入参呢，有具体代码示例吗。我用了onUploadProgress 就报错，不用这个传参，打包部署没有问题

**Comment by yang-xianzhu** [comment]
> > > 功能没有什么问题，开发模式下，可以正常使用，就是打包编译后，就不能使用了，提示上面截图的错误
> > 
> > 
> > 我也遇到过，你顺着这个组件里面调用方法，我记得是函数里用到了一个入参，但是调用的时候没有传，所以报错的
> 
> 什么入参呢，有具体代码示例吗。我用了onUploadProgress 就报错，不用这个传参，打包部署没有问题 @yang-xianzhu

不是`onUploadProgress `这个函数的问题，找不到之前做的那个项目的commit的

**Comment by xhyooo** [comment]
感谢你的回复，提供解决思路，我看看怎么定位这个问题。 @yang-xianzhu

**Comment by yang-xianzhu** [comment]
> 感谢你的回复，提供解决思路，我看看怎么定位这个问题。 @yang-xianzhu

你把你用的这个component的值发一下我，我看看

**Comment by xhyooo** [comment]
<BasicUpload
                :emptyHidePreview="true"
                :maxSize="20"
                :maxNumber="1"
                :api="uploadNewsXlsx"
                class="mr-4"
                :accept="['xlsx']"
                :btnName="t('news.batchUpload')"
                xlsxLink="/resource/file/news_example.xlsx"
              />

**Comment by xhyooo** [comment]
`              <BasicUpload
                :emptyHidePreview="true"
                :maxSize="20"
                :maxNumber="1"
                :api="uploadNewsXlsx"
                class="mr-4"
                :accept="['xlsx']"
                :btnName="t('news.batchUpload')"
                xlsxLink="/resource/file/news_example.xlsx"
              />`

**Comment by xhyooo** [comment]
`
              <BasicUpload
                :emptyHidePreview="true"
                :maxSize="20"
                :maxNumber="1"
                :api="uploadNewsXlsx"
                class="mr-4"
                :accept="['xlsx']"
                :btnName="t('news.batchUpload')"
                xlsxLink="/resource/file/news_example.xlsx"
              />
`

**Comment by xhyooo** [comment]
```javascript
              <BasicUpload
                :emptyHidePreview="true"
                :maxSize="20"
                :maxNumber="1"
                :api="uploadNewsXlsx"
                class="mr-4"
                :accept="['xlsx']"
                :btnName="t('news.batchUpload')"
                xlsxLink="/resource/file/news_example.xlsx"
              />
```

**Comment by xhyooo** [comment]
没有特别的参数，就是传了 onUploadProgress  方法就会报错

**Comment by yang-xianzhu** [comment]
截图看一下你的`uploadNewsXlsx`接口

**Comment by xhyooo** [comment]
![image](https://github.com/user-attachments/assets/e184f836-f758-4209-8c98-13baf8c465bf)

**Comment by xhyooo** [comment]
http://localhost:4173/node_modules/.pnpm/axios@1.7.2_debug@4.3.5/node_modules/axios/lib/adapters/xhr.js

![image](https://github.com/user-attachments/assets/fb068e1d-852c-4620-8f3a-e7333cca128f)

问题出在这里

**Comment by yang-xianzhu** [comment]
![image](https://github.com/user-attachments/assets/4db76cd8-f326-4ea6-9b42-e804995bfeba)
可以试试，我之前遇到过，不是这样解决的，因为后面没有用这个组件了，就不了了之了

**Comment by xhyooo** [comment]
我也怀疑http对象被更改了，我记得在哪里看到过，用了mock插件，导致一些问题

**Comment by xhyooo** [comment]
![image](https://github.com/user-attachments/assets/2b31a648-426d-44f8-b95f-57eff70a6912)

我把插件注释掉，可以上传了，就是这个问题导致

**Comment by yang-xianzhu** [comment]
![image](https://github.com/user-attachments/assets/7f727df2-9aba-444e-b0db-4c262b987227)

**Comment by youdianfan** [comment]
最后说一下解决方案，主要还是mock插件导致，上线生产环境，一定要配置相应env文件里面的VITE_USE_MOCK = false，关闭mock插件启用。
