### ISSUE TITLE
【项目改写】是否有计划使用Angular技术栈改写一版当前项目

### ISSUE THREAD

**Issue by xiaoxpai** [jeecgboot/JeecgBoot#7047]
##### 版本号：
3.4.3

##### 问题描述：

有计划使用Angular等技术栈实现当前项目的计划吗

##### 错误截图：

无

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
Angular已经被淘汰了
