### ISSUE TITLE
官网演示一对多示例，当编辑订单时，子表新增多行客户信息和机票信息，每次都只能保存一条记录。

### ISSUE THREAD

**Issue by kevinchan1979** [jeecgboot/JeecgBoot#7048]
##### 问题描述：

官网演示一对多示例，当编辑订单时，子表新增多行客户信息和机票信息，每次都只能保存一条记录。，同时删除多行记录则正常。

##### 错误截图：

![1111](https://github.com/user-attachments/assets/79f8a911-81eb-4d76-bcfe-09a653ab5b75)
![2222](https://github.com/user-attachments/assets/ceabdd30-34d6-4b3d-8c0e-800d8d52efaa)
![3333](https://github.com/user-attachments/assets/14372821-39bb-4198-a84c-9773e09f803c)
![4444](https://github.com/user-attachments/assets/023aef39-6b59-478e-8113-b0ad23a2fe67)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by kevinchan1979** [comment]
已经自己解决了
src/main/java/org/jeecg/modules/demo/test/service/impl/JeecgOrderMainServiceImpl.java
第87行updateCopyMain函数
去掉break就正常了，之前循环一次就跳出中断了！

        // 循环前台传过来的数据
        for (JeecgOrderTicket ticket:jeecgOrderTicketList){
            // 先查询子表数据库
            JeecgOrderTicket orderTicket = jeecgOrderTicketMapper.selectById(ticket.getId());
            if(orderTicket == null){
                // 当传过来的id数据库不存在时，说明数据库没有，走新增逻辑
                ticket.setOrderId(jeecgOrderMain.getId());
                jeecgOrderTicketMapper.insert(ticket);
                **//break;**
            }
            if(orderTicket.getId().equals(ticket.getId())){
                // 传过来的id和数据库id一至时，说明数据库存在该数据，走更新逻辑
                jeecgOrderTicketMapper.updateById(ticket);
            }
        }
        for (JeecgOrderCustomer customer:jeecgOrderCustomerList){
            // 先查询子表数据库
            JeecgOrderCustomer customers = jeecgOrderCustomerMapper.selectById(customer.getId());
            if(customers == null){
                // 当传过来的id数据库不存在时，说明数据库没有，走新增逻辑
                customer.setOrderId(jeecgOrderMain.getId());
                jeecgOrderCustomerMapper.insert(customer);
                **//break;**
            }
            if(customers.getId().equals(customer.getId())){
                //TODO 传过来的id和数据库id一至时，说明数据库存在该数据，走更新逻辑
                jeecgOrderCustomerMapper.updateById(customer);
            }
        }

**Comment by sjlei** [comment]
> 已经自己解决了 src/main/java/org/jeecg/modules/demo/test/service/impl/JeecgOrderMainServiceImpl.java 第87行updateCopyMain函数 去掉break就正常了，之前循环一次就跳出中断了！

应该把 break 换成 continue ，不然有可能报空指针异常

**Comment by sjlei** [comment]
> 已经自己解决了 src/main/java/org/jeecg/modules/demo/test/service/impl/JeecgOrderMainServiceImpl.java 第87行updateCopyMain函数 去掉break就正常了，之前循环一次就跳出中断了！

应该把`break`换成`continue`，不然有可能报空指针异常
