### ISSUE TITLE
地区选择器，杭州仍然是旧的划分，存在江干区下城区，没有钱塘区

### ISSUE THREAD

**Issue by wzmcoding** [jeecgboot/JeecgBoot#7049]
##### 问题描述：
地区选择器，杭州仍然是旧的划分，存在江干区下城区，没有钱塘区

##### 错误截图：
![image](https://github.com/user-attachments/assets/a4bad51f-4393-4fc2-aae2-de8cb5767c8f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Wwyz-98** [comment]
杭州的行政区划都改了两三年了，jeecg也不少人用吧，竟然到现在还没有发现

**Comment by zhangdaiscott** [comment]
jl

**Comment by wzmcoding** [comment]
> jl

啥意思

**Comment by sjlei** [comment]
问题已修复，下版本发布
