### ISSUE TITLE
添加 @vitejs/plugin-legacy 插件 打包报错

### ISSUE THREAD

**Issue by hongdapi** [jeecgboot/JeecgBoot#7050]
##### 版本号：
3.7.0

##### 问题描述：
![image](https://github.com/user-attachments/assets/c6c4e6d5-1cb5-499d-9e12-7872e925aa60)

##### 错误截图：
![image](https://github.com/user-attachments/assets/48540816-fb14-4f97-bce7-8348929dfe94)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己添加的插件，我们负责不了

**Comment by hongdapi** [comment]
> 自己添加的插件，我们负责不了

@vitejs/plugin-legacy 和你们的configThemePlugin冲突了，希望排查一下configThemePlugin的问题

**Comment by bzb745300** [comment]
> ##### 版本号：
> 3.7.0
> 
> ##### 问题描述：
> ![image](https://github.com/user-attachments/assets/c6c4e6d5-1cb5-499d-9e12-7872e925aa60)
> 
> ##### 错误截图：
> ![image](https://github.com/user-attachments/assets/48540816-fb14-4f97-bce7-8348929dfe94)
> 
> #### 友情提示：
> * 未按格式要求发帖、描述过于简单的，会被直接删掉;
> * 描述问题请图文并茂，方便我们理解并快速定位问题;
> * 如果使用的不是master，请说明你使用的分支;

哥，我也遇到了这个问题，你解决了吗?可以指点一下吗？有偿

**Comment by hongdapi** [comment]
> > ##### 版本号：
> > 3.7.0
> > ##### 问题描述：
> > ![image](https://github.com/user-attachments/assets/c6c4e6d5-1cb5-499d-9e12-7872e925aa60)
> > ##### 错误截图：
> > ![image](https://github.com/user-attachments/assets/48540816-fb14-4f97-bce7-8348929dfe94)
> > #### 友情提示：
> > 
> > * 未按格式要求发帖、描述过于简单的，会被直接删掉;
> > * 描述问题请图文并茂，方便我们理解并快速定位问题;
> > * 如果使用的不是master，请说明你使用的分支;
> 
> 哥，我也遇到了这个问题，你解决了吗?可以指点一下吗？有偿

你可以看下vite的文档 https://cn.vite.dev/guide/build.html
手动添加polyfill，用这个https://cdnjs.cloudflare.com/polyfill/
