### ISSUE TITLE
瀚高数据库Online表单开发导入数据库表功能

### ISSUE THREAD

**Issue by haveagooddaytoday** [jeecgboot/JeecgBoot#7052]
##### 版本号：
3.7.0_all

##### 问题描述：
瀚高数据库（com.highgo.jdbc.Driver）
Online表单开发，导入数据库表功能时报错，无法导入表格

##### 错误截图：
![image](https://github.com/user-attachments/assets/bbe8d1ff-e748-4092-a473-e79eb860d599)
![image](https://github.com/user-attachments/assets/233c36b9-8273-402a-bb00-9b36cf68213a)
![image](https://github.com/user-attachments/assets/c4f97355-a353-4c66-9740-d88eb549db5d)

**Comment by haveagooddaytoday** [comment]
补充：sysdba用户，有该数据库所有权限

**Comment by zhangdaiscott** [comment]
jl

**Comment by ltt1987** [comment]
> ##### 版本号：
> 3.7.0_all
> 
> ##### 问题描述：
> 瀚高数据库（com.highgo.jdbc.Driver） Online表单开发，导入数据库表功能时报错，无法导入表格
> 
> ##### 错误截图：
> ![image](https://private-user-images.githubusercontent.com/108015004/356323886-bbe8d1ff-e748-4092-a473-e79eb860d599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDczMzEsIm5iZiI6MTcyNTYwNzAzMSwicGF0aCI6Ii8xMDgwMTUwMDQvMzU2MzIzODg2LWJiZThkMWZmLWU3NDgtNDA5Mi1hNDczLWU3OWViODYwZDU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDAwOTQ0NzUyYjkxZTk4Y2ZlMjNhN2ZhNjE0NzMzOWJhM2FmODU1MDQzYjkzZjdlZGJkYTk1YTJhNGRiNTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1ORPZJCHSs16OGI-zZezOpQKtYJQaptCojBsfyATMkA) ![image](https://private-user-images.githubusercontent.com/108015004/356323965-233c36b9-8273-402a-bb00-9b36cf68213a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDczMzEsIm5iZiI6MTcyNTYwNzAzMSwicGF0aCI6Ii8xMDgwMTUwMDQvMzU2MzIzOTY1LTIzM2MzNmI5LTgyNzMtNDAyYS1iYjAwLTliMzZjZjY4MjEzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTUyNGJmNjc0Y2Q2Y2MwMDdkMjc0YzQ5MDk1ZTdkMGIzMjEyZDVlZjZiZjNlMzUwZjMxMmZhMTM3MWFiNzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bDYDESCqQq5JlzRC6U2bm7-_lW6X2QYc0NUlYTgzrcQ) ![image](https://private-user-images.githubusercontent.com/108015004/356324301-c4f97355-a353-4c66-9740-d88eb549db5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDczMzEsIm5iZiI6MTcyNTYwNzAzMSwicGF0aCI6Ii8xMDgwMTUwMDQvMzU2MzI0MzAxLWM0Zjk3MzU1LWEzNTMtNGM2Ni05NzQwLWQ4OGViNTQ5ZGI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNzE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDNmMGUyZGM5YTZjOTY2Y2NlNWJjYTk1MmE1YmI4NzhjZGFkM2M2MmRiODE0MDM3Y2MxYWQ2NGZlODY5YzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yA2hGe7DU2Tl7UyNnAOubWtd4Y7qKFBqFQOcD4mc2YU)

请问解决了吗？遇到统一的问题。

**Comment by zhangdaiscott** [comment]
下个版本发布
