### ISSUE TITLE
打开Modal弹窗，控制台报错

### ISSUE THREAD

**Issue by chenmonkey** [jeecgboot/JeecgBoot#7054]
##### 错误截图：
![报错](https://github.com/user-attachments/assets/097c3983-bd28-41a5-b7ae-33b1d1c22393)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yang-xianzhu** [comment]
这个是`antd-vue`的问题，好像不影响功能，只是浏览器的无障碍报的问题，chrome是127版本开始报这个错

**Comment by yang-xianzhu** [comment]
w3c的标准链接: [https://w3c.github.io/aria/#aria-hidden](url)
