### ISSUE TITLE
online表单，能否修改自带按钮的名称，或者隐藏自带按钮

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#7059]
##### 版本号：
3.7

##### 问题描述：

online表单，能否修改自带按钮的名称，或者隐藏自带按钮

##### 错误截图：
![image](https://github.com/user-attachments/assets/0e428dcd-ba85-4abc-9c9e-b6e849f002f0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
暂时不支持，我们考虑下

**Comment by sjlei** [comment]
功能已支持，下版本发布，可以设置默认按钮的名称、图标和权限。

![image](https://github.com/user-attachments/assets/f3c3e82b-8665-4128-a8df-bb72cba8cf20)
![image](https://github.com/user-attachments/assets/74f96309-5193-4a84-bd22-f6f387855ae2)

![image](https://github.com/user-attachments/assets/7f239fc9-b830-44ba-9fec-bfebbfc3cf8e)

**Comment by zwjsoft** [comment]
在最新发版的3.7.2，没看到这个功能啊
