### ISSUE TITLE
代码生成器不能导入其他数据库表

### ISSUE THREAD

**Issue by 12345ZMTHL** [jeecgboot/JeecgBoot#7062]
##### 版本号：
3.6.

##### 问题描述：

按照文档描述，CodeGenerateDbConfig注释掉了，jeecg_database.properties修改了需要生成代码的库，运行没问题，再点击导入数据库表配置时后端报错，看日志确实是使用了我配置的数据库，但是后面会报一个 "org.jeecg.modules.online.cgform.c.d.b" is null 空指针异常

##### 错误截图：
![image](https://github.com/user-attachments/assets/efe6b084-8aec-4a4c-8af0-35175ad64eb9)
![image](https://github.com/user-attachments/assets/78accfaf-2d17-4dd0-a1c0-a10cbcde58fb)
![image](https://github.com/user-attachments/assets/b7b165a7-8e49-4125-927d-1c1019e76484)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
应该是配置有错误

**Comment by 12345ZMTHL** [comment]
> 应该是配置有错误

除了上面我截图的地方，还有哪里需要配置的嘛？

**Comment by zhangdaiscott** [comment]
具体版本号

**Comment by 12345ZMTHL** [comment]
> 具体版本号

3.6.3，不好意思，没注意到我上面的版本少打了一个3

**Comment by zhangdaiscott** [comment]
自查，应该是你配置问题，不行升级到最新版看看
