### ISSUE TITLE
popup_dict 设置问题？

### ISSUE THREAD

**Issue by xiaobin620** [jeecgboot/JeecgBoot#7063]
##### 问题描述：
在表单的 super-query 中，superQueryConfig中设置view为popup_dict 时候，如果设置查询字段，和显示字段？

在文档中未找到相应的设置方法。
##### 错误截图：

![image](https://github.com/user-attachments/assets/05b74aa1-b385-4ed0-9798-7888051ee6a6)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
`popup_dict:{ title: "popup字典", view: "popup_dict", type: "string", order: 12, code: "report_user", destFields: "realname",   orgFields: "username" }`

- code：报表code
- destFields：渲染展示的值
- orgFields：存储的值
