### ISSUE TITLE
nacos启动失败

### ISSUE THREAD

**Issue by ZYZZYZZYZZ** [jeecgboot/JeecgBoot#7064]
##### 版本号：
v3.7.0_all

##### 问题描述：

nacos启动失败
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalOtherPersistServiceImpl' defined in URL [jar:file:/C:/Users/zhaoyeze/.m2/repository/org/jeecgframework/nacos/nacos-core/2.3.2/nacos-core-2.3.2.jar!/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.core.namespace.repository.ExternalNamespacePersistServiceImpl]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error

##### 错误截图：
![联想截图_20240811131830](https://github.com/user-attachments/assets/be225cbe-90df-4c59-bcd2-cd9a3aaf4c3f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
配置数据库了吗？maven clean试试

**Comment by ZYZZYZZYZZ** [comment]
谢谢，但数据库要怎样配置啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月11日(周日) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/JeecgBoot] nacos启动失败 (Issue #7064)




 
配置数据库了吗？maven clean试试

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/a808bcf9-f974-49ba-8f81-934c2dc98f26)

**Comment by ZYZZYZZYZZ** [comment]
我的数据库账号密码都是正确的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/JeecgBoot] nacos启动失败 (Issue #7064)




 
image.png (view on web)

**Comment by zhangdaiscott** [comment]
host配置了吗
