### ISSUE TITLE
JEECGBOOT VUE3 自定义抽屉无法正常关闭

### ISSUE THREAD

**Issue by ws-gy** [jeecgboot/JeecgBoot#7065]
##### 问题描述：
前端正常编译 配置正确 部署服务器后 点击系统管理->菜单管理->新增菜单 点击取消或者× 抽屉无法关闭 控制台无报错

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by youdianfan** [comment]
建议升级到最新版，应该是小问题，看一下封装组件事件是否被触发

**Comment by ws-gy** [comment]
> 建议升级到最新版，应该是小问题，看一下封装组件事件是否被触发
其余地方的BasicDrawer组件出现同样的情况  @ok正常触发 @close无法触发

**Comment by ws-gy** [comment]
其余地方的BasicDrawer 同样有这个问题 @ok正常触发 @close无法正常触发

**Comment by ws-gy** [comment]
https://github.com/jeecgboot/JeecgBoot/issues/7065#issuecomment-2283017263
其余地方的BasicDrawer 同样有这个问题 @ok正常触发 https://github.com/close无法正常触发

**Comment by youdianfan** [comment]
那就修一下BasicDrawer 这个组件，我目前使用3.7版本未发现你这种问题，建议同步下代码，比对一下，应该很好排查。

**Comment by youdianfan** [comment]
https://github.com/jeecgboot/JeecgBoot/releases/tag/v3.7.0
这个版本里面有drawer一些修复，不知道是不是跟你的问题相似
