### ISSUE TITLE
制作大屏时动态数据请求的公网接口无法正确发送请求

### ISSUE THREAD

**Issue by l1438** [jeecgboot/JeecgBoot#7066]
##### 错误截图：
![image](https://github.com/user-attachments/assets/4bfae73f-0093-44c6-8ade-caa50cf185ae)
![image](https://github.com/user-attachments/assets/a4056cbf-7fa2-47f1-bc6a-99883c7df3e4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
没看到你的接口

**Comment by l1438** [comment]
> 没看到你的接口

http://47.99.144.172:8080/getdapingdata/gettrojancount这是我部署的接口
https://bootapi.jeecg.com/bigscreen/#/build/1820631898897072129?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjMzMTEwMTksInVzZXJuYW1lIjoiMTgwMDU2MDM4OTQifQ.i231JzoEm7jB4Z4P8naWFQy0miSZYVXcmQ1cN_LKCTQ这是发布的大屏

**Comment by l1438** [comment]
> 没看到你的接口

![2c19aec50a55d1af7667b0db519ff1a](https://github.com/user-attachments/assets/f1be0a20-62d1-44ae-8a42-2663ae783291)
这是Nginx的配置

**Comment by zhangdaiscott** [comment]
首先你要保证你的接口是外网可访问的

**Comment by l1438** [comment]
> 首先你要保证你的接口是外网可访问的

可以的，我在浏览器直接输入接口地址都能正确收到返回的数据，但是大屏哪里发出去的请求就得不到响应

**Comment by zhangdaiscott** [comment]
https格式，需要一致

**Comment by l1438** [comment]
> https格式，需要一致
是的，我们接口用的是http，大屏上填的地址也是http

**Comment by zhangdaiscott** [comment]
需要https
