### ISSUE TITLE
BasicTable使用可编辑行功能，0值在列表不显示，但后台数据有传0

### ISSUE THREAD

**Issue by yzbzwyyt** [jeecgboot/JeecgBoot#7068]
##### 版本号：
3.6.3
##### 问题描述：
BasicTable引入可编辑行功能，0值在列表不显示，但后台数据有传0。
编辑时会显示0值，但保存后列表依旧不显示

##### 错误截图：
![question1](https://github.com/user-attachments/assets/d449d6d2-0b01-4a9a-975f-a39c69e8e428)
![question2](https://github.com/user-attachments/assets/3334c63d-177b-4711-a690-f66f5bcd4fd8)

**Comment by zhangdaiscott** [comment]
更新代码到最新试试

**Comment by yzbzwyyt** [comment]
好的，已经解决了，需要修改一下EditableCell文件
