### ISSUE TITLE
数据权限问题有个地方很奇怪

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/JeecgBoot#7069]
##### 版本号：

3.7.0
##### 问题描述：

如果我在接口上(controller)加上了@PermissionData这个注解，但是没有填写pageComponent参数，那么就会根据请求的路径进行匹配，但是我看源码的时候，发现去查询菜单表的时候会加上菜单类型为2（menu_type = 2）这个查询条件，就很奇怪为什么要加菜单类型为按钮类型这个查询条件，应该是菜单类型为一级菜单或者子菜单才对。如果要迎合这个查询条件，那么就需要去创建个菜单类型为按钮并且填访问路径才可以。
##### 错误截图：
![1723452309584](https://github.com/user-attachments/assets/cb8556a6-3913-47eb-99d0-7699097a510b)
![1723452325123](https://github.com/user-attachments/assets/7db7afa3-e9a2-48eb-b2c3-57ca5f05cf13)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/system/dataauth/userequest.html
