### ISSUE TITLE
Online一对多报表部分、条件导出报错（'where 子句'中出现未知列 'jeecg_rp_temp.id' ### 错误可能存在于 URL）

### ISSUE THREAD

**Issue by dengmin123** [jeecgboot/JeecgBoot#7071]
##### 问题描述：Online报表中使用了联合查询，搜索、列表等功能正常，全量导出正常，但部分导出会报错，报错信息见下图。sql 见下方。

SELECT
	md.id AS mdid,
	md.device_sn,
	md.device_terminal_no,
	md.device_manufacture,
	md.device_type,
	md.device_status,
	md.`status` AS mdstatus,
	md.input_time,
	md.output_time,
	md.relation_wr_no,
	m.id AS mid,
	m.merchant_name,
	m.merchant_address,
	ma.area_name,
	m.subbank_name,
	m.subbank_merchant_no,
	m.merchant_contacts,
	m.merchant_contacts_phone,
	m.`status` AS mstatus,
	m.approval_status 
FROM
	biz_merchant_device md
	LEFT JOIN biz_merchant m ON m.id = md.merchant_id
	LEFT JOIN biz_merchant_area ma ON m.merchant_area_id = ma.id
WHERE m.del_flag = 0

导出失败，失败原因：SQL执行失败： ### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause' ### The error may exist in URL [jar:file:/D:/Java/apache-maven-3.9.1/maven_repository/org/jeecgframework/boot/hibernate-re/3.7.02-beta/hibernate-re-3.7.02-beta.jar!/org/jeecg/modules/online/cgreport/mapper/xml/OnlCgreportHeadMapper.xml] ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT COUNT(*) AS total FROM (SELECT md.id AS mdid, md.device_sn, md.device_terminal_no, md.device_manufacture, md.device_type, md.device_status, md.`status` AS mdstatus, md.input_time, md.output_time, md.relation_wr_no, m.id AS mid, m.merchant_name, m.merchant_address, ma.area_name, m.subbank_name, m.subbank_merchant_no, m.merchant_contacts, m.merchant_contacts_phone, m.`status` AS mstatus, m.approval_status FROM biz_merchant_device md LEFT JOIN biz_merchant m ON m.id = md.merchant_id LEFT JOIN biz_merchant_area ma ON m.merchant_area_id = ma.id WHERE m.del_flag = 0) jeecg_rp_temp WHERE jeecg_rp_temp.id = ? ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause' ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause'
导出失败，失败原因：SQL执行失败： ### 查询数据库时出错。原因：java.sql.SQLSyntaxErrorException：'where 子句'中出现未知列 'jeecg_rp_temp.id' ### 错误可能存在于 URL [jar：file：/D：/Java/apache-maven-3.9.1/maven_repository/org/jeecgframework/boot/hibernate-re/3.7.02-beta/hibernate-re-3.7.02-beta.jar！/org/jeecg/modules/online/cgreport/mapper/xml/OnlCgreportHeadMapper.xml] ### 错误可能涉及 defaultParameterMap ### 设置参数时出错 ### SQL： SELECT COUNT（*） AS total FROM （SELECT md.id AS mdid， md.device_sn， md.device_terminal_no， md.device_manufacture， md.device_type， md.device_status， md.' 'status' AS mdstatus， md.input_time， md.output_time， md.relation_wr_no， m.id AS mid， m.merchant_name， m.merchant_address， 马.area_name， m.subbank_name， m.subbank_merchant_no， m.merchant_contacts， m.merchant_contacts_phone， m.'status' AS mstatus， m.approval_status FROM biz_merchant_device md 左联接 biz_merchant m ON m.id = md.merchant_id 左联接 biz_merchant_area 马 ON m.merchant_area_id =ma.id 其中 m.del_flag = 0） jeecg_rp_temp 其中 jeecg_rp_temp.id = ？### 原因： java.sql.SQLSyntaxErrorException： 'where clause' 中出现未知列 'jeecg_rp_temp.id' ;错误的 SQL 语法 [];嵌套异常为 java.sql.SQLSyntaxErrorException： 'where clause' 中的未知列 'jeecg_rp_temp.id'

##### 错误截图：
<img width="1280" alt="微信图片_20240813101052" src="https://github.com/user-attachments/assets/159f6201-c9fb-4283-a99a-975b5e80a12e">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by dengmin123** [comment]
<img width="1280" alt="微信图片_20240813101052" src="https://github.com/user-attachments/assets/dafb0622-6674-4080-8307-ad231d0ffbc3">

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
目前的选中导出逻辑需要id字段，在你的SQL中没有id字段所以报错了，你可以把id写在sql里但不显示出来。
![image](https://github.com/user-attachments/assets/cd268610-b986-4e9c-b783-685b6f5acdbd)

下版本会增加提示

**Comment by dengmin123** [comment]
非常感谢，问题已解决！

**Comment by dengmin123** [comment]
jeecg项目组真的很给力，有问题是真的修复啊，点赞👍

**Comment by ar996** [comment]
有个问题 ，如果是汇总表 ， 不存在这样的id ,该怎么设置， 谢谢.
