### ISSUE TITLE
jeecgboot vue3 无法 pnpm install

### ISSUE THREAD

**Issue by ws-gy** [jeecgboot/JeecgBoot#7072]
##### 问题描述：vue3 执行 pnpm install 一直打印一下日志 无法install
GET https://registry.npmmirror.com/@types/fs-extra/-/fs-extra-11.0.4.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/showdown/-/showdown-2.0.6.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@purge-icons/generated/-/generated-0.10.0.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/inquirer/-/inquirer-9.0.7.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/crypto-js/-/crypto-js-4.2.2.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/intro.js/-/intro.js-5.1.5.tgz error (ERR_PNPM_EPERM). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@purge-icons/generated/-/generated-0.10.0.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.onds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/fs-extra/-/fs-extra-11.0.4.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left. left.
 WARN  GET https://registry.npmmirror.com/@types/showdown/-/showdown-2.0.6.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/crypto-js/-/crypto-js-4.2.2.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/intro.js/-/intro.js-5.1.5.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.eft.
 WARN  GET https://registry.npmmirror.com/@types/inquirer/-/inquirer-9.0.7.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.es left.
 WARN  GET https://registry.npmmirror.com/@types/qrcode/-/qrcode-1.5.5.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.ries left.
 WARN  GET https://registry.npmmirror.com/@types/qs/-/qs-6.9.15.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.0 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@types/nprogress/-/nprogress-0.2.3.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@commitlint/config-conventional/-/config-conventional-18.6.3.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/sortablejs/-/sortablejs-1.15.8.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/lodash-es/-/lodash-es-4.17.12.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/codemirror/-/codemirror-5.60.15.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@vitejs/plugin-vue-jsx/-/plugin-vue-jsx-3.1.0.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/@types/mockjs/-/mockjs-1.0.10.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/commitizen/-/commitizen-4.3.0.tgz error (ERR_PNPM_EPERM). Will retry in 1 minute. 1 retries left.

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
百度下不清楚

**Comment by zhangdaiscott** [comment]
看看是不是这个问题
https://www.wyr.me/post/746%26wd=%26eqid=dd0ce322000010320000000265ae2306

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/2301_76633800/article/details/138787438
