### ISSUE TITLE
BasicTable表格分页数据超过50条选择框就会消失一大部分。

### ISSUE THREAD

**Issue by zhouhengisusing** [jeecgboot/JeecgBoot#7073]
##### 版本号：
3.5.5

##### 问题描述：
BasicTable表格的分页显示，当数据条数在50条以内的情况下，选择是可以的，但是我选择一次加载超过50条数据，比如说我选择了加载100条数据，那个时候选择框就会消失。

##### 错误截图：
![QQ_1723537523746](https://github.com/user-attachments/assets/ed19b960-8415-4be6-9241-eaeeb6b86aef)

![QQ_1723537649816](https://github.com/user-attachments/assets/45d01f87-867a-4317-8835-0f89a17b3827)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版
