### ISSUE TITLE
jeecgboot3_sas 后端微服务启动报错

### ISSUE THREAD

**Issue by 318313260** [jeecgboot/JeecgBoot#7074]
##### 版本号：
jeecgboot3_sas  3.7.0

##### 问题描述：

后端微服务启动报错(单体启动无异常).
1.  nacos 可正常启动
2.  gateway可正常启动
2.  jeecg-demo-cloud与jeecg-system-cloud启动均报错

错误1:
`
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot3/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
`
配置中增加  spring.main.allow-bean-definition-overriding=true配置后报下面错误
错误2:
`***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).`
##### 错误截图：
![错误1](https://github.com/user-attachments/assets/fb9ca8f0-4e81-42d3-9b62-006e36ba1079)

![错误2](https://github.com/user-attachments/assets/b026dbfb-918c-42a8-9abf-c62294548999)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liuling1314** [comment]
druid 的bug，新版本已经修复，项目目录pom文件 druid.version 改成 1.2.23 就行了

**Comment by fateblessme** [comment]
尝试将 druid.version 改成 1.2.23 也不行
![image](https://github.com/user-attachments/assets/f348b9fa-ded0-4ab1-8687-79c69db58f90)
还是还是一样的问题

所以我直接在 jeecg-system-cloud-start 中做了排除
![image](https://github.com/user-attachments/assets/358e654d-5d76-4cdc-a27c-d66f3c7327d1)
就就正常了，先这么处理吧

**Comment by rDearApple** [comment]
> druid 的bug，新版本已经修复，项目目录pom文件 druid.version 改成 1.2.23 就行了

对了 牛
