### ISSUE TITLE
table中的复选框，当鼠标移动到复选框时，或者对复选框勾选取消时，会导致表格重新渲染会非常卡

### ISSUE THREAD

**Issue by liwenbo** [jeecgboot/JeecgBoot#7075]
##### 版本号：
 3.4.4

##### 问题描述：
PC端，当table存在checkbox时，并且列表中存在customRender时，每次鼠标移动到复选框时，会导致触发customRender，并且也会导致getCheckboxProps被触发，重新渲染，目前非常影响勾选性能，非常的卡；
经过对原生的antdesign的table进行测试，是不会触发表格重新渲染的。

##### 错误截图：

![image](https://github.com/user-attachments/assets/68d5f051-74a3-4c1b-9114-9f90be2d1469)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liwenbo** [comment]
再次对原生的进行测试了，customRender方法当鼠标滑过或勾选时，会进行触发方法customRender， 但是不会触发getCheckboxProps，但是封装过后勾选取消勾选的是会触发：getCheckboxProps

**Comment by zhangdaiscott** [comment]
升级到最新版，优化过

**Comment by liwenbo** [comment]
> 升级到最新版，优化过

有确定的升级的日志吗？现在如果直接升级到最新版本，担心会产生其他问题
