### ISSUE TITLE
富文本编辑器，无法上传多个图片

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#7076]
##### 版本号：
3.6.3

##### 问题描述：
富文本编辑器，图片上传选择多个图片，upload接口成功调用多次，但是实际只显示一个

目前尝试下来，本地开发时没问题，打包后有问题，根据打印结果来看，是因为a-upload的onChange事件中uploading状态，在本地开发时一个文件会触发2次，打包后只触发一次，又因为`src/compoennts/Tinymce/src/ImgUpload.vue`中定义的uploading是共用的，没有每个文件单独定义，导致第二张图片没有emit('uploading')。也就不会触发替换
本地开发时的打印：
![1723772247006](https://github.com/user-attachments/assets/0b30daf0-1fe5-43e7-b08e-3db9453d9921)
打包后：
![image](https://github.com/user-attachments/assets/36b02754-b246-45bc-a7e1-04f345eb26d3)

##### 错误截图：
官网示例就能复现：http://boot3.jeecg.com/demo/document/form/tabIndex
![image](https://github.com/user-attachments/assets/f07c3d1c-6420-4638-b608-5cb90a39f93f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq
