### ISSUE TITLE
pnpm build报错

### ISSUE THREAD

**Issue by lbz303** [jeecgboot/JeecgBoot#7077]
##### 版本号：
3.7.0

##### 问题描述：

pnpm build打包报错
pnpm 版本和 node：
patrick@Patrick taiyi_web % pnpm --version
9.7.0
patrick@Patrick taiyi_web % node -v
v18.12.0

##### 错误截图：
![CleanShot 2024-08-13 at 20 36 33@2x](https://github.com/user-attachments/assets/86f9e827-e2fc-462a-826d-29cf67d91a13)

**Comment by zhangdaiscott** [comment]
不清楚，百度下
