### ISSUE TITLE
微服务新增模块controller类接口方法中免登录Token注解@IgnoreAuth不生效

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JeecgBoot#7081]
##### 版本号：
v3.7.0_all

##### 问题描述：

微服务，通过mvn命令新增模块，在controller中一个方法添加@IgnoreAuth注解不生效，调试发现IgnoreAuthPostProcessor.java方法中
restController instanceof Advised 返回为false，所以无法加入列表中，请解惑，谢谢！

##### 错误截图：

1.新增的controller类如下：
![image](https://github.com/user-attachments/assets/cfb65b87-688b-4d2b-b3bf-f761bab5b310)
2.IgnoreAuthPostProcessor 方法判断为false ：
![image](https://github.com/user-attachments/assets/00a21c63-2c2b-4cdb-870d-f911d04961f0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq
