### ISSUE TITLE
开启qiankun 主应用加载子应用错误

### ISSUE THREAD

**Issue by duxin14436106** [jeecgboot/JeecgBoot#7082]
##### 问题描述：拉取三个jeecgBoot-vue3，一个作为主应用，开启qiankun配置，另外两个作为子应用，页面跳转报错，已经正确进入到子应用的app中，存放子应用的容器也是存在的，但是一直处于子应用加载的状态，报错#31
1. 是否开启的项目的配置默认自动加载了子应用，导致#31（因为查到的问题是说再次进入子应用没有卸载之前，但是尝试无解）

##### 错误截图：
![image](https://github.com/user-attachments/assets/b74a559c-3ae9-4103-83c7-f116f473febd)
![image](https://github.com/user-attachments/assets/c49f6107-5617-47fe-a315-7563bd1b523f)

![image](https://github.com/user-attachments/assets/46172dca-df61-4e09-95b4-9b61683eae83)

![image](https://github.com/user-attachments/assets/8327bb83-4722-45f9-8d0e-1ebbe1b14c26)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
归集到https://github.com/jeecgboot/JeecgBoot/issues/6947
