### ISSUE TITLE
online表单扩展配置中label长度配置规则

### ISSUE THREAD

**Issue by tsgdnwxg** [jeecgboot/JeecgBoot#7083]
##### 版本号：

3.7.0_all

##### 问题描述：

online表单中扩展配置可以对label长度进行配置，但是文档之并没有相关配置的讲解描述，使用后盲猜是按照百分比配置的，但是列数不同和是否全屏情况下好像规则又不太一样，建议出一个官方的配置规则讲解。

##### 错误截图：

![微信截图_20240814195528](https://github.com/user-attachments/assets/7eb80cad-bb56-4761-9e54-4ee869a49c28)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy  文档

**Comment by lsqGitHub716** [comment]
https://help.jeecg.com/online/form/comment.html
