### ISSUE TITLE
如何去掉modal的默认滚动条

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/JeecgBoot#7085]
##### 版本号：
3.7.0_all

##### 问题描述：
modal默认鼠标移入有滚动条，明明没有超出范围，却有滚动条，用户比较困扰

##### 错误截图：
![image](https://github.com/user-attachments/assets/718baa84-b94e-4044-8462-aa9eb1d47a36)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yang-xianzhu** [comment]
![image](https://github.com/user-attachments/assets/35d8214f-55c6-4e97-92a5-66d3d61c1c0a)

**Comment by zhangdaiscott** [comment]
sq
