### ISSUE TITLE
js增强返回的对象方法之间不能有注释

### ISSUE THREAD

**Issue by Ariza-salaman** [jeecgboot/JeecgBoot#7086]
##### 版本号：
3.7.0_all

##### 问题描述：
使用js增强的时候，在return的对象内，每个方法之间有注释时，会报错： SyntaxError: Unexpected identifier ‘value’

##### 错误截图：
- 注释写在方法之间：
![注释写在方法之间](https://github.com/user-attachments/assets/34000f52-14f3-4dea-9dd8-e89bf1c1c712)
- 报错
![报错](https://github.com/user-attachments/assets/485ecedc-5ece-463a-abbc-895d19145164)
- 注释写在方法内才会正常
![注释写在方法内](https://github.com/user-attachments/assets/7e50e52d-8e7b-4cfe-9680-431762496bde)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
