### ISSUE TITLE
积木报表超过50列无法显示

### ISSUE THREAD

**Issue by Tannysiu** [jeecgboot/JeecgBoot#7087]
##### 版本号：
 3.7.0_all（发布日期：2024-06-23）

##### 问题描述：
积木报表中无法设置超过50列字段，手工添加超过50列字段时，会无法修改超过50列字段的值。

##### 错误截图：
![Uploading 微信图片_20240819103606.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
# 行数(设计页面展示多少行)
    row: 100
    # 列数(设计页面展示多少列)
    col: 100


https://help.jeecg.com/jimureport/config/yaml.html
