### ISSUE TITLE
点击右上角刷新页面变成空白

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/JeecgBoot#7088]
##### 版本号：
3.7.0_all
##### 问题描述：

![e8b29a0921c01b915aefd7cd2a48fb57](https://github.com/user-attachments/assets/a9ca6b55-90c8-45a9-941e-1620c7519be4)
![3daf02a0349c6ff02c5bcf7b57f66a00](https://github.com/user-attachments/assets/51c86d36-1080-4f44-ad3d-a20db049e040)

您好，我遇到这个问题，开发环境没问题，部署到正式环境，点击右上角刷新一次或者两次后，路由加了 redirect，并且页面变成空白的情况。怎么解决啊

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
你的样式不是最新版 3.7 另外是你自己开发的页面刷新有问题？还是所有都有问题

**Comment by qinghechaoge** [comment]
> 你的样式不是最新版 3.7 另外是你自己开发的页面刷新有问题？还是所有都有问题

样式我们进行了很多修改，部署后所有页面都有这个问题

**Comment by zhangdaiscott** [comment]
那是不是你们自己改后导致的，我们演示系统没这问题

**Comment by qinghechaoge** [comment]
> 那是不是你们自己改后导致的，我们演示系统没这问题

那就不知道什么原因了，自己也解决不了，您可以提供一下解决思路吗？

**Comment by zhangdaiscott** [comment]
自己修改后导致的，我们无法支持
