### ISSUE TITLE
springboot3_sas 分支 3.7.0 聚合路由配置后，界面空白

### ISSUE THREAD

**Issue by fateblessme** [jeecgboot/JeecgBoot#7089]
##### 版本号：
springboot3_sas 分支 3.7.0（发布日期：2024-06-17）

##### 问题描述：
配置聚合路由，页面展示没有达到预期效果

##### 预期效果
![image](https://github.com/user-attachments/assets/0ca7a2b1-4370-40ab-af4a-336a0b0d3c41)

##### 错误截图：
一级配置
![image](https://github.com/user-attachments/assets/a197bd83-2f15-432a-b0ec-8040bc06214c)

子级菜单
![image](https://github.com/user-attachments/assets/bfafe3cd-1990-48ee-8891-30550572f879)
界面展示
![image](https://github.com/user-attachments/assets/cba4f3df-cc16-4a79-bf4e-ac1b34aab0b7)

**聚合路由配置后，界面空白**

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
相关问题
https://github.com/jeecgboot/JeecgBoot/issues/6354
