### ISSUE TITLE
列字段显隐控制，如何通过配置实现

### ISSUE THREAD

**Issue by renyuanya123** [jeecgboot/JeecgBoot#7091]
##### 版本号：
3.6.3
##### 问题描述：
列字段显隐控制，如何通过配置实现
##### 错误截图：

列字段显隐控制 该如何配置，我的配置是 

![52435a4b88f8d2d0c75c80a7e3f90306](https://github.com/user-attachments/assets/a0756608-d856-41fd-8287-d978dd25a775)

![f8d193b4b8c2459a548feae8536455ea](https://github.com/user-attachments/assets/f4f31e86-71ba-4dd3-9a84-422724c0ceeb)

![85579c27405716f1759f836d0df36e7c](https://github.com/user-attachments/assets/a4f6f0d0-8c25-48ff-bfe4-b91256887953)
![0652199ec5becaf2ec682b6415e8cf40](https://github.com/user-attachments/assets/5b4b56b7-d923-4c6e-acc8-2a2ae444af79)

，帮助文档
![076033399aedb6209f037406a1ab518c](https://github.com/user-attachments/assets/dcbdadeb-4718-4f4a-b53f-8e1a994732c0)
![afbe270da3f714864048937ad83d3c80](https://github.com/user-attachments/assets/24061281-7863-4235-942c-053ebfab0a52)

这两例子我看不懂，请帮忙！！！

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by renyuanya123** [comment]
还有这说的也是表意不明确https://help.jeecg.com/vue3/auth/listfield.html

**Comment by zhangdaiscott** [comment]
你是要用online模式还是要代码生成，目前你二者混用了

**Comment by renyuanya123** [comment]
要代码生成该如何配置？在online模式该如何配置？二者混用又该如何配置？

**Comment by zhangdaiscott** [comment]
看文档

**Comment by renyuanya123** [comment]
就是看不懂文档才问您们的
