### ISSUE TITLE
为什么项目中积木报表没有“查询设置”选项？

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#7092]
##### 版本号：
3.7.0

##### 问题描述：
看官方手册上，是有查询设置选项的，可以设置默认查询、展开查询栏，是免费版没有这个选项吗？

##### 错误截图：

![积木报表](https://github.com/user-attachments/assets/4a7f630c-2d1e-4436-8147-72fda0382ca8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下个版本发布就有了
