### ISSUE TITLE
Online表单开发，范围查询不生效

### ISSUE THREAD

**Issue by littleJK-sys** [jeecgboot/JeecgBoot#7093]
##### 错误截图：
![企业微信截图_20240820110739](https://github.com/user-attachments/assets/d93ef5e7-d93d-4f32-9532-1bf8a5d82c58)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
模糊需要前后加*

**Comment by zhangdaiscott** [comment]
范围查询，要什么模糊

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by littleJK-sys** [comment]
日期范围查询也不生效啊

**Comment by zhangdaiscott** [comment]
可能是个bug，下个版本看看
