### ISSUE TITLE
online表单开发变量查询查询条件问题

### ISSUE THREAD

**Issue by ttdsl** [jeecgboot/JeecgBoot#7094]
##### 版本号：
master分支

##### 问题描述：
通过online表单开发页面，个性化查询使用了系统变量，测试时请求路径异常，请求路径在#那里被截断了

##### 错误截图：

<img width="1657" alt="image" src="https://github.com/user-attachments/assets/05fbb531-0c87-446b-a939-7a5c1f3095cb">
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/44afd90d-4fef-4fca-bb76-8453c3b2f3c8">
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/ff6c195b-bdc6-4d6f-8679-a2466971fb29">
![Uploading image.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不支持这么用吧

**Comment by zhangdaiscott** [comment]
具体使用方式，请在详细点

**Comment by zhangdaiscott** [comment]
无回复关闭
