### ISSUE TITLE
主附表启用联合查询附表字段内容显示不全；java增强附表内容不能修改；系统编码规则重复调用后台方法两次？

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/JeecgBoot#7095]
##### 版本号：
3.7.0

##### 问题描述：
主附表启用联合查询附表字段内容显示不全；想通过java增强实现主表附表编码提交时自动生成，主表java增强中修改值没问题，附表值修改不生效；系统编码规则重复调用后台方法两次？

##### 错误截图：
![image](https://github.com/user-attachments/assets/279b86aa-4cee-4b2c-9ec0-f4ae8eb78519)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
java增强附表内容不能修改；
系统编码规则重复调用后台方法两次？

图文并茂详细说明，此两个功能点的用法

**Comment by tb2888** [comment]
java增强附表内容不能修改：
比如主表销售订单，附表销售订单明细，销售订单有订单号，明细有行号，我想在java增强中实现提交后自动生成订单号和行号。主表生成没问题，附表不行
![1724639385933](https://github.com/user-attachments/assets/ca509100-6a76-499e-be13-7ea868a54571)
![1724639345775](https://github.com/user-attachments/assets/93d35f1e-ce8b-402c-8a7b-d8bdf66f5276)
![1724639317826](https://github.com/user-attachments/assets/c0fef3fe-c441-46f6-8428-9e25add8e575)
系统编码规则重复调用后台方法
![1724638534937](https://github.com/user-attachments/assets/0f616efa-3d00-4103-bc15-4691ef595e78)
![1724639772287](https://github.com/user-attachments/assets/c7da703a-0fbb-4047-81db-a697cc939547)
![1724638995682](https://github.com/user-attachments/assets/47085b03-635a-4a47-ac0a-0992c5a953aa)

**Comment by sjlei** [comment]
### 一、内容显示不全

是正常的溢出隐藏机制

### 二、【未复现】Java增强附表内容不能修改
测试了直接修改和创建新对象两种方式，均可修改

#### 方式1
![image](https://github.com/user-attachments/assets/7f616b86-de7f-4939-92fa-a97655dc036f)

#### 方式2
![image](https://github.com/user-attachments/assets/d069b055-5020-4225-913e-0439f3eaf7ed)


### 三、【已修复】系统编码规则重复调用后台方法两次
