### ISSUE TITLE
vxetable 4.7版本支持自定义拖动列了，JVxetable有升级计划吗？

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/JeecgBoot#7096]
##### 版本号：
 3.7.0_all

##### 问题描述：

vxetable 4.7版本支持自定义拖动列了，JVxetable有升级计划吗？
https://vxetable.cn/v4/#/component/grid/custom/storage

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
先归档到 https://github.com/jeecgboot/JeecgBoot/issues/1312
