### ISSUE TITLE
JVxeTable文本全部显示

### ISSUE THREAD

**Issue by 1372037590** [jeecgboot/JeecgBoot#7097]
##### 版本号：
前端3.6.1

##### 问题描述：
您好，使用JVxeTable时，我想显示全部文本，不想省略，修改了样式也不行，请问我需要怎么配置呢，
![Tlink图片_2024082191604](https://github.com/user-attachments/assets/d224cb75-525e-4b3b-8b8b-a12c24983cf5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
覆盖我们写的样式
