### ISSUE TITLE
新下载下来的项目，前端代码好多文件都有各种特别多的ts报错

### ISSUE THREAD

**Issue by manli-tonghua** [jeecgboot/JeecgBoot#7100]
##### 版本号：
最新版本-3.7.0

##### 问题描述：
1、新下载下来的项目，前端代码好多文件都有各种特别多的ts报错和eslint报错，其中eslint报错我通过忽略.vue文件解决了（但是感觉不是特别好的方案），然而还有很多ts的报错，怎么解决一下比较好呢

##### 错误截图：
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/6485eb1d-90b2-46b3-b907-cfc0f6fda03f">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
warning忽略就行
