### ISSUE TITLE
BasicTable 表尾合计行 无法实时同步列宽拖动进行同步

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7101]
##### 版本号：
3.7.0_all

##### 问题描述：
在列配置resizable: true时，如果跟表尾合计进行联动使用，列宽改变时， 表尾合计的列宽没有同步改变

##### 错误截图：
![image](https://github.com/user-attachments/assets/8284f519-b0e2-4a48-936c-84ae252b4f1a)
![image](https://github.com/user-attachments/assets/ea3a2d36-51d1-4607-be17-dd1a468b4a55)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可在 src/components/Table/src/BasicTable.vue 文件按如下修改:

![image](https://github.com/user-attachments/assets/3a5a6ca4-e8bf-4a0d-8a20-2c3b2f2677cb)

```
// update-begin--author:liaozhiyang---date:20240902---for：[issues/7101] 列配置resizable: true时，表尾合计的列宽没有同步改变
          const columns = getColumns();
          const findItem = columns.find((item) => {
            if (item['dataIndex'] != null) {
              return item['dataIndex'] === col['dataIndex'];
            } else if (item['flag'] != null) {
              return item['flag'] === col['flag'];
            }
            return false;
          });
          if (findItem) {
            findItem.width = w;
            setColumns(columns);
          }
          // update-end--author:liaozhiyang---date:20240902---for：[issues/7101] 列配置resizable: true时，表尾合计的列宽没有同步改变
          console.log('col',col);
          col.width = w;
```

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/JeecgBoot/commit/70607dbe2bf0356edaaf7e708a5a7024855a1b8c
