### ISSUE TITLE
微服务升级为单体时候出现报错，劳烦看看，谢谢

### ISSUE THREAD

**Issue by keenanon** [jeecgboot/JeecgBoot#7102]
##### 错误截图：
<img width="1220" alt="屏幕截图 2024-08-21 223109" src="https://github.com/user-attachments/assets/050345f7-898d-41cc-af01-e0178dac937e">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
提供的错误信息太少，无法分析
