### ISSUE TITLE
怎么设置数据权限的规则值

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#7103]
##### 版本号：
3.7.0

##### 问题描述：
![image](https://github.com/user-attachments/assets/c94806ca-4bbf-4a01-aacd-d5c25fc1874e)
这个怎么自定义添加

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这是系统变量，你可以自定义，自定义的话，需要扩展
org/jeecg/common/system/util/JwtUtil.java的方法getUserSystemData
