### ISSUE TITLE
打印html类型文件时无法分页，只会打印一页，超过一页内容被截取

### ISSUE THREAD

**Issue by chenmonkey** [jeecgboot/JeecgBoot#7104]
##### 错误截图：
![image](https://github.com/user-attachments/assets/ef9ae807-08b3-4262-8b4a-824b7c77011c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不支持分页，分页需要自己额外处理
