### ISSUE TITLE
启动clouddemoapplication出现报错，配置文件检查无误

### ISSUE THREAD

**Issue by keenanon** [jeecgboot/JeecgBoot#7105]
##### 版本号：
3.7

##### 问题描述：启动clouddemo时候报错：init datasource error, url: jdbc:mysql://jeecg-boot-mysql:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

##### 错误截图：
<img width="1270" alt="屏幕截图 2024-08-22 175208" src="https://github.com/user-attachments/assets/8107d428-4ed3-475b-8646-29b47ebee9e3">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
错误不是很明确，账号密码不对
