### ISSUE TITLE
创建报表保存提示成功，但是报表管理页面却看不到

### ISSUE THREAD

**Issue by treebreath** [jeecgboot/JeecgBoot#7107]
##### 版本号：
1.7.8

##### 问题描述：
集成到我的工程后，创建报表，保存成功，但是在报表管理页面看不到创建的报表，在数据库jimu_report有看到新增的记录，但是数据源的表jimu_report_data_source中却没有对应的新增记录，在报表中创建字典也是提示成功，而且表jimu_dict中也有数据了，但是返回外面也看不到刚创建的字典。

##### 错误截图：
<img width="632" alt="image" src="https://github.com/user-attachments/assets/d4d80add-b4eb-451e-9ce8-284bfb78e561">
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/0ff26623-90f8-43fa-ae59-dece96aaf820">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
开启多租户了？

**Comment by zhangdaiscott** [comment]
无回复关闭

**Comment by treebreath** [comment]
> 了？
你好，有配置了租户模式
# 积木报表配置
jeecg:
  jmreport:
    saas-mode: tenant

**Comment by treebreath** [comment]
不好意思，前两天忙下，今天才看到消息，希望能得到回复
