### ISSUE TITLE
有增加权限控制的计划吗？

### ISSUE THREAD

**Issue by treebreath** [jeecgboot/JeecgBoot#7108]
##### 版本号：
1.7.8

##### 问题描述：
jimureport在尝试使用后，感觉非常好，但是可惜没办法通过某个机制与我的RBAC权限控制进行整合。不知道后面有没有这个打算呢？如果不能有效的控制权限，感觉这个产品的吸引力就大大打折了。因为会用到数据报表的多为企业，而企业是非常注册数据机密性的。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己给sql加条件就行，跟积木没关系

**Comment by treebreath** [comment]
> 自己给sql加条件就行，跟积木没关系

请问下怎么加有具体的示例教程吗？
