### ISSUE TITLE
本地部署的项目，其他用户通过内网平台访问看不到图片，图片是本地上传的

### ISSUE THREAD

**Issue by hbz1104** [jeecgboot/JeecgBoot#7111]
##### 版本号：
v3.7.0

##### 问题描述：
想做一个公司内部用的一个小平台
本地部署的项目，其他用户通过内网访问平台看不到图片，图片是本地上传的，改过配置文件里的路径了，还是不行，

2024-08-23 11:56:57.115 [http-nio-8080-exec-3] ERROR o.jeecg.modules.system.controller.CommonController:232 - 文件[temp/OIP-C_1724385262204.jpg]不存在..
##### 错误截图：
本地访问：
![image](https://github.com/user-attachments/assets/3b981eda-db3d-422a-94ba-4ab435f7ad68)

其他用户访问：
![微信图片_20240823120125](https://github.com/user-attachments/assets/0b86e7d9-ff19-462e-a5fc-7dc824abb085)

**Comment by zhangdaiscott** [comment]
ws  测

**Comment by 1298191366** [comment]
未复现，请查看是否访问的同一个ip
![image](https://github.com/user-attachments/assets/50f62ceb-9696-4f8d-bb74-0f00378c2615)
并且确认访问的图片地址 不是localhost, 而是ip地址
![image](https://github.com/user-attachments/assets/6f7b509d-f6d4-4567-a927-8638975724c7)
