### ISSUE TITLE
basicTable选中数据，未跟随表格数据变化而清空

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#7113]
##### 版本号：
3.6.3

##### 问题描述：
basicTable设置了rowSelection功能，如果重新请求表格api（比如reload或者新的查询），选中的值（selectedRow、selectedRowKey、表格上方的已选中XX条数据）不会清空，可能选中的值里某条记录，在新的表格数据里已经不存在了

##### 错误截图：
官网截图：http://boot3.jeecg.com/comp/table/formTable
![image](https://github.com/user-attachments/assets/4bb28756-1327-446b-a53b-1c54a59dbad8)
![image](https://github.com/user-attachments/assets/8cd2eafa-b270-404d-9c5d-131fe8f1a52d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
你是想做什么操作的时候，不回显选中的selectedRowKey呢？因为有些需求是需要选中的，比如跨页选中数据，当查询第二页数据时候，第一页选中的也是需要保留的。

**Comment by havenothingtosay** [comment]
> 你是想做什么操作的时候，不回显选中的selectedRowKey呢？因为有些需求是需要选中的，比如跨页选中数据，当查询第二页数据时候，第一页选中的也是需要保留的。

我明白了你们不清除选中的原因，确实不好判断。我说的情况是：比如对选中的数据进行操作完以后，一般会重新获取表格数据，这时候可能返回数据里已经没有之前选中的数据了，但是在selectedRows里还有这两条数据。

**Comment by lsqGitHub716** [comment]
> > 你是想做什么操作的时候，不回显选中的selectedRowKey呢？因为有些需求是需要选中的，比如跨页选中数据，当查询第二页数据时候，第一页选中的也是需要保留的。
> 
> 我明白了你们不清除选中的原因，确实不好判断。我说的情况是：比如对选中的数据进行操作完以后，一般会重新获取表格数据，这时候可能返回数据里已经没有之前选中的数据了，但是在selectedRows里还有这两条数据。

删除的情况下，确实可能数据不存在了。其他的操作情况，数据理论上是一直存在，因为选中的id不会变；你可以看看针对你们的需求，去重写一下选中的这里的逻辑

**Comment by havenothingtosay** [comment]
> > > 你是想做什么操作的时候，不回显选中的selectedRowKey呢？因为有些需求是需要选中的，比如跨页选中数据，当查询第二页数据时候，第一页选中的也是需要保留的。
> > 
> > 
> > 我明白了你们不清除选中的原因，确实不好判断。我说的情况是：比如对选中的数据进行操作完以后，一般会重新获取表格数据，这时候可能返回数据里已经没有之前选中的数据了，但是在selectedRows里还有这两条数据。
> 
> 删除的情况下，确实可能数据不存在了。其他的操作情况，数据理论上是一直存在，因为选中的id不会变；你可以看看针对你们的需求，去重写一下选中的这里的逻辑

嗯，我们已经自己做了处理清空selected数据。不过也不一定是删除的情况，可能是根据状态查询的数据，操作之后状态改变就不返回这条数据了。其实原本是想在完全重新获取表格数据的时候能清空选中的ids，但是考虑分页要保留的话，确实不好区分
