### ISSUE TITLE
JRangeDate 增加presets 快捷日期 参数后出现选择异常。

### ISSUE THREAD

**Issue by CodeXiaoYan** [jeecgboot/JeecgBoot#7115]
##### 问题描述：
快捷选择之后，日期控件应该关闭，现在的情况是关闭后又重新打开了，目前使用别的方式解决了这个问题，但是解决方案不是很好。
`<template>
  <a-range-picker
    v-model:value="rangeValue"
    @change="handleChange"
    :show-time="datetime"
    :placeholder="placeholder"
    :valueFormat="valueFormat"
    :presets="rangePresets"
    :open="open"
    @open-change="open = $event"
  />
</template>

<script lang="ts">
  import { defineComponent, ref, watch, computed } from 'vue';
  import { propTypes } from '/@/utils/propTypes';
  import { Form } from 'ant-design-vue';
  import dayjs from 'dayjs';
  const placeholder = ['开始日期', '结束日期'];

  /**
   * 用于范围查询
   */
  export default defineComponent({
    name: 'JRangeDate',
    props: {
      value: propTypes.string.def(''),
      datetime: propTypes.bool.def(false),
      placeholder: propTypes.string.def(''),
    },
    emits: ['change', 'update:value'],
    setup(props, { emit }) {
      const open = ref(false);
      const rangeValue = ref([]) as any;
      const formItemContext = Form.useInjectFormItemContext();
      const rangePresets = [
        { label: '今天', value: [dayjs().add(0, 'd'), dayjs()] },
        { label: '近一周', value: [dayjs().add(-7, 'd'), dayjs()] },
        { label: '近半个月', value: [dayjs().add(-14, 'd'), dayjs()] },
        { label: '近一个月', value: [dayjs().add(-1, 'M'), dayjs()] },
        { label: '近三个月', value: [dayjs().add(-3, 'M'), dayjs()] },
        { label: '近半年', value: [dayjs().add(-6, 'M'), dayjs()] },
        { label: '近一年', value: [dayjs().add(-1, 'y'), dayjs()] },
      ];
      watch(
        () => props.value,
        val => {
          if (val) {
            rangeValue.value = val.split(',');
          } else {
            rangeValue.value = [];
          }
        },
        { immediate: true },
      );

      const valueFormat = computed(() => {
        if (props.datetime === true) {
          return 'YYYY-MM-DD HH:mm:ss';
        } else {
          return 'YYYY-MM-DD';
        }
      });

      function handleChange(arr) {
        let str = '';
        if (arr && arr.length > 0) {
          if (arr[1] && arr[0]) {
            str = arr.join(',');
          }
        }

        emit('change', str);
        emit('update:value', str);
        formItemContext.onFieldChange();
        setTimeout(() => {
          if (arr && arr.length === 2) open.value = false;
        });
      }
      return {
        rangeValue,
        placeholder,
        valueFormat,
        rangePresets,
        handleChange,
        open,
      };
    },
  });
</script>

<style scoped></style>`

##### 错误截图：
![PixPin_2024-08-24_14-56-07](https://github.com/user-attachments/assets/9018bc70-07a2-4f9b-b012-49c5c63dba8d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试无问题，更新到最新版试试
