### ISSUE TITLE
BasicTable搜索后BUG

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#7116]
##### 版本号：
3.7.0

##### 问题描述：
搜索后，后台返回7条记录，但第一条记录重复很多次。

##### 错误截图：
![bug1](https://github.com/user-attachments/assets/b711edf0-b95c-42a6-9388-249f0224b48d)
![bug2](https://github.com/user-attachments/assets/cc5b39a9-1984-43be-a83b-f40f0af600ba)
![bug3](https://github.com/user-attachments/assets/b6377ce1-abf4-4b46-8eb4-66c8a296ad79)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;
![bug2](https://github.com/user-attachments/assets/cc5b39a9-1984-43be-a83b-f40f0af600ba)

**Comment by zhangdaiscott** [comment]
你可以按照某个字段或者ID排序

**Comment by zhangdaiscott** [comment]
是你自己用法问题吧
