### ISSUE TITLE
BasicTable有类似积木报表的按单元格汇总功能吗

### ISSUE THREAD

**Issue by zhouyu629** [jeecgboot/JeecgBoot#7117]
##### 版本号：
3.7.0

##### 问题描述：
需要自己用rowSpan来实现吗？还是可以设置？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己实现，项目中有例子
