### ISSUE TITLE
前台样式问题咨询

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7118]
##### 问题描述：
前台样式里面没有找到特殊设置系统默认样式的地方，但是为啥样式和默认的ant4.0不一致？比如说ant4.0说明 Button 的圆角调整为了 6px，但是我看前台的页面实际样式是4px,请问这些全局样式是在哪里设置的？怎么修改

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
在 src/App.vue 文件对antd 4.x一些默认的样式进行了重置


<img width="1113" alt="image" src="https://github.com/user-attachments/assets/c019ee07-3554-4653-accb-e31366b78a23">
