### ISSUE TITLE
在线开发多数据源问题，system采用系统库，业务表采用另一个库，在线开发的功能测试按钮和配置菜单后查询界面数据报错，是否有修改在线开发的数据源为非默认数据源

### ISSUE THREAD

**Issue by Cordini-Lin** [jeecgboot/JeecgBoot#7120]
##### 版本号：
3.4.3

##### 问题描述：
在线开发多数据源问题，system采用系统库，业务表采用另一个库，在线开发的功能测试按钮和配置菜单后查询界面数据报错，是否有修改在线开发的数据源为非默认数据源

##### 错误截图：
![image](https://github.com/user-attachments/assets/e6a427e4-b6ed-4b7c-99e1-1bb55e15427c)
![image](https://github.com/user-attachments/assets/f6fdef6d-2fed-491c-9133-c42a3bd6d33c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
目前不支持非平台数据源

**Comment by Ramboom** [comment]
@zhangdaiscott 请问这个功能什么时候发布呢:

<img width="1003" height="1067" alt="Image" src="https://github.com/user-attachments/assets/a9aedf67-7e60-40c9-86dc-a7071f51dabf" />
