### ISSUE TITLE
拖拽排序功能与下拉框组件有冲突

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/JeecgBoot#7121]
##### 版本号：
v3.5.1

##### 问题描述：
在主子表的页面，子表中使用拖拽排序功能。当子表中使用了下拉框，如下图所示，如果下拉框组件中设置了width属性，拖拽排序的功能就无法使用，点击拖拽区域，仅能出现下移或者上移的菜单，但是无法用鼠标进行拖拽排序。请问这是什么问题？

##### 错误截图：
![image](https://github.com/user-attachments/assets/ec1f0fcb-ba96-4532-a6ca-76456fa37500)

![image](https://github.com/user-attachments/assets/adfb53c0-e554-46d2-8228-7e5264f9119f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
跟 select 组件没关系，原因是组件多了之后出现了横向滚动条，出现了横向滚动条之后是禁止拖拽排序的，但是可以使用点击的方式上下移动数据
![image](https://github.com/user-attachments/assets/e513d453-0f99-4fda-830b-4024e448a4a9)
