### ISSUE TITLE
2024-8-27刚拉的master分支，下载前端依赖下载不下来

### ISSUE THREAD

**Issue by MiaoAA-Hello** [jeecgboot/JeecgBoot#7124]
##### 版本号：
node版本20.14.0、16.20.0

##### 问题描述：
2024-8-27刚拉的master分支，下载前端依赖下载不下来。

##### 错误截图：
![image](https://github.com/user-attachments/assets/33d4603a-3cbc-489b-9e78-445fe9f5176b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
使用pnpm
