### ISSUE TITLE
使用Online 表 在线开发功能  如何设置label宽度

### ISSUE THREAD

**Issue by xiaogangya12138** [jeecgboot/JeecgBoot#7128]
##### 问题描述：
使用Online在线开发中，配置表单，当表单label 文字较长时会被隐藏。
能否动态修改 label 或者 输入框的宽度 来确保 label 文字显示正常

##### 错误截图：
![image](https://github.com/user-attachments/assets/88e074b2-62f1-48d1-8793-b3de731399ac)

#####前端安装环境：vu3
如果你是启动报错，请说明你的前端环境

#####采用的是pnpm安装还是yarn?
node版本号：v16.15.0.

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
新版有label设置功能
