### ISSUE TITLE
主键的限制害死人啊

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/JeecgBoot#7130]
##### 版本号：

ALL

##### 问题描述：

online功能相关使用，对表ID的限制 ，导致很多处理不变。

请放开对主键的限制。

过往已经一堆帖子提意见了，几年都没有动静。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ID是强制逻辑，不好改

**Comment by huangwei2013** [comment]
主键改成 long(19) 的 flag，2020年就立下了吧？ 文档也写了 ( https://help.jeecg.com/java/norm/table.html )
