### ISSUE TITLE
JDictSelectTag组件onChange执行多次

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/JeecgBoot#7131]
##### 版本号：

3.4 vue3
##### 问题描述：

JDictSelectTag组件onChange执行多次，新版本已经修复了吗？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
应该修复了
