### ISSUE TITLE
在线报表对中文字段的支持不太好

### ISSUE THREAD

**Issue by zypy333** [jeecgboot/JeecgBoot#7134]
##### 版本号：
3.7.0 mysql8

##### 问题描述：
1. 含有中文字段的SQL 解析后，不按照数据库原有顺序排列，得自己手动调整
2. 中文字段如果设置成查询，会在拼接where jeecg_rp_temp.后的字段的时候报错，希望能在源码里增加反引号来避免报错

##### 错误截图：

![image](https://github.com/user-attachments/assets/7a98d7c1-9b99-417a-86a8-61637422caff)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
截图看看你的sql

**Comment by zypy333** [comment]
![1](https://github.com/user-attachments/assets/65a2521e-31b6-4535-924c-9daf8cae8b10)
![2](https://github.com/user-attachments/assets/a745e49e-cf8b-4c09-ba8b-5e5288997dc2)
图1是定义了药品编码字段作为查询字段 图2是报错的sql

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by sjlei** [comment]
问题已修复，下版本发布
