### ISSUE TITLE
online 表单开发详情页慢的问题

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7135]
##### 版本号：
springboot3_saas  3.7.0 + jeecgboot-vue3

##### 问题描述：
现在jeecgboot 3.4.3+vue2 和 springboot3_saas +jeecgboot-vue3 3.7.0 同时在使用，发现切换编辑详情页tab栏，或者编辑具体字段配置，甚至选择下拉一些基础配置时，都要反应1秒左右页面才有交互反馈，具体如下图。jeecgboot 3.4.3+vue2 online 表单开发详情页 点击任何地方，几乎都是秒出，体现不出延迟感，为啥vue3 比vue2速度慢这么多，有什么优化方案吗，官网提供的demo也是反应很慢

##### 错误截图：

![Screenshot](https://github.com/user-attachments/assets/514bafd8-5554-43bb-bfb9-5888a6d89bd4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jeecgboot 3.4.3的确慢，我们优化过
目前最新版升级了vite

**Comment by liuling1314** [comment]
现在使用下来是 jeecgboot 3.4.3 online表单 详情页很快，jeecgboot 3.7.0 很慢，有非常明显的卡顿，其它页面也还好，就online表单详情页慢，演示系统也是如此。。。。。。因为两套同时在使用，所以对比非常明显，麻烦大神抽时间看看能不能优化下呗 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
你是开发环境还是发布环境？
浏览器的版本又是多少，
我们目前测试没发现新版卡顿问题
