### ISSUE TITLE
代码生成用不了

### ISSUE THREAD

**Issue by mtcyc1** [jeecgboot/JeecgBoot#7138]
##### 版本号：
3

##### 问题描述：

本地运行之后，点击到低代码，online表单功能后提示未找到资源，接口里面也没有相应的接口地址

##### 错误截图：
![微信图片_20240829102712](https://github.com/user-attachments/assets/559bb15b-f06d-49a8-86d1-904d824fa260)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
重启

**Comment by mtcyc1** [comment]
> 重启

重启过了，没用
