### ISSUE TITLE
数据字典空白

### ISSUE THREAD

**Issue by stanleysct** [jeecgboot/JeecgBoot#7139]
##### 错误截图：
![微信图片_20240829154105](https://github.com/user-attachments/assets/8d38a375-34ed-4284-b54d-2abc9dc992d9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
??

**Comment by stanleysct** [comment]
数据字典 不显示数据

**Comment by zhangdaiscott** [comment]
怎么出现的

**Comment by stanleysct** [comment]
> 怎么出现的

因为 修改了 public static final Boolean OPEN_SYSTEM_TENANT_CONTROL = true;

**Comment by zhangdaiscott** [comment]
那没有错，这个是开启saas多租户隔离
