### ISSUE TITLE
问个关于版权的问题：如果基于jeecg作为底层搞一套相亲交友直播聊天的业务平台。如果后期想开源自己的平台，会不会对jeecg构成侵权？

### ISSUE THREAD

**Issue by BruceLiu3385** [jeecgboot/JeecgBoot#7141]
##### 版本号：
3.7.0

##### 问题描述：

问个关于版权的问题：如果基于jeecg作为底层搞一套相亲交友直播聊天的业务平台。如果后期想开源自己的平台，会不会对jeecg构成侵权？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
参考这个
https://github.com/jeecgboot/JeecgBoot?tab=Apache-2.0-1-ov-file#readme

**Comment by zhangdaiscott** [comment]
Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
   
   In any case, you must not make any such use of this software as to develop software which may be considered competitive with this software.
