### ISSUE TITLE
jeecgboot3.7连接PG数据库Online表单开发模块创建的表没有表名的注释

### ISSUE THREAD

**Issue by chen497147884** [jeecgboot/JeecgBoot#7143]
##### 问题描述：
连接PG数据库Online表单开发模块创建的表没有表名的注释

##### 错误截图：

![image](https://github.com/user-attachments/assets/6afea11e-b58c-4e59-a235-f1699b106958)
![image](https://github.com/user-attachments/assets/fcf499a3-5950-45f4-95a4-3f1ca89182b9)

**Comment by liuling1314** [comment]
表注释貌似不会通过过去，mysql的也没有

**Comment by zhangdaiscott** [comment]
这个非必须
