### ISSUE TITLE
basicTable如何设置不限制高度

### ISSUE THREAD

**Issue by havenothingtosay** [jeecgboot/JeecgBoot#7146]
##### 版本号：
3.6.3

##### 问题描述：
basicTable如何设置不限制高度，一直往下延伸？
在tableProps里设置了maxHeight没有用，一旦setTableData()，渲染出来的max-height就会变成300px

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq
