### ISSUE TITLE
用postman连接websocket失败,防火墙没有开，

### ISSUE THREAD

**Issue by zhangyicai** [jeecgboot/JeecgBoot#7147]
##### 版本号：
Jeecg  Boot Version: 3.5.3

##### 问题描述：
web
用postman连接websocket失败

##### 错误截图：
![image](https://github.com/user-attachments/assets/a1798967-8c31-40ca-9a59-6cba9785ddd4)

![image](https://github.com/user-attachments/assets/a4cbefdf-b7ce-44d0-878a-602693d62fc4)

![image](https://github.com/user-attachments/assets/b03fdf2f-0ffe-478d-9b68-3f4896b8a3e0)

![image](https://github.com/user-attachments/assets/8f1abe40-5e44-41f5-906e-9e7b6a3c1184)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangyicai** [comment]
![image](https://github.com/user-attachments/assets/6bc6e4f4-ecd2-4144-9339-b6fcaa460a0e)

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/f26093c7-40a9-4868-b124-e423dcf19a36)
