### ISSUE TITLE
springboot3_sas 分支 online表单时间中间带T

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7148]
##### 版本号：
分支 ： springboot3_sas 版本号：3.7.0

##### 问题描述：
online表单时间类型中间都带T，master分支已经修复，麻烦大神把springboot3_sas 分支也修复下呗，springboot3_sas 我按照master分支改以后恢复正常，具体提交记录，请看下图。谢谢

##### 错误截图：

![Screenshot (1)](https://github.com/user-attachments/assets/9aa3a24b-06c0-4959-a9f2-42b641a762f3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下次版本合并，可以先手工修改了
