### ISSUE TITLE
前端pnpm install报错

### ISSUE THREAD

**Issue by laomuwt** [jeecgboot/JeecgBoot#7149]
##### 版本号：
3.7.0

##### 问题描述：
前端pnpm install

##### 错误截图：
![image](https://github.com/user-attachments/assets/6471dee6-adc5-4478-95be-1af1901331f1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
node什么版本

**Comment by zhangdaiscott** [comment]
Node.js 版本建议v20.15.0，要求Node 18+ / 16+ 版本以上

**Comment by laomuwt** [comment]
> Node.js 版本建议v20.15.0，要求Node 18+ / 16+ 版本以上

v20.16.0

**Comment by laomuwt** [comment]
主要是感觉连接到库的网络不是很稳定那种， 
https://registry.npmjs.org/@types Fintro.js error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
有时再点链接，就能打开

**Comment by laomuwt** [comment]
应该是网络问题，突然好了
