### ISSUE TITLE
省市区联动组件数据问题

### ISSUE THREAD

**Issue by LHK8088** [jeecgboot/JeecgBoot#7151]
##### 问题描述：
省市区联动组件数据json 有问题, 台湾省  710300,710400 子级id 是一样的

##### 错误截图：
![image](https://github.com/user-attachments/assets/fe02d6c1-1b74-4a31-8e3d-62cdb961bd6c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下个版本会更换新的地域数据组件
