### ISSUE TITLE
数字类型展示类需求

### ISSUE THREAD

**Issue by 1154315454** [jeecgboot/JeecgBoot#7152]
##### 版本号：
3.7.0

##### 问题描述：
在使用jeecg搭建财务类软件时，需要使用到金额的计算。
针对金额类型的数字，在页面展示时，数字靠右展示、数字展示千分位和数字保留两位小数。

 

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己扩展吧
