### ISSUE TITLE
在线表单数据修改后记录sys_data_log表中的值错误且源代码中未找到记录的代码无法修改

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/JeecgBoot#7154]
##### 问题描述：
在线表单数据修改后记录sys_data_log表中的值错误且源代码中未找到记录的代码无法修改
修改数据中的备注等字段，但是全部记录的都是删除标记字段。

##### 错误截图：
![image](https://github.com/user-attachments/assets/8a5bab17-36ae-4717-a01d-e044802f7f89)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
录个操作视频

**Comment by zhangdaiscott** [comment]
无回复关闭

**Comment by wangqian0628** [comment]
不用录视频，就是随便一个在线表单在测试中使用编辑功能保存之后，都是这样的效果

**Comment by wangqian0628** [comment]
不用录视频，就是随便一个在线表单在测试中使用编辑功能保存之后，都是这样的效果
