### ISSUE TITLE
将mysql执行脚本更换成pgsql执行脚本

### ISSUE THREAD

**Issue by zwz-create** [jeecgboot/JeecgBoot#7155]
##### 版本号：
v3.7.0

##### 问题描述：
想问一下我想使用pgsql数据库，如何执行您提供的mysql执行脚本呢

##### 错误截图：
![图片](https://github.com/user-attachments/assets/010edec6-d4b0-4f81-bc70-8be05cd63ec8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4905722
