### ISSUE TITLE
自定义表单实体类的序列号id变更导致查询报错

### ISSUE THREAD

**Issue by fengling-97** [jeecgboot/JeecgBoot#7158]
##### 问题描述：
问题：使用自定义表单生成了一批数据，此时对应业务实体类（ZmImprestRecord）的 serialVersionUID = -4833362838416877647，
后来更改了这个类（ZmImprestRecord）的serialVersionUID =3193254643107864292，也生成了一批数据；
现在查询任务就报序列化错误。

希望得到回答： 1.  如何解决这个问题？    
2.是因为哪个表直接保存了formdata的序列化数据导致的，如何修改？

##### 错误截图：

![image](https://github.com/user-attachments/assets/53e617e0-3876-49dc-8184-5ee842838270)

**Comment by zhangdaiscott** [comment]
啥意思？
