### ISSUE TITLE
3.7版本代码生成器bug

### ISSUE THREAD

**Issue by Cordini-Lin** [jeecgboot/JeecgBoot#7160]
##### 错误截图：

![4e8d695daa91ed25107351c391b6b05](https://github.com/user-attachments/assets/b6b47b76-e266-4a99-8e84-0624249b1221)
![bc49256bda831caf5187e5619b8acd1](https://github.com/user-attachments/assets/fd15dd27-cd20-4fac-8b7c-845a0b43121a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
怎么配置的
