### ISSUE TITLE
正式环境的redis不支持订阅（SUBSCRIBE）命令，导致服务无法启动

### ISSUE THREAD

**Issue by laoxiaokang** [jeecgboot/JeecgBoot#7162]
##### 版本号：
3.7.0

##### 问题描述：

正式环境的redis（云环境）不支持订阅（SUBSCRIBE）命令，导致服务无法启动，请问如何解决

##### 错误截图：
![image](https://github.com/user-attachments/assets/3dcdb3b5-8034-4599-9602-b6bb902bebc4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
麻烦提供redis server的部署信息、版本号、集群模式等

**Comment by laoxiaokang** [comment]
@EightMonth   移动云redis服务 禁用了该命令

**Comment by laoxiaokang** [comment]
现在的方法只能是切换标准版双副本redis服务
