### ISSUE TITLE
nginx部署之后其他功能正常，但无法访问积木报表

### ISSUE THREAD

**Issue by 17774122108** [jeecgboot/JeecgBoot#7163]
##### 错误截图：
![111](https://github.com/user-attachments/assets/2c1f7acc-d4ba-4bca-aba0-465ba7607624)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
本地好使？

**Comment by zhangdaiscott** [comment]
你不通过NGINX映射，访问原始后台端口试试

**Comment by 17774122108** [comment]
本地是正常的，就是局域网不行

**Comment by 17774122108** [comment]
![image](https://github.com/user-attachments/assets/c084f498-7ca3-425e-82c7-dd528e1b7aad)

**Comment by 17774122108** [comment]
也不可以，

**Comment by zhangdaiscott** [comment]
那就是部署问题

**Comment by 17774122108** [comment]
附件是nginx配置，其他的功能都是正常的可以访问使用，只有积木报表的相关功能不行




信天翁?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月4日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] nginx部署之后其他功能正常，但无法访问积木报表 (Issue #7163)





 
那就是部署问题

**Comment by 17774122108** [comment]
![前端配置截图](https://github.com/user-attachments/assets/f8a989c3-49e8-4425-bc44-06b8e4b4427e)

**Comment by 17774122108** [comment]
upstream www.luyunyan.cn {
	  server 127.0.0.1:8080;
	}
	
	server {
		#项目访问的前端端口
		listen       80;
		server_name  www.luyunyan.cn;
		#前端打的dist资源存放目录
		root		 E:\JeecgBoot-master\JeecgBoot-master\jeecgboot-vue3\dist;
		
		# 配置前端静态资源
		location / {
			 # 用于配合 browserHistory使用（很重要！）
			 try_files $uri $uri/ /index.html;
			 # 不缓存html，防止程序更新后缓存继续生效
			 if ($request_filename ~* .*\.(?:htm|html)$) {
				add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
				access_log on;
			 }
		}
		
		# 配置后端服务代理
		location  ^~/jeecgboot/ {
			#后台接口地址(我们部署去掉了/jeecg-boot项目名，如果你有请加上）
			proxy_pass         http://127.0.0.1:8080/jeecg-boot/;
			proxy_redirect off;
			#真实IP获取
			proxy_set_header  Host             $host;
			proxy_set_header  X-Real-IP        $remote_addr;
			set $my_proxy_add_x_forwarded_for $proxy_add_x_forwarded_for;
			if ($proxy_add_x_forwarded_for ~* "127.0.0.1"){
			   set $my_proxy_add_x_forwarded_for $remote_addr;
			}
			proxy_set_header   X-Forwarded-For $my_proxy_add_x_forwarded_for;
		}
 
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		} 
	}

**Comment by 17774122108** [comment]
在开发环境下，我将接口防火墙放开，用其他设备访问，积木报表也是不可以访问的，其他功能也是正常




信天翁?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月4日(星期三) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] nginx部署之后其他功能正常，但无法访问积木报表 (Issue #7163)





 
那就是部署问题

**Comment by zhangdaiscott** [comment]
本地不好使？那就是积木报表集成有问题
