### ISSUE TITLE
角色配置首页后点击菜单自动关闭

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/JeecgBoot#7165]
##### 版本号：
3.4 vue3

##### 问题描述：
将某个菜单设置为首页后，开启了组件路由，点击这个菜单会自动合并，然后展开dashboard下的首页
能不能点击菜单的时候不合并？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本太老了，看看新版有问题吗
