### ISSUE TITLE
代码生成器生成的代码可以预览，下载时报错，提示No such file or directory

### ISSUE THREAD

**Issue by kaka2008** [jeecgboot/JeecgBoot#7168]
##### 问题描述：

代码生成器生成的代码可以预览，下载时报错，提示No such file or directory
服务器：rocky 9，
没有通过docker部署，通过java -jar xxx.jar 启动
前台放在nginx下的

##### 错误截图：

![image](https://github.com/user-attachments/assets/3416e7c2-c8a9-4d3e-85aa-e34f519afd6e)

![image](https://github.com/user-attachments/assets/b4b63165-c311-4a54-af15-8e3a68d73fbb)

**Comment by zhangdaiscott** [comment]
是不是没权限？

**Comment by kaka2008** [comment]
选择的目录权限已经设置为777了，文件也生成了，可以预览，只是导出时不行。
在本地运行可以，我也怀疑可能是权限问题，应该设置哪个目录的权限呢？
![image](https://github.com/user-attachments/assets/63c09a8c-7de8-467d-9e36-ed59176c7da6)

**Comment by kaka2008** [comment]
解决了，目录  /opt/temp/codegenerate ……
设置这个路径很奇怪啊，谁能想到在/opt下建立临时文件夹呢？


![image](https://github.com/user-attachments/assets/98fc96f8-4404-48cb-b45a-ed70965a054a)
