### ISSUE TITLE
JDictSelectTag和字典相关的组件打包之后是空白的，本地运行可以，打包之后出不来，也没有报错

### ISSUE THREAD

**Issue by tangTingPC** [jeecgboot/JeecgBoot#7170]
##### 版本号：
vue3  v3.5.2

##### 问题描述：
JDictSelectTag和字典相关的组件打包之后是空白的，本地运行可以，打包之后出不来，也没有报错

##### 错误截图：
用法：
![lQLPJxsOj2QgZv_M3c0BmrB98rmdFKZF7gbAlD65sRsB_410_221](https://github.com/user-attachments/assets/b6a443fa-f3fd-4a0b-abd3-7388464dd997)

错误的:
![lQLPKdqjzLE9Yv_NA6nNB26wOAUHQN8gRyQGwELFHByjAA_1902_937](https://github.com/user-attachments/assets/f71b8d8d-5e85-46a9-96d3-17712e5603d2)

正确的：
![image](https://github.com/user-attachments/assets/1fa25779-29df-48ea-ac59-33b7e4b2a712)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
编码用法截图

**Comment by tangTingPC** [comment]
> 编码用法截图

可以帮我看看吗？

**Comment by zhangdaiscott** [comment]
看不出所以然，用最新版试试
