### ISSUE TITLE
JSelectPosition和JSelectUser等使用到useSelectBiz的组件，在传入值为多项时，初始化无法正常显示label值的问题解决

### ISSUE THREAD

**Issue by harriaHua** [jeecgboot/JeecgBoot#7171]
##### 错误截图：
![image](https://github.com/user-attachments/assets/60e20879-afb9-4599-a565-3ade03954d02)

##### 解决：
修改`src/components/Form/src/jeecg/hooks/useSelectBiz.ts`文件

``` javascript
      // params[props.rowKey] = selectValues['value'].join(',');
      params[`${props.rowKey}_MultiString`] = selectValues['value'].join(',');
```
恢复预期
![image](https://github.com/user-attachments/assets/ff4cd7a0-94cb-4bf6-b0ea-a4c57308df58)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
问题已修复，升级到最新版本试试
