### ISSUE TITLE
online生成器前端代码报错，无法展现出页面

### ISSUE THREAD

**Issue by keenanon** [jeecgboot/JeecgBoot#7172]
##### 错误截图：
<img width="1055" alt="屏幕截图 2024-09-04 164831" src="https://github.com/user-attachments/assets/96b354bf-6cb3-46cb-bb55-c373f9a3db51">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
应该是菜单配置错误

**Comment by keenanon** [comment]
这个是online创建单表那部分，没有去配置菜单，就直接用生成的sql去生成菜单

**Comment by keenanon** [comment]
菜单配置不是直接用生成的sql就可以么

**Comment by zhangdaiscott** [comment]
你前端代码放的位置对吗
