### ISSUE TITLE
在分组表头字段后面的列无法展示

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7173]
##### 问题描述：
使用分组表头组合字段，然后在分组表头之后的正常表头有部分不显示

##### 错误截图：
![1725516041627](https://github.com/user-attachments/assets/fc4d416e-62ad-4806-b864-af9ebfd546f1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
是因为滚动条？

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这种情况下需要设置width。
你按如下图进行修改试试
![image](https://github.com/user-attachments/assets/b59f2c41-32b5-452a-8dce-a41e2e17d331)

**Comment by ak-2019** [comment]
> 这种情况下需要设置width。 你按如下图进行修改试试 ![image](https://private-user-images.githubusercontent.com/8199499/366013679-b59f2c41-32b5-452a-8dce-a41e2e17d331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzQ0OTUsIm5iZiI6MTcyNjAzNDE5NSwicGF0aCI6Ii84MTk5NDk5LzM2NjAxMzY3OS1iNTlmMmM0MS0zMmI1LTQ1MmEtOGRjZS1hNDFlMmUxN2QzMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDU1NjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI5ZDMwZDY0ZmEwYWNlYTRiNjYwYzI5YWY3Mzk5M2NjOTY0ZWJhNDFmOWI0NDU3ZmFjMTNmYzM0NTYxOTAyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lAEXsHiCMTeWk6kHIyGe6JlWv1uA_VUY0xgUmBciUXQ)

感谢，加上width属性就解决了！

**Comment by sonembm** [comment]
你好，请问下分组的表头需要再添加什么参数吗？我的分组表头下的字段都无法显示，是还要设置什么参数吗
