### ISSUE TITLE
新建微服务模块上传文件后端无法接收

### ISSUE THREAD

**Issue by Haoman1** [jeecgboot/JeecgBoot#7175]
##### 版本号：
3.7.0_all

##### 问题描述：
使用微服务新建模块后，上传文件，file接收不到，但前端传了。如果把url改为jeecg自带的模块接收没有问题。是需要在新建的模块配置文件中配置什么吗？

##### 错误截图：
![1b1fa8464996f4bb7333354c89d8fb3](https://github.com/user-attachments/assets/e3b991c4-54d0-4280-858c-1a2567d36f11)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这种问题，你自己跟踪下会更好，看截图看不出来
