### ISSUE TITLE
JSearchSelect值显示错误

### ISSUE THREAD

**Issue by modefeng** [jeecgboot/JeecgBoot#7177]
##### 版本号：
3.6.3

##### 问题描述：
JSearchSelect组件内部监听 value的变化，并触发initSelectValue事件，如果我 通过defaultValue来给组件赋值默认值，在查看或者编辑页面，value事件就会触发2次，造成不必要的重复请求接口，并且initSelectValue的判断条件有问题，会导致，查看或者编辑页面，本来应该显示的是记录的值，但是错误的显示 为defaultValue 的值
##### 错误截图：
![image](https://github.com/user-attachments/assets/bbccd3a8-37f6-40d0-aeb6-e5eeb43e9d7b)
![image](https://github.com/user-attachments/assets/6c666b1b-8023-4951-9a53-982304d79460)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
升到最新版试试
