### ISSUE TITLE
xxl-job sas分支打开页面报错

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#7178]
##### 版本号：
3.6.4-SNAPSHOT

##### 问题描述：
启动cloud中的xxl-job，打开管理页面报错

##### 错误截图：

![@J0OPVSRZES2` JJ}{1R}I_tmb](https://github.com/user-attachments/assets/e084c137-00b1-4822-b260-54d7f5e3e195)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
老版本请自己分析，按道理这个后台是官方的不会出这种问题，看看是不是环境导致

**Comment by hsql** [comment]
1，试了master下载下来修改为适配springboot3，jdk17的，其他代码没动，也是这个问题,
2，重新下载了sas分支 3.7版本，应该是最新版本了，代码未做改动，仅仅改了数据库连接，打开页面也这个问题
