### ISSUE TITLE
lambdaUpdate方法触发修改操作，无法触发 mybatis拦截器（自动注入修改人、修改时间）

### ISSUE THREAD

**Issue by 578168089** [jeecgboot/JeecgBoot#7179]
##### 版本号：
3.0

##### 问题描述：
使用 lambdaUpdate方法触发修改操作，无法触发 mybatis拦截器（自动注入修改人、修改时间）

##### 错误截图：

![a951b5933a3da7146696bbecd414a073](https://github.com/user-attachments/assets/013349e5-80d5-4531-9f36-e6955670b733)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/87a09a51-4179-4c77-ac4d-8396740bc4af)
