### ISSUE TITLE
BasicTable属性canResize设置后，table表格没有达到出现竖向滚动条的时候，表格右侧会出来一个灰色竖条。

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7182]
##### 问题描述：
basicTable设置属性canResize为true后，table表格没有达到出现竖向滚动条的时候，表格右侧会出来一个灰色竖条，感觉像灰化不可操作的滚动条。官方演示网站也有同样的问题。

##### 错误截图：
![image](https://github.com/user-attachments/assets/f13b7e5b-611a-4590-848a-273bb07bef30)

![image](https://github.com/user-attachments/assets/9f6c21b9-4f7c-4024-84a0-491b51ab43e5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你的内容少，不足够出现滚动条

**Comment by ayerswu** [comment]
> 你的内容少，不足够出现滚动条

这里是内容少，不应该出现滚动条是对的，但是实际出现了滚动条阴影，看我画红框的地方。
