### ISSUE TITLE
select搜索bug

### ISSUE THREAD

**Issue by mysticdcat** [jeecgboot/JeecgBoot#7183]
##### `错误截图：`   
    label: "会员卡分类",
    field: 'cardTypeId',
    component: 'Select',
    componentProps: {
      showSearch: true,
      sync: false,/*  */
      options: [
        {
          label:"张三",
          value: 1
        },
        {
          label:"李四",
          value: 2
        }
      ]
    }

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by mysticdcat** [comment]
![image](https://github.com/user-attachments/assets/22123867-a10d-4c08-9e72-29e86a4eb9f4)
![image](https://github.com/user-attachments/assets/f043f8f7-ac98-418c-9f65-db4758e35892)

**Comment by zhangdaiscott** [comment]
sq

**Comment by mysticdcat** [comment]
怎么了，可以帮忙看看嘛

**Comment by lsqGitHub716** [comment]
你绑定的 component: 'Select',是antd vue官方的下拉选择组件，可以参考  https://next.antdv.com/components/select-cn/#components-select-demo-basic  去扩展适配你的需求
