### ISSUE TITLE
请问怎么修改BarAndLine组件中柱子的颜色？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7184]
##### 问题描述：
请问怎么修改BarAndLine组件中柱子的颜色、线条的颜色？

##### 错误截图：
![image](https://github.com/user-attachments/assets/52c8043b-54f1-487d-8f7a-a268a4626701)
![image](https://github.com/user-attachments/assets/07cc50ac-ca95-4167-823e-71a385b5b3ac)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by ak-2019** [comment]
> sq
不好意思，不太明白，是属性名吗
