### ISSUE TITLE
封装的nacos源码能放出来吗？

### ISSUE THREAD

**Issue by btoo7** [jeecgboot/JeecgBoot#7186]
##### 版本号：
v3.7.0

##### 问题描述：
封装的nacos 2.2.3源码能放出来吗？

##### 错误截图：
如题

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/nacos-dashboard
