### ISSUE TITLE
找不到打开其他用户修改密码权限的方式

### ISSUE THREAD

**Issue by 18784771** [jeecgboot/JeecgBoot#7187]
##### 版本号：
3.7.0_all

##### 问题描述：
找不到打开其他用户修改密码权限的方式

##### 错误截图：
![H NS}5NRSFOH2R60LHX2S6M](https://github.com/user-attachments/assets/a9f079f2-bd53-456b-9f28-8dd02223cb50)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
先通过角色给用户分配权限

**Comment by pangyaru** [comment]
> 先通过角色给用户分配权限

请问具体应该通过角色分配哪个页面才能让用户修改密码成功呢
