### ISSUE TITLE
关于jeecg-boot的一些思考，静待答复

### ISSUE THREAD

**Issue by FeiLi2319** [jeecgboot/JeecgBoot#7188]
##### 问题描述：
问题一：单体应用和微服务架构选型
 您好，
请问咱们服务单体应用和微服务架构的区别是什么？
主要区别除了在架构设计，可扩展性，维护性，技术栈的灵活性，业务解偶和部署方式以外，
使用微服务的优势有哪些？
什么情况下使用单体应用好？
什么情况下使用微服务好？

问题二：多租户实现方案
您好，
针对多租户的功能，
目前咱们是系统是通过租户id，
实现的逻辑数据隔离，
请问如果需要物理隔离，
咱们可以增加相应的的功能吗？
例如通过分库的方式进行租户的数据的物理隔离

问题三：不同系统如何快速集成？
如果jeecgboot需要和第三方系统集成，
像用户系统，鉴权系统，
多方系统的单点登录，
咱们平台有考虑过哪些方案吗？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
问题一：单体应用和微服务架构选型
追求简单和成本低就用单体
项目必须要求微服务就用微服务

问题二：多租户实现方案
默认是数据隔离，需要分库方案可以自己改造


问题三：不同系统如何快速集成？
二开实现，单点已经有现成成熟方案
