### ISSUE TITLE
接口请求缓存

### ISSUE THREAD

**Issue by mysticdcat** [jeecgboot/JeecgBoot#7189]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by mysticdcat** [comment]
请问下该怎么排查下问题吗， 掉的http://localhost:3100/jeecgboot/sys/login接口
![image](https://github.com/user-attachments/assets/13350ab8-bea8-42fa-ac35-a04a40b71105)
代理也已经改了，浏览器的缓存也已经清除掉了

**Comment by mysticdcat** [comment]
已经排查出来问题   vue3  不返回数据字典  不知道为什么这么设计

**Comment by zhangdaiscott** [comment]
啥意思

**Comment by zhangdaiscott** [comment]
vue3是单独的返回字段的接口，为了让登录接口变快，不然会因为字典导致登录接口慢
