### ISSUE TITLE
严重问题，数据误删除！！！online erp表单修改主表时，子表数据被全量删除

### ISSUE THREAD

**Issue by luoyeatm** [jeecgboot/JeecgBoot#7190]
##### 版本号：
3.6.3和3.7.0都试过

##### 问题描述：
 修改ERP表单的主表数据，**会触发子表的批量删除**（执行的是delete where in 语句），然后执行单个插入语句（执行的是 insert )，但是因为一页只有5条，所以插入语句也只执行了五条，导致有一张两万条数据的表只剩下五条。
![image](https://github.com/user-attachments/assets/bc49c8cb-a469-4298-9438-624414ba601d)
后续使用 binlog 恢复了数据，但这个问题确实很严重，为了确认不是我自己的代码影响，又下载了 3.7.0 测试了一遍，仍然如此，从六条数据变为了五条，所以ERP修改主表会触发子表的误删除

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布

**Comment by Alex-myl** [comment]
> ##### 版本号：
> 3.6.3和3.7.0都试过
> 
> ##### 问题描述：
> 修改ERP表单的主表数据，**会触发子表的批量删除**（执行的是delete where in 语句），然后执行单个插入语句（执行的是 insert )，但是因为一页只有5条，所以插入语句也只执行了五条，导致有一张两万条数据的表只剩下五条。 ![image](https://private-user-images.githubusercontent.com/46178130/365624448-bc49c8cb-a469-4298-9438-624414ba601d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NTU0MTksIm5iZiI6MTczNDY1NTExOSwicGF0aCI6Ii80NjE3ODEzMC8zNjU2MjQ0NDgtYmM0OWM4Y2ItYTQ2OS00Mjk4LTk0MzgtNjI0NDE0YmE2MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAwMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjOWQxMGFjZDdjZDU0MjcyYWU3YmViMjVhODE1OGNjMGUxYmJlNmM2MmJkYjUzMDFkYTc5NDNkYTJkMDlkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tiIpNdSJbwVYz2cTJ74becis6dgxpmTwLsiNLq_GOAU) 后续使用 binlog 恢复了数据，但这个问题确实很严重，为了确认不是我自己的代码影响，又下载了 3.7.0 测试了一遍，仍然如此，从六条数据变为了五条，所以ERP修改主表会触发子表的误删除
> 
> ##### 错误截图：
> #### 友情提示：
> * 未按格式要求发帖、描述过于简单的，会被直接删掉;
> * 描述问题请图文并茂，方便我们理解并快速定位问题;
> * 如果使用的不是master，请说明你使用的分支;

新版本还是存在这个问题

**Comment by Alex-myl** [comment]
> ##### 版本号：
> 3.6.3和3.7.0都试过
> 
> ##### 问题描述：
> 修改ERP表单的主表数据，**会触发子表的批量删除**（执行的是delete where in 语句），然后执行单个插入语句（执行的是 insert )，但是因为一页只有5条，所以插入语句也只执行了五条，导致有一张两万条数据的表只剩下五条。 ![image](https://private-user-images.githubusercontent.com/46178130/365624448-bc49c8cb-a469-4298-9438-624414ba601d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NTU0MTksIm5iZiI6MTczNDY1NTExOSwicGF0aCI6Ii80NjE3ODEzMC8zNjU2MjQ0NDgtYmM0OWM4Y2ItYTQ2OS00Mjk4LTk0MzgtNjI0NDE0YmE2MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAwMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjOWQxMGFjZDdjZDU0MjcyYWU3YmViMjVhODE1OGNjMGUxYmJlNmM2MmJkYjUzMDFkYTc5NDNkYTJkMDlkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tiIpNdSJbwVYz2cTJ74becis6dgxpmTwLsiNLq_GOAU) 后续使用 binlog 恢复了数据，但这个问题确实很严重，为了确认不是我自己的代码影响，又下载了 3.7.0 测试了一遍，仍然如此，从六条数据变为了五条，所以ERP修改主表会触发子表的误删除
> 
> ##### 错误截图：
> #### 友情提示：
> * 未按格式要求发帖、描述过于简单的，会被直接删掉;
> * 描述问题请图文并茂，方便我们理解并快速定位问题;
> * 如果使用的不是master，请说明你使用的分支;

新版本还是存在这个问题
