### ISSUE TITLE
上次提问可能没描述清楚，再重新描述下//BasicTable属性canResize设置后，table表格没有达到出现竖向滚动条的时候，表格右侧会出来一个灰色竖条。

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7191]
版本号：springboot3分之3.7.0
问题描述：
basicTable设置属性canResize为true后，table表格没有达到出现竖向滚动条的时候，表格右侧会出来一个灰色竖条，感觉像灰化不可操作的滚动条。官方演示网站也有同样的问题。

这里是内容少，不应该出现滚动条是对的，但是实际出现了滚动条阴影，看我画红框的地方。
===========================================================
上次答复如下：
你的内容少，不足够出现滚动条

这里是内容少，不应该出现滚动条是对的，但是实际出现了滚动条阴影，看我画红框的地方。
错误截图：
![image](https://github.com/user-attachments/assets/5cc458bd-6dc0-4af8-8ee3-9996cb14ef04)

![image](https://github.com/user-attachments/assets/36047bf0-58a6-4308-a5b1-ee95b54e7af0)

友情提示：
未按格式要求发帖、描述过于简单的，会被直接删掉;
描述问题请图文并茂，方便我们理解并快速定位问题;
如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个表格问题，设置了上下滚动就会出现这个条
