### ISSUE TITLE
下拉框更新导致其它文本框更新内容

### ISSUE THREAD

**Issue by wolfgithash** [jeecgboot/JeecgBoot#7194]
##### 版本号：

3.7.0_all
##### 问题描述：

online生成表单，无论是在线还是导出的代码，在新增或者修改时，如果页面中有下拉控件并点击下拉数据后，会同步更新第一个txt，比如标题框的内容。

##### 错误截图：

![image](https://github.com/user-attachments/assets/25683137-fbac-4b0c-94b7-4643122c34a5)
![image](https://github.com/user-attachments/assets/8b4da84e-8b14-4e18-9d79-94f615bf5a75)
![image](https://github.com/user-attachments/assets/4070855a-2b40-44b6-8907-5bedcdacd4d3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
怎么可能呢，除非你两个控件的字段key一样

**Comment by wolfgithash** [comment]
你要远程可以联系我微信，13551095495，别乱说，随便关闭bug,不是正确做事的态度。

**Comment by 1027555683** [comment]
我也遇到了，下拉框会把字段名称：title 的文本框 覆盖

<img width="762" height="595" alt="Image" src="https://github.com/user-attachments/assets/9d9be11a-28fd-431b-a2f9-18f79d84715e" />
