### ISSUE TITLE
前端pnpm安装失败（@commitlint/cli无法安装）

### ISSUE THREAD

**Issue by Wang-Yan-Jiao** [jeecgboot/JeecgBoot#7196]
##### 版本号：
3.7.0_all（发布日期：2024-06-23）

##### 问题描述：
node版本：20.15.0
pnpm版本：9.10.0

jeecgboot-vue3项目中，运行pnpm install命令无法安装完成依赖，疑似@commit/cli依赖无法正常安装。
若运行npm install也产生stylelint依赖系列版本不兼容问题。

##### 错误截图：
![image](https://github.com/user-attachments/assets/bb5dd794-47f3-4e53-bc67-17bcb0d2a892)

**Comment by zhangdaiscott** [comment]
网不好？

**Comment by Wang-Yan-Jiao** [comment]
> 网不好？

试过多次，原镜像源taobao，将镜像源修改为registry后报错问题与问题 [#7149](https://github.com/jeecgboot/JeecgBoot/issues/7149)类似，✈也一样
![image](https://github.com/user-attachments/assets/37c0b7fd-5ef4-4ccf-8281-aa1c1a4000af)

**Comment by Wang-Yan-Jiao** [comment]
去网上寻找教程，发现是pnpm与硬盘的关系，原文件在**exFat**移动硬盘上运行，pnpm似乎需要在**NTFS**硬盘上才可以运行，将项目移动到电脑硬盘上，再运行pnpm install后可正常操作

![image](https://github.com/user-attachments/assets/d7c11457-0da5-4a39-8141-3493eb4a4f36)

**Comment by zhangdaiscott** [comment]
厉害

**Comment by li-jia-nan** [comment]
厉害

**Comment by Magicdover** [comment]
怎么老是安装失败，明明网络没问题的。

**Comment by Wang-Yan-Jiao** [comment]
> 怎么老是安装失败，明明网络没问题的。

看下我的最后回复，安装项目的硬盘类型可以看下
