### ISSUE TITLE
生成的表单-可视区外主表字段校验问题

### ISSUE THREAD

**Issue by l964061682** [jeecgboot/JeecgBoot#7198]
##### 版本号：
3.7.0

##### 问题描述：
生成的表单，在分辨率低于1200*700情况下，提交时可视区外主表字段必填项，没有重新定位到可视区内

##### 错误截图：
点击提交
![image](https://github.com/user-attachments/assets/074a8908-0921-49c5-ae8d-81e21b75eace)
主表必填项未定位
![image](https://github.com/user-attachments/assets/db46b04f-7bcf-46dc-84bf-817a4ce967f0)
明细表必填项可以定位
![image](https://github.com/user-attachments/assets/2812d725-2f46-4f3f-ad20-c5ec652924ee)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
试试最新版，这块刚优化
