### ISSUE TITLE
泄露数据库表名信息- 子表获取数据失败:xxx

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7202]
##### 版本号：
3.7.0

##### 问题描述：
当主表的数据关联不上子表的任何数据时，查看详情会弹出tips 子表获取数据失败:xxx，直接暴漏了子表的名称，不是很安全，也不是很友好，能否直接把提示去掉

##### 错误截图：

![Screenshot](https://github.com/user-attachments/assets/1e286f7c-605b-4f7e-b19f-3bcfb97ccb66)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
Online还是代码生成？

**Comment by liuling1314** [comment]
> Online还是代码生成？

Online

**Comment by zhangdaiscott** [comment]
好

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
