### ISSUE TITLE
自动生成一对多表单代码中，省市区回显问题。

### ISSUE THREAD

**Issue by kevinchan1979** [jeecgboot/JeecgBoot#7203]
##### 版本号：
3.7.0

##### 问题描述：
在自动生成一对多erp表单时，BasicTable可以通过自定义回显插槽，把省市区代码转换成文字。

       <template v-slot:bodyCell="{ column, record, index, text }">
         <template v-if="column.dataIndex==='address'">
              
            <div>{{ getAreaTextByCode(text) }}</div>
         </template>
       </template>

但在生成一对多默认表单时，在BasicModal中没有在找到正确回显省市区代码的方法，请教一下如何修复这个问题。

##### 错误截图：

![微信截图_20240911235053](https://github.com/user-attachments/assets/8ba88025-6941-4fd3-aaaa-e71973ea3b38)
![微信截图_20240911235147](https://github.com/user-attachments/assets/ba4bafbb-805a-407c-bb5c-69a1784cf7dd)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
SQ

**Comment by 1298191366** [comment]
已修复，待新版本发布
