### ISSUE TITLE
用jeecg-uniapp 访问jeecg-boot（3.7.0）后台无法得到正确的token

### ISSUE THREAD

**Issue by arlien0818** [jeecgboot/JeecgBoot#7206]
##### 版本号：
jeecg-boot 后台 3.7.0
jeecg-uniapp 2.0

##### 问题描述：
我用jeecg-uniapp第一次登录进去之后 ，发现给了我一个 很怪的token:fdsafas。这个当然 不能用，于是我第二次再登录的时候登录不上了。

##### 错误截图：
![微信图片_20240912110242](https://github.com/user-attachments/assets/49773728-c0c5-443f-b694-3e5488ccac60)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现你说的问题，你是项目下载下来，登录就会出现这个问题吗？
