### ISSUE TITLE
导出失败，失败原因：操作失败，Cannot invoke "org.jeecg.modules.online.cgform.entity.OnlCgformHead.getId()" because "<local6>" is null

### ISSUE THREAD

**Issue by Fireskyunicorn** [jeecgboot/JeecgBoot#7207]
##### 问题描述：
使用Tab表风格进行联合查询后，导出功能失效
使用的是管理员账户，权限满足

##### 错误截图：
![image](https://github.com/user-attachments/assets/0b4d2d56-09c0-4807-92fa-f4c49885f1ee)
![image](https://github.com/user-attachments/assets/0c0b9ff9-18f4-44f3-b01d-e38615479903)
![image](https://github.com/user-attachments/assets/e9001f02-9a85-4421-8525-871b9bca4d36)
![image](https://github.com/user-attachments/assets/203c59ef-c225-443e-b5a3-404f5a7aebca)
![image](https://github.com/user-attachments/assets/47d45f62-f9bc-41be-a44e-08256f05fc24)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Fireskyunicorn** [comment]
使用的是tab联合查询

**Comment by zhangdaiscott** [comment]
cr

**Comment by Fireskyunicorn** [comment]
> jl

cr？插入？jl？记录？没懂什么意思，是还需要提供什么信息吗？

**Comment by Fireskyunicorn** [comment]
已经解决，原因：主表原本的附表有三个，现在仅有两个，少了一个附表，但系统认为还有三个，缺了一个参数，所以显示有内容空了
