### ISSUE TITLE
仪表盘无法读取URL参数

### ISSUE THREAD

**Issue by masterjyq** [jeecgboot/JeecgBoot#7208]
##### 问题描述：
积木仪表盘无法和积木报表一样从URL中读取参数到数据集

##### 错误截图：
![image](https://github.com/user-attachments/assets/adfd1415-5aa4-48c6-a898-a90033af9452)
![image](https://github.com/user-attachments/assets/e10e9c06-59e3-4e48-a917-580b6d3c93aa)
![image](https://github.com/user-attachments/assets/de031110-c559-4201-9f5f-a3f329e795ae)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by masterjyq** [comment]
> 你要干啥

我们想要通过URL转递变量给仪表盘，要把仪表盘嵌入到另一个系统

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
