### ISSUE TITLE
顶部左侧组合菜单

### ISSUE THREAD

**Issue by showfan** [jeecgboot/JeecgBoot#7209]
##### 问题描述：
在线演示系统中，项目配置 - 界面设置 - 顶部左侧组合菜单，打开选项后正常，关闭选项后，一级菜单没有还原。

##### 错误截图：

![image](https://github.com/user-attachments/assets/24aec922-525a-4a0b-8904-228c0f2d74a6)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可按如下图进行修改：
在 src/layouts/default/menu/useLayoutMenu.ts 文件
![image](https://github.com/user-attachments/assets/82a8573a-c8bb-41d2-a310-9b8fb05e9e94)
