### ISSUE TITLE
xxljob配置文件中的注册端口不生效

### ISSUE THREAD

**Issue by wyzltl** [jeecgboot/JeecgBoot#7210]
##### 版本号：
3.7.0

##### 问题描述：
在xxljob配置文件中配置的端口为8888，但是xxljob向admin注册的端口是10001，配置文件中改成其他端口但是注册的端口一直是10001

##### 错误截图：
![c8d5dfd0371fc874a292c64af210811c](https://github.com/user-attachments/assets/b6a569bc-38d3-4605-b433-cbb98bd5add2)

![93643778ef45a359840b68e3e3da7af3](https://github.com/user-attachments/assets/c5de3124-0753-4f5c-be81-06774f6a03ef)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
![image](https://github.com/user-attachments/assets/a2282b58-ea1d-4353-bab2-710cd42721df)

**Comment by wyzltl** [comment]
我是在jeecgboot框架用的jeecg-boot-starter-job包，不是直接运行xxljob源码
![1726279624024](https://github.com/user-attachments/assets/9fc2c85f-ac68-471e-8490-c10b282bfc28)
