### ISSUE TITLE
重要！online表单中建立视图后，无法对视图中的数据进行删除操作

### ISSUE THREAD

**Issue by ltt1987** [jeecgboot/JeecgBoot#7211]
##### 问题描述：
1、新建主表ltt001
2、新建附表s1
3、给主表建立视图ltt001$1
4、修改附表s1的外键为ltt001$1表
5、进入主表视图ltt001$1功能测试，添加、编辑功能正常，删除时提示找不到表对象t1$1

通过代码跟踪，发现有一行获取TableName的方法获得的是ltt001$1视图名称，带有$1字样，然后直接带入SQL进行查询，最终导致了报错，建议对名称进行处理，剔除掉视图标识$xx。

详细错误信息：
```
删除失败, ### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Table 'jeecgbootnew.ltt001$1' doesn't exist ### The error may exist in org/jeecg/modules/online/cgform/mapper/OnlCgformFieldMapper.java (best guess) ### The error may involve org.jeecg.modules.online.cgform.mapper.OnlCgformFieldMapper.doSelect-Inline ### The error occurred while setting parameters ### SQL: SELECT name, create_by, sys_org_code, create_time, id, update_time, update_by FROM ltt001$1 WHERE (id = ?) ### Cause: java.sql.SQLSyntaxErrorException: Table 'jeecgbootnew.ltt001$1' doesn't exist ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'jeecgbootnew.ltt001$1' doesn't exist
```

##### 错误截图：
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/89f679aa-42bc-4c09-8925-5d853b558f69">
<img width="2556" alt="image" src="https://github.com/user-attachments/assets/df06bdf0-3a6e-4da1-8507-93e2eb420921">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
试试最新版好了吗

jl

**Comment by sjlei** [comment]
> 4、修改附表s1的外键为ltt001$1表

不支持将附表的外键设置为主表的视图，请设置为主表表名
