### ISSUE TITLE
getForm()中的setFieldsValue()方法无法给RangePicker设置值

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7212]
##### 问题描述：
`BasicTable`中的查询条件，无法使用`setFieldsValue()`方法给`RangePicker`类型的字段设置值。`Input`类型的字段能正常赋值

##### 错误截图：
`const {setFieldsValue} = getForm();`
 `setFieldsValue({plnbez: '123456', getri: '2024-12-01', getri_begin: '2024-12-01',  getri_end: '2024-12-01'});`
![1726136870158](https://github.com/user-attachments/assets/5c3e82d4-f84d-4b40-84c8-9102adb5abed)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by ak-2019** [comment]
感谢！解决了
