### ISSUE TITLE
打包后请求路径不执行配置在.env.prod的VITE_GLOB_DOMAIN_URL 而是请求当前部署前端url 

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/JeecgBoot#7213]
##### 问题描述：
假设xxx.com是后端请求域名 XXXadmin.com是后台管理页访问路径 那么配置在.env.prod的VITE_GLOB_DOMAIN_URL 是https://xxx.com
但是实际部署后请求的后端路径是和后台管理页 也就是XXXadmin.com是相同的

##### 错误截图：
图一：定义在.env.prod的VITE_GLOB_DOMAIN_URL 接口请求路径
![image](https://github.com/user-attachments/assets/3e6f6b99-5ac0-4308-89e6-4ed5bda2f308)
图二：部署到线上的后台URL
![image](https://github.com/user-attachments/assets/bb09100b-d889-4d07-8da6-45e801abc222)
图三：部署后请求的路径
![image](https://github.com/user-attachments/assets/2edac0f2-3a01-4a4b-bce0-658ca8dbf6d7)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
VITE_GLOB_DOMAIN_URL  配置的是后台接口地址

**Comment by cym1231** [comment]
> VITE_GLOB_DOMAIN_URL 配置的是后台接口地址

哥我当然知道 但是奇怪的地方就是VITE_GLOB_DOMAIN_URL 配置的是https://xxxadmin.com/jeecgbot  但是实际请求的是后台页面的域名 https://xxx.com/jeecgbot

**Comment by cxhello** [comment]
@cym1231 我看了下这块代码，可能是代理走了两块逻辑，一块走的是VITE_GLOB_DOMAIN_URL，还有的地方走的是VITE_GLOB_API_URL
