### ISSUE TITLE
BasicTable的表单重置，应该在哪儿restFileds 呢？

### ISSUE THREAD

**Issue by fenghenqing** [jeecgboot/JeecgBoot#7218]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你关闭弹窗，销毁model不就行了
