### ISSUE TITLE
BasicTable组件ifShow和auth不支持Fn

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/JeecgBoot#7219]
##### 错误截图：
![image](https://github.com/user-attachments/assets/930e396f-c95e-48c6-8417-03d6aeb40889)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yang-xianzhu** [comment]
`ifShow`不是支持function么

**Comment by RacingK93** [comment]
> `ifShow`不是支持function么

auth不支持

**Comment by yang-xianzhu** [comment]
我觉得anth本来设计就是如此，如果要函数ifShow完全够用

**Comment by RacingK93** [comment]
> 我觉得anth本来设计就是如此，如果要函数ifShow完全够用

也行
