### ISSUE TITLE
各位大佬帮帮忙，我为什么部署JeecgBoot 完成后积木报表设计和仪表盘设计器不能打开啊

### ISSUE THREAD

**Issue by zq8822005** [jeecgboot/JeecgBoot#7220]
##### 版本号：
3.7.1

##### 问题描述：

部署JeecgBoot 完成后积木报表设计和仪表盘设计器不能打开啊

##### 错误截图：
积木报表设计提示http://localhost:8080/jeecg-boot/jmreport/list?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY1MDY3OTAsInVzZXJuYW1lIjoiYWRtaW4ifQ.-XISQNSbCwANWDgJFTKWmW6FT4tC-Ac2KBN8ZKdtE7w

仪表盘设计器提示
http://localhost:8080/jeecg-boot/drag/list?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY1MDY3OTAsInVzZXJuYW1lIjoiYWRtaW4ifQ.-XISQNSbCwANWDgJFTKWmW6FT4tC-Ac2KBN8ZKdtE7w&tenantId=1000

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你发这样的问题，让我们猜？

**Comment by zq8822005** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zq8822005** [comment]
不好意思刚半天加不上图片
![3DBA51BB74D73589C3FBDA7E5D531FEA](https://github.com/user-attachments/assets/fbd2b3e3-7bf1-499e-afc0-e686a6379146)
这是能正常打开的系统
![1726281755753](https://github.com/user-attachments/assets/97866910-2e5a-437e-aed7-b78d351ba944)
![1726281755770](https://github.com/user-attachments/assets/20f16f0b-c59a-4fa5-bb5c-7b5233a515ea)
这两个是打开后积木报表和仪表盘

**Comment by zq8822005** [comment]
![1726282211889](https://github.com/user-attachments/assets/39d2cc5d-344b-4b4d-adb7-38dbc3b6cde3)
这个是执行前台情况
