### ISSUE TITLE
使用部门选择用户（JSelectUserByDept）用户被删除后回显的问题

### ISSUE THREAD

**Issue by sltjsj** [jeecgboot/JeecgBoot#7221]
##### 版本号：
jeecgboot-vue3 3.6.3

##### 问题描述：

使用部门选择用户 JSelectUserByDept，已选中的某用户被冻结，组件回显的是id，组件所在表中存储有id，name等信息，需求：组件回显用表中存储的用户name，再次选择时将冻结用户在组件中删除，求解答

##### 错误截图：

![image](https://github.com/user-attachments/assets/d8435142-474e-4545-8e64-6c78d939cc0f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
WS

**Comment by 1298191366** [comment]
这个需要您自己个性化进行修改，有的需求是确定的时候不想冲掉的旧数据
修改代码参考位置：`JSelectUserByDept`选中回调的时候将冻结的用户过滤掉即可
![image](https://github.com/user-attachments/assets/97644b89-c57b-4297-ad9c-fb7532740a34)
