### ISSUE TITLE
页面长时间不操作再回来切换菜单无法切换成功，控制台报错

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/JeecgBoot#7222]
##### 问题描述：
系统如果过个一小时这种长时间不操作然后回来操作切换菜单控制台就会报错，并且页面是无法切换成功的；

usePage.ts:45 ReferenceError: Cannot access 'i18n' before initialization
    at useI18n (useI18n.ts:33:3)
    at Axios.ts:28:15

![image](https://github.com/user-attachments/assets/6a884e42-45dc-4e3a-bc77-23ec6f3cddf5)

##### 错误截图：
![image](https://github.com/user-attachments/assets/6a884e42-45dc-4e3a-bc77-23ec6f3cddf5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
提供错误日志截图

**Comment by RacingK93** [comment]
> 提供错误日志截图

![image](https://github.com/user-attachments/assets/35d8f1dc-0abf-44a6-bb9a-1b291353e71a)

**Comment by liaozhiyang** [comment]
升级版本试试，v3.7.1上测试无此问题。
