### ISSUE TITLE
jvxetable分组表头后，分组的字段无法显示

### ISSUE THREAD

**Issue by sonembm** [jeecgboot/JeecgBoot#7223]
##### 问题描述：使用jvxetable的分组表头，数据无法显示。只能显示没有分组的字段
字段配置
![image](https://github.com/user-attachments/assets/e7eee5dc-bfcf-439e-bf36-ccc3359b2a4b)

##### 错误截图：
实际效果
![QQ截图20240914113357](https://github.com/user-attachments/assets/e8aeff57-4b89-4583-b0cb-e008ccbd6929)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ws

**Comment by sjlei** [comment]
问题已修复，下版本发布
