### ISSUE TITLE
部署JeecgBoot 完成后积木报表设计和仪表盘设计器不能打开啊

### ISSUE THREAD

**Issue by zq8822005** [jeecgboot/JeecgBoot#7224]
版本号：
3.7.1

问题描述：
部署JeecgBoot 完成后积木报表设计和仪表盘设计器不能打开啊
![3DBA51BB74D73589C3FBDA7E5D531FEA](https://github.com/user-attachments/assets/95c4850c-83a8-4583-9fd9-028631a860ec)

错误截图：
积木报表设计提示http://localhost:8080/jeecg-boot/jmreport/list?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY1MDY3OTAsInVzZXJuYW1lIjoiYWRtaW4ifQ.-XISQNSbCwANWDgJFTKWmW6FT4tC-Ac2KBN8ZKdtE7w
![1726281755753](https://github.com/user-attachments/assets/a912d4ba-5aa3-460c-bf2b-e36264ded3cc)

仪表盘设计器提示
http://localhost:8080/jeecg-boot/drag/list?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY1MDY3OTAsInVzZXJuYW1lIjoiYWRtaW4ifQ.-XISQNSbCwANWDgJFTKWmW6FT4tC-Ac2KBN8ZKdtE7w&tenantId=1000
![1726281755770](https://github.com/user-attachments/assets/f38cdaef-a853-4767-9751-fcfb9ae7244f)
前端启动后的情况
![1726282211889](https://github.com/user-attachments/assets/edff8489-9b2a-4898-a126-7727c2954a12)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
原始代码和原始库什么也没改？
确认下依赖是否下载成功

**Comment by zq8822005** [comment]
> 原始代码和原始库都没改
> 都删了下，下了删了两次依赖下载成功了，要不然也不会前台启动了，只有这两个启动不了
> 

发自我的iPhone

**Comment by zhangdaiscott** [comment]
本地还是服务器

**Comment by zq8822005** [comment]
本地部署

**Comment by zhangdaiscott** [comment]
本地就不知道了

**Comment by zq8822005** [comment]
本地和服务器有什么区别

发自我的iPhone

**Comment by zhangdaiscott** [comment]
无法重新，如果可以提供重现步骤，请在发

**Comment by zq8822005** [comment]
不用了，我找到问题了，在其他机子安装好了，是pnpm 安装的问题，确切地说是服务器问题，换了源就可以了

发自我的iPhone
