### ISSUE TITLE
【3.7.1】菜单管理 - 会出现滚动区域底部部分数据 多选框无法渲染的情况的

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7225]
##### 版本号：
3.7.1

##### 问题描述：

菜单管理 - 会出现滚动区域底部部分数据 多选框无法渲染的情况的

##### 错误截图：
![image](https://github.com/user-attachments/assets/0b7680ea-c185-4dc7-8ade-cd738fbea6b2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
如何重现？

**Comment by liaozhiyang** [comment]
经测试，无法复现。
请问是在什么情况下出现的？可[ 官网 ](http://boot3.jeecg.com/)上试试
![iShot_2024-09-23_10 05 32](https://github.com/user-attachments/assets/184d15c6-841b-4744-a89d-5a77d6e63b29)

**Comment by benben120** [comment]
> 经测试，无法复现。 请问是在什么情况下出现的？可[ 官网 ](http://boot3.jeecg.com/)上试试 ![iShot_2024-09-23_10 05 32](https://private-user-images.githubusercontent.com/8199499/369735588-184d15c6-841b-4744-a89d-5a77d6e63b29.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzc2MTIsIm5iZiI6MTcyNzU3NzMxMiwicGF0aCI6Ii84MTk5NDk5LzM2OTczNTU4OC0xODRkMTVjNi04NDFiLTQ3NDQtYTg5ZC01YTc3ZDZlNjNiMjkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDIzNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZDljMzM1MzI4ZWJhNmQ1ZDQ4Zjk4OWYzNzlkNDUyNDA4YTRjMjFhNGQxM2M2YzM4N2VlYWYyODczMTlkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wVA8ca3882wXYqpNNq7rg7u7hWOdniPql2GqTSdvaQQ) [ ![iShot_2024-09-23_10 05 32](https://private-user-images.githubusercontent.com/8199499/369735588-184d15c6-841b-4744-a89d-5a77d6e63b29.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzc2MTIsIm5iZiI6MTcyNzU3NzMxMiwicGF0aCI6Ii84MTk5NDk5LzM2OTczNTU4OC0xODRkMTVjNi04NDFiLTQ3NDQtYTg5ZC01YTc3ZDZlNjNiMjkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDIzNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZDljMzM1MzI4ZWJhNmQ1ZDQ4Zjk4OWYzNzlkNDUyNDA4YTRjMjFhNGQxM2M2YzM4N2VlYWYyODczMTlkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wVA8ca3882wXYqpNNq7rg7u7hWOdniPql2GqTSdvaQQ) ](https://private-user-images.githubusercontent.com/8199499/369735588-184d15c6-841b-4744-a89d-5a77d6e63b29.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzc2MTIsIm5iZiI6MTcyNzU3NzMxMiwicGF0aCI6Ii84MTk5NDk5LzM2OTczNTU4OC0xODRkMTVjNi04NDFiLTQ3NDQtYTg5ZC01YTc3ZDZlNjNiMjkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDIzNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZDljMzM1MzI4ZWJhNmQ1ZDQ4Zjk4OWYzNzlkNDUyNDA4YTRjMjFhNGQxM2M2YzM4N2VlYWYyODczMTlkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wVA8ca3882wXYqpNNq7rg7u7hWOdniPql2GqTSdvaQQ) [ ](https://private-user-images.githubusercontent.com/8199499/369735588-184d15c6-841b-4744-a89d-5a77d6e63b29.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzc2MTIsIm5iZiI6MTcyNzU3NzMxMiwicGF0aCI6Ii84MTk5NDk5LzM2OTczNTU4OC0xODRkMTVjNi04NDFiLTQ3NDQtYTg5ZC01YTc3ZDZlNjNiMjkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDIzNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZDljMzM1MzI4ZWJhNmQ1ZDQ4Zjk4OWYzNzlkNDUyNDA4YTRjMjFhNGQxM2M2YzM4N2VlYWYyODczMTlkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wVA8ca3882wXYqpNNq7rg7u7hWOdniPql2GqTSdvaQQ)

![image](https://github.com/user-attachments/assets/a9077ae5-e49e-4c7e-a193-8e39ccb9052f)
useListPage.ts增加 scroll属性定义表格滚动高度 时候 会出现这个问题

**Comment by benben120** [comment]
> 如何重现？
useListPage.ts增加 scroll属性定义表格滚动高度 时候 会出现这个问题
