### ISSUE TITLE
导出多层嵌套数据，二层以上无法获取数据

### ISSUE THREAD

**Issue by shuixiazhimu** [jeecgboot/JeecgBoot#7227]
##### 版本号：

3.4.3
##### 问题描述：

导出多层嵌套数据，二层以上无法获取数据，返回实体类类型

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
描述太简单
