### ISSUE TITLE
严重错误！！！导入excel文件后端报错

### ISSUE THREAD

**Issue by 3099749306** [jeecgboot/JeecgBoot#7228]
##### 版本号：
3.7.0

##### 问题描述：
按照框架的导入方法，上传excel文件，后端报错。

##### 错误截图：
![image](https://github.com/user-attachments/assets/1ab54211-b23e-4b10-9253-c7888605dfb0)
![image](https://github.com/user-attachments/assets/94c707ab-ddfd-46fb-bae9-a3ea235fe98e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
可以百度下错误看看
