### ISSUE TITLE
死循环 404 /swagger-ui/null/swagger-resources/configuration/ui

### ISSUE THREAD

**Issue by rehmetjan** [jeecgboot/JeecgBoot#7229]
##### 版本号：

3.7.0
##### 问题描述：

死循环 GET 404 /swagger-ui/null/swagger-resources/configuration/ui
##### 错误截图：

![image](https://github.com/user-attachments/assets/28c802c2-7df3-4c81-a431-768602b89e05)

**Comment by zhangdaiscott** [comment]
没明白

**Comment by rehmetjan** [comment]
就是不停的发送这个请求 /swagger-ui/null/swagger-resources/configuration/ui

**Comment by zhangdaiscott** [comment]
谁发？

**Comment by rehmetjan** [comment]
跟这个issue一样，[https://github.com/springfox/springfox/issues/2907](https://github.com/springfox/springfox/issues/2907)

**Comment by zhangdaiscott** [comment]
重现步骤？

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/e812fa3e-648b-46c1-b6f0-260b234c3f73)
