### ISSUE TITLE
高德地图key是不是过期了？

### ISSUE THREAD

**Issue by beekim123** [jeecgboot/JeecgBoot#7230]
##### 版本号：
1.2.0

##### 问题描述：

 const A_MAP_URL = 'https://webapi.amap.com/maps?v=2.0&key=06313eb9c6563b674a8fd789db0692c3';
用的就是源代码中这个key

##### 错误截图：

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/7690e33d-e92a-42ca-abb4-7bfcb3967976">

**Comment by zhangdaiscott** [comment]
？

**Comment by beekim123** [comment]
> ？

这个key好像不太稳定，我提问题那天是早上不行，中午可以，下午又不行，18点左右又可以了。
9.23我看又不行了

我自己去高德注册的key可以加载地图
<img width="1819" alt="image" src="https://github.com/user-attachments/assets/e0c8e4dd-eb35-415d-adde-1c78262acd96">

源码中的key加载不了
<img width="1964" alt="image" src="https://github.com/user-attachments/assets/c2dd8773-ca66-46ed-bd29-3caab8373b85">

**Comment by beekim123** [comment]
<img width="1960" alt="image" src="https://github.com/user-attachments/assets/a2c51fac-4dee-4b14-a655-25d3638b9b93">
过了一会我再试，又可以了

**Comment by beekim123** [comment]
> 那个功能

源码中是这个，官方演示中早些版本有地图演示，现在好像隐藏了。
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/fd1bc189-b9e8-4108-9ecc-a08db7b012cb">

**Comment by zhangdaiscott** [comment]
早去掉了，自己申请key吧，现在高德开始收费了

**Comment by beekim123** [comment]
> 早去掉了，自己申请key吧，现在高德开始收费了

好的好的
