### ISSUE TITLE
jeecg jvxTable组件内custom-config设置问题

### ISSUE THREAD

**Issue by duxin14436106** [jeecgboot/JeecgBoot#7235]
##### 版本号：
 "name": "jeecgboot-vue3",
  "version": "3.6.2",

"vxe-table": "4.5.17",
 "vxe-table-plugin-antd": "3.1.0",

##### 问题描述：
1、默认配置下，点击某一列固定，出现翻译问题。比如第一列是select类型，第二列是文本框类型，点击第二列固定。第二列会更新到第一个位置，这个时候第一列的select类型的显示在原本的第二列。但是这个时候select配置的字典值为1 而非文字
2、希望能开启列拖拽的功能，但是没有参数可以控制自定义的问题

##### 错误截图：

![image](https://github.com/user-attachments/assets/6edd76da-3ba8-41a3-8cf2-02003bfeb28c)
![image](https://github.com/user-attachments/assets/e056ebf1-176f-4bd5-8249-52dd2e311755)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by jeecgDeveloper** [comment]
没有复现该问题

关于自定义列请查看 [JVXETable 官方文档](https://help.jeecg.com/component/JVxeTable.html#:~:text=%E7%BC%93%E5%AD%98%E5%86%B2%E7%AA%81%EF%BC%89-,custom,-boolean)  进行配置

关于拖拽列宽度，仅需要传递 `resizable` 参数即可
