### ISSUE TITLE
浏览器tab上的logo怎么去不掉呢？

### ISSUE THREAD

**Issue by TingGeMeiPinWei** [jeecgboot/JeecgBoot#7239]
##### 版本号：
2.4.6

##### 问题描述：
项目在浏览器tab上的logo怎么去不掉呢？

##### 错误截图：
![image](https://github.com/user-attachments/assets/afb331cd-e1c4-4bec-a2cd-b77e3aba4c46)
![image](https://github.com/user-attachments/assets/e290583b-04e8-41cc-be80-2fd35c46f49e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Lctiv** [comment]
官方就是不想给你去掉，去掉要收费的

**Comment by zhangdaiscott** [comment]
自己随便改
