### ISSUE TITLE
v3.7.1全面兼容Java 21吗

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/JeecgBoot#7241]
##### 版本号：
v3.7.1

##### 问题描述：

v3.7.1全面兼容Java 21吗

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
目前不支持，得后面升级
现在springcloud alibaba 还没完全兼容jdk21,得等

**Comment by softboy99** [comment]
[2023.0.0.0-RC1](https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2023.0.0.0-RC1)
springcloud alibaba从2023.0.0.0-RC1开始就支持jdk21了
