### ISSUE TITLE
jeecg 3.5.3版本，jdk升级为17后，启动报错

### ISSUE THREAD

**Issue by Guochanglin-gcl** [jeecgboot/JeecgBoot#7242]
##### 版本号：
3.5.3

##### 问题描述：
将jdk1.8升级为17后，加入spring ai依赖，启动报错  Failed to process import candidates for configuration class [org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration]; nested exception is java.lang.TypeNotPresentException: Type org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration not present

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Guochanglin-gcl** [comment]
![image](https://github.com/user-attachments/assets/0341c7f0-3372-406c-b19b-7f9b27135da8)
![Uploading 报错.png…]()

**Comment by zhangdaiscott** [comment]
3.5.3不清楚，最新版3.7肯定没问题

**Comment by Guochanglin-gcl** [comment]
> 3.5.3不清楚，最新版3.7肯定没问题

3.7.1行不
