### ISSUE TITLE
企业微信同步后台报错退出

### ISSUE THREAD

**Issue by wang420520** [jeecgboot/JeecgBoot#7243]
##### 版本号：
3.7.1

##### 问题描述：

第三方配置，配置完企业微信参数后，点同步，报错，后台退出

##### 错误截图：
ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:55 - 企业微信下没查询到用户！
![11](https://github.com/user-attachments/assets/55c55b21-7e60-42e3-86dd-4911fdcd597f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
请查看错误日志，这个地方是不是ip没有在白名单里面？ip在日志后面有显示
![image](https://github.com/user-attachments/assets/fda6ae91-0337-4559-a66c-7c784c50f32b)


![image](https://github.com/user-attachments/assets/30037355-c3c7-4d07-8e7d-ab6a33acbd51)

同步成功示意图
![image](https://github.com/user-attachments/assets/2b63f703-57c2-4597-a3db-b83e8dc49e52)
