### ISSUE TITLE
jeecg boot 3.7.1版本， 启动systemCloudApplication报错

### ISSUE THREAD

**Issue by Guochanglin-gcl** [jeecgboot/JeecgBoot#7247]
##### 版本号：
jeecg boot 3.7.1，  springboot 2.7.10

##### 问题描述：

SystemCloudApplicatiuon启动报错 说Type org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration not present，网上查资料说加上web依赖但是加上了也不行，后来朋友说RestClient属于springboot3.2.X 版本里的，但是jeecgboot不是没有springboo3.2.X 版本嘛，实在不知道怎么解决了，这个问题已经2天了，希望官方大大协助解决，JDK使用的是17，springboot 2.7.10，谢谢！

##### 错误截图：

![image](https://github.com/user-attachments/assets/64954e23-f802-4caa-9ac5-c8c46f73c23d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
 - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
使用的是jeecgboot默认代码还是自己改过什么

**Comment by Guochanglin-gcl** [comment]
> 使用的是jeecgboot默认代码还是自己改过什么

默认代码，业务代码是自己写的，加入spring Ai依赖后写了个测试接口，然后重启服务 就报这个错误了

**Comment by zhangdaiscott** [comment]
spring ai需要springboot3架构，不支持

**Comment by Guochanglin-gcl** [comment]
> spring ai需要springboot3架构，不支持

咱们jeecgboot3.7.1支持springboot3版本吗老师

**Comment by Guochanglin-gcl** [comment]
> spring ai需要springboot3架构，不支持
咱们jeecgboot3.7.1支持springboot3版本吗老师
