### ISSUE TITLE
【重大BUG】顶部混合导航改为侧边栏，一级菜单丢失

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/JeecgBoot#7248]
##### 问题描述：
顶部混合导航改为侧边栏，一级菜单丢失

##### 错误截图：
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/f2d07171-d2f8-46b5-9cca-81b6017ca668">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
已经修复会尽快发布
