### ISSUE TITLE
【优化】每次刷新loading加载太慢太慢

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/JeecgBoot#7249]
##### 问题描述：
每次刷新loading加载太慢太慢【不是说首次】， 随便一个VUE2项目， 或者其他基于vben的项目，都很快

##### 错误截图：
<img width="765" alt="image" src="https://github.com/user-attachments/assets/fdcec81e-2c8d-4951-ad18-157bad475794">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
多慢？

**Comment by ayerswu** [comment]
> vben是静态页面，jeecg调用后台接口加载数据，不可能要求完全一样

jeecg页面加载通通过F12查看，加载的资源数量和大小都比较大，导致F5刷新或者第一次打开会非常慢，不知道这个有没有优化方案？

**Comment by zhangdaiscott** [comment]
zy

**Comment by yang-xianzhu** [comment]
上到生产会快一些，因为很多依赖都只是在开发场景用到，开发环境是有一点慢

**Comment by liaozhiyang** [comment]
二刷效果：
![iShot_2024-10-08_17 13 53](https://github.com/user-attachments/assets/eb848417-7b01-4869-bdf4-74f989100093)

二刷基本秒开和其他的并无差别，因为js都被浏览器缓存了，首次进入确实相对前面几个网站会慢点（JeecgBoot包含的功能相对丰富些引入的依赖和封装组件会多些）。
首次慢的原因有：
1.封装的组件多些 （src/components/Form/src/componentMap.ts）
2.引入了 vxetable 及相关自己封装的组件 （src/settings/registerThirdComp.ts）
3.为了业务中不频繁引入便捷操作，antd组件一开始就全局加载了 （src/components/registerGlobComp.ts）
4.打包的目标是es2015（vite.config.ts）

可从这几方面根据自己的业务场景进行调整，为了不影响业务及其他人暂不对这块进行调整。
