### ISSUE TITLE
【BUG】自动锁屏输入9999999无法解锁

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/JeecgBoot#7250]
##### 问题描述：
没点击锁屏，没设置密码，当自动锁屏直接输入999999然后自动就锁住了，且再次登录还是锁住，清理浏览器缓存无效

##### 错误截图：

<img width="352" alt="image" src="https://github.com/user-attachments/assets/0022dc04-dff1-4513-8fcf-dd9f54944f13">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。

你本地可按如下修复：

src/utils/cache/persistent.ts
![image](https://github.com/user-attachments/assets/7428247c-8175-4713-9065-150e27445701)

src/layouts/default/setting/components/InputNumberItem.vue :
![image](https://github.com/user-attachments/assets/ed266206-628d-4abf-94eb-eb05fd068475)


1.输入需要做限制，setTimeout最大支持2^31-1，超过这个就会立马执行，所以当你输入999999时就会立马锁屏。
2.再次登录还是锁屏，是因为有些localStorage没被清除。
