### ISSUE TITLE
super-query高级查询构造里面，不支持常用的不模糊包含等条件

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7252]
##### 版本号：
3.7.0_all

##### 问题描述：
高级查询构造里面，不支持常用的如下选项
 NOT_LIKE("NOT_LIKE","not_like","不模糊包含"),
 /**查询规则 不以…结尾*/
 NOT_LEFT_LIKE("NOT_LEFT_LIKE","not_left_like","不以…结尾"),
 /**查询规则 不以…开头*/
 NOT_RIGHT_LIKE("NOT_RIGHT_LIKE","not_right_like","不以…开头"),

我看后台是有这个枚举的，但是前台选不到这个选项，这个组件没有开源，自己也改不了。请问有版本支持计划吗？

##### 错误截图：

![image](https://github.com/user-attachments/assets/c7b481af-f7bd-4625-9408-d54312ea57f5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
等于不就是不模糊？

**Comment by ayerswu** [comment]
> 等于不就是不模糊？

我描述的不准确，不好意思，我的意思是模糊不包含，既NOT_LIKE， NOT_LEFT_LIKE，NOT_RIGHT_LIKE这些选项

**Comment by zhangdaiscott** [comment]
未打算支持
