### ISSUE TITLE
如何实现字段自动显示当前部门名称？

### ISSUE THREAD

**Issue by suminchina** [jeecgboot/JeecgBoot#7253]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你使用部门控件，设置了默认值，不是可以自动翻译吗

**Comment by suminchina** [comment]
> 你使用部门控件，设置了默认值，不是可以自动翻译吗

我看教程中https://help.jeecg.com/java/online/form/comp/expression.html，只有sysOrgCode：当前登录用户的部门编号，这种，没有部门名称的变量，所以请教下怎么实现？

**Comment by zhangdaiscott** [comment]
你可以自己扩展
