### ISSUE TITLE
菜单管理 BasicTable组件设置默认展开不生效

### ISSUE THREAD

**Issue by pingsanddoss** [jeecgboot/JeecgBoot#7254]
版本号：3.7.1
前端版本：vue3版
问题描述：菜单管理 BasicTable组件设置默认展开不生效；
截图&代码：
![image](https://github.com/user-attachments/assets/a9b5923b-485d-4015-aa87-6760760bf392)
![image](https://github.com/user-attachments/assets/c4837913-3984-443c-96ee-001b97b358b0)

友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by pingsanddoss** [comment]
看了一下vben官网，defaultExpandAllRows、defaultExpandedRowKeys 属性在 basicTable 中不受支持，并且在antv table v2.2.0 之后也被移除。

**Comment by liaozhiyang** [comment]
静态数据是可以的（即渲染前就数据就存在），动态数据不行（即先渲染后给数据）
![image](https://github.com/user-attachments/assets/84ac7063-89c3-42d4-ae55-f41fd307433e)

动态数据可以在得到数据之后通过 expandAll() 方法得到你想要的结果
![image](https://github.com/user-attachments/assets/516b4ceb-a34b-43fb-b6d8-883fd9192420)

**Comment by pingsanddoss** [comment]
谢谢
