### ISSUE TITLE
jeecgboot 3.5.3，JDK17升级冲突解决

### ISSUE THREAD

**Issue by Guochanglin-gcl** [jeecgboot/JeecgBoot#7257]
##### 版本号：
jeecgboot 3.5.3，JDK17

##### 问题描述：

jeecgboot 3.5.3，原先JDK为1.8，升级到17后，这个HandlerInterceptorAdapter怎么解决，我看文档没有说明

##### 错误截图：

![image](https://github.com/user-attachments/assets/100173b5-6189-4179-8972-4a89beab9f6b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
参考最新版
