### ISSUE TITLE
当使用原生的a-modal时，由于全局样式的污染，导致关闭按钮位置移位，感觉不协调

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7260]
##### 版本号：
v3.7.0_all

##### 问题描述：
当使用原生的a-modal时，全局样式的污染，导致关闭按钮位置移位，感觉不协调，建议优化。

##### 错误截图：
![image](https://github.com/user-attachments/assets/7084e077-db53-4940-ae74-a59d95ff0b82)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可按如下图进行修改:

![image](https://github.com/user-attachments/assets/5edd268b-2757-40e6-bddb-d1524618449f)
![image](https://github.com/user-attachments/assets/40c0e043-aa11-48aa-a6cf-0fb849e8104b)
![image](https://github.com/user-attachments/assets/0c010006-c85d-4894-9b1c-2f186f8907a3)
![image](https://github.com/user-attachments/assets/5ffdaacf-9095-4a7c-835f-1fb24c8b8c9a)
![image](https://github.com/user-attachments/assets/fc967b68-5a45-43e9-a68f-ed9b933e8de0)

**Comment by liaozhiyang** [comment]
我们会采用这种方式修复，下一版本发布。
![image](https://github.com/user-attachments/assets/7fa2f77e-3e71-4a39-a877-640afd036fad)
![image](https://github.com/user-attachments/assets/f1a963be-e404-4a43-9d15-6373c9e93d35)
![image](https://github.com/user-attachments/assets/461ae4ff-022a-4da6-aa07-aa1046109958)
![image](https://github.com/user-attachments/assets/92b29148-7b88-4f19-bb29-2fb70ed523a7)
