### ISSUE TITLE
sys_gateway_route 表中没有del_flag，导致报错

### ISSUE THREAD

**Issue by zfq308** [jeecgboot/JeecgBoot#7262]
##### 版本号：

Jeecg-Boot 3.7.1 

##### 问题描述：

sys_gateway_route 表中没有del_flag，导致报错

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
![image](https://github.com/user-attachments/assets/4b37880a-c6c2-40d8-8bf4-b609d325cda7)

**Comment by zhangdaiscott** [comment]
最新代码应该有了，可能你下载的比较早，你可以按照截图执行增量SQL或者下载最新版
