### ISSUE TITLE
设置VITE_DROP_CONSOLE=false上线控制台还是不打印console信息

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/JeecgBoot#7263]
##### 错误截图：
![image](https://github.com/user-attachments/assets/1f46e5d6-3166-4424-aae1-151b91ca7c3c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不是修改这个参数

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/8e5f401d-97ef-4418-95d2-916721d4b37d)
