### ISSUE TITLE
online开发中怎么配置某一个表只显示创建人是当前用户的数据

### ISSUE THREAD

**Issue by hehaijian** [jeecgboot/JeecgBoot#7266]
##### 问题描述：

我是想在online开发中实现，表是商品表，a用户只能看到创建人是a用户的商品，看不到b用户的商品，管理员能看到所有的商品，
我应该怎么操作？谢谢

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
设置数据权限，根据创建人隔离

**Comment by hehaijian** [comment]
多谢

**Comment by hehaijian** [comment]
没找到响应的功能说明，能把说明中的连接地址发一下吗
