### ISSUE TITLE
请问BasicTable怎么在固定表头的情况下自适应高度呢？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7271]
##### 问题描述：
BasicTable表格设置了固定表头属性，自适应高度就失效了
![image](https://github.com/user-attachments/assets/a0a17dbb-7338-4e8d-b2a1-841107c4cce3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
自适应高度就是固定了表头啊，不需要单独设置scroll:{y:800}
效果如下图：
![iShot_2024-09-30_09 41 55](https://github.com/user-attachments/assets/ece4e306-df1f-4ce5-9ce4-90e5ae29a062)
