### ISSUE TITLE
官网的在线演示怎么变成API文档了，前端怎么访问

### ISSUE THREAD

**Issue by greenlgy** [jeecgboot/JeecgBoot#7272]
##### 版本号：
3.7.1

##### 问题描述：

官网的在线演示怎么变成API文档了，前端怎们访问，请说明一下

##### 错误截图：
![image](https://github.com/user-attachments/assets/e16cd651-692c-493f-8274-49f68d80303c)

**Comment by zhangdaiscott** [comment]
你访问的那个地址

**Comment by greenlgy** [comment]
在chrome里，手打地址：http://boot3.jeecg.com 访问一下，再点击【JeecgBoot演示】按钮就好了
不知道什么情况，缓存吧

**Comment by zhangdaiscott** [comment]
你应该是采用https格式访问的

**Comment by zhangdaiscott** [comment]
已经修复了
