### ISSUE TITLE
表单设计器是否支持if判断功能

### ISSUE THREAD

**Issue by pipipiper** [jeecgboot/JeecgBoot#7274]
##### 版本号：
v3.7.1

##### 问题描述：
表单设计器是否支持if判断，如有一个是否需要上传附件的开关，打开开关下方即展示附件上传组件，关闭则不展示。

##### 错误截图：

![image](https://github.com/user-attachments/assets/25f78ae3-6187-43f4-9a6c-e2a226e57e2e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
有业务规则
