### ISSUE TITLE
主表控制子表展示

### ISSUE THREAD

**Issue by javazhangyi** [jeecgboot/JeecgBoot#7275]
一个主表，多个附表
通过国内，或者国外，按钮，来控制 google 子表 和AppStore 子表 展示

<img width="712" alt="image" src="https://github.com/user-attachments/assets/a54d0480-9da8-466f-a6f4-c111cf7a32f3">

**Comment by zhangdaiscott** [comment]
先归档到https://github.com/jeecgboot/JeecgBoot/issues/1312

**Comment by jeecgDeveloper** [comment]
已经支持该功能。
![iShot_2024-10-21_17 59 17](https://github.com/user-attachments/assets/4995465d-ec47-4415-bc94-8a1717dc373b)

[文档地址](https://help.jeecg.com/java/online/enhanceJs/form.html)
![image](https://github.com/user-attachments/assets/04677ae2-be7a-4010-bd1d-8f94a5eb30f6)

演示测试代码：
![image](https://github.com/user-attachments/assets/c924811d-3bf4-4ab2-99eb-1b1512ada5cf)
