### ISSUE TITLE
关于online 表单开发主附表遇到权限问题

### ISSUE THREAD

**Issue by robert88-luo** [jeecgboot/JeecgBoot#7277]
##### 错误截图：
![image](https://github.com/user-attachments/assets/11ee2a5e-8b59-4471-b1d6-ad5ec9877f1a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
请确认是否配置了菜单并且菜单授权正确

**Comment by robert88-luo** [comment]
都配置了权限

**Comment by sjlei** [comment]
> 都配置了权限

问题没有复现，请提供一下主子表配置、菜单配置和权限分配情况用于测试
