### ISSUE TITLE
代码生成器 生成的子父表 没有生成.data文件

### ISSUE THREAD

**Issue by Mipuqt** [jeecgboot/JeecgBoot#7278]
##### 版本号：
3.6.3

##### 问题描述：
代码生成器 生成的子父表 没有生成.data文件
希望子表可以使用树

##### 错误截图：
主表的
![image](https://github.com/user-attachments/assets/b0eeca78-6a01-4acf-b715-871d349b27be)

单表的
![image](https://github.com/user-attachments/assets/58dc7e40-5551-46a4-9b10-279a13f6fbbc)

**Comment by Mipuqt** [comment]
![image](https://github.com/user-attachments/assets/7095b56c-091a-46d2-b234-4e9c1ce56992)
原生能生成

**Comment by zhangdaiscott** [comment]
子父表 没有生成.data文件 
是什么

**Comment by Mipuqt** [comment]
![image](https://github.com/user-attachments/assets/b67c942b-9bbd-4082-aaee-6a96719eef9b)
配置文件

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你这就是将子表单独生成一下树列表是吧？有没有错误日志，我这测着没问题。如果不是，请详细描述一下你的操作步骤
