### ISSUE TITLE
离线模式下，部分图标需要远程加载

### ISSUE THREAD

**Issue by ayerswu** [jeecgboot/JeecgBoot#7279]
##### 问题描述：
本地vscode启动模式下，会有远程图标访问请求，请问这个需要怎么解决？
下面有两个截图：
第一个截图是离线模式无痕浏览模式下进入主页，有好几个api.iconify.design/ant-design.json远程请求

第二个截图发现版本自带的mdi:chevron-down图标就可以不用远程加载就能使用，但是当我替换成mdi:chevron-double-down后就需要远程加载，离线模式就会加载失败。为啥mdi:chevron-down可以本地加载，mdi:chevron-double-down就不可以，需要怎么解决？

真是部署环境是内网环境，因此需要解决这个问题。麻烦帮忙看下，多谢！

##### 错误截图：
![image](https://github.com/user-attachments/assets/7117c745-4469-4f77-84da-d4a5946e7143)

![image](https://github.com/user-attachments/assets/6391087f-51e6-4fbe-b3f6-f28e1b5b89ae)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看看这个可以生成本地化
https://help.jeecg.com/config/icongen.html
