### ISSUE TITLE
怎么在每次加载页面前根据该页面路径信息来判断加载不同的layout

### ISSUE THREAD

**Issue by youzi-gif** [jeecgboot/JeecgBoot#7281]
##### 版本号：
3.7.0

##### 问题描述：

我基于jeecg二次开发自有页面，需要加载不同的layout，目前在getUserPermissionByToken接口里让后端返回了两个menu，想实现menu1加载jeecg的layout，menu2de加载自己写的layout，请问怎么实现。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你可以扩展一个字段，用于存不同类型

**Comment by youzi-gif** [comment]
> 你可以扩展一个字段，用于存不同类型

这个已经实现了，在新增一个页面的时候扩展了一个字段，后端根据这个字段来判断是属于menu1还是menu2，这些已经实现，现在问题是前端怎么根据这个判断加载不同的layout
