### ISSUE TITLE
jeecgboot 微服务使用tongweb

### ISSUE THREAD

**Issue by liulitang** [jeecgboot/JeecgBoot#7283]
##### 版本号：
2.4.2

##### 问题描述：
1：jeecgboot 微服务使用tongweb部署，该如何处理。
2：本地idea使用外置tomcat启动微服务，该如何配置和启动，主要是gateway模块该如何处理
3：目前配置如下图所示，配置完成之后，能够注册到nacose，但是无法访问到接口

##### 错误截图：
![微信图片_20240926165157](https://github.com/user-attachments/assets/6a55cf7b-f37a-409f-bc56-07fc781f67c2)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/tongweb-deploy.html

**Comment by liulitang** [comment]
官网是单例服务，麻烦提供下微服务的配置

**Comment by liulitang** [comment]
麻烦提供下处理的方式

**Comment by Honeysuckle1212** [comment]
请问大佬tongweb部署成功了吗 我按照官方的来出错了
