### ISSUE TITLE
actuator/httptrace泄露用户token

### ISSUE THREAD

**Issue by yanglihangissue** [jeecgboot/JeecgBoot#7284]
##### 版本号：
3.4.4

##### 问题描述：
有了token权限后，调用该接口会获取到其他用户的token并且可用

##### 错误截图：

![image](https://github.com/user-attachments/assets/b39763c9-5cc2-48b4-bfe2-424aa7ea46e8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
shiro 中注释掉actuator/httptrace排除配置
