### ISSUE TITLE
生成erp表单时，当region代码是81和82开头，也就是香港澳门区域时，JAreaLinkage地址组件显示不完整

### ISSUE THREAD

**Issue by kevinchan1979** [jeecgboot/JeecgBoot#7290]
##### 错误截图：
![C7640290C283C978A68EEACC01389292](https://github.com/user-attachments/assets/597eeb9b-b0e2-43e1-870b-26c60046987b)
![47EB4E07D0512774C14A144028EDC4CF](https://github.com/user-attachments/assets/bc194582-e41f-4d69-bf11-d17801a4510d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by yankuncui** [comment]
兄弟，你这个地址是怎么显示的，中文

**Comment by kevinchan1979** [comment]
> 兄弟，你这个地址是怎么显示的，中文

在list页面加回显插槽
       <template v-slot:bodyCell="{ column, record, index, text }">
         <template v-if="column.dataIndex==='address'">
              
            <div>{{ getAreaTextByCode(text) }}</div>
         </template>
       </template>

**Comment by kevinchan1979** [comment]
> jl

已经找到问题了，源代码中香港、澳门只有两级其它省份是三级，实际都是三级，我去掉了相关条件判断可以正确显示了，请老板指正。
![WX20240929-092930@2x](https://github.com/user-attachments/assets/a2e9b7a3-ee05-457e-b71b-213b442fdcc4)
![WX20240929-093006@2x](https://github.com/user-attachments/assets/33703dd5-cd9a-449a-9b14-90891572ea0a)
![WX20240929-094049@2x](https://github.com/user-attachments/assets/5633d59f-39d0-4500-a633-0b0c84e54497)

**Comment by sjlei** [comment]
问题已修复，下版本发布
