### ISSUE TITLE
online非编辑类列表的方法

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#7291]
##### 版本号：
3.6.2

##### 问题描述：
online表达可以快速制作一个增删改查的界面，在实际应用中还有一类列表类型的应用，也就是界面主要就是一个列表，在列表上执行一些操作，本身不属于需要增删改的表单。列表上执行选择行执行一些操作。

能不能有如下功能：根据sql迅速生成列表，并支持条件，类似现在online报表的功能，但是可以通过增加按钮，增强之类的方法，执行一些相关操作。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
目前没有，可以把online的按钮都隐藏掉
