### ISSUE TITLE
stylelint 版本问题，导致npm install失败

### ISSUE THREAD

**Issue by petma** [jeecgboot/JeecgBoot#7292]
##### 版本号：
3.7.1

##### 问题描述：
前端无法启动
package.json中
    "stylelint": "^16.2.1",
    "stylelint-config-prettier": "^9.0.5",

##### 错误截图：
npm install时提示，应该是要降stylelint的版本

npm error Could not resolve dependency:
npm error peer stylelint@">= 11.x < 15" from stylelint-config-prettier@9.0.5
npm error node_modules/stylelint-config-prettier
npm error   dev stylelint-config-prettier@"^9.0.5" from the root project

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
按文档来，使用pnpm
