### ISSUE TITLE
查询我的部门问题

### ISSUE THREAD

**Issue by mutudu95** [jeecgboot/JeecgBoot#7293]
##### 版本号：
3.7.0

##### 问题描述：
查询我的部门时候如果org_code编码超出长度位数+1的时候 比如A03是一个层级，A031是一个层级，那么我查询A03的数据的时候  我就会查询到A031的数据，因为这里的查询sql写的是A03%,右边模糊查询，这个其实也不算是个bug，按道理来说，层级应该不会超过很多，但是问题出现了，我还是提下这个问题，希望官方可以看下
![image](https://github.com/user-attachments/assets/31fff4cb-8efe-492d-8968-f739286dbcb7)

##### 错误截图：
![image](https://github.com/user-attachments/assets/b12affd1-eec7-4232-9ee5-ee944668e872)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
那应该先改下邮编生成规则

**Comment by zhangdaiscott** [comment]
org\jeecg\common\util\YouBianCodeUtil.java
![image](https://github.com/user-attachments/assets/3971b108-7837-4218-9ebc-d3e8ba6e7dd4)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/system/orgcode.html

**Comment by mutudu95** [comment]
好的，谢谢
