### ISSUE TITLE
JAreaSelect组件选择完省市区，单选出来的数字怎么转化成对应地名的，相关json文件在哪找

### ISSUE THREAD

**Issue by yankuncui** [jeecgboot/JeecgBoot#7295]
##### 版本号：
3.7.0

##### 问题描述：
JAreaSelect组件选择完省市区，单选出来的数字怎么转化成对应地名的，相关json文件在哪找

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
？
