### ISSUE TITLE
JvxeTable 怎么实现筛选

### ISSUE THREAD

**Issue by maxiaole-z** [jeecgboot/JeecgBoot#7296]
##### 版本号：
3.4.3

##### 问题描述：
JvxeTable 想实现列的筛选就像截图这种，希望大佬能说下代码具体怎么写的，谢谢啦
![image](https://github.com/user-attachments/assets/4112385e-61f3-40c8-acf2-89494c32b9cd)
![image](https://github.com/user-attachments/assets/da52e8a4-85e1-46cc-a73d-b7e0e12c9162)

**Comment by zhangdaiscott** [comment]
默认没这功能

**Comment by qinghechaoge** [comment]
我已经实现了

**Comment by qinghechaoge** [comment]
+qq 861616966
