### ISSUE TITLE
关于mvn install一直显示错误该怎么解决

### ISSUE THREAD

**Issue by blacksmall-mos** [jeecgboot/JeecgBoot#7297]
![屏幕截图 2024-09-29 143747](https://github.com/user-attachments/assets/6b639740-c1e4-4068-b931-a9cae7ab8d05)
会一直在jeecg-boot-base-core 出错显示Faliure
错误显示如下：
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:3.9.8 or one of its dependencies could not be resolved:
[ERROR]         org.apache.maven.plugins:maven-resources-plugin:jar:3.9.8 was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
改过了镜像和其他东西依旧显示错误

**Comment by zhangdaiscott** [comment]
是通过parent install的吗

**Comment by blacksmall-mos** [comment]
在此路径上D:\code\Code\JEECG\java\JeecgBoot-master\jeecg-boot使用视频提到的mvn install

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/488af02c-1d31-48f6-a82a-c836df11824c)

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/3732a44e-6c44-4536-9d2e-df52367a6ed3)
这里显示报错是因为maven配置不对嘛

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/5ffc73dc-c3db-4760-9568-f3f1a9b4c554)

**Comment by blacksmall-mos** [comment]
我用的是jdk23是不是跟settings里的jdk1.4也要修改

**Comment by zhangdaiscott** [comment]
默认支持jdk17和jdk8 更高项目也不支持

**Comment by blacksmall-mos** [comment]
但是我选择到jdk17也显示报错
![image](https://github.com/user-attachments/assets/c1d717bc-98a3-4b85-a0a4-98f03a03933b)

**Comment by 929033778** [comment]
使用jdk17也是同样失败，开发环境如下
IDEA-2024.1
jdk-17.0.10
maven-3.9.7
MySQL-8.0.29
redis-5.0.10
nacos-2.3.2

降回 jdk-1.8.0_361，执行顺利通过
