### ISSUE TITLE
关于online表单开发主附表查询问题

### ISSUE THREAD

**Issue by robert88-luo** [jeecgboot/JeecgBoot#7299]
##### 错误截图：
![image](https://github.com/user-attachments/assets/fe3632ef-89c2-4f1f-83f4-5f4b92afcf48)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
使用高级查询？

**Comment by zhangdaiscott** [comment]
jl

**Comment by robert88-luo** [comment]
就是一般查询，不是高级查询

**Comment by sjlei** [comment]
问题已修复，下版本发布
