### ISSUE TITLE
角色自定义首页后出现相同目录

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/JeecgBoot#7300]
##### 问题描述：
3.7.0版本给指定角色设置自定义首页后，出现相同的菜单如图：
![image](https://github.com/user-attachments/assets/a1fe7184-0b78-4f6e-abf7-c6b82f258f93)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
如何配置的做个详细或者录个视频

**Comment by sjlei** [comment]
没有复现该问题，确保现有菜单和自定义首页菜单配置的完全一致

![image](https://github.com/user-attachments/assets/91f711c6-aa2b-4d87-a690-7ad4448433e9)

![image](https://github.com/user-attachments/assets/ec1a2eb8-1aa4-457f-9424-12895505e58d)
