### ISSUE TITLE
CodeGenerateDbConfig注释放开online表单导入表还走jeecg_database.properties

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#7301]
##### 版本号：
3.6.4

##### 问题描述：
根据CodeGenerateDbConfig注释说明放开了CodeGenerateDbConfig类，想让online表单开发模块的“导入数据库表”走配置类
但是注释放开后点“导入数据库表”还是查询的jeecg_database.properties中配置的数据源

请问这个注释说明过时了吗？

##### 错误截图：
![image](https://github.com/user-attachments/assets/e6fab079-28d1-4a39-afa7-b160515d8d35)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版代码生成器依赖

**Comment by hsql** [comment]
我现在的代码生成器的依赖是 1.4.7 ，请问最新版本是多少呢，哪里能看？

**Comment by hsql** [comment]
看到了 1.4.82

**Comment by hsql** [comment]
好了
