### ISSUE TITLE
vue3 启动后刷新页面一直报错Tag mismatch

### ISSUE THREAD

**Issue by ak850455** [jeecgboot/JeecgBoot#7302]
##### 问题描述：

javax.crypto.AEADBadTagException: Tag mismatch!

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
截图看看
并提供重现步骤
