### ISSUE TITLE
在线开发、表头添加提示可配置。

### ISSUE THREAD

**Issue by zousg** [jeecgboot/JeecgBoot#7303]
##### 问题描述：
群主您好、如何在在线开发中table头部添加一个自定义的提示、当我给鼠标放放到某个字段表头就提示出来。

##### 错误截图：

![abc](https://github.com/user-attachments/assets/33babd77-450c-481c-bbf8-a323b4efa2bb)

![image](https://github.com/user-attachments/assets/6da3b360-6c66-408a-81e4-69181784443b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
目前不支持
