### ISSUE TITLE
增加全屏按钮

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/JeecgBoot#7304]
##### 版本号：
3.7.1

##### 问题描述：

有时需要全屏，比如生产销售监控大屏

##### 截图：

![image](https://github.com/user-attachments/assets/53738050-241c-4a47-b2d0-47e2a2f79af6)

全屏：
![image](https://github.com/user-attachments/assets/a4152a2f-dea1-4238-8b47-391e7b8031a8)

**Comment by zhangdaiscott** [comment]
自己放开就行
src\settings\projectSetting.ts
![image](https://github.com/user-attachments/assets/edbcd723-e912-46ca-a7b8-909f0c7ea96d)

**Comment by softboy99** [comment]
试了，不起作用
