### ISSUE TITLE
springboot3_sas分支 token到期后没有刷新toke延长时间的相关功能，导致使用中途被退出了

### ISSUE THREAD

**Issue by hjtjiajia** [jeecgboot/JeecgBoot#7305]
##### 问题描述：

springboot3_sas分支 token到期后没有刷新toke延长时间的相关功能，导致使用中途被退出了

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
等更新3.7.1
