### ISSUE TITLE
Online表单开发-@jeecg/online库在哪里

### ISSUE THREAD

**Issue by wushifeng** [jeecgboot/JeecgBoot#7306]
##### 版本号：
v3.7.1

##### 问题描述：
Online表单开发的配置中，前端页面为 super/online/cgform/index 
这个页面好像是在 @jeecg/online 这个前端库中
@jeecg/online 这个前端库的代码在哪里？ 想对这个页面增加些功能，如何做?

https://npmmirror.com/package/@jeecg/online/versions?tags=all&versions=all 这里也是只有发布包

##### 错误截图：
![1727679414074](https://github.com/user-attachments/assets/50240911-7bb8-4d87-b3fa-6706d7e60a7f)

**Comment by zhangdaiscott** [comment]
非开源部分

**Comment by RememberTheID** [comment]
得加钱
