### ISSUE TITLE
3.7.1】菜单管理 - 会出现滚动区域底部部分数据 多选框无法渲染的情况的 增加实现场景

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7307]
##### 版本号：

3.7.1
##### 问题描述：

菜单管理 - 会出现滚动区域底部部分数据 多选框无法渲染的情况
useListPage.ts增加 scroll属性定义表格滚动高度 时候 会出现这个问题

##### 错误截图：
![image](https://github.com/user-attachments/assets/49a39c3b-2255-4057-b888-f118f5d169a2)
![image](https://github.com/user-attachments/assets/75a377d2-51ec-4a87-86a2-a55324e3038c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
图片裂了，无法分析

**Comment by benben120** [comment]
@zhangdaiscott 还炸么 看看这个问题？

**Comment by zhangdaiscott** [comment]
jl

**Comment by kingAJIN** [comment]
还不可以 我也遇到了这个问题useListPage已经没有scroll这个配置了  最后几个复选框无法渲染

**Comment by kingAJIN** [comment]
@zhangdaiscott

**Comment by guanjieyanzoudashi** [comment]
我也遇到这个问题了

**Comment by guanjieyanzoudashi** [comment]
![3e5f316a86707cef6363c9973b830b2](https://github.com/user-attachments/assets/419faca5-b336-4fa2-b463-1034b87b3ba2)

**Comment by jeecgDeveloper** [comment]
问题已修复，下版本发布
