### ISSUE TITLE
前端无法访问后端api

### ISSUE THREAD

**Issue by slcboy** [jeecgboot/JeecgBoot#7309]
##### 错误截图：
![image](https://github.com/user-attachments/assets/0a65f89f-585f-47c1-a210-19fde6d1e436)

前端nginx配置
![image](https://github.com/user-attachments/assets/e432cd1c-6f7a-4b3f-b614-9b0ff083ba78)

后端api正常访问
![image](https://github.com/user-attachments/assets/d130c078-bb51-411d-b16a-ce0f267cac5b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看文档
https://help.jeecg.com/java/publish/jar.html#%E4%B8%89%E9%80%9A%E8%BF%87nginx%E9%83%A8%E7%BD%B2vue3%E5%89%8D%E7%AB%AF

**Comment by slcboy** [comment]
已配置了后端接口地址，前端访问错误依旧。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月7日(星期一) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 前端无法访问后端api (Issue #7309)





 
看文档
 https://help.jeecg.com/java/publish/jar.html#%E4%B8%89%E9%80%9A%E8%BF%87nginx%E9%83%A8%E7%BD%B2vue3%E5%89%8D%E7%AB%AF
