### ISSUE TITLE
本地启动后，使用仪表盘设计器，图表里面没有地图

### ISSUE THREAD

**Issue by CaptainYuan** [jeecgboot/JeecgBoot#7311]
##### 版本号：
3.7.1

##### 问题描述：
本地启动后，使用仪表盘设计器，图表里面没有地图组件，我看升级日志里面又有地图相关内容，需要额外设置？

##### 错误截图：
<img width="256" alt="image" src="https://github.com/user-attachments/assets/8b8c10ae-af35-43bc-bec4-8206fd765ba7">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
企业版的功能
