### ISSUE TITLE
使用cloud时候system模块引用的是哪个配置文件呢，我改了好几个都没生效

### ISSUE THREAD

**Issue by 18525709247** [jeecgboot/JeecgBoot#7312]
##### 版本号：
3.2.0

##### 问题描述：

使用cloud时候system模块引用的是哪个配置文件呢，我改了好几个都没生效，nacos的也修改了 还是不生效

Maven Profile 勾选的dev和SpringCloud

##### 错误截图：
![image](https://github.com/user-attachments/assets/054b6a9f-5ea2-485c-aa70-a96787757123)
![image](https://github.com/user-attachments/assets/b99af3ee-8dac-4f90-8239-f9bc3df623a1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/98212615-245d-4397-9289-dcf7e735042c)
改的地方不对
