### ISSUE TITLE
编辑online表单后保存的时候报错

### ISSUE THREAD

**Issue by GengZhaoHui** [jeecgboot/JeecgBoot#7313]
##### 版本号：
3.6.1

##### 问题描述：
编辑online表单之后保存时会报错   Handler dispatch failed; nested exception is java.lang.NosuchMethodError:
org.jeecg.common.api.vo.Result.ok

##### 错误截图：

<img width="1267" alt="企业微信截图_17282841407225" src="https://github.com/user-attachments/assets/5539f8d5-ced7-475b-870c-64c5375e8c80">
<img width="889" alt="企业微信截图_17282841038387" src="https://github.com/user-attachments/assets/7a28ca4f-2aed-4dfa-983d-bd0652070ea8">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版试试，你的版本老，我们不好判断
