### ISSUE TITLE
jar分离打包优化建议

### ISSUE THREAD

**Issue by 12345ZMTHL** [jeecgboot/JeecgBoot#7314]
##### 版本号：
3.6.3

##### 问题描述：

jar分离打包优化建议，分离打包成功后，发现业务代码相关也就是jeecg前缀开始的jar也被放到外部了，这样再发布的时候比较麻烦需要确定是那一部分有更新，再去更新lib下的jar包。看下有没有别方式可以将业务代码打包的jar放到jeecg-system-start下，这样后续更新jar只需要更新jeecg-system-start下的就行，不需要去管其他的biz或者api啥的。

##### 错误截图：
![image](https://github.com/user-attachments/assets/fe824c36-6c89-48fd-af91-0914f2b9afc2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jwcjf** [comment]
就是有没有方法直接用打包后的jar包，而不需要去biz包找来更新。

**Comment by zhunian2003** [comment]
分离式打包pom配置，启动： java -jar -Dfile.encoding=UTF-8 -Dloader.path=lib jeecg-system.jar        
<plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <layout>ZIP</layout>
                    <includes>
                        <include>
                            <groupId>nothing</groupId>
                            <artifactId>nothing</artifactId>
                        </include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        
                        <id>copy-resources</id>
                        <phase>package</phase>
                        <goals>
                            
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    
                                    
                                    <directory>${project.build.directory}/classes</directory>
                                    
                                    <includes>
                                        <include>*.xml</include>
                                        <include>*.yml</include>
                                        <include>jeecg/**</include>
                                        <include>static/**</include>
                                        <include>templates/**</include>
                                    </includes>
                                </resource>
                            </resources>
                            
                            <outputDirectory>${project.build.directory}/config</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
