### ISSUE TITLE
jeecgBoot中使用JPopup组件出现以下问题，如何解决

### ISSUE THREAD

**Issue by End-ZB** [jeecgboot/JeecgBoot#7316]
##### 版本号：
vue3+ts+vite    "version": "3.6.1"

##### 问题描述：
jeecgBoot中使用JPopup组件出现报错，无法解决，无法显示，master分支
![image](https://github.com/user-attachments/assets/dd630729-9932-4c47-8d37-56e1a8c2b592)
![image](https://github.com/user-attachments/assets/c15e5b30-e962-47f1-8f0e-d22def92764e)
![image](https://github.com/user-attachments/assets/0c57b6e9-8369-47d4-a50c-4e91b1f61fa1)
![image](https://github.com/user-attachments/assets/c4e11a3f-e000-4167-8630-c4388053b290)

##### 错误截图：
![image](https://github.com/user-attachments/assets/71c650d5-ee85-475e-92ad-80d8556166f9)

![Snipaste_2024-10-09_15-31-58](https://github.com/user-attachments/assets/02449707-3a5e-44d1-b867-deac89f33b47)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
没明白

**Comment by zhangdaiscott** [comment]
再详细描述下你要做什么
