### ISSUE TITLE
切换人大金仓数据库后,项目启动不了

### ISSUE THREAD

**Issue by Wly123456789** [jeecgboot/JeecgBoot#7318]
##### 问题描述：切换人大金仓数据库后,启动报错 
Unsatisfied dependency expressed through field 'sysTableWhiteListService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysTableWhiteListServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysTableWhiteListMapper' defined in file [D:\IdeaProjects\JeecgBoot-master (1)\JeecgBoot-master\jeecg-boot\jeecg-module-system\jeecg-system-biz\target\classes\org\jeecg\modules\system\mapper\SysTableWhiteListMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'quartzDataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration$JdbcStoreTypeConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.quartz.QuartzDataSourceScriptDatabaseInitializer]: Factory method 'quartzDataSourceScriptDatabaseInitializer' threw exception; nested exception is java.lang.IllegalStateException: Unable to detect database type

##### 错误截图：
![Uploading 微信图片_20241010094550.png…]()
![微信图片_20241010094636](https://github.com/user-attachments/assets/7e3b1ef5-5e33-4041-8841-cfe3a55612b5)
![微信图片_20241010094715](https://github.com/user-attachments/assets/f545da42-12e6-4f87-adcb-488b510b83d4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Wly123456789** [comment]
![Uploading 微信图片_20241010094550.png…]()

**Comment by Wly123456789** [comment]
配置文件是用的框架自带的kingbase8配置文件,只改了数据库连接

**Comment by Wly123456789** [comment]
报错截图
![微信图片_20241010095447](https://github.com/user-attachments/assets/9b14fdc2-9839-4c7a-9412-06d965ca6ca6)

**Comment by zhangdaiscott** [comment]
你自己转库了吗

**Comment by Wly123456789** [comment]
> 你自己转库了吗

转库是啥意思

**Comment by zhangdaiscott** [comment]
初始化数据库你怎么弄的

**Comment by Wly123456789** [comment]
> 初始化数据库你怎么弄的

把框架db包下的sql放到mysql数据库中执行,然后通过navicat将数据拷到人大金仓数据库中

**Comment by zhangdaiscott** [comment]
那可能转库有问题，单独去找下定时部分的sql执行下

**Comment by Wly123456789** [comment]
> 那可能转库有问题，单独去找下定时部分的sql执行下

好像不是库的问题,我用之前jeecg-boot2.4.5版本是可以正常启动的,升级到jeecg-boot3.7.1版本后就报这个错

**Comment by Wly123456789** [comment]
> 那可能转库有问题，单独去找下定时部分的sql执行下

感觉是配置文件中initialize-schema: never没生效,我把quartz依赖删掉,就成功启动了

**Comment by GreatWisd0m** [comment]
> > 那可能转库有问题，单独去找下定时部分的sql执行下
> 
> 感觉是配置文件中initialize-schema: never没生效,我把quartz依赖删掉,就成功启动了

为什么我和你同样的问题，解决不了啊。真的好奇怪
