### ISSUE TITLE
后端调用 下载 方法 jmreportServices.exportExcel)  多次（两次）调用，下载回来的报表异常

### ISSUE THREAD

**Issue by lostYoungWuYun** [jeecgboot/JeecgBoot#7319]
##### 版本号：
1.4.32
##### 问题描述：
后端调用 jmreportServices.exportExcel(reportId, queryParam, echartBase)  多次（两次）调用，第二次调用回来的报表异常，会出现数值转换异常 错误，导致报表不完整

##### 错误截图：

![ggg](https://github.com/user-attachments/assets/a6927697-c7d1-442b-aa2b-b7352252d635)

![gg2](https://github.com/user-attachments/assets/42046bc3-34b9-47f4-aad4-d83f119fcf21)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本太老无法处理，升级到最新版看看
