### ISSUE TITLE
主菜单打开后，没有在标签页显示菜单名

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7320]
##### 问题描述：
点击菜单打开页面后，没有在标签栏位置显示菜单名。不是必现，但是频繁出现

##### 错误截图：
![1728529190402](https://github.com/user-attachments/assets/8050e538-0ac5-405d-afa0-8ebe4c0933ff)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
如何重现？请提供重现步骤

**Comment by ak-2019** [comment]
步骤：
![image](https://github.com/user-attachments/assets/14e48f1e-3280-4b16-a413-af6cfc73bb5b)
1. 点击导航栏菜单
2. 多点击几个打开
3. 关闭几个再打开
大概率会出现没有显示菜单名的情况，刷新页面后就正常

**Comment by zhangdaiscott** [comment]
zy
