### ISSUE TITLE
JVxeTable 拖拽如何去除下拉框或去除插入一行

### ISSUE THREAD

**Issue by 1372037590** [jeecgboot/JeecgBoot#7322]
##### 版本号：
前端 3.61

##### 问题描述：
JVxeTable 拖拽如何去除下拉框或去除插入一行
![image](https://github.com/user-attachments/assets/e5f5fe9d-e4e1-4497-9e93-1e5c41463429)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
回头加个配置项

**Comment by sjlei** [comment]
问题已修复，下版本发布。

新增 `installRow` 参数，传为`false`时将隐藏插入一行

```html
<JVxeTable :installRow="false" />
```

![image](https://github.com/user-attachments/assets/562a9e31-cdb2-40ec-ba5b-d26e2f37a0f6)

**Comment by sjlei** [comment]
新增 `installRow` 参数，传为`false`时将隐藏插入一行

```html
<JVxeTable :installRow="false" />
```

![image](https://github.com/user-attachments/assets/562a9e31-cdb2-40ec-ba5b-d26e2f37a0f6)
