### ISSUE TITLE
如何更改全局的字体啊

### ISSUE THREAD

**Issue by 99huan** [jeecgboot/JeecgBoot#7323]
##### 错误截图：
![b0c1e1f395f3c6125a4bd108f2508c5d](https://github.com/user-attachments/assets/bb8c2697-fbe2-4e50-8220-5cd53f4b1033)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy
