### ISSUE TITLE
建议优化部门编码的一个设计缺陷

### ISSUE THREAD

**Issue by tanyicheng** [jeecgboot/JeecgBoot#7326]
##### 版本号：
v3.7.1，其实所有版本都存在这个缺陷

##### 问题描述：
这并不属于框架的bug，但是在实际业务场景中却是非常重要的一个设计缺陷。

例子：为了便于查看，A01=1,A02=2，依次类推
- 部门1
   - 部门1-1
   - 部门1-2
   - 部门1-3
      - 部门1-3-1
      - 部门1-3-2
- 部门2
   - 部门2-1
      - 部门2-1-1
      - 部门2-1-2
- 部门3
   - 部门3-1

问题1：由于子部门的上级部门无法变更，在实际业务场景部门1-3发生变化，其子部门都合并到部门1-2中，目前的做法只能将原1-3-1、1-3-2部门删除，然后重新新增到部门1-2下，新增部门1-2-1、部门1-2-2。此时原部门1-3及其子部门下的员工都要手动变更部门，若是在几百几千人的公司中将是一次不小的改动，显然不是合理的操作方式

问题2：在业务表中保存部门编码，不是很合理
场景：某员工在部门3-1中创建了几条单据，后由于人事变动转移到部门1-1，若部门1-1的领导有数据权限「只能看本部门的数据」则无法看到新转进来的员工的历史单据

##### 错误截图：
无

**Comment by zhangdaiscott** [comment]
先归档到
https://github.com/jeecgboot/JeecgBoot/issues/1312
