### ISSUE TITLE
jeecg-boot-base-core ............................... FAILURE安装错误

### ISSUE THREAD

**Issue by blacksmall-mos** [jeecgboot/JeecgBoot#7328]
这里安装错误是什么原因
![image](https://github.com/user-attachments/assets/d8eb46d5-2886-42e5-9f22-94e188c5beb2)

**Comment by zhangdaiscott** [comment]
看错

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/652bf7e4-c55d-4887-8c78-698ef5e246ed

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/786fdbcc-b201-4000-9494-16d95da2acfa)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/bb5ff7bc-c0f2-4271-be73-4f2f1cef5ecb)


看看maven版本和jdk版本

**Comment by blacksmall-mos** [comment]
maven是安装的3.9.8
![image](https://github.com/user-attachments/assets/25238cf9-bb88-4d2e-842f-9024baeb4316)
然后jdk安装的是压缩包里的jdk-17

**Comment by blacksmall-mos** [comment]
然后安装要求装了镜像后是这一地方出现了错误
![image](https://github.com/user-attachments/assets/5f641296-9915-47c5-8712-639467e88787)

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/2ff90087-ed70-4186-908f-f5c8702fd05e)
然后该在哪个地方解决，我看问题是没有读取到正确的aliyun地址

**Comment by zhangdaiscott** [comment]
百度吧，应该是你环境配置问题

**Comment by blacksmall-mos** [comment]
![image](https://github.com/user-attachments/assets/46dec804-dd28-44ea-a089-45515d47d715)
这个是哪里出现问题了，该怎么解决
