### ISSUE TITLE
咨询官方大大有没有考虑前端升级vben5

### ISSUE THREAD

**Issue by pingsanddoss** [jeecgboot/JeecgBoot#7330]
##### 版本号：
v3.7.1

##### 问题描述：

如标题所问

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
vben 本身发展并不好，我们自己维护自己的

**Comment by pingsanddoss** [comment]
没有其他意思，就是感觉最新版的vben5UI好看一点^_^，希望jeecgUI也有升级，越办越好
