### ISSUE TITLE
请问BasicTable 表格怎么根据角色配置单元格的编辑权限

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7331]
##### 问题描述：
请问BasicTable 表格怎么根据角色配置单元格的编辑权限

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
个性化的需要自己实现
