### ISSUE TITLE
最新版本，附表隐藏部分字段，从主表更新字段，隐藏字段数据丢失

### ISSUE THREAD

**Issue by javazhangyi** [jeecgboot/JeecgBoot#7334]
前段推送数据，bid 字段隐藏，接口没有推送bid 信息
![image](https://github.com/user-attachments/assets/11836378-b7ee-453e-8007-cbdece207274)

数据库，最终bid 数据为空

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/add64634-2267-43bb-b418-63e78c9dea46">

**Comment by zhangdaiscott** [comment]
按格式发帖
