### ISSUE TITLE
租户隔离后，popup弹窗的online报表不支持租户隔离

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#7335]
##### 版本号：
3.7
##### 问题描述：

租户隔离后，popup弹窗的online报表不支持租户隔离，这样造成的巨大的数据问题，能否在online报表增加租户的系统变量，类似目前的#{sys_user_code}等

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你写sql的时候可以加上

**Comment by zwjsoft** [comment]
> 你写sql的时候可以加上

tenant_id=1000这么写吗？还是类似tenant_id='#{XXX}'，如果按照tenant_id=1000这个写，那不同租户都只能参照到1000的数据了。

**Comment by zhangdaiscott** [comment]
后面，不是支持系统变量吗

**Comment by zhangdaiscott** [comment]
tenantId

tenant_id

**Comment by zwjsoft** [comment]
> tenantId
> 
> tenant_id

测试了'#{tenant_id}' 可以用，谢了
