### ISSUE TITLE
连接达梦数据库Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by linayukari** [jeecgboot/JeecgBoot#7336]
##### 版本号：
jeecgboot版本2.4.5 springboot版本2.3.5 

##### 问题描述：
按照官网文档连接达梦数据库，但是一直报错
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class

我在pom里添加了驱动
		<dependency>
			　　<groupId>com.dameng</groupId>
			　　<artifactId>DmJdbcDriver18</artifactId>
			　　<version>8.1.3.140</version>
		</dependency>
		<dependency>
			　　<groupId>com.dameng</groupId>
			　　<artifactId>DmDialect-for-hibernate5.6</artifactId>
			　　<version>8.1.3.140</version>
		</dependency>
并且按照https://help.jeecg.com/java/setup/dameng8.html的说明修改了配置，但是项目无法启动并报上述错误

##### 错误截图：
![image](https://github.com/user-attachments/assets/ec59e953-fed4-407a-994d-0d3b1609d5ea)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
2.4.5不知道支不支持
