### ISSUE TITLE
jeecg继承积木报表后右键没有导出配置选项

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#7338]
##### 版本号：
3.7.0

##### 问题描述：
jeecg中集成积木报表 1.8.1
![image](https://github.com/user-attachments/assets/99d14270-c291-46bd-989e-d87e12a1e039)
zai在积木报表的官方文档中，在报表设计页面右键有一个“导出报表配置”的按钮
![image](https://github.com/user-attachments/assets/ca00e980-2bbc-47b1-973c-e7746f480bbd)
在积木报表官网的体验页面也有这个按钮
![image](https://github.com/user-attachments/assets/c9b63d1d-f3c7-43f4-8769-b27228b3625f)

但是在集成点进去的页面却没有
![image](https://github.com/user-attachments/assets/d1b86f24-55f5-4ae3-b0ec-159312e3051b)
请问应该怎么处理

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
滚动底部
