### ISSUE TITLE
vue2版本前端打包失败

### ISSUE THREAD

**Issue by AnShengFather** [jeecgboot/JeecgBoot#7339]
##### 版本号：
vue2最终版本

##### 问题描述：
前端打包的时候报错，打包失败
已经安装了webpack

##### 错误截图：
![image](https://github.com/user-attachments/assets/48b58d46-b54b-49c0-9b3d-1bd7738a9506)
![image](https://github.com/user-attachments/assets/5678d9ca-8f18-4eb7-b99d-f191961d1172)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
百度吧，应该是环境问题或者依赖版本冲突了，可以把版本号前面的^删掉
