### ISSUE TITLE
前端websocket使用方法

### ISSUE THREAD

**Issue by 12341234-yangboran** [jeecgboot/JeecgBoot#7340]
##### 版本号：
3.7.0

##### 问题描述：
前端页面中如何使用websocket，在onMounted中直接使用connectWebSocket吗？这样重复进入页面会产生多个websocket连接，正确写法应该是什么？

##### 错误截图：
![image](https://github.com/user-attachments/assets/88fd41e6-07f6-4d50-947a-7d6b01beaf9d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgDeveloper** [comment]
![image](https://github.com/user-attachments/assets/25ae4f1b-f908-4dc7-a75c-a95c19990d01)

你可以在页面初始化的时候去初始webSocket，在页面销毁的时候移除掉webSocket。

或者在弹窗打开或者关闭的时候初始化webSocket和移除webSocket，这样就不会创建多个webSocket。
