### ISSUE TITLE
积木报表

### ISSUE THREAD

**Issue by GrougChar** [jeecgboot/JeecgBoot#7341]
##### 问题描述：

jeecg-boot 集成了积木报表 我想禁用积木报表 如果操作

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
搜索依赖 jimureport-spring-boot-starter 注释掉
