### ISSUE TITLE
不出验证码

### ISSUE THREAD

**Issue by jackrjl** [jeecgboot/JeecgBoot#7342]
##### 版本号：
3.7.1 或3.7.0

##### 问题描述：
win10下，将dict 里面的内容copy 到 nginx html目录下，nginx.conf 就用默认值
server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }
}

dist里面的 _app.config.js 里面的 "VITE_GLOB_DOMAIN_URL":"http://localhost:8080/jeecg-boot"

chrome中访问 localhost，不出验证码，其中 index-BgVTXMBq.js

send: function(Te) {
                    var Oe = this;
                    if (this.custom.options.body = Te,
                    !this.match) {
                        this.custom.xhr.send(Te);
                        return
                    }

Te值为undefine

但如果在cmd（JeecgBoot-3.7.1\jeecgboot-vue3）中运行 pnpm dev，访问 localhost:3100，验证码是可以出来的
请问那配置不对？jack_rjl@163.com

##### 错误截图：

![jeecgBoot](https://github.com/user-attachments/assets/230dc17b-a422-40b8-8f7c-5abfbd8ce0bc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
看部署文档
https://help.jeecg.com/java/publish/jar.html

**Comment by jackrjl** [comment]
您这个https://help.jeecg.com/java/publish/jar.html是针对linux的nginx的？

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/73c5dad4-ecda-453b-ae82-be54ddc989bd)

这个配置加了吗
