### ISSUE TITLE
缓存如何不同的key配置不同的过期时间呢？现在统一都是6个小时。

### ISSUE THREAD

**Issue by wyx666518** [jeecgboot/JeecgBoot#7343]
##### 版本号：
3.7.1

##### 问题描述：
缓存如何不同的key配置不同的过期时间呢？现在统一都是6个小时。我看到要去改common的逻辑，有其他办法和配置文档中没有说明吗？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot-starter/blob/master/jeecg-boot-common/src/main/java/org/jeecg/common/modules/redis/config/RedisConfig.java

通过这个来设置，可以自定义starter
