### ISSUE TITLE
标签页样式异常

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/JeecgBoot#7345]
##### 版本号：
3.7.1

##### 问题描述：
主题工具栏切换到「标签页样式」为极简模式会导致标签页样式异常。

##### 错误截图：

![20241015-105629](https://github.com/user-attachments/assets/74e2b90b-656f-41e2-aef7-dba7d6519fcc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。

你本地可按如下修复：
![image](https://github.com/user-attachments/assets/86eafbea-0f28-49ea-b198-d1830c946913)
![image](https://github.com/user-attachments/assets/a640dd3c-9eb5-451e-ac4f-75b7d0108ef7)
![image](https://github.com/user-attachments/assets/59c1728b-1c57-45f1-bbfa-d3a61503fc0b)



```
<style lang="less" scoped>
  @prefix-cls: ~'@{namespace}-multiple-tabs';
  .@{prefix-cls} {
    :deep(.anticon) {
      display: inline-block;
    }
    .rightExtra {
      display: flex;
      :deep(svg) {
        &:not(.icon) {
          vertical-align: -0.3em;
        }
      }
      .ai-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        width: 36px;
        color: @text-color;
        text-align: center;
        border-left: 1px solid @border-color-base;
      }
    }
  }
</style>

```
