### ISSUE TITLE
切换达梦数据库表脚本好像没有找到

### ISSUE THREAD

**Issue by yanglihangissue** [jeecgboot/JeecgBoot#7348]
##### 版本号：
3.4.4

##### 问题描述：
切换达梦数据库表脚本好像没有找到，现在想mysql数据库转达梦，后端版本3.4.4支持达梦数据库吗

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
数据库脚本不提供，需要自己转
