### ISSUE TITLE
 ERROR com.alibaba.druid.pool.DruidDataSource:2930 

### ISSUE THREAD

**Issue by Canpike** [jeecgboot/JeecgBoot#7351]
##### 版本号：
3.7.1

##### 问题描述：
后端项目启动错误

##### 错误截图：

2024-10-16 18:17:36.438 [Druid-ConnectionPool-Create-224473864] ERROR com.alibaba.druid.pool.DruidDataSource:2930 - create connection SQLException, url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by drummerglen** [comment]
workaround：
请尝试将源码中的所有相应mysql、redis主机地址由127.0.0.1修改为对应的docker-compose服务地址即可
127.0.0.1:3306 -> jeecg-boot-mysql:3306
host: 127.0.0.1 -> jeecg-boot-redis

## mysql相关文件
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-product/target/classes/application.yml
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-product/src/main/resources/application.yml
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-order/target/classes/application.yml
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-order/src/main/resources/application.yml
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-account/target/classes/application.yml
./jeecg-boot/jeecg-server-cloud/jeecg-visual/jeecg-cloud-test/jeecg-cloud-test-seata/jeecg-cloud-test-seata-account/src/main/resources/application.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-prod.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-test.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-dev.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-prod.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-test.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-dev.yml

## redis相关文件
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-prod.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-kingbase8.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-test.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-dev.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/target/classes/application-dm8.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-prod.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-kingbase8.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-test.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-dev.yml
./jeecg-boot/jeecg-module-system/jeecg-system-start/src/main/resources/application-dm8.yml

**Comment by zhangdaiscott** [comment]
账号密码错误
