### ISSUE TITLE
条件过滤动态参数不显示

### ISSUE THREAD

**Issue by bugw** [jeecgboot/JeecgBoot#7352]
##### 问题描述：
使用“条件过滤动态参数”功能的时候，字典table填写：表名where条件（当前表字段值）的查询如：field_subform where main_id like	'%${label_id}%'
![{BA349351-76A0-412F-BD42-B196B5907BBA}](https://github.com/user-attachments/assets/45315a96-339e-4cc1-a912-2b5510dee05b)
在功能测试能显示查询结果，但是复制代码，重新运行项目，打开相应表单，没有显示

##### 错误截图：
官方文档功能
![e5666b62daa855936a5cfb7f35e69064](https://github.com/user-attachments/assets/7b188c4f-1232-42e1-af3e-71744bb829ce)
online表功能测试
![466f485d36df6163c40293cdb4093360](https://github.com/user-attachments/assets/bd19538a-84b7-4db0-bc2b-5860d46bbc48)
复制代码，重启项目，对应位置没有结果
![8d6b5faeb9949bd1b34081fc8b00fb50](https://github.com/user-attachments/assets/ea39fcd5-03cb-4c4c-a483-c377989a8a09)
online界面：
![{45BB4271-1D0E-4AE8-B947-F1BBE577162A}](https://github.com/user-attachments/assets/04d9243c-deae-4974-a66c-a5b5cf494ca5)

**Comment by zhangdaiscott** [comment]
JL

**Comment by jeecgDeveloper** [comment]
该功能目前仅支持**Online在线功能测试**使用，不支持生成代码后使用
