### ISSUE TITLE
The bean 'dataSource', defined in class path resource 

### ISSUE THREAD

**Issue by heyyangyang1** [jeecgboot/JeecgBoot#7353]
##### 版本号：
<version>3.7.1</version>

##### 问题描述：
SpringCloud 模式
启动JeecgNacosApplication后，启动JeecgDemoCloudApplication 报datasource 重复问题
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

##### 错误截图：
<img width="1145" alt="截屏2024-10-17 21 17 24" src="https://github.com/user-attachments/assets/08587742-b8fe-44a0-b1bf-1dcf6cc8d243">

**Comment by zhangdaiscott** [comment]
默认代码？

**Comment by heyyangyang1** [comment]
正在忙，有时间看到会回复。

**Comment by heyyangyang1** [comment]
对，刚刚从git下载的完整项目代码，单体项目时也有时出现这个异常，maven reload project后有时会正常，转为spring cloud 后启动reload 并没有好转。

**Comment by heihesui** [comment]
看一下yaml配置文件里的autoconfigure exclude的路径是不是有问题，在springboot3上应该是com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceAutoConfigure，在springboot2上应该是com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure，我今天在springboot3_sas上遇到类似的问题，通过https://github.com/jeecgboot/JeecgBoot/pull/7361/commits/40542cebca0e883b91900792166e63db5c244ed7解决了

**Comment by zhangdaiscott** [comment]
感谢已经提了
