### ISSUE TITLE
从3.5.4升级到3.7.1登录到首页点击左侧菜单->低代码开发->Online表单开发，菜单打不开，一直转圈圈，控制台报错clipboard@2.0.11 does not provide an export named 'default'

### ISSUE THREAD

**Issue by baiyajin** [jeecgboot/JeecgBoot#7354]
##### 版本号：
从3.5.4升级到3.7.1

##### 问题描述：
从3.5.4升级到3.7.1登录到首页点击左侧菜单->低代码开发->Online表单开发，菜单打不开，一直转圈圈，控制台报错如下：
SyntaxError: The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=64e7a0fb' does not provide an export named 'default' (at useCgformList-f41d4dc1.mjs:37:8)
重新安装了clipboard@2.0.11插件依赖还是报相同的错。

##### 错误截图：
SyntaxError: The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=64e7a0fb' does not provide an export named 'default' (at useCgformList-f41d4dc1.mjs:37:8)
![image](https://github.com/user-attachments/assets/33e51e90-8cbc-41a4-87c2-19015e8803f2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
vite缓存清空一下

**Comment by ericlin26** [comment]
删除node_modules/.vite缓存也没用
