### ISSUE TITLE
角色权限和部门权限的问题

### ISSUE THREAD

**Issue by chenxofhit** [jeecgboot/JeecgBoot#7355]
什么是角色权限，什么是部门权限，我看了所有的issue，还是有点懵。
这两者发生冲突的时候，系统使用的是什么权限？

涉及到的帖子有：
1，https://github.com/jeecgboot/JeecgBoot/issues/3772
2，https://github.com/jeecgboot/JeecgBoot/issues/4495
3，https://github.com/jeecgboot/JeecgBoot/issues/6526
4，https://github.com/jeecgboot/JeecgBoot/issues/4741
5，https://github.com/jeecgboot/JeecgBoot/issues/4495
感觉都没有说清楚。

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/system/auth.html

**Comment by chenxofhit** [comment]
若依上人家说得比较清楚，部门权限其实就是数据权限。
