### ISSUE TITLE
在线开发无法使用

### ISSUE THREAD

**Issue by yanxiangxin** [jeecgboot/JeecgBoot#7357]
##### 版本号：
 "version": "3.7.0",
##### 问题描述：
在线开发页面进不去  把node_modules 删除掉也不好使
执行了clean:cache也不好使
执行了命令 清理缓存  也不好使

##### 错误截图：

![2EWO9 KV3(W3A)$_S@J4 K0](https://github.com/user-attachments/assets/2e2a91cf-25b5-4344-b225-e591eb6c980c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不清楚

**Comment by yanxiangxin** [comment]
有解决方案吗
