### ISSUE TITLE
本地没问题 线上报错 ： useModal instance is undefined!

### ISSUE THREAD

**Issue by xxxtnco** [jeecgboot/JeecgBoot#7358]
##### 问题描述： 本地测试很多遍 都能正常使用 线上就不行了 

应该是没有获取到暴露的方法 

研究这个问题很久了 一直没有找到解决方法 广大的网友有没有 遇到过这种问题的 

补充一下 在线上通过 getCurrentInstance 获取的上下文打印 发现 SysMessageModal 这个组件为undefined 而本地确实可以拿到实例的 如下图 
##### 错误截图：

![image](https://github.com/user-attachments/assets/1c151517-8b21-4726-abc8-be09e8048ebf)
![image](https://github.com/user-attachments/assets/d267d88f-56a9-48ba-b553-a0e77638b228)
![image](https://github.com/user-attachments/assets/a31b619a-650d-46b2-92cb-4aad0063b249)
![image](https://github.com/user-attachments/assets/33708344-c815-461c-9c71-35476de82b8c)
![image](https://github.com/user-attachments/assets/50f1061c-1edf-4f92-abee-1f5fb521e6be)

![image](https://github.com/user-attachments/assets/56d5bcd4-8144-4bff-9ef3-a305dedd0a45)

#### 友情提示：

  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
那个版本号

**Comment by xxxtnco** [comment]
什么版本号

**Comment by xxxtnco** [comment]
> 那个版本号

node吗

**Comment by xxxtnco** [comment]
> 那个版本号

18.20.4

**Comment by xxxtnco** [comment]
> 那个版本号

可以优先处理一下这个问题吗，谢谢你

**Comment by zhangdaiscott** [comment]
jeecgboot 版本号

**Comment by xxxtnco** [comment]
> jeecgboot 版本号

3.7.0

**Comment by zhangdaiscott** [comment]
如何重现

**Comment by xxxtnco** [comment]
> 如何重现

啥意思

**Comment by zhangdaiscott** [comment]
我们测试无此问题

**Comment by aiftt** [comment]
用的 jeecg vue3  3.7.3 出现一样的问题：

<img width="1282" alt="Image" src="https://github.com/user-attachments/assets/b811a1a3-dbf7-48dc-b4bf-fbce5b081740" />

求怎么解决 @zhangdaiscott
