### ISSUE TITLE
online表单开发，同步后，功能测试，新增，出个白屏

### ISSUE THREAD

**Issue by jackrjl** [jeecgboot/JeecgBoot#7367]
##### 版本号：
3.7.0

##### 问题描述：
online表单开发，同步后，功能测试，新增，出个白屏，数据库已经有表了，无法新增数据

##### 错误截图：
![jeecgBoot2](https://github.com/user-attachments/assets/7e2b54d1-4b31-4ffd-ada3-fc2fc965b8f4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
怎么出现的

**Comment by jackrjl** [comment]
操作步骤就是：online表单开发，同步数据库，功能测试，新增，出个白屏，你自己操作一下，3.7.0版本

**Comment by zhangdaiscott** [comment]
无法重现

**Comment by jackrjl** [comment]
我换了个低版本3.4.0，出现同样问题
![jeecg-boot3 4 0](https://github.com/user-attachments/assets/f4483970-0409-49a9-8232-3b5ab2e156ca)

后端报

2024-10-21 14:10:43.474 [http-nio-8080-exec-2] [34mINFO [0;39m [36morg.jeecg.common.aspect.PermissionDataAspect:71[0
;39m - 拦截请求 >> /online/cgform/api/getData/be9dc64d53d74f0f83d44f46e3fa3999 ; 请求类型 >> GET .

**Comment by zhangdaiscott** [comment]
我们测试无此问题
