### ISSUE TITLE
修改了项目的根路径之后，启动时无法找到AbstractQueryBlackListHandler.class

### ISSUE THREAD

**Issue by tmq77** [jeecgboot/JeecgBoot#7369]
##### 版本号：
3.6.3

##### 问题描述：
修改了项目的根路径之后，启动时无法找到AbstractQueryBlackListHandler.class

修改后的工程已经使用很久，之前是使用`{"org.jeecg.common", "com.xxxx}`这样的形式扫描包，没有任何问题，现在需要引入online报表，将扫包的配置改为了`{"org.jeecg", "com.xxxx}`后，出现问题所述的错误，

AbstractQueryBlackListHandler这个类已因根路径修改后变更了package的全限定地址，理论上类加载时应自动寻找新的地址，但是现在启动时仍然回去寻找最初的路径
 [org/jeecg/common/util/security/AbstractQueryBlackListHandler.class] 

> 项目的根路径配置、mapper配置都是ok的，已经使用很久了

引入的报表依赖
```xml
<dependency>
      <groupId>org.jeecgframework.boot3</groupId>
      <artifactId>hibernate-re</artifactId>
      <version>3.6.1-GA</version>
</dependency>
```

##### 错误截图：
![image](https://github.com/user-attachments/assets/07faa082-4911-4147-9f07-325cc0421ea0)

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/qa
