### ISSUE TITLE
form表单，调用appendSchemaByField后，提交表单时报错

### ISSUE THREAD

**Issue by mysticdcat** [jeecgboot/JeecgBoot#7372]
##### 问题描述：form表单，调用appendSchemaByField后，提交表单时getValueType方法会报错，因为拿不到最新的schema

这里拿到的schema没有我appendSchema之后的那条数据，所以报错（提交表单时会调用validate方法，validate会调用getValueType）

##### 错误截图：

![image](https://github.com/user-attachments/assets/bedf992a-5425-41ff-ba32-57a1c89d467d)

![image](https://github.com/user-attachments/assets/48b26cd7-dfb5-44b7-ad0e-1e111af3bd0d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by mysticdcat** [comment]
你好  请问会修复吗

**Comment by jeecgDeveloper** [comment]
最新版本已经修复。

具体修改如下：
src/components/Form/src/hooks/useForm.ts
![image](https://github.com/user-attachments/assets/5692a47c-ac8d-456d-b1c2-ccc23aaa478a)
src/components/Form/src/hooks/useFormEvents.ts
![image](https://github.com/user-attachments/assets/776015d4-8de1-48e9-b71d-edfe6bf50e90)
src/components/Form/src/types/form.ts
![image](https://github.com/user-attachments/assets/644e4d82-6876-4920-a05a-e670eb2c4ab2)
src/components/Form/src/BasicForm.vue
![image](https://github.com/user-attachments/assets/c399fcc9-d5da-4e12-b499-cf2ff2611245)
src/utils/index.ts
![image](https://github.com/user-attachments/assets/499d1732-4246-4435-aeb8-d7bf5dfd5c97)
