### ISSUE TITLE
我设置了内网穿透，然后文件上传不成功，上传不了，但局域网是可以的，有哪位大佬知道是什么原因吗

### ISSUE THREAD

**Issue by 17774122108** [jeecgboot/JeecgBoot#7373]
##### 问题描述：
我设置了内网穿透，然后文件上传不成功，上传不了，但局域网是可以的，有哪位大佬知道是什么原因吗

##### 错误截图：
![错误截图](https://github.com/user-attachments/assets/d5f58d3b-2424-480b-b0ed-ab983545b77b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
debug跟踪代码，看错误提示

**Comment by 17774122108** [comment]
控制台不会出现任何的错误提示，都没有到后台




信天翁?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 我设置了内网穿透，然后文件上传不成功，上传不了，但局域网是可以的，有哪位大佬知道是什么原因吗 (Issue #7373)





 
debug跟踪代码，看错误提示

**Comment by 17774122108** [comment]
局域网下是正常的，没有问题，公共网络就会上传失败，




信天翁?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 我设置了内网穿透，然后文件上传不成功，上传不了，但局域网是可以的，有哪位大佬知道是什么原因吗 (Issue #7373)





 
debug跟踪代码，看错误提示

**Comment by 17774122108** [comment]
信天翁?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 我设置了内网穿透，然后文件上传不成功，上传不了，但局域网是可以的，有哪位大佬知道是什么原因吗 (Issue #7373)





 
debug跟踪代码，看错误提示
