### ISSUE TITLE
分支 springboot3_sas 发现 cloud版本下 xxljob新增了一些字段 db数据库文件未同步

### ISSUE THREAD

**Issue by FuGuiLiu** [jeecgboot/JeecgBoot#7375]
##### 版本号：
springboot3_sas 

##### 问题描述：
springboot3_sas Cloud下**xxljob** 代码有些mapper xml 例如表 **xxl_job_info** 加了一些字段 但是**db**目录文件夹未同步最新的表结构

##### 错误截图：
![image](https://github.com/user-attachments/assets/c835a4b1-593d-4b70-971e-04120d2b7241)
![image](https://github.com/user-attachments/assets/95f71cb4-dac0-4924-8306-05756b511cc7)

**Comment by EightMonth** [comment]
可以更新下代码，最新版本是有的
![image](https://github.com/user-attachments/assets/99037236-a28d-4a56-98b7-0dbb34572486)

**Comment by FuGuiLiu** [comment]
谢谢
