### ISSUE TITLE
仪表盘设计器API数据集报错 

### ISSUE THREAD

**Issue by yemangzheng** [jeecgboot/JeecgBoot#7376]
##### 问题描述：
仪表盘设计器API数据集报错 ,使用的自带的示例数据点击API解析报一下错误

##### 错误截图：
![微信截图_20241023171535](https://github.com/user-attachments/assets/7ae84b23-655c-4228-85fd-d611ed83ccba)
![image](https://github.com/user-attachments/assets/c0f3d0b2-0a6f-498d-9e17-5c3c127cf02f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
