### ISSUE TITLE
后端接收MQ消息并更新表，表是基于online报表建立和管理，更新表报错无权限

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/JeecgBoot#7377]
##### 版本号：

>=3.6.2

##### 问题描述：

1. 数据库表A 是通过纯前端低代码的 online 报表方式建立，并管理（非代码方式）
2. A的报表更新，要通过消费MQ消息来更新，部分字段来自MQ的消息内容

期望，有纯后端能处理此类情况的方式

##### 错误截图：

代码如：
```
        try {
            onlCgformHeadService.editManyFormData(cgformHeadId, new JSONObject(orderRecord));
        }catch (Exception e){
            e.printStackTrace();
        }
```

报错，无权限操作表
```
org.jeecg.common.exception.JeecgBootException: online修改表单数据异常:系统未找到当前登陆用户信息
```

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
MQ? 我们这边没用MQ

**Comment by huangwei2013** [comment]
没法避开异步通讯的场景吧

**Comment by huangwei2013** [comment]
哎，又被人为消灭需求
