### ISSUE TITLE
仪表盘地址栏传动态参数不生效

### ISSUE THREAD

**Issue by wildtree001** [jeecgboot/JeecgBoot#7380]
##### 版本号：
1.8.1-beta

##### 问题描述：
仪表盘地址栏传动态参数不生效

##### 错误截图：
![image](https://github.com/user-attachments/assets/fb8a0b37-3f40-4906-b22e-111a037222df)
![image](https://github.com/user-attachments/assets/0d5e24e5-a0e1-48cb-bcd2-875fdf0fe2c2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
已经实现，下个版本发布
