### ISSUE TITLE
在页面查询数据后，切换到另一个TAB，再切换回上一个TAB，查询条件没有了，页面也刷新了

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/JeecgBoot#7383]
##### 问题描述：
今天下载了最新的版本，发现个别页面查询后，切换TAB页，再切换回去，页面会刷新，有的不会刷新，查询条件还在。具体情况如下：
1.用户管理、角色管理，使用页面上方的查询工具查询后，切换到其他TAB，再切换回上一个，查询条件还在
2.数据字典、职务管理，同样查询后切换到其他TAB，再切换回来，页面就刷新，查询条件也没有了
3.用Online表单开发一个新页面，也是以上的情况2，下载代码后，放在项目代码中也是同样问题

是需要改哪里的代码或配置，才能达到像情况1的效果，即切换后页面不刷新，查询条件还在。

##### 错误截图：
![问题](https://github.com/user-attachments/assets/9cffc9fa-d50a-4e7f-b50a-00c9c7918f53)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by ddwolf715** [comment]
Online表单开发后下载代码，要怎么设置路由缓存？
数据字典、职务管理，也要设置吗？还是等代码更新呢？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/config/menu/cache.html
