### ISSUE TITLE
BasicTable在二级表头中，行编辑失效

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7384]
##### 问题描述：
BasicTable在二级表头中，行编辑失效

##### 错误截图：
![image](https://github.com/user-attachments/assets/d24899d7-de8b-4aef-b8e6-a49f47a89d75)
![image](https://github.com/user-attachments/assets/f3187a72-2a69-4e6f-b8ed-b7f7befa2054)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by ak-2019** [comment]
![image](https://github.com/user-attachments/assets/f5630cf9-4529-4c18-977a-1a3e48381433)
试了一下，可编辑单元格在二级表头里面也是不行的。

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。

你本地可按如下进行修改：
src/components/Table/src/hooks/useColumns.ts
![image](https://github.com/user-attachments/assets/23430601-401d-4671-9d2e-c2fa950d9737)
