### ISSUE TITLE
在使用openCustomModal时，show/hide控制会在多个自定义按钮间互相影响造成显示错误

### ISSUE THREAD

**Issue by TNTest** [jeecgboot/JeecgBoot#7387]
##### 版本号：
3.7.1

##### 问题描述：
自定义按钮+JS增强如果添加了超过一个， 在使用openCustomModal时，show/hide控制会在多个按钮间互相影响造成显示错误。

###### 举例：
定义两个按钮，出库，入库。 每个按钮弹出的界面只需要显示入库或者出库输入框。
按钮定义如下：
<img width="762" alt="image" src="https://github.com/user-attachments/assets/f9489d8a-1b77-4a6e-8672-e63c08d42dd2">
js增强代码：
```javascript
plus(row) {
  this.openCustomModal({
    row: row,
    title: '入库',
    width: 800,
    show: ['plus']
  });
}

minus(row) {
  this.openCustomModal({
    row: row,
    title: '出库',
    width: 800,
    show: ['minus']
  });
}
```

##### 错误截图：
使用时第一次打开是正常的：
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/94e45371-d208-4c76-babd-2305fc536ffc">
当使用另外一个按钮时显示隐藏逻辑就混在一起了，造成什么都不显示：
<img width="1253" alt="image" src="https://github.com/user-attachments/assets/5a4163a5-6efd-4955-9c2e-cef6903f7e44">

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
