### ISSUE TITLE
我不小心默认首页改了，我该如何把它改成原来的样子

### ISSUE THREAD

**Issue by blacksmall-mos** [jeecgboot/JeecgBoot#7389]
![image](https://github.com/user-attachments/assets/9e48a164-cd82-4bcb-ab87-d4ac13394c85)

**Comment by blacksmall-mos** [comment]
然后出现这个报错
![image](https://github.com/user-attachments/assets/a11ebc91-4c4f-45b2-9642-15f126ae6380)

**Comment by blacksmall-mos** [comment]
就是我改了菜单栏里面设置默认页面这一个选项，然后改完刷新回来左边的菜单栏都不见了

**Comment by zhangdaiscott** [comment]
你怎么改的，就原路还原

**Comment by blacksmall-mos** [comment]
但是左边的菜单栏不见了，该怎么改

**Comment by zhangdaiscott** [comment]
你怎么改的，我们也不知道
