### ISSUE TITLE
页面显示这个错误

### ISSUE THREAD

**Issue by blacksmall-mos** [jeecgboot/JeecgBoot#7391]
查询失败:Expected one result (or null) to be returned by selectOne(), but found: 2
![image](https://github.com/user-attachments/assets/da883601-ca8e-482b-8bc4-182a6f76bf01)

**Comment by zhangdaiscott** [comment]
按照格式发帖

**Comment by blacksmall-mos** [comment]
就是左边菜单里有一个栏可以选择默认页面，然后我选择了默认页面选择了一个之后刷新就显示了这个错误，是不是因为navicat过期了的缘故
