### ISSUE TITLE
ERP一对多表的字段不显示

### ISSUE THREAD

**Issue by bugw** [jeecgboot/JeecgBoot#7394]
##### 问题描述：
使用erp的一对多模式，表的字段刷新后不显示。如果在列设置里重置字段，保存刷新后，子表只剩一个字段，如果将子表列设置重置如图：
![image](https://github.com/user-attachments/assets/a8582eec-c559-4448-a0ac-5544b3fd0425)
保存后主表只剩一个字段，浏览器清空缓存并硬性重新加载了一样的。

##### 1. 重置主表
![image](https://github.com/user-attachments/assets/c2371b11-29bd-4cd6-bd2a-bedfdf18ba0b)
##### 2. 重置子表
![image](https://github.com/user-attachments/assets/6ae46bcb-89cf-4263-b979-a37780c076bc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
刚克隆下来的代码，经查无复现。确定版本对吗？你可官网上试试或者克隆一份纯净的代码再试下
https://github.com/user-attachments/assets/2a350327-4dea-44d9-8fb6-9c3a4f0becf6

**Comment by Missing-C** [comment]
> 刚克隆下来的代码，经查无复现。确定版本对吗？你可官网上试试或者克隆一份纯净的代码再试下 https://github.com/user-attachments/assets/2a350327-4dea-44d9-8fb6-9c3a4f0becf6

相同情况，主表隐藏一个字段后，切换另一个子表只显示操作列或者重复的主表显示字段，
![image](https://github.com/user-attachments/assets/fb64f9db-cc8a-4bc0-82e7-40dcc8fd4d35)
![image](https://github.com/user-attachments/assets/e63dd7b8-a808-4586-9496-4a735926c697)

**Comment by jeecgDeveloper** [comment]
> > 刚克隆下来的代码，经查无复现。确定版本对吗？你可官网上试试或者克隆一份纯净的代码再试下 https://github.com/user-attachments/assets/2a350327-4dea-44d9-8fb6-9c3a4f0becf6
> 
> 相同情况，主表隐藏一个字段后，切换另一个子表只显示操作列或者重复的主表显示字段， ![image](https://private-user-images.githubusercontent.com/55477307/381036621-fb64f9db-cc8a-4bc0-82e7-40dcc8fd4d35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDI1NjIsIm5iZiI6MTczMDIwMjI2MiwicGF0aCI6Ii81NTQ3NzMwNy8zODEwMzY2MjEtZmI2NGY5ZGItY2M4YS00YmMwLTgyZTctNDBkY2M4ZmQ0ZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDA5NTA1NGY2NWI2YjFkNDEwOTY0MDZjZDUzOWMyMjdkZDZhY2Q2N2QwNjA2ODlhNGI5ODRiNTNmZjY0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MhY_MIcy-vyGur1KCfMY1aXNctbjBqjrarRSv5Nf3hM) ![image](https://private-user-images.githubusercontent.com/55477307/381036627-e63dd7b8-a808-4586-9496-4a735926c697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDI1NjIsIm5iZiI6MTczMDIwMjI2MiwicGF0aCI6Ii81NTQ3NzMwNy8zODEwMzY2MjctZTYzZGQ3YjgtYTgwOC00NTg2LTk0OTYtNGE3MzU5MjZjNjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjUzNTMxNWE5YjdjNTUwYTZkZjY3YmFlZGZjNmU4MzliYWI1Y2JhNDJhZmNjZDg3ZDIwN2QzNjhkMjUzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hI9KMapBZW0ss9yP3l2URt_s23oos1X6qFPFVC5uLjU)

你是什么版本？之前确实有这个问题，但是在6月份已经修复了。你通过 [演示系统](https://boot3.jeecg.com/)查看是否可重现。

演示系统测试结果：
https://github.com/user-attachments/assets/364c2322-f7a5-4894-ad51-3de1f91c94af
