### ISSUE TITLE
前端部分报错[plugin:vite:vue-jsx] Cannot find package 'C:\Users\123\Desktop\JeecgBoot-master\pincone_system\jeecgboot-vue3\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.4.9_@types+node@20.16.13_less@4.2.0_terser@5.36.0__vue@3.5.12_typescript@4.9.5_\node_modules\@babel\plugin-transform-typescript\lib\index.js' imported from C:\Users\123\Desktop\JeecgBoot-master\pincone_system\jeecgboot-vue3\node_modules\.pnpm\@vitejs+plugin-vue-jsx@3.1.0_vite@5.4.9_@types+node@20.16.13_less@4.2.0_terser@5.36.0__vue@3.5.12_typescript@4.9.5_\node_modules\@vitejs\plugin-vue-jsx\dist\index.cjs Did you mean to import "@babel/plugin-transform-typescript/lib/index.js"?

### ISSUE THREAD

**Issue by BoBoloverrrr** [jeecgboot/JeecgBoot#7396]
##### 版本号：
v3.7.1

##### 问题描述：
vue3部分安装依赖之后运行起来前端出现这样的错误，另外一台设备不会出现这样的问题，试过重新拉取代码也解决不了

##### 错误截图：
![报错截图](https://github.com/user-attachments/assets/23b9cc45-70b1-494e-a324-8ef70d61f871)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
删除依赖，重新install
或者确认下node版本

**Comment by zhangdaiscott** [comment]
是因为文件的路径太长导致

https://blog.csdn.net/weixin_43235500/article/details/142144989
https://blog.csdn.net/qq_25996219/article/details/140328092
