### ISSUE TITLE
前端vben框架整合问题

### ISSUE THREAD

**Issue by mistHuShuai** [jeecgboot/JeecgBoot#7397]
##### 版本号：

3.7.1

##### 问题描述：

前端vben框架整合问题

请问一下vben5.x在你们的更新计划之中吗，如果在计划中，大概什么时候能做一个更新升级。

**Comment by zhangdaiscott** [comment]
无

**Comment by sunjie798893816** [comment]
vben。。。。我估计jeecg 选择vben都快后悔死了，升级是不可能升级的
