### ISSUE TITLE
jeecgboot如何与乾坤集成后，子应用前端继续使用jeecgboot框架

### ISSUE THREAD

**Issue by xiaoqi003** [jeecgboot/JeecgBoot#7401]
##### 版本号：
vue2

##### 问题描述：
请教大师，我想把jeecgboot （vue2的版本）与qiankun完成分布式前端，但子应用仍然采用jeecgboot的前端框架，这样的话，每个子应用都附带有一个数据库，就与主应用的数据库产生冲突了，大师有好的方案没
我用jeecgboot做了很多模块了，现在想把这些模块的前端用乾坤qiankun拆成分布式的，发现子应用如果带有数据库可以通的，但我的子应用只想用jeecgboot的前端基本风格与框架，不想再带着数据库，因为主应用已完成了用户管理，菜单管理功能，这个一直没搞定

##### 错误截图：

无

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下个版本vue3会提供jeecgboot前端作为乾坤子应用的方案代码
https://help.jeecg.com/java/publish/qiankun-micro.html
