### ISSUE TITLE
CollapseContainer组件怎么设置默认不展开？

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/JeecgBoot#7402]
##### 版本号：
vue3 3.4.4

##### 问题描述：

CollapseContainer组件怎么设置默认不展开？
我看组件中没有这个设置选项

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已增加，下一版本发布。
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/0aaeee33-1a02-4574-a1cc-fe2a18ca9c83">
