### ISSUE TITLE
BasicTable分页切换无效

### ISSUE THREAD

**Issue by fenghenqing** [jeecgboot/JeecgBoot#7403]
##### 错误截图：
![image](https://github.com/user-attachments/assets/391b368b-c325-4f10-b293-0c41508f0dcc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
经测试，无问题。你下载最新的纯净版试试，看是否本地更改了代码导致。
![iShot_2024-11-11_13 54 15](https://github.com/user-attachments/assets/9b603698-5a90-4066-989e-5a3b48cb3e4d)
测试代码：
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/c4855271-de8e-4112-a689-31d39be648c8">
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/40016875-592d-48ce-b306-dbfff3ae2444">
