### ISSUE TITLE
online表单开发设置好页面控件生成代码后依然显示文本框

### ISSUE THREAD

**Issue by changguoxu** [jeecgboot/JeecgBoot#7404]
##### 版本号：
3.7.1

##### 问题描述：

我在online表单开发创建一张表单设置页面属性控件类型为关联记录，在online表单开发能力测试上没问题，但是我生成代码后的前端页面就是文本框了

##### 错误截图：

![Uploading 微信截图_20241029111234.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
图裂了

**Comment by zhangdaiscott** [comment]
无回复关闭
