### ISSUE TITLE
部门选择用户同时全部选择两页用户，回显到父页面。第二页用户显示的不是真是姓名

### ISSUE THREAD

**Issue by wm92646364** [jeecgboot/JeecgBoot#7405]
##### 问题描述：
自定义组件页面中，部门选择用户 同时全部选择两页用户时，回显到父页面。第二页用户显示的不是真是姓名，而是用户名。
角色选择组件、职务选择组件 存在相同的问题

##### 错误截图：
![1](https://github.com/user-attachments/assets/8416eb34-fb99-4b11-a846-5d9cd164735c)
![2](https://github.com/user-attachments/assets/5b1f9e37-f142-4609-bace-cf4cf61f03c4)
![3](https://github.com/user-attachments/assets/25a7af00-51cc-4c8b-a65f-e8eac96e7e1f)
![4](https://github.com/user-attachments/assets/ce458d1f-96d4-40dc-a49a-39dcb74439d4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
你本地可在src/components/Form/src/jeecg/hooks/useSelectBiz.ts文件按照如下已进行修复
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/bd4a10ad-90c9-406f-b50f-307fc9105f3a">
