### ISSUE TITLE
集成MongoDB编译报错

### ISSUE THREAD

**Issue by yujiayong123** [jeecgboot/JeecgBoot#7407]
##### 版本号：
2.1.3.RELEASE

##### 问题描述：

集成mongodb后，引入mongodbTemplete编译报错，但是ctrl能进入源码

##### 错误截图：
![QQ截图20241029162713](https://github.com/user-attachments/assets/e6053856-517a-4bc2-9637-f693b5865a43)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本号多少？

**Comment by yujiayong123** [comment]
2.3.0

**Comment by zhangdaiscott** [comment]
jeecgboot的版本号，pom截图

**Comment by yujiayong123** [comment]
![Uploading QQ截图20241101131146.png…]()

**Comment by zhangdaiscott** [comment]
图裂

**Comment by zhangdaiscott** [comment]
版本太老了，你可以自己多百度研究下
