### ISSUE TITLE
循环块无法使用，是灰色的

### ISSUE THREAD

**Issue by Roko-181** [jeecgboot/JeecgBoot#7408]
##### 版本号：
1.8.1

##### 问题描述：

选中区域右键循环块是灰色的

##### 错误截图：

![574FFDD21E8AD918E187E8DA59865589](https://github.com/user-attachments/assets/643d4fbe-1370-4748-bdba-0b14071487a6)

![6C3FD52B8F288FAA2A45A02F0020B65C](https://github.com/user-attachments/assets/afe073bc-8ca6-4de2-b119-f5ce4ade457f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
http://jimureport.com/vip

企业版功能
