### ISSUE TITLE
金仓数据库

### ISSUE THREAD

**Issue by GreatWisd0m** [jeecgboot/JeecgBoot#7410]
##### 版本号：
Jeecg  Boot Version: 3.7.1
Spring Boot Version: 2.7.18 (v2.7.18)
##### 问题描述：
我先将mysql数据库的信息转移到金仓数据库中，期间没有报错。然后打算连接金仓数据库，但是一直不行。按照开发文档的指示运行结果就是如下：

##### 错误截图：
![image](https://github.com/user-attachments/assets/7f67c023-02ae-4e77-8b03-6a5c9d04b4a2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
转库有问题，定时任务的几个表需要单独执行下原始初始化SQL
