### ISSUE TITLE
BasicTable 表格怎么自定义合计行内容

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7414]
##### 问题描述：我想统计当前查询条件下数据之和，但是目前仅支持统计当前页面记录的。自定义调用接口的时候，尝试了两种思路，均失败了，请指点一下。
1. summaryFunc: onSummary  在自定义的合计方法中，写接口调用数据会报错
![image](https://github.com/user-attachments/assets/298bf8b4-cf19-47b8-9797-4806acfb63e8)

2. summaryData:[amountTotal.value] 自定义合计数据怎么在每次查询之后更新summaryData的值呢？
在表单的自定义提交按钮submitFunc: customSubmitFunc方法中，调用接口更新没有效果

##### 错误截图：
![image](https://github.com/user-attachments/assets/948dda99-2e6c-4bfb-8301-b264a4d1e156)
![image](https://github.com/user-attachments/assets/c27d058f-c11c-4b01-a90c-28817de105e9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
不支持异步写法。

给个思路：既然列表和合计是两个接口，你可以点击按钮时拿到条件你先调用合计的接口拿到总数，填充在页面的全局变量，再去调用列表接口，渲染时onSummary可以填充你之前合计接口的值了。

**Comment by ak-2019** [comment]
搞定了，感谢！
