### ISSUE TITLE
shardingsphere 集成异常

### ISSUE THREAD

**Issue by FuFengs** [jeecgboot/JeecgBoot#7416]
##### 问题描述：
单体项目 集成shardingsphere 尝试过 在system-start模块 和 system-biz 模块引入
	<dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-boot-starter-shardingsphere</artifactId>
        </dependency>
报错 缺失 Type
![image](https://github.com/user-attachments/assets/78ba1df6-f0a2-4c62-a171-3d5a31ca22d9)

在引入shardingsphere 官方依赖
         <dependency>
		<groupId>org.apache.shardingsphere</groupId>
		<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
		<version>5.1.1</version>
时候存在异常;
借鉴过 Issue https://github.com/jeecgboot/JeecgBoot/issues/4149
没有找到图片上的类
![image](https://github.com/user-attachments/assets/5ca254bd-6807-4a32-89fd-ee7afdfcae79)

##### 错误截图：
![image](https://github.com/user-attachments/assets/1f07dc2d-f516-4abd-8cca-6253eb853ad7)
![image](https://github.com/user-attachments/assets/206fa96b-1693-46ab-b45f-b0a02d41efde)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by EightMonth** [comment]
请参考官方文档以及对应案例进行集成，已测试最新案例启动成功
文档：https://help.jeecg.com/java/springcloud/starter/shardingsphere.html

运行效果：
![image](https://github.com/user-attachments/assets/262d7a52-8f8e-4304-bcda-823bb59e90c9)
