### ISSUE TITLE
积木报表配置菜单时参数怎么自定义

### ISSUE THREAD

**Issue by zjfksj** [jeecgboot/JeecgBoot#7418]
##### 版本号：
3.7.0

##### 问题描述：
我想在这个地方自定义拼接参数传到积木报表里，每次请求都携带上这个参数，应该怎么改

##### 错误截图：
![83c9c71e5d47d704777fa5d87bbc08b](https://github.com/user-attachments/assets/9d0c027d-d647-45e3-8be4-963725f3b0d3)
![cf5bf140a7cb9258a46b753eb1abd52](https://github.com/user-attachments/assets/45033bac-9e77-44d7-a26d-208c37e74620)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zjfksj** [comment]
![image](https://github.com/user-attachments/assets/f407c78f-9ed5-4889-9d1e-d7d205a3c9a7)

**Comment by zjfksj** [comment]
![image](https://github.com/user-attachments/assets/32e2958b-bf7d-45dc-941d-bf8f60b29a09)

**Comment by zhangdaiscott** [comment]
动态的只支持jeecg的默认  租户和token，是专门改的代码，你自定义的不支持，你可以写死传递出参数值
