### ISSUE TITLE
验证码无法打开

### ISSUE THREAD

**Issue by mortal706** [jeecgboot/JeecgBoot#7419]
##### 问题描述：
验证码无法打开

##### 错误截图：
![屏幕截图 2024-11-02 194953](https://github.com/user-attachments/assets/61e3a17f-c1b7-427d-bc13-475bce054c2e)
![屏幕截图 2024-11-02 194917](https://github.com/user-attachments/assets/ca2b75d5-f866-42cf-9ced-7c66ad4ba065)
![屏幕截图 2024-11-02 194820](https://github.com/user-attachments/assets/491508db-6327-4b95-85d7-85a25d140900)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/c3c6189c-1996-403b-9510-47d9f5aed6f8)

1、首先生产配置不需要配置代理

![image](https://github.com/user-attachments/assets/9fd307b5-7f62-4de9-bd86-39c3f6115fcb)
2、你的配置参数怎么都少了下划线横线
3、nginx映射为什么没有项目名 jeecg-boot
![image](https://github.com/user-attachments/assets/449d5910-75ea-4147-92ec-62244a586aa0)
