### ISSUE TITLE
SysBaseApiImpl.java:758:5 java: 方法不会覆盖或实现超类型的方法

### ISSUE THREAD

**Issue by zhwm12** [jeecgboot/JeecgBoot#7421]
##### 版本号：
3.7.1

##### 问题描述：
src/main/java/org/jeecg/modules/system/service/impl/SysBaseApiImpl.java

	@Override          java: 方法不会覆盖或实现超类型的方法
// src/main/java/org/jeecg/common/system/api/ISysBaseAPI.java
    /**
     * 20获取所有角色
     * @return
     */
    public List<ComboModel> queryAllRole();

// src/main/java/org/jeecg/modules/system/service/impl/SysBaseApiImpl.java
	@Override
	public List<ComboModel> queryAllRole() {
		List<ComboModel> list = new ArrayList<ComboModel>();
		List<SysRole> roleList = roleMapper.selectList(new QueryWrapper<SysRole>());
		for(SysRole role : roleList){
			ComboModel model = new ComboModel();
			model.setTitle(role.getRoleName());
			model.setId(role.getId());
			list.add(model);
		}
		return list;
	}
	
// src/main/java/org/jeecg/modules/api/controller/SystemApiController.java
     * 获取所有角色 带参
     * roleIds 默认选中角色
     * @return
     */
    @GetMapping("/queryAllRole")
    public List<ComboModel> queryAllRole(@RequestParam(name = "roleIds",required = false)String[] roleIds){
        if(roleIds==null || roleIds.length==0){
            return sysBaseApi.queryAllRole();
        }else{
            return sysBaseApi.queryAllRole(roleIds);
        }
    }

JeecgBoot\jeecg-boot\jeecg-module-system\jeecg-system-biz\src\main\java\org\jeecg\modules\system\service\impl\SysBaseApiImpl.java:758:5
java: 方法不会覆盖或实现超类型的方法
##### 错误截图：
![18](https://github.com/user-attachments/assets/f4a983ae-2b8e-4999-892d-9ce1a0aae9f5)

![17](https://github.com/user-attachments/assets/495740d8-144e-4f7b-9ad6-ebf5ca19c094)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhwm12** [comment]
更改本地数据库为:  root@127.0.01 密码root，不要改application-dev.yml
里面的username: root password: root
mvn install
java -jar jeecg-system-start-3.7.1.jar
这次顺利达到
        Local:          http://localhost:8080/jeecg-boot/
        External:       http://10.112.65.77:8080/jeecg-boot/
        Swagger文档:    http://10.112.65.77:8080/jeecg-boot/doc.html
以上！

**Comment by JIANBANGHAI** [comment]
卧槽，我也遇到这个问题了
