### ISSUE TITLE
online在线报表的字典翻译功能存在bug

### ISSUE THREAD

**Issue by zongxing719** [jeecgboot/JeecgBoot#7423]
##### 版本号：
3.7.1

##### 问题描述：
我在使用online报表的弹框时，发现有这个问题，就是配置报表的时候，字典字段配置的字典编码没有生效。

##### 错误截图：
![04c303982d5ebef361826e25b1191bd4](https://github.com/user-attachments/assets/ee474da9-0130-4da6-927b-73ca51970920)

![image](https://github.com/user-attachments/assets/3205f2c2-1427-4db3-9b2d-2a06b63065a3)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by zongxing719** [comment]
zy是什么意思？？？

**Comment by jeecgDeveloper** [comment]
经测试无问题。
![iShot_2024-11-11_14 31 39](https://github.com/user-attachments/assets/d6801440-096c-48b0-ab32-f4c9fe8d0780)
你看看这个接口dictOptions返回来的是什么？字典的值是从这个地方读取的。
![image](https://github.com/user-attachments/assets/2df8422e-147e-4e94-b86c-943ce4bb1f3a)

**Comment by zongxing719** [comment]
![image](https://github.com/user-attachments/assets/4d8f67dc-799a-49e6-ad28-22476ef080a8)
大佬，请问还有可能是哪里出了问题？

**Comment by zongxing719** [comment]
找到原因了，我之前对字典组件做过调整，增加了参数字段。

**Comment by zongxing719** [comment]
找到原因了，我之前对字典组件做过调整，增加了参数字段。
![image](https://github.com/user-attachments/assets/0abc3140-2119-4f61-9f07-777dc70e20e0)

**Comment by zhangdaiscott** [comment]
重现了，字典加载是在登录时候做的，所以这个问题退出重新登录就好了
