### ISSUE TITLE
shardingsphere 

### ISSUE THREAD

**Issue by FuFengs** [jeecgboot/JeecgBoot#7424]
##### 问题描述：
按照 https://www.kancloud.cn/zhangdaiscott/jeecg-boot/3085227 集成单体项目分表 控制台打印日志显示集成成功 但是没有按照日志类型路由到对应的表
依赖:
		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>jeecg-boot-starter-shardingsphere</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>guava</artifactId>
					<groupId>com.google.guava</groupId>
				</exclusion>
			</exclusions>
		</dependency>
因为启动时候 guava依赖报错依赖冲入所以排除了
配置:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    props:
      sql-show: true
    rules:
      sharding:
        binding-tables: sys_log
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
        sharding-algorithms:
          table-classbased:
            props:
              strategy: standard
              algorithmClassName: org.jeecg.sharding.SyslogShardAlgorithm
            type: CLASS_BASED
        tables:
          sys_log:
            actual-data-nodes: ds0.sys_log$->{0..1}
            table-strategy:
              standard:
                sharding-algorithm-name: table-classbased
                sharding-column: log_type

##### 错误截图：

![Snipaste_2024-11-04_11-41-27](https://github.com/user-attachments/assets/5b0f158d-65f8-464c-9832-783b155c1173)

![Snipaste_2024-11-04_11-41-56](https://github.com/user-attachments/assets/d68577ee-0c5a-4e8d-8a33-f22624276639)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zj

**Comment by EightMonth** [comment]
经测试，没有问题，如果旧版本有问题，建议升级至最新版，或对应代码修改

`Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594966749360130, admin, 2024-11-21 21:49:24.322, 分库分表测试, 0, 20]
Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594974500433921, admin, 2024-11-21 21:49:26.184, 分库分表测试, 0, 22]
Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594974714343425, admin, 2024-11-21 21:49:26.251, 分库分表测试, 0, 24]
Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594975137968130, admin, 2024-11-21 21:49:26.342, 分库分表测试, 0, 26]
Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594975406403585, admin, 2024-11-21 21:49:26.409, 分库分表测试, 0, 28]
Actual SQL: ds0 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594975876165633, admin, 2024-11-21 21:49:26.516, 分库分表测试, 0, 30]

Actual SQL: ds1 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594974399770626, admin, 2024-11-21 21:49:26.16, 分库分表测试, 0, 21]
Actual SQL: ds1 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594974613680130, admin, 2024-11-21 21:49:26.213, 分库分表测试, 0, 23]
Actual SQL: ds1 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594974957613058, admin, 2024-11-21 21:49:26.294, 分库分表测试, 0, 25]
Actual SQL: ds1 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594975322517506, admin, 2024-11-21 21:49:26.369, 分库分表测试, 0, 27]
Actual SQL: ds1 ::: INSERT INTO sys_log0 (id, create_by, create_time, log_content, log_type, operate_type) VALUES (?, ?, ?, ?, ?, ?) ::: [1859594975754530818, admin, 2024-11-21 21:49:26.487, 分库分表测试, 0, 29]`

![image](https://github.com/user-attachments/assets/0580b444-76fb-4c6a-9610-f7638db1ea83)

![image](https://github.com/user-attachments/assets/dc99bbca-6b92-47aa-94b5-898e6b334c33)

**Comment by FuFengs** [comment]
现在你这边测试的版本是 3.5.3 的版本吗
我重新拉一套代码看看

**Comment by FuFengs** [comment]
我没有用包含测试类的依赖  只引入了 jeecg-boot-starter-shardingsphere 依赖 使用测试类测试 不会走分表路由

**Comment by FuFengs** [comment]
使用 3.7.1的版本  集成shardingsphere 不走分表路由 全部插入 sys_log 里边了

**Comment by FuFengs** [comment]
没有用包含测试类的依赖 只引入了 jeecg-boot-starter-shardingsphere 依赖 使用测试类测试 不会走分表路由 @EightMonth
