### ISSUE TITLE
vue3 如何打包成 测试包?

### ISSUE THREAD

**Issue by lihongguang-lhg** [jeecgboot/JeecgBoot#7426]
##### 问题描述：
vue3 如何打包成 测试包? 目前只有开发, 生产, 我想打包一个测试包

##### 错误截图：

![image](https://github.com/user-attachments/assets/5567ebe0-70ae-4c79-a43a-a471609977b3)
具体如何配置呢?

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by vvyman** [comment]
构建命令上需要添加vite build --mode <环境名>， 不添加默认是 production，这个报错试试把 dist 文件夹删掉再 build 一次

**Comment by lihongguang-lhg** [comment]
> 构建命令上需要添加vite build --mode <环境名>， 不添加默认是 production，这个报错试试把 dist 文件夹删掉再 build 一次

我把dist 删掉,在重新build 成功,  谢谢大佬

**Comment by lihongguang-lhg** [comment]
> 构建命令上需要添加vite build --mode <环境名>， 不添加默认是 production，这个报错试试把 dist 文件夹删掉再 build 一次

我把dist 删除 然后在build一次成功了, 但是打的包还是默认的 prod的包 没有打到 我的测试包, 怎么弄呢

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
经测试，无异常。

vite build --mode test


<img width="1511" alt="image" src="https://github.com/user-attachments/assets/a99c2505-dc98-4f24-af67-381b02022e37">
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/dcfd827a-15b4-4e1e-8feb-1269b831bd41">
![image](https://github.com/user-attachments/assets/2e30297e-bcc8-4c6a-bfdf-3fa87c624b34)
![image](https://github.com/user-attachments/assets/352dfd2f-3275-46f6-95dd-f999de2d68ab)
