### ISSUE TITLE
basicTable单选框部分消失

### ISSUE THREAD

**Issue by guanjieyanzoudashi** [jeecgboot/JeecgBoot#7427]
##### 错误截图：
![845b1ffd9e480888b1a273f182c1af5](https://github.com/user-attachments/assets/e16dc59a-3ab8-4b9b-b0ae-fe166af97156)
![c34c56ed821a2c7ff7826c5cd1156cd](https://github.com/user-attachments/assets/6a5154ae-10c8-42bd-ba0e-01cd6ed2b38d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级版本，老版本的bug
