### ISSUE TITLE
表格点击“编辑”的时候，onChange的option第一次不回显（是undefined）

### ISSUE THREAD

**Issue by zgya** [jeecgboot/JeecgBoot#7430]
##### 版本号：

3.7.0
##### 问题描述：
表格点击“编辑”的时候，onChange的option第一次不回显（是undefined）

##### 错误截图：
![0% M(V 1(%U$PO9CQ7K8EE](https://github.com/user-attachments/assets/d340c7e5-95dc-465b-9802-058c12f775c7)

![XAJ20ER1AU66A6@IO3Y$ EK](https://github.com/user-attachments/assets/f196e4d4-6e08-450b-8aa3-97eaa4320674)

![W4YOL1_3~0706TLER6F8@N8](https://github.com/user-attachments/assets/fb464682-93ea-4a57-92ca-f58c9d36884f)
![C1(}} T$JS7CA0)M3X~}2J2](https://github.com/user-attachments/assets/1c2adfb1-fc8d-40d0-8161-bce12136099f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
经测试，无法重现。请提供更详细的信息

![iShot_2024-11-11_15 23 02](https://github.com/user-attachments/assets/f3de5728-c2a9-4e70-aa37-3ad8050ac2fd)


你可在系统用户页面进行测试，如果还有问题可下载一份最新的代码测试下，看是本身就带了的问题还是后期修改了代码导致的
 src/views/system/user/user.data.ts 
 
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/80853120-572a-4633-be4d-a7cbb760efa4">
