### ISSUE TITLE
怎么遍历JVxeTable里面的值？特别是新增加行的临时rowkey

### ISSUE THREAD

**Issue by afearboy** [jeecgboot/JeecgBoot#7431]
##### 版本号：

3.7.2
##### 问题描述：
1、在实际使用中，JVxeTable表的值首先生成，在生成后，通过外部某个值的变化，需要同时变化JVxeTable的相应值，通过datasource或setvalue, 但对于新增的行，没有办法拿到rowkey id, 不能使用setvalues，请问如何去拿到新表的rowkey，或者怎么遍历去更新我需要更新的值。请提供一个样例。

2、另外，我使用了另外一种方法来更新值，即通过循环来获取JVxeTable的值，然后通过datasource来改变他原来的值，但是对于 jveTable类型为JVxeTypes.selectDictSearch，他的值可以获取，但是不能赋予，赋予后一直为空。

##### 错误截图：

第一种方法我是没有rowkey id值。

第二种我用了一下代码
  这是类型设置：
    title: '子项分配人',
      key: 'subMgr',
      type: JVxeTypes.selectDictSearch,
 这是循环push.

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by MuShan-bit** [comment]
dataSource 是单向传递的，所以你只能通过dataSource初始化表格，但是修改表格 dataSource 不会变更。
![image](https://github.com/user-attachments/assets/2796dc4e-f1a4-4846-8b3c-4754bf97a893)
需要通过 ref 拿到组件实例，然后调用文档中的方法

**Comment by MuShan-bit** [comment]
你不要使用dataSource来改变表格的值。dataSource只有一个作用，就是编辑的时候初始化数据，和新增的时候置空数据。
并且初始化数据只用于已经存储到数据库中的数据。因为通过dataSource更新的数据是不会置空id的，而没有id的时候他会提供一个id为"row_xxx"，这东西存数据库里会出现主键重复的。你必须使用 addRows 和 pushRows来添加数据，当然可以使用 dataSource = [] 来置空表格。
![image](https://github.com/user-attachments/assets/b3119d20-1a29-4a81-880f-6290184d1e5a)
![image](https://github.com/user-attachments/assets/687e414c-42cd-40c1-add9-a2f8463d120b)
![image](https://github.com/user-attachments/assets/ac4856fa-bcc7-49cf-aa6e-c8327ddab5d6)
下拉框你用错组件了：
![image](https://github.com/user-attachments/assets/65135e94-a950-4cf8-8da3-b01c094ef93d)

**Comment by afearboy** [comment]
我解决了。如果是初始化数据里面有，那么用getTableData来获取数据进行更新，就存在id,如果初始化没有数据，就用getNewDataWithId，然后通过setValues设置值就行了。 至于你说的pushRows，我也push了map数据，但是用pushrows一直出错。问题解决了就算了，谢谢关注。
