### ISSUE TITLE
parent pom.xml 不对

### ISSUE THREAD

**Issue by sycao5** [jeecgboot/JeecgBoot#7432]
##### 问题描述：

Maven版本3.8.3, 然后编译的时候就出现了，parent pom.xml 不对。

##### 错误截图：

[ERROR]     Non-resolvable parent POM for org.jeecgframework.boot:mox-dms-base-core:2.4.2: The following artifacts could not be resolved: org.jeecgframework.boot:mox-dms-base:pom:2.4.2 (absent): org.jeecgframework.boot:mox-dms-base:pom:2.4.2 was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
补充版本号

**Comment by sycao5** [comment]
是的版本号不一致，已经修好了。
