### ISSUE TITLE
【3.7.0_all】vue3 数据字典优化建议

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7433]
##### 版本号：
3.7.0_all

##### 问题描述：

vue3目前的数据字典 重新添加 编辑修改 值后 默认都还是读取缓存的字典值 每次都得退出登录才能更新字典值，
点击个人信息右上角的刷新缓存 再刷新浏览器好像也没有什么作用，
 有没有更好的优化方案？
还有可以告知一下下个版本的发布时间吗 谢谢

##### 错误截图：

![image](https://github.com/user-attachments/assets/57fad065-6ef6-48b6-bec2-009510532e71)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
字典修改会自动更新缓存，不是吗

**Comment by zhangdaiscott** [comment]
好，我们看下

**Comment by benben120** [comment]
> 好，我们看下

大概什么时间发布下一个版本呢

**Comment by zhangdaiscott** [comment]
ws

**Comment by EightMonth** [comment]
修改字典时，前端缓存未变更
![5327bc0d3eaf467e87c0e6216b12eecd](https://github.com/user-attachments/assets/0640cea2-eb30-4cde-9c25-b335dc47685f)
![0765ee0ec3828239a51279412e82c389](https://github.com/user-attachments/assets/5c849663-2714-46be-b8df-3d41834336ec)

**Comment by jeecgDeveloper** [comment]
已优化，待新版本发布，你可以参考如下修改，刷新缓存的时候重新设置一下
```
userStore.setAllDictItems(res.result);
```
![image](https://github.com/user-attachments/assets/0eae664d-a74f-4e9e-b918-51a322776325)
