### ISSUE TITLE
initCodeGenerateDbConfig 失败

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#7435]
##### 版本号：
3.7.0

##### 问题描述：
放开了CodeGenerateDbConfig， 注释了jeecg_database.properties， 想取yml中的配置作为代码生成器导入表的来源
![image](https://github.com/user-attachments/assets/2dfad4e0-3d9f-487e-873a-ba71ec6b5565)
![image](https://github.com/user-attachments/assets/1d0223ef-f5cf-4b57-afe7-5af85f2cc05b)

但是启动报错Can't find resource for bundle java.util.PropertyResourceBundle, key diver_name， 请问org.jeecgframework.codegenerate.a是在什么地方初始化的，这个报错是什么问题呢

##### 错误截图：
![image](https://github.com/user-attachments/assets/1d0223ef-f5cf-4b57-afe7-5af85f2cc05b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by hsql** [comment]
第二个截图错了
![image](https://github.com/user-attachments/assets/2bda28ec-dedc-4912-afbd-563b4a591bd1)

**Comment by hsql** [comment]
请看这个类里的注释，这里说“【加了此类，则online模式DB连接，使用平台的配置，jeecg_database.properties配置无效”， 那如果CodeGenerateDbConfig这个类也放开，jeecg_database.properties也放开，最终使用的是哪个链接呢
![image](https://github.com/user-attachments/assets/3eb3ab41-984a-450e-ad56-1c07369b4e71)

**Comment by zhangdaiscott** [comment]
CodeGenerateDbConfig

**Comment by hsql** [comment]
好的，我之前以为jeecg_database.properties就没用了，把jeecg_database.properties注释了，我放开再试下，感谢

**Comment by hsql** [comment]
可以了，感谢
