### ISSUE TITLE
如何删除online 表单字段

### ISSUE THREAD

**Issue by wendyayang** [jeecgboot/JeecgBoot#7438]
##### 问题描述：

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/689342f2-e778-40f5-aba8-cdc2918792b2">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
勾选
![image](https://github.com/user-attachments/assets/b70ad743-6c71-4b67-a31b-c33e83ef78f0)
