### ISSUE TITLE
online配置

### ISSUE THREAD

**Issue by dszhang163com** [jeecgboot/JeecgBoot#7440]
##### 版本号：
3.7.1

##### 问题描述：
生成不了后端代码

##### 错误截图：

![image](https://github.com/user-attachments/assets/9e9bd71b-87e0-4af1-9e6c-3613dc2928a4)

![image](https://github.com/user-attachments/assets/ff056b6b-165b-472b-b09b-7754a354930e)
![image](https://github.com/user-attachments/assets/c3a6b562-4f99-4497-956f-ab6358af7593)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by dszhang163com** [comment]
文件夹路径 有 vue 字符不能生成后台代码

**Comment by zhangdaiscott** [comment]
vue 字符是指？

**Comment by zhangdaiscott** [comment]
请及时回复

**Comment by zhangdaiscott** [comment]
无回复，暂时关闭
