### ISSUE TITLE
online 生成的表单是否支持多租户

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7441]
##### 版本号：
3.7.1

##### 问题描述：
直接online 生成的表单是否支持多租户，没有生成具体代码那种，完全在线配置的表单，我尝试了下，配置多租户后，能看到菜单，但是获取 online信息的时候，提示无权限访问（操作）

##### 错误截图：

![4791730961287_ pic](https://github.com/user-attachments/assets/0e021d8c-4a6e-4aaf-9c4e-35c497eb2811)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liuling1314** [comment]
@zhangdaiscott 大神有时间帮忙看下，谢谢哈

**Comment by zhangdaiscott** [comment]
这块没有做

**Comment by liuling1314** [comment]
> 这块没有做

好的，谢谢解答
