### ISSUE TITLE
积木仪表盘访问增加token和开启租户，新增仪表盘后看不到

### ISSUE THREAD

**Issue by 468024855** [jeecgboot/JeecgBoot#7444]
##### 问题描述：积木仪表盘访问增加token和开启租户，新增仪表盘后看不到，看数据库这条‘666’仪表盘数据
tenant_id已有数据

##### 错误截图：
![image](https://github.com/user-attachments/assets/48b757fc-81a9-457f-aea3-de96bb9f2a3e)
![image](https://github.com/user-attachments/assets/c085164c-4bde-4b88-af49-c67c0aaa6000)
![image](https://github.com/user-attachments/assets/5c6a9d6d-b69a-4209-bec5-f8dea1fb3b98)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
