### ISSUE TITLE
分享链接

### ISSUE THREAD

**Issue by 468024855** [jeecgboot/JeecgBoot#7446]
##### 错误截图：
![image](https://github.com/user-attachments/assets/047171b8-2eb0-4e86-ad3d-b65291f09111)
![image](https://github.com/user-attachments/assets/d733176b-9253-45f2-9f96-f2fb50cc034d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不支持，可以使用最新版的仪表盘jimubi
