### ISSUE TITLE
use @docusaurus/faster 3.6.1. if blog has chinese folder docusaurus start can't work

### ISSUE THREAD

**Issue by 596094101** [jeecgboot/JeecgBoot#7447]
##### 版本号：
"@docusaurus/core": "3.6.1",
"@docusaurus/faster": "^3.6.1",

##### 问题描述：
if blog has chinese folder docusaurus start can't work

##### 错误截图：
<img width="925" alt="image" src="https://github.com/user-attachments/assets/f800b2c0-9aa1-4660-9c64-dcb2463068c5">

codesandbox url: https://codesandbox.io/p/devbox/vl8pl5

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
这个插件依赖的是webpack，是webpack生态插件，jeecgBoot是vite构建的。是不兼容的
![image](https://github.com/user-attachments/assets/3a667cd9-84cb-40f9-b3f6-387dd88d5eeb)
