### ISSUE TITLE
积木仪表盘的sql数据集字典项配置问题

### ISSUE THREAD

**Issue by 468024855** [jeecgboot/JeecgBoot#7448]
##### 错误截图：

![image](https://github.com/user-attachments/assets/812e2f8f-c682-47ee-a570-1e03357871e5)
![image](https://github.com/user-attachments/assets/9959bc24-cea8-4ac7-8638-c33f95fe08ce)
![image](https://github.com/user-attachments/assets/5a9b2733-83f5-4a21-8c4a-8429ca088590)
![image](https://github.com/user-attachments/assets/a6df0b6d-81cc-4164-9c2d-5403ecf26835)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
参考下这个实现
https://github.com/jeecgboot/JimuReport/blob/master/jimureport-example/src/main/java/com/jeecg/modules/jmreport/extend/JimuDragExternalServiceImpl.java
