### ISSUE TITLE
积木仪表盘自定义背景图片

### ISSUE THREAD

**Issue by 468024855** [jeecgboot/JeecgBoot#7449]
##### 错误截图：

![image](https://github.com/user-attachments/assets/f8ba7a80-4a97-49da-9216-35530758733a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
点击保存配置

**Comment by 468024855** [comment]
点击保存配置，背景没有变

**Comment by 468024855** [comment]
保存配置后仍然没反应
保存后预览背景图片还是显示不出来
