### ISSUE TITLE
启动nacos之后，再启动jeecg-system-cloud-start报错

### ISSUE THREAD

**Issue by MyJNMQQ** [jeecgboot/JeecgBoot#7450]
##### 版本号：
3.7.1(当前最新版本）

##### 问题描述：
jeecg-system-cloud-start启动报错

##### 错误截图：
启动nacos之后，再启动jeecg-system-cloud-start报错

![1111](https://github.com/user-attachments/assets/862d7e67-d605-449d-9836-8238f0857fb8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by MyJNMQQ** [comment]
感谢你的回复。
我给你截图，帮忙分析下






我启动nacos之后，可以正常访问的。我在pom.xml里也配置了nacos的ip和用户名密码。
代码是最新下载的，很多都是默认的，我修改的内容也不多，仅限于上。
请帮忙分析下







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 下午4:44
***@***.***&gt;;
抄送:&nbsp;"My ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 启动nacos之后，再启动jeecg-system-cloud-start报错 (Issue #7450)





 
配置host了吗，你这个是nacos没连上吧

**Comment by zhangdaiscott** [comment]
图在哪

**Comment by zhangdaiscott** [comment]
无回复 暂时关闭
