### ISSUE TITLE
BUG：新版本详情页给整个modal进行了禁用，导致子表格无法进行横向拖动

### ISSUE THREAD

**Issue by MuShan-bit** [jeecgboot/JeecgBoot#7451]
##### 错误截图：
![image](https://github.com/user-attachments/assets/547c9ce1-0811-43fb-aa2b-692ed9fd5011)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
你是什么浏览器？是online吗？
online 经测试一对多的详情滚动条没问题
![iShot_2024-11-15_17 22 36](https://github.com/user-attachments/assets/43271897-1e64-4fb2-b0c5-8b9e0bc95e81)

**Comment by MuShan-bit** [comment]
不是Online，是代码生成后的 JvxeTable，新版本新增了 JModel 的新组件，详情时是直接禁用了整个 Model，可以看到我的截图里面鼠标是禁用状态

**Comment by jeecgDeveloper** [comment]
你是自己改的吧？
JModal组件只在erp风格和单表tree生成，其他风格JModal不生成且Jmodal组件内不生成JvxeTable。
