### ISSUE TITLE
BUG：查看详情时，子表格字典失效

### ISSUE THREAD

**Issue by MuShan-bit** [jeecgboot/JeecgBoot#7452]
##### 错误截图：
![image](https://github.com/user-attachments/assets/bcb69b53-a9a1-475d-876a-66d44e8fc424)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
问题同你之前提的 [ issues/7451](https://github.com/jeecgboot/JeecgBoot/issues/7451)
如果是自己修改了代码生成之后的代码出现的问题得自己修复
