### ISSUE TITLE
日期控件显示不全是中文，只有部分是中文

### ISSUE THREAD

**Issue by hhdt2** [jeecgboot/JeecgBoot#7454]
##### 版本号：
3.7.0

##### 问题描述：
日期控件显示不全是中文，只有部分是中文

##### 错误截图：

![image](https://github.com/user-attachments/assets/c5fc064f-0c74-4320-87c2-2ea53104af30)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by FlawlessChen** [comment]
请问解决了吗，我也遇到了

**Comment by zhangdaiscott** [comment]
zy
