### ISSUE TITLE
导出总合计自定义格式化

### ISSUE THREAD

**Issue by duangdangding** [jeecgboot/JeecgBoot#7455]
##### 问题描述：导出excel的时候不能自定义合计结果格式化
![image](https://github.com/user-attachments/assets/b21690b8-7300-4e53-8919-83206a6a2f0d)

有个需求需要设置保留4位小数，这里固定设置2位

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
太老的版本，我们无法支持了
