### ISSUE TITLE
项目启动，数据源datasource报错

### ISSUE THREAD

**Issue by TBOOMp** [jeecgboot/JeecgBoot#7456]
##### 版本号：
3.7.1

##### 问题描述：
项目启动，数据源datasource报错

##### 错误截图：

![image](https://github.com/user-attachments/assets/b7c69150-795c-40ab-9c60-3d6060ef921f)

![image](https://github.com/user-attachments/assets/4a801cba-fea4-42a0-9da7-c44f4e7f125d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你改什么了？

**Comment by zhangdaiscott** [comment]
无回复 暂时关闭
