### ISSUE TITLE
jeecg定时任务不执行问题

### ISSUE THREAD

**Issue by matchaxxx** [jeecgboot/JeecgBoot#7457]
##### 版本号：
3.7.1

##### 问题描述：
执行定时任务时，如图每周的周三至周日都是正常执行功能的，但是经过周一之后，周二的定时任务就会执行失败

##### 错误截图：
![image](https://github.com/user-attachments/assets/b18da4b2-dea2-4f2a-9ee2-cdf13effe5fd)
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by matchaxxx** [comment]
没有执行

**Comment by zhangdaiscott** [comment]
zj

**Comment by EightMonth** [comment]
经过测试，cron表达式跳过执行没有问题，请查证自己服务是否存在阻塞或宕机。
![image](https://github.com/user-attachments/assets/6d845d3f-5b15-4732-8527-5879c0741d6e)
![image](https://github.com/user-attachments/assets/0b6faba2-62d5-41f3-b11c-542fd1933388)
