### ISSUE TITLE
如何实现表单数据根据用户的部门实现权限管理

### ISSUE THREAD

**Issue by changguoxu** [jeecgboot/JeecgBoot#7458]
##### 版本号：

3.7.1
##### 问题描述：

表单中有一个系统字段所属部门（sys_org_code）如何才能让不同部门的人只能看到自己部门的数据。
例如：A用户属于财政部，B用户属于研发部。A在表单中新增了一条数据,B在查看表单时如何才能使B看不到A用户新增的数据,只能看到自所属部门的数据

##### 错误截图：

![Uploading 微信截图_20241113105335.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/system/dataauth/use.html
