### ISSUE TITLE
springboot3_sas 分支无法使用@Ignoreauth注解

### ISSUE THREAD

**Issue by imapach** [jeecgboot/JeecgBoot#7459]
##### 版本号：
springboot3_sas

##### 问题描述：
springboot3_sas 分支无法使用@Ignoreauth注解
看代码InMemoryIgnoreAuth放了要ignore的路径，但是没有使用InMemoryIgnoreAuth的地方

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zj

**Comment by zhangdaiscott** [comment]
已经提交
