### ISSUE TITLE
高级查询中部门选择可以配置是否多选吗

### ISSUE THREAD

**Issue by xiaoLogin** [jeecgboot/JeecgBoot#7461]
##### 版本号：

3.7.1
##### 问题描述：
我在高级查询中使用部门选择组件：
`export const superQuerySchema = {
  userId: { title: '用户ID', order: 1, view: 'list', type: 'string', dictTable: 'sys_user', dictCode: 'id', dictText: 'realname' },
  roleId: { title: '角色ID', order: 2, view: 'list', type: 'string', dictTable: 'sys_role', dictCode: 'id', dictText: 'role_name' },
  departId: { title: '部门ID', order: 3, view: 'sel_depart', type: 'string' },
};`
但我发现如果在departId中添加：multiple: false
弹出来的部门选择依然是可以多选的

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy
