### ISSUE TITLE
钉钉登录后，没有默认的租户信息，每次都要手动选择

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7462]
##### 问题描述：使用钉钉登录之后，没有在前端设置全局的租户信息，不过后端代码也没有传给前端。
导致钉钉登录后的用户，每次都要手动选择一下租户。
我尝试自己在`modelMap.addAttribute`中设置其他信息，可是前端只能接收到token属性，请问怎么获取其他信息，并设置到全局的租户信息中？

![image](https://github.com/user-attachments/assets/e3445a49-abea-4a0e-a203-bca732925f16)
![image](https://github.com/user-attachments/assets/f409ac2a-38aa-4a85-a8c6-9d662b322fa3)

##### 错误截图：

![image](https://github.com/user-attachments/assets/f4175d50-24af-4346-81f1-8dda2b2c18bf)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by ak-2019** [comment]
![image](https://github.com/user-attachments/assets/eb2315d1-fc2d-455a-ac05-98022b47d552)
![image](https://github.com/user-attachments/assets/043fc3cb-adb3-4164-85dd-7d2745173601)
已经手动处理好了，不知道还有没有更完善的方案

**Comment by jeecgDeveloper** [comment]
未复现。
1、在前台里面有设置当前租户，请查看你是否有这个逻辑
![image](https://github.com/user-attachments/assets/707333da-9aa0-4ec4-8751-9db447899378)
2、查看后端有无设置当前租户的逻辑，具体设置租户逻辑请查看`setUserTenantAndDepart`方法
![image](https://github.com/user-attachments/assets/928eb30c-c1be-4db7-88a6-f4deae2e61c1)
