### ISSUE TITLE
单表树的查询不出子节点对应的名称或节点

### ISSUE THREAD

**Issue by starsrainfly** [jeecgboot/JeecgBoot#7463]
##### 问题描述：
使用onLine开线开发，生成一张树结构的管理界面，与你们原来的例子一样 单表（树）。
问题1 生成代码时，详情对应的字典有不对应的问题
预览时，查询详情时，其中有两个字段是isrohs,status，校验都填写了字典，分别是 yn，status.在预览时 点详情 都能显示对应的汉字 是，或正常。但是生成代码后，isrohs的是否不显示了，只显示0或1.status显示是正常的。
问题2，在生成代码页面配置中选择了对应字段的查询，并选择了模糊查询，但是生成代码后，查询功能不是太正常。如有一个是子节点，我查询名称（material_code,material_name）写全之后，也查询不出来，编码也是一样，不清楚有什么特殊处理的地方。多谢。

##### 错误截图：
页面属性
![image](https://github.com/user-attachments/assets/242e521b-518d-46ef-8b04-9bd571f15d72)
检验字段
![image](https://github.com/user-attachments/assets/38adbb33-4e4f-4c28-8c3f-5bef8d78f9cb)
功能测试时 详情 正常
![image](https://github.com/user-attachments/assets/10ea2e75-e4be-4a73-a6ff-54d27e4bb45c)
生成代码后 详情中 是否符合ROHS 只显示 0或1
![image](https://github.com/user-attachments/assets/c300d452-f223-4991-a6c6-bfb96e36a401)
这时查询之前的原来的数据
![image](https://github.com/user-attachments/assets/0ab64d68-f94c-42bc-86b3-6a2c30b86f02)

查询子节点时 输入名称 并点击查询 得到的结果是空
![image](https://github.com/user-attachments/assets/d04b8666-0132-4475-8553-9b6bf4adb775)

查询编码也是一样的
![image](https://github.com/user-attachments/assets/b74e9c34-7d37-474c-88ea-760c25d5576b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgDeveloper** [comment]
已修复，待新版本发布。您可以在查询的时候将

**Comment by starsrainfly** [comment]
问题1：我已经找到原因了，是因为我把对应的字段在数据库中设置的是int，然后字典里应该是字符串类型。导致数据类型不一致而没法匹配；
问题2：我添加了hasQuery="true" 界面上不会自动展开对应的节点，不知道后面这些是否可以优化出来这些。
非常感谢你的回复。加油
