### ISSUE TITLE
前端技术

### ISSUE THREAD

**Issue by haohewei123** [jeecgboot/JeecgBoot#7464]
##### 问题描述：
请教一下，前端为什么要用Ant-Design-Vue组件库，element-UI不香吗？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
element-UI  vue2的时代很丑很low,
现在不知道了
