### ISSUE TITLE
json兼容性问题？

### ISSUE THREAD

**Issue by hujia1758** [jeecgboot/JeecgBoot#7465]
##### 错误截图：
![image](https://github.com/user-attachments/assets/a515d154-11c3-4969-b15f-284817962436)
![image](https://github.com/user-attachments/assets/d03c92a6-81a4-4696-a66e-9db7e80a8fa5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/e1ee7207-693d-4ba8-a32d-8f46f5d48df0)

**Comment by hujia1758** [comment]
fastjson:1.2.83试过了也不行

**Comment by zhangdaiscott** [comment]
你是用的jeecgboot?还是集成到自己框架

**Comment by zhangdaiscott** [comment]
请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
