### ISSUE TITLE
有没有不生成代码也能实现逻辑删除的方案

### ISSUE THREAD

**Issue by changguoxu** [jeecgboot/JeecgBoot#7467]
##### 版本号：
3.7.1

##### 问题描述：

现在文档上只能找到通过@TableLogic注解的方式实现逻辑删除，但是我的部分表单除了逻辑删除不需要编写其他后端或前端逻辑便可满足。因此能否有不生成代码的方式或者更简便的方式实现逻辑删除

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
不生成的方式没有
