### ISSUE TITLE
DynamicDBUtil.getDbSourceByDbKey 一段时间后连接超时

### ISSUE THREAD

**Issue by hsql** [jeecgboot/JeecgBoot#7468]
##### 版本号：

3.7.0
##### 问题描述：

业务中用到了动态数据源功能，每次调用DynamicDBUtil.getDbSourceByDbKey方法
![image](https://github.com/user-attachments/assets/73cd393e-e8da-4d05-af71-44c7e2585f39)
![image](https://github.com/user-attachments/assets/3d6da647-f6b2-4c22-882f-d6999f16ed80)

但是在使用一段时间后会出现连接失败的报错， 这个时候的解决办法是将动态数据源里的连接重新编辑保存下就好了，不知道是什么问题

##### 错误截图：
![image](https://github.com/user-attachments/assets/0fa8d354-b3ec-451a-b1ae-ed2a48ecb081)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zj

**Comment by EightMonth** [comment]
很简单的原因，是因为同时连接数已经超过了最大数，并且该连接的闲置时间达到了释放标准，自然就被释放了。然后重新编辑保存，就是重新编辑保存就是创建了一个新的连接，自然就能再次生效。

解决办法：
1.调大maxActive
2.调大idleTime
