### ISSUE TITLE
使用Popup弹框时，能否在附表获取主表的值来作为参数

### ISSUE THREAD

**Issue by changguoxu** [jeecgboot/JeecgBoot#7470]
##### 版本号：
3.7.1

##### 问题描述：

我现在在子表中有部分字段使用Popup弹框需要根据主表的一个字段去查询数据，现在能否实现在子表获取主表的字段作为参数查询弹框的数据

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个需求，你只能自己扩展，默认没有这逻辑
