### ISSUE TITLE
formSchema前端表单数据下拉框中的数据请求获取有延时没有同步写入问题

### ISSUE THREAD

**Issue by liqing618** [jeecgboot/JeecgBoot#7472]
##### 问题描述：
前端配置在data.ts配置表单数据formSchema，实现两个下拉框关联联动问题，如图所属，短信签名的数据依赖选择的短信渠道中的onChange事件进行请求接口二次筛选获取数据，但是短信签名筛选数据options并没有同步更新

##### 错误截图：

![image](https://github.com/user-attachments/assets/f90b1e0c-0687-442c-8634-3769303243e4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
在短信渠道中的onChange事件使用updateSchema函数修改短信签名的中的options

可参考这个 src/views/system/user/user.data.ts


<img width="1196" alt="image" src="https://github.com/user-attachments/assets/150454e7-b096-4186-b8c8-14eb21193008">
