### ISSUE TITLE
示例仪表盘查询报错

### ISSUE THREAD

**Issue by lanbohello163** [jeecgboot/JeecgBoot#7473]
##### 问题描述：
示例仪表盘“我的第一个大屏”，查询数据报错.

##### 错误截图：

![image](https://github.com/user-attachments/assets/2c681008-c391-47ed-9dd5-c73c62d285f8)

![image](https://github.com/user-attachments/assets/be55570f-f657-450e-8e56-8a1dbd666085)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
无回复关闭
