### ISSUE TITLE
【提了问题无响应，只能再提】在线表单-java增强-表单api-表单加载事件中对 【详情 / 编辑 】 事件都不起作用

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/JeecgBoot#7474]
##### 版本号：

3.6.x
##### 问题描述：

在线表单-java增强-表单api-表单加载事件，

  1.在查询、编辑，都注册了增强函数
  2.在列表查询页，有效
  3.在详情、编辑页，都无效

##### 需求描述

从业务场景来看，列表上能看到的信息，如果详情中看不到，是不是让使用者会无所适从。

定义上，信息完整度应该如此吧：详情 > 列表
延伸的，“编辑”页 是基于 “详情”页，所以信息完整度应该有： 编辑 >= 详情
这不是技术问题，这是常规使用方式带来的述求。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
原issue

**Comment by huangwei2013** [comment]
[#7238](https://github.com/jeecgboot/JeecgBoot/issues/7238#issuecomment-2381059101)

请不要做无情的 issue 关闭机器人，多谢

**Comment by huangwei2013** [comment]
没有反馈吗

**Comment by jeecgDeveloper** [comment]
@huangwei2013 您好，在**前端**页面的**详情**和**编辑**操作事件中是不能直接触发**后端**的`Java增强`的，如果您希望在上述操作中加入自定义的业务操作，可以使用`JS增强`来实现。
参考文档：
[JS增强](https://ojrjjvdr7z.k.topthink.com/java/online/enhanceJs.html)
[JS增强：编辑前置事件](https://ojrjjvdr7z.k.topthink.com/java/online/enhanceJs/listBefore.html#%E4%B8%80%E7%BC%96%E8%BE%91%E5%89%8D%E7%BD%AE%E4%BA%8B%E4%BB%B6)
[JS增强：表单加载事件（详情）](https://ojrjjvdr7z.k.topthink.com/java/enhanceJs/form/loaded.html)

**Comment by huangwei2013** [comment]
我知道现状是如此。

但请看下现在设计是不是有待商榷，和常规理解有明显差异，如：

```
从业务场景来看，列表上能看到的信息，如果详情中看不到，是不是让使用者会无所适从。

 - 定义上，信息完整度应该如此吧：详情 > 列表
 - 延伸的，“编辑”页 是基于 “详情”页，所以信息完整度应该有： 编辑 >= 详情
```

**Comment by zhangdaiscott** [comment]
不采纳

**Comment by huangwei2013** [comment]
不意外，但很失望！！

@zhangdaiscott @jeecgDeveloper
