### ISSUE TITLE
首页切换角色后，会有404页面

### ISSUE THREAD

**Issue by hejie3225** [jeecgboot/JeecgBoot#7475]
##### 问题描述：

管理员：有用户管理菜单权限。
普通用户：没有用户管理菜单权限。

当管理员登陆后，并停留在用户列表页面，然后退出登录，使用普通用户账号登，会默认跳转到用户列表页面，但是因为没有权限，直接页面显示404，
期望结果：
如果用户无权限：默认跳转首页。
若有权限：默认跳转redirect页面。

##### 错误截图：

![image](https://github.com/user-attachments/assets/36fe27dc-6847-4557-b5a6-0c964fab1bcb)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
需要可以自己改，这么改会出问题，用户访问所有404页面都会跳转首页
有的业务场景，可能需要展示404
