### ISSUE TITLE
连接达梦数据库gateway启动异常

### ISSUE THREAD

**Issue by lucy-1206** [jeecgboot/JeecgBoot#7476]
##### 版本号：
3.5.0

##### 问题描述：
背景是测试更换达梦数据库，根据jeecg官方文档的【nacos连接达梦数据库】【连接达梦数据库】操作后（操作包含：nacos升级至2.3.2、数据库的NACOS数据库建好、nacos服务的配置文件已改、nacos的网站上的配置文件pplication-dev.yml已改），nacos启动正常，gateway起不来。

##### 错误截图：

![image](https://github.com/user-attachments/assets/dffe99e8-7243-49b1-8c37-5c27c1a86c29)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
3.5.0
这个版本不支持nacos链接达梦数据库吧

**Comment by lucy-1206** [comment]
您好，我这边有新的进展，重新调整了达梦驱动之后，在测试类里连接达梦是ok的，如图：
![image](https://github.com/user-attachments/assets/74549433-fcbc-4186-8f21-ec2e498f6de1)
MAVEN里的org.jeecgframework.nacos这个版本为2.0.4，本地运行nacos项目成功，但是没有查询到数据库的信息（如下图，数据库里的配置文件没有读到）：
![image](https://github.com/user-attachments/assets/07d4ebfa-8d4f-421e-be16-50fd1111a1eb)
求助！！大佬，这样有什么办法可以解决吗？
3.5.0版本一定不能支持连接达梦数据库吗？

**Comment by zhangdaiscott** [comment]
手工把nacos升级的官方最新版
