### ISSUE TITLE
安装部署到正式环境，开发的功能提示Token失效，请重新登录

### ISSUE THREAD

**Issue by linxinsu** [jeecgboot/JeecgBoot#7478]
##### 版本号：
3.2.0（发布日期：20220425）

##### 问题描述：
在开发环境测试正常，安装部署到正式环境，可以登陆一些功能也可以正常打开，自己开发的功能不正常。查看提示:
{"success":true,"message":"Token失效，请重新登录!","code":401,"result":null,"timestamp":1732153873802}

##### 错误截图：
图片1：
![image](https://github.com/user-attachments/assets/0cb79eb6-9f83-406a-ac2d-1f1239523334)
图片2：
![image](https://github.com/user-attachments/assets/483e73af-f08a-4592-8ccc-5df332d2c736)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个问题不好分析，版本也有点老了，自己debug跟下吧
