### ISSUE TITLE
fastjson 1.x 远程含有反序列化漏洞

### ISSUE THREAD

**Issue by zhao-yongzheng** [jeecgboot/JeecgBoot#7480]
##### 版本号：
1.9.0

##### 问题描述：
积木报表最新版本依然引用了fastjson 1.2.83 版本，此版本号是否含有反序列化漏洞及远程执行代码风险

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
cr

**Comment by lem0n817** [comment]
1.2.83及以上版本的漏洞基本上很难利用。

**Comment by jeecgos** [comment]
@zhao-yongzheng fastjson 1.2.83是fastJson1.x的最新版本，反序列化漏洞及远程执行代码漏洞都已经修复了。
