### ISSUE TITLE
版本号：master 多租户模式下 数据权限使用变量：#{tenant_id} 报错

### ISSUE THREAD

**Issue by geegku** [jeecgboot/JeecgBoot#7481]
##### 版本号：master

开启了多租户模式

##### 问题描述：B方式: 通过请求URL实现数据权限，数据规则系统自动属性：#{tenant_id} 配置上报错；
提示 Integer 转换成错误！

临时解决：QueryGenerator，添加了下面代码。
![image](https://github.com/user-attachments/assets/bc24ef60-38a3-4ab8-b079-7a377d3ac730)

##### 错误截图：
系统把 #{tenant_id} 变量之间转 Integer 报错了。
![image](https://github.com/user-attachments/assets/fb29c060-d83b-4e37-b5e1-76ee65f50dc4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
cr
