### ISSUE TITLE
积木报表仪表盘中的部分组件无法使用

### ISSUE THREAD

**Issue by zongxing719** [jeecgboot/JeecgBoot#7483]
##### 版本号：
3.7.1

##### 问题描述：
积木报表仪表盘中的部分组件无法使用，例如下面图中的：是否分页和显示序列号都无法使用

##### 错误截图：

![image](https://github.com/user-attachments/assets/92a7a5b3-b267-4f9b-99d2-a4944efe7068)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
大屏吗

**Comment by zongxing719** [comment]
嗯，是的，另外，还有组件的背景色和边框也不起作用
![image](https://github.com/user-attachments/assets/f353e16d-1617-4b1d-ad0c-2f7513fdd503)

**Comment by zongxing719** [comment]
如果可以的话，最好可以独立设置组建的长和宽，这样可以统一控制组件的大小。目前这种拖动的不敢太好控制。

**Comment by zongxing719** [comment]
非常感谢！！！

**Comment by zongxing719** [comment]
对了，仪表盘那个背景色功能是好的

**Comment by zhangdaiscott** [comment]
目前大屏属于迅速研发中，目前不稳定，你可以看下演示功能，后面会尽快发布新版
https://boot3.jeecg.com/

**Comment by zongxing719** [comment]
好滴，非常感谢，你们的奉献！！！

**Comment by zongxing719** [comment]
期待新的版本发布！
