### ISSUE TITLE
数据导出，如果参数是日期段就会错误

### ISSUE THREAD

**Issue by libo5410391** [jeecgboot/JeecgBoot#7485]
##### 问题描述：
我发现导出数据的一个BUG，在有日期段的参数的时候，他导出的时候，日期参数是按数组传递的，day[]这种。 然后就查不出数据了，也就导出来是空的

但是正常页面查询的时候，是day_begin，和day_end。 这样传递参数是哈哈，查询是正确的。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
能来点截图吗

**Comment by libo5410391** [comment]
我们已经修复了，不明白为什么你们在导出的时候，没有复用查询的 beforeFetch

**Comment by zhangdaiscott** [comment]
描述过于简单，无法分析
