### ISSUE TITLE
手机号码登录，在请求头中无法获取租户id

### ISSUE THREAD

**Issue by chenjiayang2008** [jeecgboot/JeecgBoot#7488]
##### 问题描述：
开启多租户后，手机号码登录，x-tenant-id会是0，而账号密码登录可以获取x-tenant-id

##### 错误截图：

![image](https://github.com/user-attachments/assets/16cee976-f9f4-4be5-8fae-8dd074b636b4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
ws

**Comment by chenjiayang2008** [comment]
![image](https://github.com/user-attachments/assets/7ec8df56-735f-4c81-9dc9-c25658406748)
ws连接是成功的

**Comment by chenjiayang2008** [comment]
在3.6版本中，手机号码登录，在请求头中是有租户id的

**Comment by jeecgDeveloper** [comment]
已修复，待新版本发布。您可以在用户手机登录成功之后设置一下当前租户信息

![image](https://github.com/user-attachments/assets/61d7493d-bbab-432c-8e8c-59396dc90dd4)
