### ISSUE TITLE
sas 版本新建模块 请求 出现404

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/JeecgBoot#7489]
##### 问题描述：
未使用jeecg包名，但已加包扫描路径，pom中引入了jeecg-boot-base-core，项目pom和start的pom中都引入了新建的模块，application-dev.yml中mybitisPlus和MybatisPlusSaasConfig添加了mapper路径，Swagger2Config添加了包路径，清过缓存，始终404。
maven clean  maven install了无数遍，

filter 加断点能拦截到

##### 错误截图：

![image](https://github.com/user-attachments/assets/b1b4f729-98f5-408b-8449-b0ebb8deadd2)

![image](https://github.com/user-attachments/assets/b99ffa2f-251a-4b35-8ed3-53b18b251346)

![image](https://github.com/user-attachments/assets/09a5fea5-a3e5-4ec3-a5e2-6bc0c2b4f5b5)

**Comment by zhangdaiscott** [comment]
扫码加载路径怎么改的

**Comment by softboy99** [comment]
![image](https://github.com/user-attachments/assets/f86ee095-3add-4082-8c83-fa1a260d16d7)
![image](https://github.com/user-attachments/assets/8f9ed328-17b9-45a4-a747-ec849b7e6972)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/advanced/basepath.html
