### ISSUE TITLE
执行启动类失败

### ISSUE THREAD

**Issue by yegevvvv** [jeecgboot/JeecgBoot#7490]
##### 版本号：
3.7.1

##### 问题描述：
执行 jeecg-system-start/src/main/java/org/jeecg/JeecgSystemApplication.java 启动失败

##### 错误截图：
![image](https://github.com/user-attachments/assets/dfb5f9fb-9472-4763-8f96-b7cfc6876009)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这不提示了吗，按照提示修改
命令过长
