### ISSUE TITLE
运行时间好长，效率慢

### ISSUE THREAD

**Issue by jianhualll** [jeecgboot/JeecgBoot#7491]
##### 问题描述：

校验了两次shiro一次一百多毫秒两次就三百毫秒了

##### 错误截图：
![image](https://github.com/user-attachments/assets/249ea36f-18a2-4a0d-839d-d0d93a4d855d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jianhualll** [comment]
DelegatingFilterProxy过滤器和shiroFilterFactoryBean都被配置了，导致请求被处理了两次
![image](https://github.com/user-attachments/assets/384c2053-3ffa-48d5-8eda-c56e8d72a96d)
注释掉上面那个就可以了

**Comment by zhangdaiscott** [comment]
zj

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
