### ISSUE TITLE
仪表盘设计-统计卡片和简介卡片，选择动态数据源时，无法展示和选择映射关系

### ISSUE THREAD

**Issue by 1093702350** [jeecgboot/JeecgBoot#7492]
##### 问题描述：
在仪表盘设计中-左侧添加统计卡片或简介卡片，编辑并选择动态数据源时，正常应该在下方显示映射关系，但是3.7.1版本中无法显示，导致无法使用动态数据源加载数据。
官网上的案例网站是可以选择的

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by 1093702350** [comment]
错误截图：
<img width="1228" alt="微信图片_20241124224437" src="https://github.com/user-attachments/assets/57b60d42-4905-4862-aedb-bcccf6615ebc">
官网样例（PS:样例使用静态数据都加载不出来，动态也不行）
<img width="1270" alt="微信图片_20241124224847" src="https://github.com/user-attachments/assets/26743f50-bf4b-4da0-8324-8004a9fa240e">

**Comment by zhangdaiscott** [comment]
sq

**Comment by zongxing719** [comment]
谢谢

**Comment by zongxing719** [comment]
下个版本大概什么时候发布？
