### ISSUE TITLE
业务字典表的缓存前端有吗？JDictSelectUtil：filterDictTextByCache查不到

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/JeecgBoot#7495]
##### 问题描述：
似乎业务字典表的缓存前端似乎没有，只有系统字典表的值，通过JDictSelectUtil：filterDictTextByCache读取不到
想在一个modal界面的js代码中根据value获取翻译，只能再次向后端发请求吗？
![image](https://github.com/user-attachments/assets/d202d25a-e472-4c79-87af-53def223bddf)

**Comment by zhangdaiscott** [comment]
业务字典表 是指那种用法？

**Comment by zhangdaiscott** [comment]
如果指的是表字典注解，那是不支持

**Comment by softboy99** [comment]
是的，那这里是否有优化的空间，text就在界面上，代码就取不到，岂不是很诡异？

**Comment by zhangdaiscott** [comment]
这个逻辑我们不做，需要可以自己扩展，把业务数据都缓存了，前端很占用很多资源

**Comment by softboy99** [comment]
不一定要缓存的吧？能从界面取到即可
