### ISSUE TITLE
JUpload bizPath传中文乱码

### ISSUE THREAD

**Issue by softboy99** [jeecgboot/JeecgBoot#7496]
##### 问题描述：
JUpload bizPath传中文路径，造成乱码, bizPath和fileName都是乱码

##### 错误截图：
![image](https://github.com/user-attachments/assets/295bcfdf-4161-4d25-9c0b-53d9ed544d29)

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/cb54b22d-8169-4c54-9c88-07265558a84e)

**Comment by softboy99** [comment]
是bizPath变量，不是文件名，是文件夹名

**Comment by EightMonth** [comment]
建议参考头像上传功能，再次测试，无该问题
![image](https://github.com/user-attachments/assets/ad9ef355-08e0-427c-b14e-9f41ff203ce9)

**Comment by softboy99** [comment]
> 建议参考头像上传功能，再次测试，无该问题 ![image](https://private-user-images.githubusercontent.com/23272421/390811145-ad9ef355-08e0-427c-b14e-9f41ff203ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDE3NDgsIm5iZiI6MTczMjg0MTQ0OCwicGF0aCI6Ii8yMzI3MjQyMS8zOTA4MTExNDUtYWQ5ZWYzNTUtMDhlMC00MjdjLWIxNGUtOWY0MWZmMjAzY2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwNTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNjA0NTYxZGZlZTgwZWU1OTEwMzNjYjA2M2U3MTAwNWVlYzc4ODg5ZDZjZjBhMDI4NGYwNjUzZmMwMWFjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hBKVyjqyKgJ9m0srwMB7_oOkjrjbRy6HPrFepoGFhpY)



你截图中的bizPath为null, bizPath为中文时，你试下

**Comment by EightMonth** [comment]
未复现，参考jeecg组件示例，自定义组件示例
![image](https://github.com/user-attachments/assets/feae8e0c-f0a5-4aa0-9f19-34be9f2fa15e)
![image](https://github.com/user-attachments/assets/6e3fb7a7-0914-4add-ad50-040ae527a876)

**Comment by softboy99** [comment]
> 未复现，参考jeecg组件示例，自定义组件示例 ![image](https://private-user-images.githubusercontent.com/23272421/391404495-feae8e0c-f0a5-4aa0-9f19-34be9f2fa15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTQ3NjAsIm5iZiI6MTczMzExNDQ2MCwicGF0aCI6Ii8yMzI3MjQyMS8zOTE0MDQ0OTUtZmVhZThlMGMtZjBhNS00YWEwLTlmMTktMzRiZTlmMmZhMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA0NDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDNhMTZmZjA5MDE2YWE4OTY0NzZiMGM5N2Y3MzQ1Y2FlZTJkMzk0NGIwZTE2OGJlNmRiMTc0YzFhOTg1ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0dydkIzepFaGkpkfiQsDIglTHKU42HZUcIVUO8HAcZk) ![image](https://private-user-images.githubusercontent.com/23272421/391404571-6e3fb7a7-0914-4add-ad50-040ae527a876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTQ3NjAsIm5iZiI6MTczMzExNDQ2MCwicGF0aCI6Ii8yMzI3MjQyMS8zOTE0MDQ1NzEtNmUzZmI3YTctMDkxNC00YWRkLWFkNTAtMDQwYWU1MjdhODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA0NDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YmNmZmViY2U4YmIwMWY2YTJkZDEzOTA2M2UzYmM5Yjc0MTA4YjI1NTY4NjI0NjAzMGRmZGRhYjViMmNmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8jHAfuSt_K7U0DesCT-4BScx0GtQR-zU4uZD2oE91CU)

uploadType，换成minio试下

**Comment by softboy99** [comment]
您看的是master分支吧？问了下gpt,得到的回复是：
![image](https://github.com/user-attachments/assets/ff2e271f-b73a-49fc-b4d4-9d6c9e7c056e)

**Comment by zhangdaiscott** [comment]
我们可能不好重现，这种问题如果真有，自己简单debug很快处理了，还是部署编码问题
