### ISSUE TITLE
jvxetable 字典问题

### ISSUE THREAD

**Issue by guanjieyanzoudashi** [jeecgboot/JeecgBoot#7497]
##### 错误截图：
![9615a27f0fa41c2f524ad6484a65537](https://github.com/user-attachments/assets/dca6a412-0483-40c9-8ec1-f66d961489b1)
![f3d17617ad7fb57314ce6b5a1580d47](https://github.com/user-attachments/assets/32e38871-db6c-4cbb-b11b-b77f7d1794fd)
![d281e0943fb53599c450c51f7826a35](https://github.com/user-attachments/assets/89c5f020-4c47-44c3-b658-7ee0ba54d65f)
ser-attachments/assets/5ad2d06b-3308-4514-832c-ebe66e4572b4)
![image](https://github.com/user-attachments/assets/fd3839c5-3997-4085-bce9-48f67cea40b7)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
请描述下你截图的功能，那个点有问题

**Comment by guanjieyanzoudashi** [comment]
就是我把这个表格的某一个列隐藏后，“规格型号”这个列的值字典翻译失效了，隐藏之前字典是可以翻译出来的

**Comment by zhangdaiscott** [comment]
zy

**Comment by Zebzhong** [comment]
这个bug是由于列隐藏显示切换以后导致触发了这个value的更新，而value的值前后对应的字段不一样了，打印newValue和oldValue就看的出来了，现在这个解决方案是有问题的，如果两个下拉框的枚举值是一样的，翻译就会有问题
