### ISSUE TITLE
A route named "PageNotFound" has been added as a child of a route with the same name.

### ISSUE THREAD

**Issue by RexCN** [jeecgboot/JeecgBoot#7500]
##### 版本号：
3.7.1（发布时间：2024-09-12）

##### 问题描述：
跳转不到登录页面。node 版本：v20.17.0

##### 错误截图：

![登录路由报错](https://github.com/user-attachments/assets/7c851910-6c8a-4255-a305-1641ce31a6cd)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己改过东西了？还是下载的原始代码

**Comment by 67gogo** [comment]
node20.15.0，安装了pnpm。install 、dev之后也出现了这个问题

**Comment by RexCN** [comment]
![依赖反馈](https://github.com/user-attachments/assets/d3cf2785-c591-4c98-b925-d87a6f461b28)

**Comment by Gorilla019** [comment]
我也有同样的情况

**Comment by zhangdaiscott** [comment]
使用的pnpm i安装的依赖？

**Comment by Gorilla019** [comment]
> 使用的pnpm i安装的依赖？
是的

**Comment by Gorilla019** [comment]
> 使用的pnpm i安装的依赖？

请问跟使用pnpm有关系吗

**Comment by zhangdaiscott** [comment]
刚测了下，没问题
![image](https://github.com/user-attachments/assets/3b28f08f-daac-4fc4-aa81-ed6519cf443d)

![image](https://github.com/user-attachments/assets/9a07c4a2-dae3-4b91-af7d-c51fea5bb553)

![image](https://github.com/user-attachments/assets/43726554-f1ae-4507-9204-55439dcc5610)

**Comment by 67gogo** [comment]
我刚才试了上边的node16.15.0 pnpm7.13.5，在pnpm install上就有问题，
3.7.1这个有问题，你这个好像不是最近版本的环境

**Comment by git4frank** [comment]
遇到同样问题，请问解决了吗？

**Comment by git4frank** [comment]
昨天新下的代码启动报错：
![image](https://github.com/user-attachments/assets/6a7953d7-8f39-4d95-a16e-0f9420e09788)

**Comment by RexCN** [comment]
![image](https://github.com/user-attachments/assets/720791ba-1b1d-4376-ae27-aa5b90ec3c4f)
我这样解决了。

**Comment by RexCN** [comment]
路由的name和path都重复，应该是会出问题的吧？

**Comment by RexCN** [comment]
为了保证环境纯净，使用docker来测试的，镜像用的node官方镜像node:22-bookworm。pnpm -i、dev。在局域网内的其他没打开过jeecgboot网页的电脑访问8100。结果会是这样。

**Comment by lihang121** [comment]
![微信截图_20241127103806](https://github.com/user-attachments/assets/72b699eb-13a7-486f-b5ed-3ad40fd197b5)
改完又出现了这个问题还是跳转不了

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
是因为vue-router4.5.0版本导致。
可按如下图修复：
![image](https://github.com/user-attachments/assets/875b227a-f85a-4840-a88a-906240ad0d27)

**Comment by RexCN** [comment]
thanks

**Comment by jeecgDeveloper** [comment]
上午改的可能不全，得改如下修复：
![image](https://github.com/user-attachments/assets/b58501f9-c21a-45d0-9545-e4982bcfe495)
![image](https://github.com/user-attachments/assets/61e09f09-1ada-4fa7-9e71-78a1395450db)
![image](https://github.com/user-attachments/assets/8d8ba6f4-3e61-487b-8ba8-5583125970b9)
![image](https://github.com/user-attachments/assets/2ba33cdc-e3a7-41da-b016-f1d8e3ba6a4d)

**Comment by louchenaishang** [comment]
> 上午改的可能不全，得改如下修复： ![image](https://private-user-images.githubusercontent.com/185453451/390318337-b58501f9-c21a-45d0-9545-e4982bcfe495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Nzg2OTAsIm5iZiI6MTczMjg3ODM5MCwicGF0aCI6Ii8xODU0NTM0NTEvMzkwMzE4MzM3LWI1ODUwMWY5LWMyMWEtNDVkMC05NTQ1LWU0OTgyYmNmZTQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMTA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGRhNjI1MGIzODJlNjg4OTU2NDk1OWE0ZGI0MGUzOGM2OWQ0ZDVjZTMxOGUyNDBkZTU5NGIyNGViZjcxNGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yt7vEaWipnKtgfuGVIFKnPg4W__c8G0TnYActEeUxJM) ![image](https://private-user-images.githubusercontent.com/185453451/390318403-61e09f09-1ada-4fa7-9e71-78a1395450db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Nzg2OTAsIm5iZiI6MTczMjg3ODM5MCwicGF0aCI6Ii8xODU0NTM0NTEvMzkwMzE4NDAzLTYxZTA5ZjA5LTFhZGEtNGZhNy05ZTcxLTc4YTEzOTU0NTBkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMTA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDAxNzVmOWE2ZDljMmM4MzE4ZDAzZGZlYWNiZDk3MTM5NTVlNDViNTE4YTliZjBhYmQ2YjlmMDIzYzNiNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k9aTfrN9i1rjR7lry3JiZpF5bOxAok8obolyHdFWsbg) ![image](https://private-user-images.githubusercontent.com/185453451/390318576-8d8ba6f4-3e61-487b-8ba8-5583125970b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Nzg2OTAsIm5iZiI6MTczMjg3ODM5MCwicGF0aCI6Ii8xODU0NTM0NTEvMzkwMzE4NTc2LThkOGJhNmY0LTNlNjEtNDg3Yi04YmE4LTU1ODMxMjU5NzBiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMTA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjQ4ZmViMTVlZDA3MTEzNTI5MmE2MTBhZTk5MTBkMjFiNTQ2NTk1NDFkYTE1MzQyMWNjY2VhMDBlYzQyOTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z1s1KZhWsypnXY2MzxfNVKB4P4q_AkXbtljPRwB2P1I) ![image](https://private-user-images.githubusercontent.com/185453451/390318861-2ba33cdc-e3a7-41da-b016-f1d8e3ba6a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Nzg2OTAsIm5iZiI6MTczMjg3ODM5MCwicGF0aCI6Ii8xODU0NTM0NTEvMzkwMzE4ODYxLTJiYTMzY2RjLWUzYTctNDFkYS1iMDE2LWYxZDhlM2JhNmE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMTA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTVlNTkxYjViNmI0MjU4NTE3ZTlhMWFlNGYyMWRiODczY2VlOWQ2MzNkODUzNDQ5NWEyYzIzZDg1YjJlYjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LwhV3RW6WIcDx1n1jM73X41NnfHZM1cwaffR-D5AUfE)

可以解决问题 2024-11-29

**Comment by 123164867376464646** [comment]
"vue-router": "4.3.0", 也会出现相同情况，已经按照上面新增PAGE_NOT_FOUND_NAME_404把几个图片的流程走完就没报错了，也不会进入404页面

**Comment by BabyCabbage** [comment]
我本地之前是正确的，闲置有一段时间了，今天启动页报错PageNotFound问题，我看package 中有"vue-router": "^4.3.0" 依赖关系，估计是执行了pnpm install 不知道其它什么模块没固定导致的，改成PageNotFound404 问题修复
