### ISSUE TITLE
仪表盘 配置数据集sql时，根据租户id无法过滤数据

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7503]
##### 版本号：
3.7.1

##### 问题描述：

在  数据集配置中无法 获取 url中的租户id的值

##### 错误截图：

![image](https://github.com/user-attachments/assets/6cbaa7de-c851-47c2-b28a-cc0e64a6fa38)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liuling1314** [comment]
@zhangdaiscott 大佬帮忙看下，有什么办法能支持根据租户id过滤数据吗

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
