### ISSUE TITLE
非admin 用户无法online 导入数据库表

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7504]
##### 版本号：
3.7.1

##### 问题描述：

某些政府项目验收，不允许出现admin，root 类似账号名，但是有些功能只能admin账号才能使用，比如 用户 online 导入数据库表，是否能放宽下限制

##### 错误截图：

![WeChatd8a38020dbe130fe0ac01302b9c49cf9](https://github.com/user-attachments/assets/a53220f7-8b31-418e-9efa-4dbaf3b6369f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liuling1314** [comment]
@zhangdaiscott 大佬有时间给看下呗，谢谢啦

**Comment by liuling1314** [comment]
是生成表单的时候报错，不是查询表的时候，截图如下，确定用的最新版本
![WeChat4e6374bda83ef31cfe119baf9fa96aad](https://github.com/user-attachments/assets/567755c7-d0f9-4fa7-995e-396615198f7b)

**Comment by zhangdaiscott** [comment]
cr

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。
