### ISSUE TITLE
启动项目时报datasource错误

### ISSUE THREAD

**Issue by AllureLove1998** [jeecgboot/JeecgBoot#7505]
##### 问题描述：
昨天刚拉取的3.7.1版本的代码，可以正常启动，今天启动后就报错，在spring里加入allow-bean-definition-overriding:true仍未解决

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

##### 错误截图：

![image](https://github.com/user-attachments/assets/8b5247a4-2692-4a05-b45e-13b1f01e8eb0)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by 67gogo** [comment]
我也出现这个问题了，请问解决了么

**Comment by AllureLove1998** [comment]
> 我也出现这个问题了，请问解决了么

问题引发原因没有解决，但是在maven的配置文件里面轮流切换dev、prod、springcloud后都重建一次maven，然后切换回dev就不会报错了...不知什么原因

**Comment by jianhualll** [comment]
![image](https://github.com/user-attachments/assets/d5c5277f-32e4-4326-ab8f-de7d4a5bd052)
清一下maven就可以了

**Comment by cao-zheng** [comment]
![image](https://github.com/user-attachments/assets/f6c407c6-0d60-418d-9a33-62fb460eab14)
咦？我这边clean还是有问题

**Comment by ruolunhui** [comment]
目前我这边的处理方式是 配置里面全部不勾选 然后 mvn clean 再到项目根目录的pom.xml   执行这两个操作
右键 -> Maven -> 重新加载项目 
右键 -> Maven -> 生成源代码并更新文件夹
执行完之后就好了

![1734608990874](https://github.com/user-attachments/assets/41cf3150-e98a-4c2e-9418-623df4947981)
