### ISSUE TITLE
1.9.0版本仪表盘设计中-左侧添加统计卡片或简介卡片，编辑并选择动态数据源时，无法加载数据

### ISSUE THREAD

**Issue by 1093702350** [jeecgboot/JeecgBoot#7506]
##### 问题描述：
1.9.0版本仪表盘设计中-左侧添加统计卡片或简介卡片，编辑并选择动态数据源时，无法加载数据。（静态数据也无法加载）

##### 错误截图：

![c3a5138e-ee05-4c84-9f10-19433967378d](https://github.com/user-attachments/assets/2c9e8519-20cf-4b25-a43d-b3128f098549)
![QQ20241127-234721](https://github.com/user-attachments/assets/990c9a9e-4cb0-40f5-8f3f-3a5b491a234a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
