### ISSUE TITLE
框架自带输入框按钮本地化不生效

### ISSUE THREAD

**Issue by guoshiyu2025** [jeecgboot/JeecgBoot#7507]
版本号：jeecgboot-vue3  3.6.2

问题描述：框架自带输入框按钮本地化失效，同时栅格样式失效。框架自带的基于basicform和basicmodal的样式基本全部出现了这个问题，栅格排版无法分块也同时出现了。node版本18.16.0，

错误截图：
![mmexport1732757457774](https://github.com/user-attachments/assets/446d8f02-eba3-4001-9b28-04cf17bdff37)
![mmexport1732757455274](https://github.com/user-attachments/assets/f7b6737b-1883-4294-88d2-1ab00127cf32)
![mmexport1732757453126](https://github.com/user-attachments/assets/d578d73e-773a-44dc-aafe-70604ba73306)
![mmexport1732757450600](https://github.com/user-attachments/assets/8500c637-49f8-4395-bec7-563beb30e202)
![mmexport1732757447972](https://github.com/user-attachments/assets/25ffe863-c42f-465c-a16f-81262cc929cb)
[1_package.json](https://github.com/user-attachments/files/17941617/1_package.json)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你是指国际化？

**Comment by zhangdaiscott** [comment]
另外请用最新版测试
