### ISSUE TITLE
前端管理界面打开时经常性卡死

### ISSUE THREAD

**Issue by LZW-Andrewlu** [jeecgboot/JeecgBoot#7508]
##### 版本号：
V3.7.0

##### 问题描述：

使用Edge浏览器打开管理端界面时，经常性卡死在LOADING界面。
一旦出现卡死状态，更换不同电脑打开时，也会同时卡死在LOADING界面，无法进入登录界面。
清理浏览器缓存后，刷新又能正常恢复。出现此问题频繁非常高。又找不到具体原因。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
能给我们详细的重现步骤吗

**Comment by LZW-Andrewlu** [comment]
1. 打开后台管理系统，正常登录完成。
2. 再开一个标签，打开同样的网址，卡在LOADING界面，无任何异常显示。
3. 测试地址：https://api.tickets.andrewlu.cn
4. 账号：admin/5215596#Ampz
5. 观察系统任务管理器，发现标签页所在进程内存持续快速增长，直到内存爆满，页面弹出无响应，继续等待弹窗。
6. 怀疑点：首页加载流程中，某个地方代码产生内存泄漏。每次进首

https://github.com/user-attachments/assets/fcbba324-6f51-48c8-a8ff-89d2db996880

页时就会卡死，但直接给地址拼接上其他页面路由，则能正常进入。
7. 问题演示视频：链接: https://pan.baidu.com/s/1g2xyHpWVGvJGhJqUVRLyew?pwd=zidr 提取码: zidr

**Comment by LZW-Andrewlu** [comment]
问题似乎与 #6861 问题相同，我先按此方法进行修复解决。非常感谢。
