### ISSUE TITLE
高级查询在online开发表单时功能测试正常，生成代码后只要有附表的都会报错，官方最新代码也会

### ISSUE THREAD

**Issue by twosSign** [jeecgboot/JeecgBoot#7509]
##### 错误截图：
![Uploading 50b9f45a859d1ba8510ba2de9ecec6b2.png…]()

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by twosSign** [comment]
![50b9f45a859d1ba8510ba2de9ecec6b2](https://github.com/user-attachments/assets/1a1119f2-776c-4601-b37a-75346f0c7d44)

**Comment by zhangdaiscott** [comment]
图裂

**Comment by zhangdaiscott** [comment]
ws

**Comment by twosSign** [comment]
图片后面有补充

**Comment by jeecgDeveloper** [comment]
代码生成不支持。你可以参考以下步骤实现：
![image](https://github.com/user-attachments/assets/45796620-aca6-43d0-9772-06f534d4b02d)

**Comment by jeecgDeveloper** [comment]
代码生成不支持。你可以参考以下步骤实现：

1. 后台list接口接收到请求之后，有两个参数 `superQueryMatchType（and 或者 or）`、`superQueryParams`查询参数
2. 将`superQueryParams`中的子表数据摘出来，根据前表名、后字段的方式 查询符合条件子表数据关联的外键
3. 根据外键 in查询主表，并将superQueryParams子表的数据删除
4. 后续会提供示例

![image](https://github.com/user-attachments/assets/45796620-aca6-43d0-9772-06f534d4b02d)
