### ISSUE TITLE
tab跳转错误

### ISSUE THREAD

**Issue by Gorilla019** [jeecgboot/JeecgBoot#7510]
##### 版本号：
3.7.1

##### 问题描述：

jeecgboot顶部tab从有参数页面切换到无参数页面跳转失败问题尾部拼接上了undefined

##### 错误截图：

![aec386da664596efad95e1e6b884e7c8](https://github.com/user-attachments/assets/300ec217-2b10-4ad2-8716-c62c94113780)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Gorilla019** [comment]
jeecg-boot实例上面好像没有子页面，新增编辑查看都是弹窗，我这边的需求是需要进入子页面的，还需要通过url传递参数。会出现进入子页面后点击tab过大概十秒在url上拼上了undefined，请问有大佬知道这个是什么原因吗

**Comment by zhangdaiscott** [comment]
zy

**Comment by Gorilla019** [comment]
您好，我这边大概看了下好像是qiankun乾坤框架父子服务之间的跳转出现的问题，跟下文情况类型，但是按照他这个配置了还是会跳转到undefined
https://blog.csdn.net/chaoPerson/article/details/131398285

**Comment by Gorilla019** [comment]
大佬，菜单配置里面好像只能配置子菜单，子页面如何配置呀

**Comment by jeecgDeveloper** [comment]
你是乾坤框架吗？新增按钮是在父应用，点击新增按钮进入的是子应用地址？
