### ISSUE TITLE
表单增删示例中插槽前面的冒号如何去掉呢

### ISSUE THREAD

**Issue by dongyzw** [jeecgboot/JeecgBoot#7511]
##### 版本号：
最新版

##### 错误截图：
![image](https://github.com/user-attachments/assets/b283522a-385b-4c1d-9e08-a32ffc0ad6b5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
补充版本信息

**Comment by dongyzw** [comment]
3.7.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 表单增删示例中插槽前面的冒号如何去掉呢 (Issue #7511)





 
补充版本信息

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
1. css 
![image](https://github.com/user-attachments/assets/2b171f4b-dc3e-4123-9e60-4e2b3727a938)
```
<style lang="less" scoped>
  .ant-form {
    > :deep(.ant-row) {
      > .ant-col {
        &:nth-child(3n) {
          .ant-form-item-label {
            label {
              &::after {
                display: none;
              }
            }
          }
        }
      }
    }
  }
</style>

```

2. 去掉label 空格
![image](https://github.com/user-attachments/assets/582846c5-5262-4d9b-b99a-d82e43a96f3e)
![image](https://github.com/user-attachments/assets/911c2237-7f92-4cf4-b474-c5dcb49215d4)
