### ISSUE TITLE
登录之后首页显示404

### ISSUE THREAD

**Issue by liuxianghsh** [jeecgboot/JeecgBoot#7512]
##### 问题描述：

登录之后，显示404，刷新首页后提示errorPage 再次刷新界面正常

##### 错误截图：

![img_v3_02h2_1cdcd88d-b243-4f37-8af8-207aaa9a7ceg](https://github.com/user-attachments/assets/e36d01c1-1ba4-4ee3-aab0-d818b2819537)

**Comment by liuxianghsh** [comment]
![img_v3_02h2_e1bea65e-5872-423e-8f65-7f8b1f3fa1fg](https://github.com/user-attachments/assets/0e457158-b3e3-4197-903c-06f6d998a6ff)

**Comment by zhangdaiscott** [comment]
什么时间下载的代码

**Comment by liuxianghsh** [comment]
在 https://gitee.com/下载的代码，我换github上  以及重置数据库就可以了

**Comment by liuxianghsh** [comment]
单实例以及微服务版本切换时

**Comment by jeecgDeveloper** [comment]
你在 src/router/guard/permissionGuard.ts 文件看下是否有如下代码？
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/08b8319b-e234-4f19-97b7-09edf41931d3">

如果没有则根据 [Commit e2aaf0f] (https://github.com/jeecgboot/JeecgBoot/commit/e2aaf0f9788e2629f204a0c3cddd37f40eebfa3a#diff-06973b79ad199c60d5636a6c9c48a838db1b52904f789c1afbe14c506b5baa23)  更新下代码即可。
