### ISSUE TITLE
最新版本jeecgboot本地跨域代理后端拿不到真实 ip 只能拿到我本地代理配置的 ip

### ISSUE THREAD

**Issue by xxxtnco** [jeecgboot/JeecgBoot#7514]
##### 版本号：
最新版本

##### 问题描述：
最新版本jeecgboot本地跨域代理后端拿不到真实 ip 只能拿到我本地代理配置的 ip

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你怎么配置的

**Comment by zhangdaiscott** [comment]
无回复关闭
