### ISSUE TITLE
添加SSL证书配置，无法启动

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/JeecgBoot#7515]
##### 问题描述：

下载最新的代码，没有任何修改，就添加了SSL配置，pom文件已经排除了pfx，无法启动，同一个证书文件放以前老的版本2.4.5没有问题。

##### 错误截图：
![微信图片_20241129160215](https://github.com/user-attachments/assets/1df6dd12-4698-4c9b-9953-e70c4ee251dd)
![微信图片_20241129160323](https://github.com/user-attachments/assets/5fe4dd2f-4c7c-46ec-a879-547f7838c34d)
![微信图片_20241129160450](https://github.com/user-attachments/assets/ed0ee3f0-63a6-4a61-964f-c3bf225c94cd)

**Comment by zhangdaiscott** [comment]
zj

**Comment by EightMonth** [comment]
![image](https://github.com/user-attachments/assets/931de603-1de4-47a9-8354-fe886c4d845d)

**Comment by lijinlang** [comment]
> ![image](https://private-user-images.githubusercontent.com/23272421/392712101-931de603-1de4-47a9-8354-fe886c4d845d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTgyMTgsIm5iZiI6MTczMzM5NzkxOCwicGF0aCI6Ii8yMzI3MjQyMS8zOTI3MTIxMDEtOTMxZGU2MDMtMWRlNC00N2E5LTgzNTQtZmU4ODZjNGQ4NDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDExMjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MzEzN2I4ODllNWY0NWFhY2RmN2I2NTBhNTBmM2FkNzY5MGUyOWYwNTY4ZTNhM2I1ZTUyNTNlYWQ1MGE5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8tY4nDR0Tm757aCsFVYH0ArTHYiTi2LikVCbIfNrmFI)

你用的是哪个版本啊，我试过很多次了，下载了最新版的代码不做任何修改也运行不起来，按你的这个配置也是一样的错误
