### ISSUE TITLE
积木报表的查询能不能自主定义是默认合并还是展开

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/JeecgBoot#7516]
##### 版本号：
 3.4.4

##### 问题描述：

查询框能不能自定义展开还是关闭，

##### 错误截图：
目前是默认合并的 

![image](https://github.com/user-attachments/assets/ed37bf10-d591-42e6-bba7-ffab19ba85b4)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版，或者看老文档
