### ISSUE TITLE
能否在“租户角色”界面增加授权功能

### ISSUE THREAD

**Issue by simonshh** [jeecgboot/JeecgBoot#7518]
##### 版本号：
3.7.1

##### 问题描述：
“我的租户”下的“租户角色”界面能否添加和“系统管理”下的“角色管理”界面相同的授权功能？如果可以的话应该怎样修改？

##### 错误截图：
![111](https://github.com/user-attachments/assets/78e1e68f-a3cc-4201-81f1-b0e115dd19cd)
![112](https://github.com/user-attachments/assets/38aecc9a-6230-42ed-b6d1-31e0643023cf)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
租户有个套餐包，通过套餐包来分配权限

**Comment by fenghlkevin** [comment]
> 租户有个套餐包，通过套餐包来分配权限

如果是这样的话，所有租户必须设置相同的套餐权限吗
