### ISSUE TITLE
RandDate组件设置预设范围后，点击预设项后日期区域选择弹框未自动关闭，需在外部额外再点一击次（试了antd原生的组件会自动关闭）

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/JeecgBoot#7525]
##### 版本号：
3.7.1

##### 问题描述：
RandDate组件设置预设范围后，点击预设项后日期区域选择弹框未自动关闭，需在外部额外再点一击次（试了antd原生的组件会自动关闭），如下图：
<img width="798" alt="image" src="https://github.com/user-attachments/assets/649fe7d0-9bac-4e49-9318-ea5d31e954c9">

代码：
<img width="966" alt="image" src="https://github.com/user-attachments/assets/fd5711af-406f-4df7-a940-6ff279379484">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
![iShot_2024-12-09_16 30 35](https://github.com/user-attachments/assets/2a6002ae-1c38-4f83-b14d-643781deb989)

你按如下改成异步写法就没问题
<img width="859" alt="image" src="https://github.com/user-attachments/assets/2ed6128e-646b-4eb4-9d77-68028f0ef858">

**Comment by jeecgDeveloper** [comment]
经查没复现，有更详细的信息吗？
![iShot_2024-12-09_18 29 52](https://github.com/user-attachments/assets/b448df84-0920-4e85-b576-999c845e78f0)
对应的组件是src/components/Form/src/jeecg/components/JRangeDate.vue，依赖的就是antd原生组件。


测试代码，你按我下面代码测试看是否有问题？
src/views/system/user/user.data.ts

```
{
    field: 'birthday_',
    component: 'RangeDate',
    label: '性别下拉',
    helpMessage: ['component模式'],
    componentProps: ({ tableAction, formActionType }) => {
      console.log('tableAction::', tableAction);
      return {
        presets: [
          { label: '今天', value: [dayjs(), dayjs()] },
          { label: '本周', value: [dayjs().day(1), dayjs().day(6).add(1, 'd')] },
        ],
        onChange: (e) => {
          const { reload } = tableAction;
          reload();
        },
      };
    },
    defaultValue:`${dayjs().add(-1,'year').format('YYYY-MM-DD')},${dayjs().format('YYYY-MM-DD')}`
  }



```
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/4b5e6b48-17e8-43cf-8e84-b9a1879cae3d">
