### ISSUE TITLE
多标签模式下，如何设置打开多个标签后，点击回到已打开的标签页面时不刷新页面，而是停留在上一次打开的状态

### ISSUE THREAD

**Issue by hhxyjsj** [jeecgboot/JeecgBoot#7526]
##### 版本号：
3.7.1

##### 问题描述：
多标签模式下，如何设置打开多个标签后，点击回到已打开的标签页面时不刷新页面，而是停留在上一次打开的状态

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
菜单路由开启缓存
