### ISSUE TITLE
BasicTable字段整体宽度不足矣撑满容器时，点击两列中间，前一列就会自动变宽

### ISSUE THREAD

**Issue by Chris19M25** [jeecgboot/JeecgBoot#7527]
##### 版本号：
3.7.0-beta

##### 问题描述：
当BasicTable字段较少时，点击两列中间，前一列就会自动变宽
当追加字段数直到出现横向滚动条后，就不会有这个问题

##### 错误截图：
![image](https://github.com/user-attachments/assets/fa96378e-dccd-4b6e-88cd-fb9d253e4919)

**Comment by zhangdaiscott** [comment]
最新版有这个问题吗

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
底层依赖的antd特性如此，只有当所有列给了width才会如此。

原生antd测试代码：
```
<template>
  <a-table :columns="columns" :data-source="data" @resizeColumn="handleResizeColumn">
    <template #headerCell="{ column }">
      <template v-if="column.key === 'name'">
        <span>
          <smile-outlined />
          Name
        </span>
      </template>
    </template>

    <template #bodyCell="{ column, record }">
      <template v-if="column.key === 'name'">
        <a>
          {{ record.name }}
        </a>
      </template>
      <template v-else-if="column.key === 'tags'">
        <span>
          <a-tag v-for="tag in record.tags" :key="tag" :color="tag === 'loser' ? 'volcano' : tag.length > 5 ? 'geekblue' : 'green'">
            {{ tag.toUpperCase() }}
          </a-tag>
        </span>
      </template>
      <template v-else-if="column.key === 'action'">
        <span>
          <a>Invite 一 {{ record.name }}</a>
          <a-divider type="vertical" />
          <a>Delete</a>
          <a-divider type="vertical" />
          <a class="ant-dropdown-link">
            More actions
            <down-outlined />
          </a>
        </span>
      </template>
    </template>
  </a-table>
</template>
<script lang="ts" setup>
  import { ref } from 'vue';
  import { SmileOutlined, DownOutlined } from '@ant-design/icons-vue';
  import type { TableColumnsType } from 'ant-design-vue';

  const data = [
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York No. 1 Lake Park',
      tags: ['nice', 'developer'],
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      address: 'London No. 1 Lake Park',
      tags: ['loser'],
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      address: 'Sidney No. 1 Lake Park',
      tags: ['cool', 'teacher'],
    },
  ];

  const columns = ref<TableColumnsType>([
    {
      dataIndex: 'name',
      key: 'name',
      width: 80,
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
      resizable: true,
      width: 150,
    },
    {
      title: 'Address',
      dataIndex: 'address',
      key: 'address',
      resizable: true,
       width: 150,
    },
    {
      title: 'Tags',
      key: 'tags',
      dataIndex: 'tags',
       width: 150,
      resizable: true,
    },
    {
      title: 'Action',
      key: 'action',
      width: 400,
    },
  ]);
  function handleResizeColumn(w, col) {
    col.width = w;
  }
</script>

```
![iShot_2024-12-09_19 23 18](https://github.com/user-attachments/assets/fb3f9d96-450e-44ce-9522-4f6fd36fc510)

你业务代码可如此修改（使用系统用户为例）：
src/views/system/user/user.data.ts
1.不是所有列都给宽度。

export const columns: BasicColumn[] = [
  {
    title: '用户账号',
    dataIndex: 'username',
    resizable: true,
    width: 150,
  },
  {
    title: '用户姓名',
    dataIndex: 'realname',
    minWidth: 150,
    width: true,
  },
  {
    title: '头像',
    dataIndex: 'avatar',
    customRender: render.renderAvatar,
  },
];

2.都值只给最小宽度
export const columns: BasicColumn[] = [
  {
    title: '用户账号',
    dataIndex: 'username',
    resizable: true,
    width: 150,
  },
  {
    title: '用户姓名',
    dataIndex: 'realname',
    minWidth: 150,
    width: true,
  },
  {
    title: '头像',
    dataIndex: 'avatar',
    customRender: render.renderAvatar,
  },
];

3.都不给宽度
export const columns: BasicColumn[] = [
  {
    title: '用户账号',
    dataIndex: 'username',
    resizable: true,
    minWidth: 150,
  },
  {
    title: '用户姓名',
    dataIndex: 'realname',
    minWidth: 150,
    resizable: true,
  },
  {
    title: '头像',
    dataIndex: 'avatar',
    minWidth: 150,
    resizable: true,
    customRender: render.renderAvatar,
  },
];
