### ISSUE TITLE
请问从仓库拉取来的最新的jeecgboot3.7.1，集成的积木报表不是最新版的是怎么回事啊

### ISSUE THREAD

**Issue by icegao** [jeecgboot/JeecgBoot#7528]
##### 版本号：
Jeecg  Boot Version: 3.7.1

##### 问题描述：
请问从仓库拉取来的最新的jeecgboot3.7.1，集成的积木报表不是最新版的是怎么回事啊
手动改版本号，重新install也还是这样
```
<dependency>
   <groupId>org.jeecgframework.jimureport</groupId>
   <artifactId>jimureport-spring-boot-starter</artifactId>
   <version>1.9.0</version>
</dependency>
```

##### 错误截图：
![image](https://github.com/user-attachments/assets/3436a6f3-a79a-468d-a3c1-ec33717cc0ce)
![image](https://github.com/user-attachments/assets/dfc15d9c-fbd0-4ccf-9c32-1c70a8c90785)
![image](https://github.com/user-attachments/assets/52fafe26-5f76-4cb6-b471-c094fc335b5f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
已经升级到最新了
