### ISSUE TITLE
请问JVxeTable表格怎么给表头设置样式

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7529]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by ak-2019** [comment]
![image](https://github.com/user-attachments/assets/d4d57656-a76a-457d-93aa-944844625cac)
![image](https://github.com/user-attachments/assets/9f6fc52b-a652-4ebf-bb21-ed3037be8a27)
按照官方文档加上去没有效果

**Comment by zhangdaiscott** [comment]
jl

**Comment by jeecgDeveloper** [comment]
支持 header-cell-class-name ，你写错了。header-cell-class-name  是字符串不是对象
![image](https://github.com/user-attachments/assets/1fcbe308-7eb6-4404-a078-67a73e999b3d)

**Comment by ak-2019** [comment]
> 支持 header-cell-class-name ，你写错了。header-cell-class-name 是字符串不是对象 ![image](https://private-user-images.githubusercontent.com/185453451/398374857-1fcbe308-7eb6-4404-a078-67a73e999b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzI0NTIsIm5iZiI6MTczNTAzMjE1MiwicGF0aCI6Ii8xODU0NTM0NTEvMzk4Mzc0ODU3LTFmY2JlMzA4LTdlYjYtNDQwNC1hMDc4LTY3YTczZTk5OWIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwOTIyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODE3Mjc4NTgwNmYzMjMyYjMwY2MxMmY2OGJiZjE4ZDQyYmExYjcyMTVmMDQ3YTFmNDg4MDJlYjMwODBjNzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xbYfj_Q3hT8OcQboCfGmmqbsWhbxxGGDlljjrjt3APU)

![1735035816988](https://github.com/user-attachments/assets/0ccb9f23-8361-41ee-af0f-f353f7ec9090)
![image](https://github.com/user-attachments/assets/bda71e5b-1302-418e-8570-172eecc8d6b9)
你好，请问字符串样式赋值之后，怎么设置样式？这样设置没有效果

**Comment by ak-2019** [comment]
> 支持 header-cell-class-name ，你写错了。header-cell-class-name 是字符串不是对象 ![image](https://private-user-images.githubusercontent.com/185453451/398374857-1fcbe308-7eb6-4404-a078-67a73e999b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDE5ODMsIm5iZiI6MTczNTA0MTY4MywicGF0aCI6Ii8xODU0NTM0NTEvMzk4Mzc0ODU3LTFmY2JlMzA4LTdlYjYtNDQwNC1hMDc4LTY3YTczZTk5OWIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxMjAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2E2N2U3YTA1OTQ0ZjhhNzg5NTM3ZWIzZmFiNmJjZmM4MDMyZTM5NDJmNmRlYmQ1ODY3NGRlYWQxZDNlYzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0uAlH0b6lowsLPbdjyzuNPxORah9A4S3XMSihaRVlj0)

![image](https://github.com/user-attachments/assets/d8de1747-0abb-4e82-a122-0b04f97bdba9)
![image](https://github.com/user-attachments/assets/2557e328-3173-4eac-ac06-832811f51d37)
我是想给不同的字段设置不同的背景颜色来着，请问是这样写吗？没有效果

**Comment by ak-2019** [comment]
感谢！
