### ISSUE TITLE
联动组件位置出现漂移

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7530]
##### 版本号：
3.7.1

##### 问题描述：

使用联动组件，选择第一个值时，位置出现漂移

##### 错误截图：

![Screenshot](https://github.com/user-attachments/assets/37b410ab-55dd-4ad7-ab81-f8a820a31e75)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个是正常的，因为弹出表单太小了
