### ISSUE TITLE
请问怎么关闭左侧和顶部菜单栏

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/JeecgBoot#7532]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
下个版本会有机制
https://help.jeecg.com/config/page-params.html
