### ISSUE TITLE
【3.7.1】JVxeTypes.rowNumber使用后 报错 提示 组件尚未注册，获取增强失败

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7533]
##### 版本号：
3.7.1

##### 问题描述：
JVxeTypes里有配置rowNumber 但是未定义相关代码 请问是否有关联的对应功能组件？还是未开发完成？

##### 错误截图：
![image](https://github.com/user-attachments/assets/235a7b13-1dc0-452b-af0f-19f5300f1d34)
![image](https://github.com/user-attachments/assets/a58e7d78-ade8-4eb4-8f11-8b8f9d66dc29)
![image](https://github.com/user-attachments/assets/bd3d62fb-9847-4f11-915f-0756f3d8f7db)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
这个是专用的，不是外面用的

**Comment by softboy99** [comment]
专用的？什么意思？

**Comment by benben120** [comment]
> 专用的？什么意思？

就是付费服务
