### ISSUE TITLE
通过编辑功能修改主子表关联字段会提示子表id主键冲突

### ISSUE THREAD

**Issue by yuqingwan** [jeecgboot/JeecgBoot#7535]
##### 版本号：
3.7.1

##### 问题描述：
在线表单通过编辑功能修改主子表关联字段会提示子表id主键冲突，如订单表和订单子表通过订单号关联，已生产订单修改订单号，提示子表id主键冲突

##### 错误截图：
![id](https://github.com/user-attachments/assets/c2c77061-41f8-409c-9541-011e6604124a)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
？具体配置详细说明

**Comment by yuqingwan** [comment]
[配置信息.docx](https://github.com/user-attachments/files/18045911/default.docx)
配置信息见附件word文件。

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgos** [comment]
已修复，请等待新版本发布。

**Comment by jeecgDeveloper** [comment]
代码生成需要您自行修改后台代码，详情请参考，修改代码方法为`updateMain`

![image](https://github.com/user-attachments/assets/02e3686f-c849-40cf-889a-49ee535d7509)
