### ISSUE TITLE
文件上传失败，源代码中接口找不到

### ISSUE THREAD

**Issue by Logers-kcm** [jeecgboot/JeecgBoot#7537]
##### 版本号：
3.7.1（发布日期：2024-09-12）

##### 问题描述：
我用平台建了一张mysql的数据表，建成功以后通过excel向里面导数据，导不进去，没有online/cgform/api/importXls这个接口，idea控制台没有报错输出

##### 错误截图：
<img width="932" alt="157cc5599c62dfbb58edc4157049473" src="https://github.com/user-attachments/assets/021bf076-6689-4860-a719-6064ce4017fe">
<img width="757" alt="2d3134e745ea99741995bf718e96b2c" src="https://github.com/user-attachments/assets/c3ddee8b-2535-4cdc-8599-ac6bb0f327e6">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个源码不提供
