### ISSUE TITLE
jeecgboot-vue3 部分页面使用@primary-color不生效

### ISSUE THREAD

**Issue by Ada-wxr** [jeecgboot/JeecgBoot#7539]
##### 版本号：
3.6.3
##### 问题描述：
部分页面使用background-color: @primary-color;会跟随系统主题，但一些页面使用不生效，代码写的完全相同

##### 错误截图：
下图为跟随主题色不生效代码及项目截图
![跟随主题色不生效代码](https://github.com/user-attachments/assets/f6ea9bea-6bf1-4d8c-a753-eb6fef0ccc19)
![跟随主题色不生效项目截图](https://github.com/user-attachments/assets/3ba8133c-f86b-4950-b3c9-cccafe85e1a7)

下图为跟随主题色生效代码
![正常跟随主题色代码](https://github.com/user-attachments/assets/6235ab9f-5f1c-4634-ac46-1956c4d19568)
![跟随主题色生效项目截图](https://github.com/user-attachments/assets/0441294e-73f4-43a6-8e6e-d04fc95d0a9a)

甚至有的界面没有写代码也会变的跟随主题色

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Ada-wxr** [comment]
您好，请问我提的issue是哪里有问题吗？

**Comment by zhangdaiscott** [comment]
自己写的代码，我们没办法判断
