### ISSUE TITLE
后端部署tomcat报错

### ISSUE THREAD

**Issue by zpfzpf123** [jeecgboot/JeecgBoot#7540]
##### 版本号：
3.7.1

##### 问题描述：

后端代码打包后部署到tomcat，日志报错，本地运行无问题

##### 错误截图：
![Snipaste_2024-12-04_10-34-25](https://github.com/user-attachments/assets/c60e9534-e35e-433a-a2a6-d815796b8d71)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
百度，不清楚
