### ISSUE TITLE
代码自动生成后，把代码文件移动项目中就爆这样的错

### ISSUE THREAD

**Issue by 313761744** [jeecgboot/JeecgBoot#7544]
##### 版本号：
3.7.1

##### 问题描述：
代码自动生成后，把代码文件移动项目中就爆这样的错

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by 313761744** [comment]
2024-12-05 13:46:35.977 [http-nio-8080-exec-1] WARN  org.apache.shiro.mgt.AbstractRememberMeManager:449 - There was a failure while trying to retrieve remembered principals.  This could be due to a configuration problem or corrupted principals.  This could also be due to a recently changed encryption key, if you are using a shiro.ini file, this property would be 'securityManager.rememberMeManager.cipherKey' see: http://shiro.apache.org/web.html#Web-RememberMeServices. The remembered identity will be forgotten and not used for this request.
2024-12-05 13:46:35.978 [http-nio-8080-exec-1] WARN  org.apache.shiro.mgt.DefaultSecurityManager:618 - Delegate RememberMeManager instance of type [org.apache.shiro.web.mgt.CookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.crypto.CryptoException: Unable to execute 'doFinal' with cipher instance [Cipher.AES/GCM/NoPadding, mode: decryption, algorithm from: SunJCE].

**Comment by zhangdaiscott** [comment]
具体怎么用的，录歌视频或者详细说明步骤

**Comment by 313761744** [comment]
生成的代码文件，我把他放到项目中重新运行，就爆这样的错



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月5日(星期四) 中午1:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/JeecgBoot] 代码自动生成后，把代码文件移动项目中就爆这样的错 (Issue #7544)














 
具体怎么用的，录歌视频或者详细说明步骤

**Comment by 313761744** [comment]
现在项目只要访问个菜单就会爆警告“There was a failure while trying to retrieve remembered principals.  This could be due to a configuration problem or corrupted principals.  This could also be due to a recently changed encryption key, if you are using a shiro.ini file, this property would be 'securityManager.rememberMeManager.cipherKey' see: http://shiro.apache.org/web.html#Web-RememberMeServices. The remembered identity will be forgotten and not used for this request.”，请问怎么把这个关闭，不要爆了，好烦，谢谢啦

**Comment by zhangdaiscott** [comment]
百度吧，应该是你的环境问题

**Comment by 313761744** [comment]
online自动生成的模糊查询文本框不显示用不了，怎么回事？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月6日(星期五) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 代码自动生成后，把代码文件移动项目中就爆这样的错 (Issue #7544)





 
Closed #7544 as completed.

**Comment by zhangdaiscott** [comment]
换成jinput组件

**Comment by 313761744** [comment]
<JInput placeholder="请输入车号" v-model:value="queryParam.carNo" allow-clear&gt;</JInput&gt;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 代码自动生成后，把代码文件移动项目中就爆这样的错 (Issue #7544)





 
换成jinput组件

**Comment by 313761744** [comment]
根据前面字段名，下拉模糊查询没有效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/JeecgBoot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/JeecgBoot] 代码自动生成后，把代码文件移动项目中就爆这样的错 (Issue #7544)





 
换成jinput组件
