### ISSUE TITLE
jeecgboot3 table每页条数超过80条 导致。复选框丢失

### ISSUE THREAD

**Issue by mazhijiang318** [jeecgboot/JeecgBoot#7545]
##### 版本号：
jeecgboot3

##### 问题描述：
table 每页超过80条数据复选框丢失
![Snipaste_2024-12-05_15-07-07](https://github.com/user-attachments/assets/16d05c98-7bdf-4956-9ee4-9d8f55a0ae59)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本号

**Comment by mazhijiang318** [comment]
3.5.4

**Comment by zhangdaiscott** [comment]
升级到最新版，优化过
