### ISSUE TITLE
springboot3的前端分支首页无限loading

### ISSUE THREAD

**Issue by yaleond** [jeecgboot/JeecgBoot#7547]
##### 版本号：
3.7.1

##### 问题描述：
springboot3分支的前端代码启动后，浏览器访问时一直无限loading
下载master分支的前端代码连接springboot3的后端服务，首页能正常显示登录界面

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by yaleond** [comment]
搜到另一个ID的问题6861，现象一致。
是不是master的前端代码跟springboot3的代码不一致导致的？
我可不可以用master的前端代码去连springboot3的后端？

**Comment by zhangdaiscott** [comment]
可以，一样的前端现在

**Comment by yaleond** [comment]
> 可以，一样的前端现在

好的，谢谢，那我用master分支的前端了，估计springboot3的前端代码不是最新的了
