### ISSUE TITLE
显示左侧logo时会导致下面菜单滚动显示不全

### ISSUE THREAD

**Issue by ZHANGLUInfinite** [jeecgboot/JeecgBoot#7548]
##### 问题描述：
显示左侧logo时，因为logo高度为60，但是下面菜单计算时减去的是48会导致菜单滚动到底部时显示不全。

##### 错误截图：
![image](https://github.com/user-attachments/assets/5218c058-1cc1-46ea-b5e3-289dd57d3d98)

##### 正确的显示应该是可以把菜单padding部分也显示全的。。正确显示截图：
![image](https://github.com/user-attachments/assets/839704ec-ca8b-46fe-b950-01b125a8ab21)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本号

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
