### ISSUE TITLE
Online 表单开发 页面属性 查询选择模糊查询 结果生成的代码是  JRangeNumber  而且页面中不显示

### ISSUE THREAD

**Issue by mistHuShuai** [jeecgboot/JeecgBoot#7549]
##### 版本号：
官方domo地址 https://boot3.jeecg.com/online/cgform

##### 问题描述：
Online 表单开发 页面属性 查询选择模糊查询 结果生成的代码是  JRangeNumber  而且页面中不显示

##### 错误截图：

![image](https://github.com/user-attachments/assets/101f2ef5-dc16-447c-9dfc-dfe6223be46e)
![image](https://github.com/user-attachments/assets/b10e83b8-091d-4a61-aa56-83179fdc1b47)
![image](https://github.com/user-attachments/assets/24540127-e79b-4ba9-bead-e2180a7ee2c4)
![image](https://github.com/user-attachments/assets/69310fb0-a201-46ea-974c-b6371b383361)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本号

**Comment by zhangdaiscott** [comment]
ws

**Comment by mistHuShuai** [comment]
> 版本号

https://boot3.jeecg.com/online/cgform 在官方示例里面

**Comment by zhangdaiscott** [comment]
修改版本修复

**Comment by mistHuShuai** [comment]
> 修改版本修复

对不起 这个修改版本修复是什么意思 我不明白
