### ISSUE TITLE
正式环境下积木BI无法预览和设计

### ISSUE THREAD

**Issue by jackson03180824** [jeecgboot/JeecgBoot#7550]
##### 版本号：
3.7.1

##### 问题描述：
jeecgboot集成了最新版的积木报表BI的版本，在部署到正式环境后，积木报表使用没有任何问题，但是积木BI点击设计或者预览仪表板或者大屏的时候接口就请求不通了。

##### 错误截图：
![8F4ECFA33FA8D5E5481463514BF4EC22](https://github.com/user-attachments/assets/0b6d7ec4-dc2f-4212-b354-4ef93c3c4a8f)
![52FF81C1081B6CC9728FA560FB7BDE5D](https://github.com/user-attachments/assets/7f445673-b485-403b-b3d4-e953b9020be8)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
仪表盘的访问地址是什么样的

**Comment by jackson03180824** [comment]
http://192.168.0.8:8989/dentao-api/drag/index?pageId=1024892041946910720&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzM3NjU5NzksInVzZXJuYW1lIjoiYWRtaW4ifQ.jvIR-kFWnfM7JQQfgKXNWOl7dqQ5j574CL5wWTYseyI&tenantId=1000&style=default

**Comment by jackson03180824** [comment]
@zhangdaiscott http://192.168.0.8:8989/dentao-api/drag/index?pageId=1024892041946910720&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzM3NjU5NzksInVzZXJuYW1lIjoiYWRtaW4ifQ.jvIR-kFWnfM7JQQfgKXNWOl7dqQ5j574CL5wWTYseyI&tenantId=1000&style=default

**Comment by zhangdaiscott** [comment]
积木报表的呢

**Comment by jackson03180824** [comment]
http://192.168.0.8:8989/dentao-api/jmreport/index/965205577251782656?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzM3NjU5NzksInVzZXJuYW1lIjoiYWRtaW4ifQ.jvIR-kFWnfM7JQQfgKXNWOl7dqQ5j574CL5wWTYseyI&tenantId=1000

**Comment by zhangdaiscott** [comment]
不清楚，看看我们演示环境，没问题
https://boot3.jeecg.com

**Comment by jackson03180824** [comment]
我现在是通过内网的地址访问的，jar包运行在34567端口，我前端通过内网不走nginx直接连34567端口是没问题的，但是通过nginx代理过后就无法设计预览了，但是其他功能也没有问题啊，就只有BI无法设计预览

**Comment by zhangdaiscott** [comment]
那还是代理的事

**Comment by jackson03180824** [comment]
location /dentao-api {
proxy_pass http://127.0.0.1:34567/dentao-api;
proxy_redirect off;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}这是我配置的代理
![image](https://github.com/user-attachments/assets/a55296c7-b1e5-462a-a3ee-86da149e6511)
![image](https://github.com/user-attachments/assets/c58a8893-0699-49ff-8050-29c8d57a6a62)
上面的都有端口，下面的端口都没了是咋回事啊
