### ISSUE TITLE
启动参数设置问题

### ISSUE THREAD

**Issue by Teslaxzy** [jeecgboot/JeecgBoot#7551]
##### 版本号：

3.2.0
##### 问题描述：
想多个环境共用一个jar包，切换环境不重新打包，在启动参数添加 --spring.profiles.active=dev 后，启动不生效，还是会读取打包时的环境参数，需要怎么配置？

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这么配置没错具体问题需要自己看
