### ISSUE TITLE
jeecgboot导入excel文件报错

### ISSUE THREAD

**Issue by ouoie** [jeecgboot/JeecgBoot#7553]
##### 版本号：
The Latest Version： 3.4.4（Release date：2022-11-21） 

##### 问题描述：
使用框架方法导入excel文件，当文件中有空格，会识别报错；当字典值填入不匹配，也会识别报错；
怎么解决，求解决方法，最好有案例

##### 错误截图：
<img width="1280" alt="导入问题01" src="https://github.com/user-attachments/assets/30de9230-db65-4632-96dd-4a46bb8ec77b">
<img width="86" alt="导入问题02" src="https://github.com/user-attachments/assets/1f2827fa-ada7-476d-85d2-555ee6c37824">
<img width="87" alt="导入问题03" src="https://github.com/user-attachments/assets/1a0a35e0-ba25-40dd-b0a1-7ff0559d4400">
![image](https://github.com/user-attachments/assets/517c252a-95ac-492b-adc0-9ba9ac3aaa75)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
老版本，可以debug跟踪代码
我们不好分析
https://github.com/jeecgboot/autopoi
