### ISSUE TITLE
1.9.1版本的积木仪表盘，统计卡片，动态数据，某些数值、总数等无法展示

### ISSUE THREAD

**Issue by 1093702350** [jeecgboot/JeecgBoot#7554]
##### 版本号：
1.9.1

##### 问题描述：
1.9.1版本的积木仪表盘，统计卡片选择动态数据，接口返回了数据，标题能展示，但是数值、总数等选择后无法展示。

不确定是不支持复杂sql，还是哪里设置有问题？

##### 错误截图：

![微信图片_20241208172235](https://github.com/user-attachments/assets/fe73a8b8-204c-4cfd-841c-4ffe47c6adcc)

![QQ20241208-172640](https://github.com/user-attachments/assets/2e168578-1bf9-454c-8bd2-360b7e74928f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by 1093702350** [comment]
问题已解决，在此留帖，希望后续能帮助到其他人。是因为 数据集sql 下方的字段名设置必须是大写！！！，这一点希望写在帮助手册中，这太隐蔽了，尝试了很多方式，才最终得出结论。
![微信图片_20241208173111](https://github.com/user-attachments/assets/ff7331a9-57d8-4ead-b6fb-ecdf42da61af)

**Comment by 1093702350** [comment]
再补充一点，不知道是不是因为主库区分大小写的原因，我的情况是使用oralce的数据源，且主库区分大小写。

**Comment by zhangdaiscott** [comment]
就是大小写导致的

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
