### ISSUE TITLE
配置https

### ISSUE THREAD

**Issue by bigBoy-pp** [jeecgboot/JeecgBoot#7557]
你好，我在使用jeecgboot时，部署到阿里云上，在tomcat的server.xml配置http时，限制文件上传大小50m是没问题的，后来我使用https配置在tomcat时，上传文件接口总是返回：Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly，我想问一下咱们这个系统在配置https时，需要在yml文件中配置什么吗

**Comment by zhangdaiscott** [comment]
你百度下看你的配置，我们应该没有限制

**Comment by bigBoy-pp** [comment]
问一下，如果在tomcat中配置了https，还用在jeecgboot的yml中配置吗

**Comment by zhangdaiscott** [comment]
不需要
