### ISSUE TITLE
主题切换为顶部混合模式时，页面顶部内容显示不出来，被遮盖

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/JeecgBoot#7561]
##### 版本号：
3.7.2

##### 问题描述：
顶部混合模式下页面布局问题

##### 错误截图：
![1](https://github.com/user-attachments/assets/c7a68157-d5c4-45b2-9954-d3d771783ed1)

![2](https://github.com/user-attachments/assets/b2fb4990-a949-4bdf-b5bc-3285f81a5437)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by dfreng** [comment]
自行调整方法：
src/layouts/default/header/MultipleHeader.vue
103行
if (
          ((unref(getShowFullHeaderRef) || !unref(getSplit)) && unref(getShowHeader) && !unref(getFullContent)) ||
          unref(getMenuType) == MenuTypeEnum.MIX
        ) {
          height += HEADER_HEIGHT;
        }

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。
