### ISSUE TITLE
首次启动项目，报flyway相关的SQL异常。

### ISSUE THREAD

**Issue by SpencerPeng** [jeecgboot/JeecgBoot#7562]
##### 版本号：
3.7.2

##### 问题描述：

首次启动项目，报flyway相关的SQL异常。经核实，当前表中已有相关字段。

##### 错误截图：

<img width="1297" alt="image" src="https://github.com/user-attachments/assets/6099d192-443e-4304-ab22-c4c9c73a6cf1">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你是什么时间下载的jeecgboot

**Comment by EightMonth** [comment]
未复现
![image](https://github.com/user-attachments/assets/1c7dafb2-af3e-4b63-92b2-fb9f3ac6cdcc)

**Comment by zhangdaiscott** [comment]
应该你是最近下载的版本，那个时候已经加入了积木BI

**Comment by SpencerPeng** [comment]
昨天下载的，昨天本地部署，需要删除flyway里面最新一个SQL文件。

**Comment by SpencerPeng** [comment]
相关内容在初始化部署导入MYSQL时（jeecgboot-mysql-5.7.msql），已经写入了最新的数据。

**Comment by SpencerPeng** [comment]
建议删除最后一个flyway的 SQL文件，或者在jeecgboot-mysql-5.7.msql中删除有关数据。不然拉取最新的master分支应该会有同样异常。

**Comment by zhangdaiscott** [comment]
那个

**Comment by SpencerPeng** [comment]
v3.7.21__jimureport_upgrade.sql

**Comment by zhangdaiscott** [comment]
你是什么时候的数据库

**Comment by zhangdaiscott** [comment]
是有问题，明白了
