### ISSUE TITLE
编译缺失文件useMyRunningTaskList

### ISSUE THREAD

**Issue by elinxer** [jeecgboot/JeecgBoot#7563]
##### 版本号：

v3.7.2

##### 问题描述：

编译缺失文件useMyRunningTaskList，打开源码，没有发现这个文件

(imported by src/hooks/web/useDragNotice.ts): ENOENT: no such file or directory,

##### 错误截图：

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/f1c39792-3d36-4de5-aa3c-a1047d896dc6">

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
提交了
