### ISSUE TITLE
刚下载的3.7.2启动报错

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/JeecgBoot#7565]
##### 版本号：

3.7.2
##### 问题描述：

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dataSource', defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
master分支？

**Comment by zhangdaiscott** [comment]
代码一点没改？

**Comment by zhangdaiscott** [comment]
单体还是微服务？请详细说明

**Comment by wuxiangliang821** [comment]
![微信截图_20241210171603](https://github.com/user-attachments/assets/18a9f70d-08ac-462a-b147-0d248b8cabf3)
![image](https://github.com/user-attachments/assets/ac41b8e0-866e-46ba-875f-4a68e83be071)
我的也报错了，master分支，单体项目启动

**Comment by zhangdaiscott** [comment]
你这个错误都不知道吗，白做java开发了
![image](https://github.com/user-attachments/assets/4783f581-71e9-4dba-9dee-690c941afb83)

**Comment by zwjsoft** [comment]
我后来配 spring.main.allow-bean-definition-overriding=true后好了，现在删除了也是好的，原因不详

**Comment by zhangdaiscott** [comment]
好发现问题再发issue
