### ISSUE TITLE
jeecgboot-vue2启动前端服务异常

### ISSUE THREAD

**Issue by WangYe2017** [jeecgboot/JeecgBoot#7566]
##### 版本号：
jeecgboot-vue2

##### 问题描述：
yarn install 安装依赖成功后，运行yarn run serve报错找不到模块@jridgewell/gen-mapping/dist/gen-mapping.umd.js，但是/dist/gen-mapping.umd.js这个地址是@jridgewell/gen-mapping模块export出来的，在@jridgewell/gen-mapping模块中实际并没有dist这个文件夹

##### 错误截图：

![WX20241210-164304@2x](https://github.com/user-attachments/assets/bef2c8c2-96e2-4bb9-9bbc-45593215cabd)
![WX20241210-164334@2x](https://github.com/user-attachments/assets/0b6bc482-c0b6-45a5-bac0-8648134f9057)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本太老，依赖有冲突，你可以把package。json中的依赖版本都固定
去掉所有的
![image](https://github.com/user-attachments/assets/2fb1d480-1387-4918-9926-c47f1006dc9a)
