### ISSUE TITLE
大屏功能的动态数据，报： 接口地址异常

### ISSUE THREAD

**Issue by cy9296** [jeecgboot/JeecgBoot#7571]
##### 版本号：
在线大屏设计器，[v1.9.1 首个大屏稳定版]

##### 问题描述：
咨询：  大屏功能的动态数据 ，我配置了自己云服务器的地址，用浏览器可以正常访问，但是在系统里点刷新，报：接口地址异常
下面的地址写法有问题吗：
http://121.37.1.1:8010/generation/

接口地址返回：
{
    "data": [
        {
            "backgroundColor": "#67C23A",
            "prefixText": "xx省销售额",
            "value": "3254",
            "suffixText": "元"
        },
        {
            "backgroundColor": "#409EFF",
            "prefixText": "xx省销售额",
            "value": "1596",
            "suffixText": "元"
        },
        {
            "backgroundColor": "#E6A23C",
            "prefixText": "xx省销售额",
            "value": "6354",
            "suffixText": "元"
        },
        {
            "backgroundColor": "#F56C6C",
            "prefixText": "xx省销售额",
            "value": "7256",
            "suffixText": "元"
        },
        {
            "backgroundColor": "#7232dd",
            "prefixText": "xx省销售额",
            "value": "6365",
            "suffixText": "元"
        },
        {
            "backgroundColor": "blue",
            "prefixText": "xx省销售额",
            "value": "3294",
            "suffixText": "元"
        }
    ]
}

我的地址返回：
{
    "data": [
        {
            "backgroundColor": "#7232dd",
            "prefixText": "园区总发电量",
            "value": "5604",
            "suffixText": "kWh"
        },
        {
            "backgroundColor": "blue",
            "prefixText": "CO2总减排量",
            "value": "3284",
            "suffixText": "kg"
        }
    ]
}

##### 错误截图：
![image](https://github.com/user-attachments/assets/16024c2b-2b00-470e-95bd-af8f2a3dcc35)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
录个视频看配置和错误效果

**Comment by cy9296** [comment]
请参见附件视频。
只要不是原来默认的API网址，就会报错。

https://github.com/user-attachments/assets/7b2522e5-3c2e-4eb5-85a2-5ec4ea8dfb06

**Comment by zhangdaiscott** [comment]
F12看看什么错

**Comment by cy9296** [comment]
声明，不是内网地址，是一个云服务器的地址。

http://121.37.189.206
:8009/generation/
F12没有报什么错误。

你把这个地址配进去，试试看有无错误。

**Comment by cy9296** [comment]
> 你真有才 你那个接口地址，是你的内网地址吧

声明，不是内网地址，是一个云服务器的地址。

http://121.37.189.206
:8009/generation/
F12没有报什么错误。

你把这个地址配进去，试试看有无错误。

**Comment by jeecgDeveloper** [comment]
> > 你真有才 你那个接口地址，是你的内网地址吧
> 
> 声明，不是内网地址，是一个云服务器的地址。
> 
> http://121.37.189.206 :8009/generation/
> 
> 你们范例给的地址 url，最后没有 /，而我这个有 /，这个会有影响吗？
> 
> F12没有报什么错误。
> 
> 你们把这个地址配进去，试试看有无错误，就知道这个问题是否真实存在了。

报错了，需要提供https前缀的接口 ![image](https://github.com/user-attachments/assets/353d0d21-8702-423f-9d57-9f74dd11f680)

**Comment by zhangdaiscott** [comment]
官网是https的，无法去调用http开头的接口

**Comment by cy9296** [comment]
了解了，我再试一下 https 的，thks。
建议文档里说明一下这个限制。

**Comment by cy9296** [comment]
> > > 你真有才 你那个接口地址，是你的内网地址吧
> > 
> > 
> > 声明，不是内网地址，是一个云服务器的地址。
> > http://121.37.189.206 :8009/generation/
> > 你们范例给的地址 url，最后没有 /，而我这个有 /，这个会有影响吗？
> > F12没有报什么错误。
> > 你们把这个地址配进去，试试看有无错误，就知道这个问题是否真实存在了。
> 
> 报错了，需要提供https前缀的接口 !

测试了 https，可以了，谢谢！
