### ISSUE TITLE
Online 表单零代码模块，可以免费商用吗？

### ISSUE THREAD

**Issue by coderBy** [jeecgboot/JeecgBoot#7572]
##### 问题描述：
Online 表单零代码模块，可以免费商用吗？需要购买商业授权吗？

##### 错误截图：

![image](https://github.com/user-attachments/assets/160bbfd7-098f-49d7-9046-f9cf7099860c)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
可以免费用
