### ISSUE TITLE
【3.7.2】jeecg-boot-vue3能否通过qiankun 集成 jeecg-boot-vue2作为子应用项目 【提议】

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7574]
##### 版本号：

3.7.2
##### 问题描述：
jeecg-boot-vue3能否通过qiankun 集成 jeecg-boot-vue2 【提议】
有jeecg-boot-vue2的老旧项目 作为子应用 集成在 主应用 jeecg-boot-vue3中的方案么
跟之前提的issue有误解 目前大部分新项目使用vue3版本 但是 无法集成jeecg-boot-vue2项目过来 完全重构 使用vue3新项目 时间也不足。
通过迭代 一步步替换掉jeecg-boot-vue2 子应用的 页面功能。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
应该可以

**Comment by benben120** [comment]
> 应该可以

jeecg-boot-vue2作为子应用 的方案代码 有安排一下么 因为目前大部分原因都是 无法直接弃用旧的 jeecg-boot-vue2 项目 而是 需要并行使用 并且一步步在新的jeecg-boot-vue3项目上迭代旧页面代码

**Comment by zhangdaiscott** [comment]
jeecg-boot-vue2 自己集成乾坤吧，我们维护不过来
