### ISSUE TITLE
大屏中https的链接却访问http接口

### ISSUE THREAD

**Issue by 1169797088** [jeecgboot/JeecgBoot#7577]
##### 版本号：
3.7.1

##### 问题描述：
使用https打开大屏设计的页面，访问接口时访问的是http,已经使用nginx做重定向处理，其它接口可以，但是大屏不行

##### 错误截图：
<img width="449" alt="3f5de739cf8ee12647b6bd10ae219b7" src="https://github.com/user-attachments/assets/dfe3e626-d6e4-4316-8351-c032881ce88c" />

<img width="1442" alt="afe812972eec95392fb51f2cd366e08" src="https://github.com/user-attachments/assets/11e99c36-00a4-4562-b0f7-76b886331441" />

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
boot3.jeecg.com
演示无问题
