### ISSUE TITLE
tinymce可以集成下kityformula-editor

### ISSUE THREAD

**Issue by yangfeng005** [jeecgboot/JeecgBoot#7578]
##### 版本号：
3.7.2

##### 问题描述：
 tinymce目前不支持数学公式

##### 错误截图：
![WX20241212-144914@2x](https://github.com/user-attachments/assets/d0de0e05-5df0-479b-9cfc-fa0e70cf6fcb)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
需要什么自己扩展就行，我们为了让项目小，特意弄的最简配
