### ISSUE TITLE
onlDragCompController的bean冲突问题

### ISSUE THREAD

**Issue by ruya-song** [jeecgboot/JeecgBoot#7579]
##### 问题描述：jeecg3.5.2版本集成积木报表1.9.1，导入依赖后重启system报错
024-12-12 14:39:09.418 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:591 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgSystemCloudApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'onlDragCompController' for bean class [org.jeecg.modules.drag.b.c] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.drag.b.e]

##### 错误截图：
![dc6976ef-6dea-4105-af3d-a5bb08bbe6e7](https://github.com/user-attachments/assets/aec624f5-f18f-438f-a506-6b676ab9c001)

**Comment by zhangdaiscott** [comment]
你需要把原来的仪表盘去掉
