### ISSUE TITLE
大屏/BI设计器编辑的时候，出现报错 Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by Adonis-li** [jeecgboot/JeecgBoot#7580]
##### 版本号：
3.7.1

##### 问题描述：
https访问 /drag/index 预览或则设计页面的时候报错 Failed to execute 'open' on 'XMLHttpRequest': Invalid URL，而且一直转圈圈

##### 错误截图：

![image](https://github.com/user-attachments/assets/9f6747aa-3fc7-4f49-bb15-00790d0690d1)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by Adonis-li** [comment]
@zhangdaiscott 就是open的那个地址拼接了一个 ip：-1 导了这个问题，我使用的版本是1.9.1，请问官方最新的版本是这个吗

**Comment by Adonis-li** [comment]
> 试下最新版
> 
> boot3.jeecg.com演示环境没问题啊

就是open的那个地址拼接了一个 ip：-1 导了这个问题，我使用的版本是1.9.1，请问官方最新的版本是这个吗

**Comment by zhangdaiscott** [comment]
最新的
截图看，哪里有-1

**Comment by Adonis-li** [comment]
> 最新的 截图看，哪里有-1

![image](https://github.com/user-attachments/assets/b4a38c2f-5765-4c40-bb19-ad90de868f3e)
找到问题了，就是获取ip的时候获取的是当前机器的ip和端口并且拼接的是http 怎么 能够拼接成https://域名

**Comment by Adonis-li** [comment]
已解决，通过配置nginx的配置解决了
![image](https://github.com/user-attachments/assets/f1bf7c41-1c14-443a-8ea5-6ecd30508b90)

**Comment by Adonis-li** [comment]
已解决，通过配置nginx
![1734052686362](https://github.com/user-attachments/assets/45d021f5-038e-43f4-b7d0-2b06e98db669)

**Comment by jeecgDeveloper** [comment]
> > 最新的 截图看，哪里有-1
> 
> ![image](https://private-user-images.githubusercontent.com/53810297/395094487-b4a38c2f-5765-4c40-bb19-ad90de868f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTk5MDgsIm5iZiI6MTczNDM5OTYwOCwicGF0aCI6Ii81MzgxMDI5Ny8zOTUwOTQ0ODctYjRhMzhjMmYtNTc2NS00YzQwLWJiMTktYWQ5MGRlODY4ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMTExYzZiOTI1ZWM5OWVjMGU4MzZjMjU5ZTBmZWEyN2VhM2JlNzU0NTY5N2M3NzBhZDM4NGEyYWRiYTc5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z2K0w_yj8IwdYmgSsxuiNR_ZVhA1i5syeC7D96iU4S0) 找到问题了，就是获取ip的时候获取的是当前机器的ip和端口并且拼接的是http 怎么 能够拼接成[https://域名](https://%E5%9F%9F%E5%90%8D)

你说的 -1 是哪个地方？没看到你截图有-1的地方呢？

**Comment by 1169797088** [comment]
> > > 最新的 截图看，哪里有-1
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/53810297/395094487-b4a38c2f-5765-4c40-bb19-ad90de868f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTk5MDgsIm5iZiI6MTczNDM5OTYwOCwicGF0aCI6Ii81MzgxMDI5Ny8zOTUwOTQ0ODctYjRhMzhjMmYtNTc2NS00YzQwLWJiMTktYWQ5MGRlODY4ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMTExYzZiOTI1ZWM5OWVjMGU4MzZjMjU5ZTBmZWEyN2VhM2JlNzU0NTY5N2M3NzBhZDM4NGEyYWRiYTc5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z2K0w_yj8IwdYmgSsxuiNR_ZVhA1i5syeC7D96iU4S0) 找到问题了，就是获取ip的时候获取的是当前机器的ip和端口并且拼接的是http 怎么 能够拼接成[https://域名](https://%E5%9F%9F%E5%90%8D)
> 
> 你说的 -1 是哪个地方？你们是微服务方式使用的吗？

我用的单体服务，我也出现了地址是https，但是有两个接口访问是http，想问下这个有配置么?
![image](https://github.com/user-attachments/assets/49bf1f9f-7674-4474-81c2-e886a47105e4)
![image](https://github.com/user-attachments/assets/1309603c-7098-47d7-81a2-767f4068f072)

**Comment by jeecgDeveloper** [comment]
> > > > 最新的 截图看，哪里有-1
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/53810297/395094487-b4a38c2f-5765-4c40-bb19-ad90de868f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTk5MDgsIm5iZiI6MTczNDM5OTYwOCwicGF0aCI6Ii81MzgxMDI5Ny8zOTUwOTQ0ODctYjRhMzhjMmYtNTc2NS00YzQwLWJiMTktYWQ5MGRlODY4ZjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMTExYzZiOTI1ZWM5OWVjMGU4MzZjMjU5ZTBmZWEyN2VhM2JlNzU0NTY5N2M3NzBhZDM4NGEyYWRiYTc5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z2K0w_yj8IwdYmgSsxuiNR_ZVhA1i5syeC7D96iU4S0) 找到问题了，就是获取ip的时候获取的是当前机器的ip和端口并且拼接的是http 怎么 能够拼接成[https://域名](https://%E5%9F%9F%E5%90%8D)
> > 
> > 
> > 你说的 -1 是哪个地方？你们是微服务方式使用的吗？
> 
> 我用的单体服务，我也出现了地址是https，但是有两个接口访问是http，想问下这个有配置么? ![image](https://private-user-images.githubusercontent.com/67069429/396395514-49bf1f9f-7674-4474-81c2-e886a47105e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjA5MTQsIm5iZiI6MTczNDQyMDYxNCwicGF0aCI6Ii82NzA2OTQyOS8zOTYzOTU1MTQtNDliZjFmOWYtNzY3NC00NDc0LTgxYzItZTg4NmE0NzEwNWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MzAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYjExOWZiZDc1NjU3ODNjMjgxMjhhZmE0ODA1MDhhYzA0YjM5OTM0MTg1ZjBhM2UzY2U5MWY4NWIyNGM5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R9i4YumJX3xGpXwsdidUnFvILyGDGKjPDTUVdWc0DzQ) ![image](https://private-user-images.githubusercontent.com/67069429/396395823-1309603c-7098-47d7-81a2-767f4068f072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjA5MTQsIm5iZiI6MTczNDQyMDYxNCwicGF0aCI6Ii82NzA2OTQyOS8zOTYzOTU4MjMtMTMwOTYwM2MtNzA5OC00N2Q3LTgxYTItNzY3ZjQwNjhmMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MzAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MzUwY2NjZDkwNzM4MGU4ZDFkYTUyM2JmNDJmMDljZjA5NDRhNjU2YWI5ZWM0MzI5MmU1NmVlOGRkNDJhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I9L0usJVISg6JwqrzpcOOk-ByaDw2BSv8B3JxguGHNM)

配置一下 X-Forwarded-Scheme

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布后可测试
