### ISSUE TITLE
图表是否支持添加查询条件呢？

### ISSUE THREAD

**Issue by baotianrui** [jeecgboot/JeecgBoot#7584]
图表是否支持添加查询呢条件？如下图，期望各个小图表都根据顶部的“当月”、“当前季度”等查询条件变化显示
![image](https://github.com/user-attachments/assets/25171083-a6cd-46c2-b9c1-4ad254df68f3)

**Comment by zhangdaiscott** [comment]
可以

按照个发发帖，都不知道你是那个版本号
