### ISSUE TITLE
账户设置->修改手机号：获取验证码接口 404 错误

### ISSUE THREAD

**Issue by dahai2025** [jeecgboot/JeecgBoot#7587]
##### 版本号：
3.7.2

##### 问题描述：
账户设置。修改手机号。获取验证码接口 404 错误

##### 错误截图：
![36d6bbfcf680a4bc162d6f94dccfa98](https://github.com/user-attachments/assets/4be9eb40-53ba-4c1b-afae-6e14fc531272)

![bba8eef5384f6c2deca9fa6b4a384cd](https://github.com/user-attachments/assets/0283f431-796d-45b8-acfc-b84167123146)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
已经提交
