### ISSUE TITLE
ApiSelect

### ISSUE THREAD

**Issue by YJH1074863743** [jeecgboot/JeecgBoot#7588]
##### 问题描述：
ApiSelect怎么主动刷新

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by YJH1074863743** [comment]
![b0c47aedaec9de2db92dac161e0e4504](https://github.com/user-attachments/assets/9192f4f5-38f7-40d7-b8a5-b413784e6973)

**Comment by YJH1074863743** [comment]
![9692d289b2e2c1b18c503959e9c2ce8c](https://github.com/user-attachments/assets/3768c114-a87d-479b-b799-9e1bc80d77cc)

**Comment by zhangdaiscott** [comment]
ws

**Comment by jeecgDeveloper** [comment]
你是需要选择产品大类后，自动刷新表格吗？还是进入页面时产品大类先不请求，点击时再请求获取产品大类options？





1.如果需要选择产品大类后，自动刷新表格。（这种场景可按如下修改）

![image](https://github.com/user-attachments/assets/f8948617-c249-4d5a-942c-1873835b5847)
![image](https://github.com/user-attachments/assets/68ec926b-6645-4084-8503-b50d741bad12)

2.ApiSelect组件渲染时不加载，点击下拉时加载。（这种场景可按如下修改）
<img width="786" alt="image" src="https://github.com/user-attachments/assets/58e7dafa-8dbf-4e9a-a435-32a4c2194cea" />
