### ISSUE TITLE
JSelectUser选择用户 组件 当选择非第一页用户后，再次点开选择时 ，无法选择，且网页直接卡死

### ISSUE THREAD

**Issue by CharlesWuu** [jeecgboot/JeecgBoot#7589]
##### 版本号：
3.5.4

##### 问题描述：
JSelectUser选择用户 选择用户的时候都在第一页的话正常,选择了第一页后再进去也是正常,只有选择非第一页的时候 关闭再次选择会直接卡死,需要改动哪些地方?有没有提交记录可以看下,前端方面的 

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
升级到最新版看看

**Comment by CharlesWuu** [comment]
我没升级，我发现有个这个场景有个无限循环 将 useCustomSelection.tsx文件中   watch([selectedKeys, selectedRows], () => {
    nextTick(() => {
      syncSelectedRows();
    });
  }); 注释 目前好了，不知道有没有其他的问题
