### ISSUE TITLE
无法更新到3.7.2

### ISSUE THREAD

**Issue by jiangbr1614** [jeecgboot/JeecgBoot#7590]
##### 版本号：
3.7.2

##### 问题描述：

我的JEECG boot 包 无法从3.6.3 升级到 3.7.2，我把各个目录下的pom 都升级到了3.7.2
但是好像一点maven install  就无法从aliyun仓库里下3.7.2的资源包

##### 错误截图：
![Uploading 1.png…]()

**Comment by jiangbr1614** [comment]
![1](https://github.com/user-attachments/assets/beeecbae-09c5-49b8-aebd-35ff26dfae44)

**Comment by jiangbr1614** [comment]
![2](https://github.com/user-attachments/assets/4476b962-ad6e-434f-a2cc-72ce3058a8c7)

**Comment by zhangdaiscott** [comment]
不是这么省的，合并代码
https://github.com/jeecgboot/JeecgBoot/blob/master/jeecg-boot/db/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.md
