### ISSUE TITLE
签名拦截器对POST请求报错 

### ISSUE THREAD

**Issue by wuwu955** [jeecgboot/JeecgBoot#7591]
##### 版本号：

3.6.0
##### 问题描述：
签名拦截器对POST请求报错 

##### 错误截图：

<img width="790" alt="image" src="https://github.com/user-attachments/assets/8bbf6577-8721-4e4d-9efd-ff2e284e5b01" />
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/4782f8d1-daa3-41e6-adfd-2f263b25cc41" />

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
可以升级到最新版，可能已经修复了
