### ISSUE TITLE
更新3.7.2后，quartz执行的job报错

### ISSUE THREAD

**Issue by jiangbr1614** [jeecgboot/JeecgBoot#7592]
##### 版本号：
3.7.2

##### 问题描述：
升级3.7.2后，quartz 的job 执行报错，看起来不知道是quartz的问题，还是mybatis版本的问题，只单独更新了jeecg-boot的包。

##### 错误截图：

![1](https://github.com/user-attachments/assets/40f4f482-eaf5-4d97-bf52-60052afc904a)

**Comment by zhangdaiscott** [comment]
都告诉你了，不是这么升级的

**Comment by jiangbr1614** [comment]
> 都告诉你了，不是这么升级的

大佬帮帮忙，这一块怎么处理quartz这里
