### ISSUE TITLE
【3.7.2】ApiSelect 通过setFieldsValue设置默认值时 值配置了 但是不触发@change事件

### ISSUE THREAD

**Issue by benben120** [jeecgboot/JeecgBoot#7595]
##### 版本号：
3.7.2

##### 问题描述：
ApiSelect 通过setFieldsValue设置默认值时 值配置了 但是不触发@change事件

##### 错误截图：
![image](https://github.com/user-attachments/assets/3020ac85-7a35-4348-a44c-67373db63506)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
zy

**Comment by jeecgDeveloper** [comment]
通过setFieldsValue设置值时，暂不增加触发change事件功能。
ant-design-vue组件，你在外面通过代码更改value值时也不会触发change事件。

如果你想通过setFieldsValue设置值时，触发change事件可按如下修改
![image](https://github.com/user-attachments/assets/35fa2a52-4bc0-4650-b10c-83b0fb4b6de0)
