### ISSUE TITLE
3.5.2版本集成积木大屏1.9.1版本，获取不到tenantI的问题

### ISSUE THREAD

**Issue by ruya-song** [jeecgboot/JeecgBoot#7596]
##### 问题描述：已做操作如下：1.配置文件中的 saasMode 设置成tenant
                                                        2.JimuReportTokenService类实现新增方法getTenantId
                                                        3.在菜单管理积木报表处新增属性tenantId
                                                        4.shiro 设置匿名访问大屏
                              前端代码没有改动。
                              集成后重启后端，刷新进入页面，点击[积木BI大屏]，页面跳转至大屏页面/drag/list?token=xxx&tenantId=undefined
                              后端打印日志发现request中没有tenant相关的请求头，系统当中的其他接口的请求参数中是存在x-tenant-id的
##### 错误截图：
![1734397905533](https://github.com/user-attachments/assets/f6ca52a0-8f97-421e-b03f-82e5f51f226c)

![1734398145554](https://github.com/user-attachments/assets/72f43dc9-9936-4ac1-a226-b48041deb6ca)
![1734398309935](https://github.com/user-attachments/assets/145af9ac-d0da-4196-9132-05bd4f5f19f6)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
菜单配置有问题吧
![image](https://github.com/user-attachments/assets/bfbb621f-57c4-4608-a318-4f8ce6419a51)

**Comment by ruya-song** [comment]
> 菜单配置有问题吧 ![image](https://private-user-images.githubusercontent.com/3162115/396316700-bfbb621f-57c4-4608-a318-4f8ce6419a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDA5MDMsIm5iZiI6MTczNDQwMDYwMywicGF0aCI6Ii8zMTYyMTE1LzM5NjMxNjcwMC1iZmJiNjIxZi01N2M0LTQ2MDgtYTMxOC00ZjhjZTY0MTlhNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDE1NjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjI1NzQ5MjQ5Mzg0YjA3YmQwMzA2MmMwZmUxZWU1ZTAyN2U2NzkxYTEwMGQzMjk2NzdiYmQ2ZDNmNmViZWFkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.M6JVc-ecU90J8AtneGC-63qEH5MpSQSx4trQe_02Mjg)

点击大屏的菜单跳转后的链接，undefined应该是headerTenantId = request.getParameter(JmConst.TENANT_ID);代码中headerTenantId 的值，菜单配置如下：
![1734400777663](https://github.com/user-attachments/assets/152e7e85-8d31-495b-8a31-771d6d2611a0)
{{ window._CONFIG['domianURL'] }}/drag/list?token=${token}&tenantId=${tenantId}

**Comment by zhangdaiscott** [comment]
jeecgboot 3.5.2 应该还不支持租户这个参数变量，自己扩展吧
