### ISSUE TITLE
【3.7.2】上传组件功能异常

### ISSUE THREAD

**Issue by jxlgzwh** [jeecgboot/JeecgBoot#7597]
##### 版本号：
3.7.2

##### 问题描述：
上传组件无法上传文件

##### 错误截图：

![image](https://github.com/user-attachments/assets/02c3d70c-1193-4105-947f-13ef68320615)

##### 问题重现步骤

重现方式一
1、我搭建的是微服务版本，按默认配置，只将前端 .env.development 配置文件修改为微服务配置，其他按默认配置 。
`VITE_PROXY = [["/jeecgboot","http://localhost:9999"],["/upload","http://localhost:3300/upload"]]`
`VITE_GLOB_DOMAIN_URL=http://localhost:9999`

2、打开上传组件，选择文件，点击开始上传，提示 上传失败，“网络请求错误,未找到该资源!” 。
![image](https://github.com/user-attachments/assets/f200264b-7581-4488-8ea5-07451c2b9b44)

重现方式二

1、访问官网 重现问题
    https://boot3.jeecg.com/comp/third/upload 

2、打开上传组件，选择文件，点击开始上传，提示 上传失败，“网络请求错误,未找到该资源!” 。

#####  期望的解答

1、在微服务环境下，前端组件要如何配置才能同时上传多个附件。
2、在微服务环境下，后端要如何配置，希望能提供一个示例代码，感谢。

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个废弃了
看看这个
https://help.jeecg.com/component/JUpload.html
![image](https://github.com/user-attachments/assets/d74f4182-a34b-4413-a5e3-140260d79790)
