### ISSUE TITLE
Mapper.xml中查询结果映射实体类出现异常

### ISSUE THREAD

**Issue by 23527454** [jeecgboot/JeecgBoot#7600]
##### 错误截图：
![image](https://github.com/user-attachments/assets/eec2a5dc-d2c9-4a90-97fa-580097fd0b80)
![image](https://github.com/user-attachments/assets/01a27110-f978-4a15-b432-be07c4f07735)
![image](https://github.com/user-attachments/assets/8a8b2f7a-ea97-47c8-b60a-5f1fbe3fa9f5)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/38a0f1cd-62ce-47ec-b176-daf01211a3d4)
你改什么了，为什么会把日期转int

**Comment by 23527454** [comment]
> ![图像](https://private-user-images.githubusercontent.com/3162115/396346063-38a0f1cd-62ce-47ec-b176-daf01211a3d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDg0NDEsIm5iZiI6MTczNDQwODE0MSwicGF0aCI6Ii8zMTYyMTE1LzM5NjM0NjA2My0zOGEwZjFjZC02MmNlLTQ3ZWMtYjE3Ni1kYWYwMTIxMWEzZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDQwMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIzZDg0NWIwYmY4OTU2Y2JjOWZkNWM2MjVhYWQ3Njc5MjAwMDkyZWZkMWQ1OGMwZDgxMzY5OWMyZTI3NzQ3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.D4mauuCTgGSLcwiTbdOjmop_THzbBMmZJaZ4_UuVKL0)你改什么了，为什么会把日期转int

只是在mapper.xml里加了个左连接查询，后面发现把person_id和auth_id这两个字段从查询中移除或者把这两个放在时间字段的后面就不会再报错了，有点奇怪

**Comment by zhangdaiscott** [comment]
此类问题，自己研究吧，应该还是写的有问题
