### ISSUE TITLE
v3.7.2弹窗全屏底部有空隙

### ISSUE THREAD

**Issue by goatown** [jeecgboot/JeecgBoot#7601]
##### 版本号：
v3.7.2--12.17下载

##### 问题描述：
弹窗全屏底部有空隙

##### 错误截图：
![微信截图_20241217145519](https://github.com/user-attachments/assets/a0fb6d52-7758-4905-b265-3e474567d94e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这个可以忽略吧

**Comment by goatown** [comment]
这个页面可以忽略，举这个例子是所有的弹窗都有这个问题，官网boot.jeecg.com是正常的
![微信截图_20241217152038](https://github.com/user-attachments/assets/2294c3fe-3a42-47f4-8d55-9fbf01a99c6e)

![微信截图_20241217152048](https://github.com/user-attachments/assets/9f21dd79-d2fa-4c1d-883c-fca3f87bfacd)

**Comment by curry91** [comment]
固定ant-design-vue版本为 4.2.5 ，记得吧^去掉，要不然还是4.2.6；ant-design-vue 4.2.6的Modal编译后 页面元素 <div tableindex="0">这个包裹了里面的元素，导致全屏样式异常，之前的版本不会包裹，就没有这个全屏样式异常

**Comment by goatown** [comment]
> 固定ant-design-vue版本为 4.2.5 ，记得吧^去掉，要不然还是4.2.6；ant-design-vue 4.2.6的Modal编译后 页面元素
> 
> 这个包裹了里面的元素，导致全屏样式异常，之前的版本不会包裹，就没有这个全屏样式异常


感谢大佬们回复，亲测有效，完美解决缝隙问题  @zhangdaiscott @curry91

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。

本地按如下修改：
![image](https://github.com/user-attachments/assets/4b311fa5-5773-4e0b-83db-081304226e7e)
