### ISSUE TITLE
 poi-excel导入问题

### ISSUE THREAD

**Issue by naaaameeee** [jeecgboot/JeecgBoot#7603]
##### 问题描述：
导入数据会提示有错误数据的警告，其实导入成功了，原因是除了录入的数据还有改变格式的空行，导致逻辑判断出现异常

##### 错误截图：
错误提示

![image](https://github.com/user-attachments/assets/60fed4b2-f958-4fee-8501-e87378659979)
![image](https://github.com/user-attachments/assets/5d7bbb41-f1d1-4361-87ce-4527f247a5c1)

错误原因

![image](https://github.com/user-attachments/assets/54d521f1-73bf-4bac-85ff-80efcea34295)

错误位置

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by naaaameeee** [comment]
是不是在3.7.1修了，我只更新poi可以吗
![image](https://github.com/user-attachments/assets/0ebb6b76-d92f-4904-8232-f274dbecf1c4)

**Comment by zhangdaiscott** [comment]
不可以

**Comment by naaaameeee** [comment]
> 是不是在3.7.1修了，我只更新poi可以吗 ![image](https://private-user-images.githubusercontent.com/99253064/396435852-0ebb6b76-d92f-4904-8232-f274dbecf1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjc5NTQsIm5iZiI6MTczNDQyNzY1NCwicGF0aCI6Ii85OTI1MzA2NC8zOTY0MzU4NTItMGViYjZiNzYtZDkyZi00OTA0LTgyMzItZjI3NGRiZWNmMWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWE2Y2NmZjA5Yzk2OTNlZmU4ZDJkMDAwYTI2NjgzY2ExZWY5OWRiMjdkMTYxOTM4N2Y0YzczMzgwMThlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eq_Lu8zC93CBqUa7USB6S7GG5QVzNpkg2Q6iewWke0M)

换了最新的  <autopoi-web.version>1.4.11</autopoi-web.version> 没有解决
