### ISSUE TITLE
将tenantId注入到jwt-token中的claims中失败，其他字段比如user_key是成功的

### ISSUE THREAD

**Issue by jeanson-leo** [jeecgboot/JeecgBoot#7604]
##### 问题描述：

将tenantId注入到jwttoken中的claims中失败，其他字段比如user_key是成功的

##### 错误截图：
![image](https://github.com/user-attachments/assets/9f770b16-371e-4995-ac59-ce7d4804ef46)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己扩展的逻辑，我们没法分析
