### ISSUE TITLE
最新版样式错乱

### ISSUE THREAD

**Issue by timfengzi** [jeecgboot/JeecgBoot#7605]
##### 版本号：
3.7.2

##### 问题描述：
主题切换为
![image](https://github.com/user-attachments/assets/0c1c36a2-752c-4710-beb7-090f4bc5a184)
这样时，样式有问题

##### 错误截图：
![image](https://github.com/user-attachments/assets/d7305c67-d819-447f-891e-d92b5483d7da)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
什么时候下载的代码

**Comment by timfengzi** [comment]
下午下载的代码

**Comment by jeecgDeveloper** [comment]
该问题已修复，还未发版。

你本地可先按如下修改：
![image](https://github.com/user-attachments/assets/5247a921-3e27-4472-a156-23b1749c4cd2)

**Comment by zhangdaiscott** [comment]
提了
