### ISSUE TITLE
仪表盘布局错乱

### ISSUE THREAD

**Issue by liuling1314** [jeecgboot/JeecgBoot#7607]
##### 版本号：
3.7.1

##### 问题描述：
当我把配置的仪表盘设置为默认首页时，遇到404 ，点击返回首页，仪表盘的布局就会完全错乱，具体截图如下，我是直接使用样例的仪表盘测试

##### 错误截图：
错误布局重现步骤

![Screenshot3](https://github.com/user-attachments/assets/d60dae57-f11f-4c31-8e24-e82defd1476b)
错误布局截图

![Screenshot1](https://github.com/user-attachments/assets/adeb797d-88e8-454e-b792-03b695b62ce3)

正确布局截图

![Screenshot2](https://github.com/user-attachments/assets/3a6188b3-d632-4b8e-b910-76f34ffb437e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by liuling1314** [comment]
@zhangdaiscott  感觉像是返回首页时 没有获取到仪表盘布局的信息，强制刷新下样式又好了，是不是在返回首页的时候强制刷新下会解决问题? 本人不太懂前端，麻烦大神帮忙给看下，如果有解决方案了，希望能先贴一下，万分感谢

**Comment by zhangdaiscott** [comment]
404怎么出现的

**Comment by liuling1314** [comment]
> 404怎么出现的

  随便输入一个有问题的地址，获取地址输错了，都是返回404， 例如 https://boot3.jeecg.com/dashboard/analysis1 上述地址用你们官网就会返回404

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
已修改， 下版本更新

**Comment by liuling1314** [comment]
> 已修改， 下版本更新
你好大神，能先把结局方案贴一下吗，万分感谢

**Comment by liuling1314** [comment]
@jeecgDeveloper 有临时解决方案吗，我jmreport 加了 apiBasePath 配置后，返回首页后还是布局错乱
