### ISSUE TITLE
导入功能的请求url

### ISSUE THREAD

**Issue by blwwcc** [jeecgboot/JeecgBoot#7614]
##### 问题描述：在网络条件限制的条件下，用户导入失败
问题发生场景：
前端使用nginx部署，后端使用了微服务，nginx的部署是这样：

客户访问端口--端口1；
客户访问地址--IP1；
前端标记--指定dist路径
后端标记--后端gateway地址和端口--IP2：端口2

其中ip1：端口1，客户是可以访问的。 ip2:端口2,客户网路不同，没法访问。

客户访问的时候，点击表单的其他功能按钮（如导出、添加、修改等），按F12看到的请求的url是IP1：端口1，可以正常使用。
但是导入功能的按钮，按F12的请求地址是IP2：端口2，因为客户对IP2网络不通，因此导入失败。

查看本地运行的结果，发现其他接口都是访问的前端端口（3100--前端接口），而导入接口访问的都是（8080--后端接口），是不是跟这个有关系。

##### 错误截图：
![1734581655273](https://github.com/user-attachments/assets/4517a117-3f9d-48b1-9196-d678aebbb479)
![1734581693119](https://github.com/user-attachments/assets/d45f899e-17ff-4c70-a2c1-e399fe98c6ca)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
这种问题是自己环境导致，我们分析不了
