### ISSUE TITLE
树形表格的展开的位置可以改变吗

### ISSUE THREAD

**Issue by zrj008009** [jeecgboot/JeecgBoot#7615]
##### 问题描述：
树形表格的展开的列位置可以改变吗，默认都是最前面吗，可以设定展开icon它自己为一列吗

![image](https://github.com/user-attachments/assets/f24f4a2a-92b3-43a3-8d10-a535fcc2ede9)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
自己扩展即可

**Comment by zrj008009** [comment]
@zhangdaiscott 可以告诉一下在那个文件扩展吗

> 自己扩展即可
