### ISSUE TITLE
tomcat可以自己更新版本吗

### ISSUE THREAD

**Issue by blwwcc** [jeecgboot/JeecgBoot#7616]
##### 问题描述：报了个漏洞，说需要更新tomcat版本
可以在其他条件不动的情况下，升级tomcat的版本吗

##### 错误截图：
![1734596110874](https://github.com/user-attachments/assets/f266b5ba-b1cd-4037-b560-c5fc11ce28d8)
![1734596140499](https://github.com/user-attachments/assets/80a7075b-c2aa-4d8c-9275-f1728e823d6e)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
单独升级tomcat插件试试

**Comment by blwwcc** [comment]
单独升级tomcat插件，是指的升级idea的插件；还是更新jeecgboot的jar包，如果是后者的话，怎么操作呢
