### ISSUE TITLE
3.7.2版本积木报表开发、仪表盘设计器页面部分资源加载失败

### ISSUE THREAD

**Issue by humorl** [jeecgboot/JeecgBoot#7618]
##### 版本号：
3.7.2

##### 问题描述：

积木报表开发、仪表盘设计器页面部分资源加载失败，菜单：低代码开发-积木报表开发，仪表盘设计器都报错
怀疑路径映射不正确

##### 错误截图：

![error](https://github.com/user-attachments/assets/c506bf38-2a97-47fa-9f52-30b58b4e149d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
截图提供完整的，你自己改过什么，默认的功能我们测试过没问题

**Comment by zhangdaiscott** [comment]
无回复，关闭
