### ISSUE TITLE
仪表盘中的统计插件，是否可以支持小数点数据展示

### ISSUE THREAD

**Issue by su20241001** [jeecgboot/JeecgBoot#7620]
##### 版本号：
最新版本

##### 问题描述：
![image](https://github.com/user-attachments/assets/ff4ce70c-fe69-4533-828a-1bb78c4b7bea)
请问：
上面的数据是否支持小数点展示，在某些情况下，数据要到小数点后6位。现在直接给我四舍五入了。
不知道是否可以支持。
例如：
2000 展示 2000
2000.1456 展示 2000.1456

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by su20241001** [comment]
不太懂，能给一个样例吗？

**Comment by jeecgDeveloper** [comment]
已修改，下版本发布
