### ISSUE TITLE
积木大屏1.9.1 组件图标404

### ISSUE THREAD

**Issue by ruya-song** [jeecgboot/JeecgBoot#7622]
##### 错误截图：

![1734655898815](https://github.com/user-attachments/assets/98e593e0-a00e-4766-8ee1-71cb5a5a32ef)

![1734655952793](https://github.com/user-attachments/assets/a7bb683b-2bdf-46d3-861c-1de6aa6ce3e9)

**Comment by zhangdaiscott** [comment]
资源映射还是有问题

**Comment by ruya-song** [comment]
> 资源映射还是有问题
网关中新增下面配置，可以访问了
{
    "id": "jeecg-system-api-rewrite",
    "order": 0,
    "predicates": [
      {
        "name": "Path",
        "args": {
          "_genkey_0": "/img/**"
        }
      }
    ],
    "filters": [
      {
        "name": "RewritePath",
        "args": {
          "_genkey_0": "/img/(?<segment>.*)",
          "_genkey_1": "/drag/lib/img/${segment}"
        }
      }
    ],
    "uri": "lb://jeecg-system"
  },
