### ISSUE TITLE
3.7.1 bug：JVxeTable 单选删除不生效

### ISSUE THREAD

**Issue by MuShan-bit** [jeecgboot/JeecgBoot#7624]
##### 问题描述：JVxeTable 单选删除不生效
![image](https://github.com/user-attachments/assets/13ecbae4-4781-42ab-bfb2-a75f32947697)
传递props用的"radio"这里删除却是用的"row-radio"做判断
![image](https://github.com/user-attachments/assets/7781acfe-bff6-4366-8e6e-cf4336420056)
![image](https://github.com/user-attachments/assets/6364c4c8-21cf-42ce-86e0-52f8484a333d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jeecgDeveloper** [comment]
已修复，下一版本发布。

你本地可按如下修改：
![image](https://github.com/user-attachments/assets/b4fb34ca-7d06-490e-8424-45b79714ffe3)
