### ISSUE TITLE
仪表盘设计-自定义按钮无法编辑

### ISSUE THREAD

**Issue by sunjulei** [jeecgboot/JeecgBoot#7632]
##### 版本号：
2024.12.21  官网的演示地址
https://api3.boot.jeecg.com/jimubi/index?pageId=1030366441254506496&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzUwNzQyMzEsInVzZXJuYW1lIjoiamVlY2cifQ.4iWcJzmAmB-I4eU5T1EsYEHjClIBviHrQkFFomLYizw&tenantId=3&style=default

##### 问题描述：

仪表盘设计新增了自定义按钮之后，保存页面。再刷新页面（多刷新几次），点击自定义按钮右上角的编辑没有响应。

##### 错误截图：
![image](https://github.com/user-attachments/assets/b1f31cc8-31b2-4d4a-b345-740314aee2e2)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
sq

**Comment by jeecgDeveloper** [comment]
你是操作哪个菜单下的组件显示的这个呢
