### ISSUE TITLE
启动镜像容器组报错

### ISSUE THREAD

**Issue by howso123** [jeecgboot/JeecgBoot#7634]
##### 版本号：
根据官方文档https://help.jeecg.com/java/docker/quickcloud.html操作拉取的最新版本

##### 问题描述：
执行启动镜像容器组命令时报错

##### 错误截图：
![image](https://github.com/user-attachments/assets/12c29173-8eb2-4004-9a23-d2c51ac06a07)

**Comment by zhangdaiscott** [comment]
看看是不是这个问题
![image](https://github.com/user-attachments/assets/07311c37-cf32-4403-9d8b-a32cb3791e6e)
https://blog.csdn.net/xiaolong1155/article/details/131917155
