### ISSUE TITLE
jar包运行报错找不到数据源

### ISSUE THREAD

**Issue by pinktigerkk** [jeecgboot/JeecgBoot#7636]
##### 问题描述：
idea启动正常但是同样的环境打成jar包后通过java -jar找不到数据源报错

##### 错误截图：
![image](https://github.com/user-attachments/assets/0e7a0de5-c2a7-49ee-9758-a5036782afb1)
![image](https://github.com/user-attachments/assets/7dd445b0-f65f-4899-b3fe-ab3511f1f053)
![image](https://github.com/user-attachments/assets/15b8ba0b-3474-4495-b312-c15da2731967)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
仔细确认环境问题
