### ISSUE TITLE
JSelectUserByDept为什么选出来数据是数组的形式，能不能改成字符串

### ISSUE THREAD

**Issue by Allison-qs** [jeecgboot/JeecgBoot#7637]
#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zrj008009** [comment]
![image](https://github.com/user-attachments/assets/4b0409b1-92bb-4bb7-a5f4-ee206ed00c32)
找到组件自己修改就好了
