### ISSUE TITLE
前端启动成功，但界面无法正常显示

### ISSUE THREAD

**Issue by caipeishen** [jeecgboot/JeecgBoot#7638]
##### 版本号：
springboot3_sas

##### 问题描述：
前端启动成功，但界面无法正常显示

##### 错误截图：
![image](https://github.com/user-attachments/assets/2107bdc2-25d0-42dc-b67d-6434dde2c727)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zrj008009** [comment]
随便百度一下就能找到答案了，router版本高了
