### ISSUE TITLE
前端路由重复引用报错

### ISSUE THREAD

**Issue by beaverwu** [jeecgboot/JeecgBoot#7641]
##### 版本号：
3.7.2 使用springboot3的分支

##### 问题描述：
constant.ts中export const PAGE_NOT_FOUND_NAME = 'PageNotFound';
，在basic.ts文件引用的时候，重复引用导致路由报错

// 404 on a page
export const PAGE_NOT_FOUND_ROUTE: AppRouteRecordRaw = {
  path: '/:path(.*)*',
  name: PAGE_NOT_FOUND_NAME,
  component: LAYOUT,
  meta: {
    title: 'ErrorPage',
    hideBreadcrumb: true,
    hideMenu: true,
  },
  children: [
    {
      path: '/:path(.*)*',
      name: PAGE_NOT_FOUND_NAME + '_child',
      component: EXCEPTION_COMPONENT,
      meta: {
        title: 'ErrorPage',
        hideBreadcrumb: true,
        hideMenu: true,
      },
    },
  ],
};
##### 错误截图：
![8d9ed1a076adf086c20dc86787d797a5](https://github.com/user-attachments/assets/c06a626d-9682-4d8c-a691-9f4655fb86e7)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你不是主干吧

**Comment by beaverwu** [comment]
您好，您的邮件已收到，我会尽快给您回复。
