### ISSUE TITLE
生成代码无后端代码，freemarker报错

### ISSUE THREAD

**Issue by Dro9an** [jeecgboot/JeecgBoot#7643]
##### 版本号：
3.7.2

##### 问题描述：
生成代码无后端代码只有前端代码，后端freemarker关键报错如下：

2024-12-24 20:04:09.942 [http-nio-8080-exec-1] ERROR org.jeecgframework.codegenerate.generate.impl.a.a:99 - java.lang.IllegalStateException: cannot process templateString:erp/onetomany/java/${bussiPackage}/${entityPackage}/vue/V${currentDate}_1__menu_insert_${entityName}.sql cause:freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> currentDate  [in template "templateString..." at line 1, column 60]

同样的表，从git拉取的同一个分支，使用远程数据库与redis，除jeecg_config.properties内project_path改为自己本地项目地址外其他所有配置全部一致，其他同项目开发者可以正常生成；

出现问题的开发者所有表（包括自带示例表）全部无法生成

##### 错误截图：
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/578cba14-952e-41d3-9ede-c3a31aa5cda5" />
<img width="2487" alt="image" src="https://github.com/user-attachments/assets/c476cec2-16da-42ef-83a2-96e434b317b8" />
<img width="1631" alt="image" src="https://github.com/user-attachments/assets/a9af4ad8-e45f-4947-8a98-c5d709e2c529" />
<img width="2499" alt="image" src="https://github.com/user-attachments/assets/e5420e2c-fc7b-41f4-97f7-ec755ec5db69" />
<img width="2510" alt="image" src="https://github.com/user-attachments/assets/71e057ce-13c5-42df-869a-b16b54bad49e" />

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你是什么系统

**Comment by RoganLeon** [comment]
> 你是什么系统

我是MacOS 15，也有同事Windows11 x86_64也和我一模一样的故障症状无法生成

**Comment by zhangdaiscott** [comment]
看这意思，currentDate值有问题？
本地执行这个方法看看

```
	/**
	 * 获取当前日期 短格式
	 */
	public static String getCurrentDateStr() {
		Date currentDate = new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
		String formattedDate = sdf.format(currentDate);
		return formattedDate;
	}
```

**Comment by RoganLeon** [comment]
> 看这意思，currentDate值有问题？ 本地执行这个方法看看
> 
> ```
> 	/**
> 	 * 获取当前日期 短格式
> 	 */
> 	public static String getCurrentDateStr() {
> 		Date currentDate = new Date();
> 		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
> 		String formattedDate = sdf.format(currentDate);
> 		return formattedDate;
> 	}
> ```

这是在出现代码生成问题项目下的start测试用例内的执行结果，看起来是正常的
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/fcdcc684-95aa-4ff6-8f2d-1c4ea3830b2f" />

**Comment by zhangdaiscott** [comment]
你的项目路径是不是有中文或者空格

**Comment by RoganLeon** [comment]
> 你的项目路径是不是有中文或者空格

确定是没有的

<img width="821" alt="image" src="https://github.com/user-attachments/assets/68484332-0f77-463a-b2cd-6b764fefb173" />

**Comment by zhangdaiscott** [comment]
那神奇了，如何重现

**Comment by RoganLeon** [comment]
我发现了100%重现步骤，代码生成不能生成到项目所在目录，但是报错信息似乎跟这个原因所在没有联系，选择项目外其他任意一个目录即可100%生成成功，请问这是bug吗？

**Comment by zhangdaiscott** [comment]
目录有写权限吗

**Comment by RoganLeon** [comment]
有的，父级目录以及所在目录都是有读写执行权限
<img width="957" alt="image" src="https://github.com/user-attachments/assets/f03dc6e5-4b74-4009-b586-e9565ad47b65" />

**Comment by RoganLeon** [comment]
包括之前提到的另外一个无法生成Windows系统环境的开发者，更换生成目录后也可以生成了

**Comment by zhangdaiscott** [comment]
那还是目录权限问题

**Comment by RoganLeon** [comment]
可是我在测试用例内编写的测试用例是可以正常写入文件，并且前端代码可以正常生成也佐证了权限没问题这一点，怀疑是freemaker或相关依赖的bug
<img width="1926" alt="image" src="https://github.com/user-attachments/assets/a688fbd4-2e02-4ae1-897f-98eae0a88f2e" />
