### ISSUE TITLE
积木报表1.9，数据填报时，上传图片后路径不正确。

### ISSUE THREAD

**Issue by masterjian** [jeecgboot/JeecgBoot#7648]
##### 版本号：
JeecgBoot：3.7.1
积木报表：1.9.0

##### 问题描述：
积木报表中填报时，图片上传后，数据库中存储的路径由于已经自带了【/jeecg-boot/jmreport/img/】前缀，所以在前端自动显示此图片时，前缀自动又加了一次，变成了【/jeecg-boot/jmreport/img/jeecg-boot/jmreport/img/jimureport/bashshell_1735099020022.png】

建议：能否增加积木报表填报时文件/图片上传路径的设置

##### 错误截图：
![ff921511beb8fc7ecc735fa99278e0e5](https://github.com/user-attachments/assets/225f43c0-775e-4a54-b5a8-214bba27e2e9)

![cde42aa1e50ba7093a79bd887c63de7c](https://github.com/user-attachments/assets/476b67f2-3428-45d6-b647-93533c681a86)

![image](https://github.com/user-attachments/assets/772ae107-6994-452b-be54-46fe663c32da)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你升级积木报表到1.9.1试试

**Comment by masterjian** [comment]
> 你升级积木报表到1.9.1试试 http://jimureport.com/doc/log

测试了，1.9.1已经没有这个bug
