### ISSUE TITLE
升级3.7.2 flyway自动升级失败

### ISSUE THREAD

**Issue by testnet0** [jeecgboot/JeecgBoot#7650]
##### 版本号：
3.7.2

##### 问题描述：

尝试升级3.7.2，使用flyway自动升级脚本，会出现失败，分析原因是flyway升级晚于积木报表1.9.1中bean加载，然后就报错表jimu_report_export_job不存在，把FlywayConfig这里改成`@PostConstruct`可以解决这个问题

##### 错误截图：

![image](https://github.com/user-attachments/assets/662b95d8-bd5d-4007-b1c0-8bb95270073f)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by jeecgos** [comment]
已修复，请等待积木报表新版本发布。
