### ISSUE TITLE
j-dict-select-tag int类型不回显

### ISSUE THREAD

**Issue by KongZouXiang** [jeecgboot/JeecgBoot#7654]
##### 版本号：
origin/springboot3_sas 最新版

##### 问题描述：

string 类型就会回显

##### 错误截图：
![image](https://github.com/user-attachments/assets/b4f9e073-6703-4ae0-a53f-29963cd6fab2)
![image](https://github.com/user-attachments/assets/624b0aa5-4065-402d-9c0a-3f8fff82263b)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/user-attachments/assets/49b67d7c-73f7-40f8-a8fe-fce31264e9a0)
