### ISSUE TITLE
部署websocket 出现身份认证失败

### ISSUE THREAD

**Issue by zyp0529** [jeecgboot/JeecgBoot#7656]
##### 版本号：
3.4.4

##### 问题描述：
部署websocket 前端传过来的token是验证成功的,然后走着着token就获取为null了,然后直接报身份验证失败错误

##### 错误截图：
![PixPin_2024-12-26_14-57-05](https://github.com/user-attachments/assets/f4044ced-e50d-4ae3-a212-8dc4762b6339)
![Snipaste_2024-12-26_15-00-10](https://github.com/user-attachments/assets/aafc3b93-4c90-4e52-a652-d7dc3c5d341d)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
版本太老了，没法支持，自己debug看看吧
