### ISSUE TITLE
咨询 online 问题

### ISSUE THREAD

**Issue by bianww** [jeecgboot/JeecgBoot#7657]
##### 版本号：v3.7.2
下载地址：https://github.com/jeecgboot/JeecgBoot
master分支

##### 问题描述：
请问现在下载最新版本的代码，本地启动后很多功能提示资源未找到，比如online功能，根据发起的接口请求地址发现代码里面根据没有这块的后台代码，请问 online 的后台代码是不开源了吗？具体位置需要怎么找呢

##### 错误截图：

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/4955033a-4ae7-4ebe-90e3-71f6ba642c4e" />

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
你是改了什么代码？其他人没这问题

**Comment by bianww** [comment]
> 你是改了什么代码？其他人没这问题

没改呢，就是从 github 上面的 master 分支下载下来的压缩包，导入到 idea 里面运行的，online 这块后台服务代码是在哪个模块里面的额，能帮忙给截个图吗

**Comment by zhangdaiscott** [comment]
这块是依赖
