### ISSUE TITLE
ChatGPT AI助手支持国产AI模型吗?

### ISSUE THREAD

**Issue by filicat** [jeecgboot/JeecgBoot#7659]
##### 问题描述：
看文档似乎仅支持openAI?

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
目前只支持chartgpt
