### ISSUE TITLE
https://help.jeecg.com/ 访问失败

### ISSUE THREAD

**Issue by ChnMig** [jeecgboot/JeecgBoot#7666]
##### 版本号：
ALL

##### 问题描述：
https://help.jeecg.com/ 访问失败, 导致文档无法查看

##### 错误截图：
![image](https://github.com/user-attachments/assets/8683552c-dd8f-4263-b42c-c0c35bb9b5bc)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
https://ojrjjvdr7z.k.topthink.com/
