### ISSUE TITLE
希望允许自定义主键字段

### ISSUE THREAD

**Issue by ericzha76** [jeecgboot/JeecgBoot#7668]
##### 版本号：
3.72

##### 问题描述：

强制ID作为主键字段，会导致主细表数据从属关系可读性差，
且现有业务表里已经定义了诸如orno订单号之类的主键字段，导致无法使用jeecg产品。

希望允许自定义主键字段。
如附件中其他产品所示。
Jeecg其他方面非常棒，就这个ID强制主键让我们很尴尬。

##### 错误截图：

![image](https://github.com/user-attachments/assets/9d409b11-164c-4d23-b6a5-a4beb3dcab39)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
在线模式不支持，可以生成代码后，自己改
