### ISSUE TITLE
启动报错 Field onlDragShareDao in org.jeecg.modules.drag.service.a.i required a bean of type 'org.jeecg.modules.drag.dao.OnlDragShareDao' that could not be found.

### ISSUE THREAD

**Issue by zhu3402592** [jeecgboot/JeecgBoot#7669]
##### 问题描述：

启动报错 Field onlDragShareDao in org.jeecg.modules.drag.service.a.i required a bean of type 'org.jeecg.modules.drag.dao.OnlDragShareDao' that could not be found.

##### 错误截图：
![image](https://github.com/user-attachments/assets/ddec6d2c-6232-4326-94c3-bbdf352f594b)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
怎么出现的错误？默认代码还是自己改过什么

**Comment by zhu3402592** [comment]
找到了 是配置文件的问题  
![Uploading image.png…]()

**Comment by zhu3402592** [comment]
minidao :
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*   这个没有配置

**Comment by zhangdaiscott** [comment]
默认不是有这个配置吗
