### ISSUE TITLE
代码生成工具生成的前端代码包含未知方法startProcess

### ISSUE THREAD

**Issue by BegForLove** [jeecgboot/JeecgBoot#7671]
##### 版本号：
3.7.2

##### 问题描述：
生成的前端代码中包含一个未知方法，如下
从api/common/api路径中引入startProcess，但是对应文件中没有该方法
  import { startProcess } from '/@/api/common/api';

    /**
   * 提交流程
   */
  async function handleProcess(record) {
    let params = {
      flowCode: 'dev_tms_md_cheliang_001',
      id: record.id,
      formUrl: 'com/rhjc56/wms/components/TmsMdCheliangForm',
      formUrlMobile: ''
    }
    await startProcess(params);
    handleSuccess();
  }

##### 错误截图：

![image](https://github.com/user-attachments/assets/71ab145f-ae6e-4666-9d49-1728c80bf0b4)
![image](https://github.com/user-attachments/assets/de9eed6a-12f8-4040-bd98-dd24e33f3d54)

#### 友情提示：
  - 未按格式要求发帖、描述过于简单的，会被直接删掉;
  - 描述问题请图文并茂，方便我们理解并快速定位问题;
  - 如果使用的不是master，请说明你使用的分支;

**Comment by zhangdaiscott** [comment]
删了就行

**Comment by zhangdaiscott** [comment]
你应该是开源版加了bpm_status字段，去掉这个字段就好了

**Comment by BegForLove** [comment]
> 你应该是开源版加了bpm_status字段，去掉这个字段就好了

哦哦好的，多谢，不过这是在哪个文件去掉

**Comment by BegForLove** [comment]
> 删了就行

删除引用吗，那对应用的地方调用逻辑是不是会出错

**Comment by BegForLove** [comment]
> 你应该是开源版加了bpm_status字段，去掉这个字段就好了

找到了，已解决
